<?php 
$statusarr = array('100'=>'<font color="#FF0000">已下线</font>','101'=>'待审核','102'=>'<font color="#006600">已上线</font>','103'=>'<font color="#FF0000">不通过</font>');
?>
<div class="conmian">
  <h1><?php echo $this->AreaTitle;?>
  <?php if($this->mycommon->checkA($this->Staff_Area_ID) || $this->mycommon->checkW($this->Staff_Area_ID)){?>
         -> 
         <a href="javascript:;" onclick="openbox('<?=$this->indexurl?>/addtype')">添加分类</a>  |
         <a href="javascript:;" onclick="openbox('<?=$this->indexurl?>/edittype/tid/<?=$this->type?>')">编辑分类</a> | 
         <a href="<?=$this->indexurl?>/addlink/tid/<?=$this->type?>">添加连接</a> 
 <?php }?></h1>

<?php if (count($this->messages)) : ?>
<div class="alert fade in">
     <button type="button" class="close" data-dismiss="alert">×</button>
<?php foreach ($this->messages as $message) : ?>
    <p class="message"><strong><?php echo $this->escape($message); ?></strong></p>
<?php endforeach; ?>
 </div>
<?php endif; ?>      
	<div class="fr u_right">
    <div class="tab_content">
    
    <div class="tab_tit1">
        <ul class="fl">
          <!--<li <?=$this->type=='0'?'class="on"':''?>><a href="?type=0" style="width:150px;">图片链接<em></em><b class="blank3"></b></a></li>-->
          <?php foreach($this->linktype as $type){?>
          <li <?=$this->type==$type['id']?'class="on"':''?>><a href="?type=<?=$type['id']?>" style="width:150px;<?=($type['status']?'':'color:#999999')?>" title="<?=($type['status']?'已上线':'已下线')?>"><?=$type['name']?><em></em><b class="blank3"></b></a></li>
          <?php }?>
        </ul>
        </div>

      </div>
      <div class="tab_con mb10">
        <table class="producttable table" border="0">
          <thead>
                <th width="80">类型</th>
                <th width="80">网站logo</th>
                <th width="100">名称</th>
                <th width="80">连接地址</th>
                <th width="50">排序</th>
                <th width="80">Email</th>
                <th width="100">描述</th>
                <th width="60">状态</th>
                <th width="60">首页推荐</th>
                <th width="70">添加时间</th>
                <th width="60">添加人</th>
                <th width="70">更新时间</th>
                <th width="60">更新人</th>
                <th width="100">操作</th>
                </thead>
              <tbody>
                <?php 
				if(empty($this->data)){?>
                <tr>
                  <td colspan="9"><center>暂无记录</center></td>
                </tr>
                <?php }else{
			   foreach($this->data as $k=>$v){
					$bgclass='class="hover_tr"';
					if($k%2==1) $bgclass = 'class="bgf9 hover_tr" bgcolor="#F0EDED"';	
				?>
                <tr <?=$bgclass?>>
                  <td><?=$v['link_type']==1?'文字链接':'图片链接'?></td>
                  <td><?php if($v['icon'] && file_exists(substr($v['icon'],1))){?><img src="<?=$v['icon']?>" width="50" height="25" /><?php }?></td>
                  <td><?=$v['name']?></td>
                  <td><a href="<?=$v['url']?>" target="_blank"><?=$v['url']?></a></td>
                  <td><?=$v['displayorder']?></td>
                  <td><a href="mailto:<?=$v['email']?>" target="_blank"><?=$v['email']?></a></td>
                  <td><?=$v['introduction']?></td>
                  <td><?=$statusarr[$v['status']]?></td>
                  <td><?php if($v['home']==1) {?> <font color="#006600">是</font>
				<?php }else {?><font color="#FF0000">否</font></font><?php }?></td>
                <td><?=$v['created']?date("Y-m-d H:i:s",$v['created']):''?></td>
                <td><?=$v['created_by']?></td>
                <td><?=$v['modified']?date("Y-m-d H:i:s",$v['modified']):''?></td>
                <td><?=$v['modified_by']?></td>
                <td><?php if($this->mycommon->checkA($this->Staff_Area_ID) || $this->mycommon->checkW($this->Staff_Area_ID)){?>
         <a href="<?=$this->indexurl?>/editlink/id/<?=$v['id']?>">编辑</a> 
 <?php }?></td>
                </tr>
                <?php }}?>
              </tbody>
        </table>
    <div class="pagination divpage">
        <?=$this->page_bar;?>
      </div>
  </div>
</div>
