<ul>
  <?php foreach($this->showarr as $arr){if($arr){?>
  <li>
    <h3><a href="/code-<?=$arr['id']?>.html" title="<?=$arr['title']?>" target="_blank"><?=$this->fun->utf_substr($arr['title'],30,'')?></a></h3>
    <?php if($arr['need_pass']==1){?>
<span class="fontorange">需要密码</span>
<?php }else{?>
    <?=$arr['spendpoints']?'<span><ins class="jficon" style="vertical-align:middle;"></ins>'.$arr['spendpoints'].'</span>':'<span class="fontorange">免费</span>'?>
    <?php }?>
    <p>开发环境：<?=$arr['dep_environment']?></p>
  </li>
  <?php }}?>
</ul>
