<link rel="stylesheet" type="text/css" href="/css/default/scheme.css"/>
<div class="w">
    <div class="breadcrumbs">		
    	<span><?=$this->translate('Menu_CurrentPosition')?></span><a href="/" ><?=$this->translate('Menu_Home');?></a>&nbsp;&nbsp;»&nbsp;&nbsp;<a href="/webinarlist" ><?=$this->translate('Menu_Seminar')?></a> 
        <?php foreach($this->semLevel1 as $sem){
        	  	 if($this->selectid==$sem['id']) echo '&nbsp;&nbsp;»&nbsp;&nbsp;<span>'.$sem['name'].'</span>';
			  }
	    ?>     
    </div>
</div>

<div class="w clearfix ld " >

<div class="listleftmenu">
    <h1><a href="/webinarlist">应用分类</a></h1>
	<ul class="schemeleft">
        <?php foreach($this->semLevel1 as $sem){?>
            <li <?php if($this->selectid==$sem['id']) echo 'class="on"';?>><span class="fore<?=$sem['id']?>"></span><s></s><a href="/webinarlist-<?=$sem['id']?>.html" title="<?=$sem['name']?>" class="logclick" rev="webinarlist" rel="<?=$sem['id']?>"><?=$sem['name']?></a></li>
            <?php }?>
    </ul>

</div>

<div class="listright fr schemelist">
	<div class="w_100">
    	<?php if(empty($this->allSol)){?>
        <div class="tipnothing">没有记录</div> 
        <?php }else{
			foreach($this->allSol as $sol){?>
         <article class="posts">
            <h2><a href="/webinar-<?=$sol['id']?>.html"  title="<?=$sol['title']?>" class="logclick" rev="webinar" rel="<?=$sol['id']?>"  target="_blank"><?=$sol['title']?><?php if($sol['type']=='vdo') echo '&nbsp;<img src="/images/default/video.jpg">';?></a></h2>
            <div class="postmeta">
                <span>来源：</span><?=$sol['source']?>
                <span class="ml10">作者：</span><?=$sol['author']?>
                <span class="ml10">关键词：</span><?php 
					$tip = explode(',',$sol['keyword']);
					for($i=0;$i<count($tip);$i++){
						echo $tip[$i].' ';
				 }?>
				 <?php if($sol['type']=='vdo'){?>
                    <span class="ml10">公司名：</span><?=$sol['company']?>
                <?php }?>
				
            </div>
            <div class="row">
                <p><?=$sol['description']?></p>
            </div>
            <div class="read_more">
                <span class="fontgray">创建时间：<?=date('Y-m-d',$sol['created'])?></span>
                <?php if($sol['type']=='vdo'){?>
                <a class="button seebutton fr logclick" href="/webinar-<?=$sol['id']?>.html"  title="<?=$sol['title']?>" rev="webinar" rel="<?=$sol['id']?>" target="_blank">进入观看</a>
                <?php }else{?>
                <a class="redbutton fr logclick" href="/webinar-<?=$sol['id']?>.html"  title="<?=$sol['title']?>" rev="webinar" rel="<?=$sol['id']?>" target="_blank">查看更多</a>
                <?php }?>
            </div>
        </article>
        <hr />
       <?php }}?>
	</div>
    <div class="pagination fr"><?=$this->page_bar;?></div>
</div>
</div>

<div class="clr"></div>