<link rel="stylesheet" type="text/css" href="/css/default/directory.css"/>

<div class="w">
    <div class="breadcrumbs">		
    	<span><?=$this->translate('Menu_CurrentPosition')?></span><a href="/"><?=$this->translate('Menu_Home');?></a>&nbsp;&nbsp;»&nbsp;&nbsp;<span>搜索结果</span>&nbsp;&nbsp;»&nbsp;&nbsp;<b><?=$this->keyword?></b>        
    </div>
</div>

<div class="w clearfix ld">
	<div class="classfiy">
<h1><em><?=$this->keyword?></em> 的相关搜索结果<strong>（<?=$this->searchnum;?>）</strong></h1>
    
    </div>
	<?php if(!empty($this->allProd)){?>
    <table cellpadding="0" cellspacing="0" class="listtable">
    	<tbody>
        <tr>
        	<th width="18%">型号</th>
            <th width="10%">品牌</th>
            <th width="35%">产品描述</th>
            <th width="7%">库存</th>
            <th width="15%">阶梯价格</th>
            <th width="15%">操作</th>
        </tr>
        <?php 
        foreach($this->allProd as $k=>$prod){
			$prod = $this->fun->filterProduct($prod);
			$break_price='';$stock = 0;$show_price = 0;
			if($prod['f_show_price_sz']){
			    $show_price = $prod['f_show_price_sz'];
				$stock      = $prod['f_stock_sz'];
				$break_price = $prod['f_break_price_notitle_sz'];
			}elseif($prod['f_show_price_hk']){
			    $show_price = $prod['f_show_price_hk'];
				$stock      = $prod['f_stock_hk'];
				$break_price = $prod['f_break_price_notitle_hk'];
			}elseif($prod['f_break_price_notitle_sz']){
				$break_price = $prod['f_break_price_notitle_sz'];
			}elseif($prod['f_break_price_notitle_hk']){
				$break_price = $prod['f_break_price_notitle_hk'];
			}
			$bgclass='';
			if($k%2==1) $bgclass = 'class="tabletrf9"';
		?>
        <tr <?=$bgclass?>>
        	<td align="left" >
            <a href="<?=$prod['f_produrl']?>" class=" fontb fontwei fontblue logclick" title="<?=$prod['part_no']?>" target="_blank"  rev="search_part_id" rel="<?=$prod['id']?>">
			<?=str_ireplace($this->keyword,'<em>'.strtoupper($this->keyword).'</em>',$prod['part_no']);?></a>
            </td>
            <td><?=$prod['bname']?></td>
            <td align="left"><p title="<?=$prod['description']?>"><?=$this->fun->utf_substr($prod['description'],68)?></p></td>
            <td>
           <?php
                    if(($prod['f_stock_sz']+$prod['f_stock_hk'])>0){echo '<font color="#469F68">现货</font>';}
					else {echo '<font color="#FC9C30">订货</font>';}?>
            </td>

            <td><div class="price_btn_table"><?=($break_price?$break_price:'--')?></div></td>
            <td><div class="tabelbtn">
            <?php if(!$prod['noinquiry']){?>
                 <a href="javascript:" onclick="openInquiry('<?=$prod['id']?>')" class="abtnquestion logclick" title="询价"  rev="search_part_id" rel="<?=$prod['id']?>">询价</a>
            <?php }else{?>
            	<a class="abtnquestion_gray ">询价</a>
            <?php }?>
            
            <?php if($show_price){?><a href="javascript:" onclick="buy('<?=$prod['id']?>')"  class="abtnbuy logclick" title="购买"  rev="search_part_id" rel="<?=$prod['id']?>">购买</a>
            <?php }else{?>
            <a class="abtnbuy_gray ">购买</a>
            <?php }?></div></td>
        </tr>
        <?php } ?>
        </tbody>
        </table>
    <div class="pagination fr"><?=$this->page_bar;?></div>
    <?php }else{ //if(empty($this->allProd)){?>
     <div class="nodata" style="font-size:16px;"><strong>
     <?php if(isset($_SESSION['code'])){ echo $_SESSION['message'];}else{ echo '很抱歉，没有找到任何<em>'.$this->keyword.'</em>相关搜索结果。您可以提交型号，我们会尽快帮你寻找！';}?></strong></div>    
           <form id='searchform' name="searchform" action='' method='post'>
           <input type="hidden" name="type" value="2" />
            <?php  
	       if($this->reUser['mobile'] && $this->reUser['tel'])
		   	  $contact = $this->reUser['mobile'].';'.$this->reUser['tel'];
		   elseif($this->reUser['mobile'])
		      $contact = $this->reUser['mobile'];
		    else $contact = $this->reUser['tel'];
	      ?>
          	<div class="divtitbg1ts">
            <span class="titbg1ts">提交产品型号</span>
            <table cellpadding="0" cellspacing="0" class="table nodatatable">
                <tbody>
                <tr>
                    <td width="120" style="border-top:0" align="right">上线通知：</td>
                    <td width="210" align="left" style="border-top:0">
              			<input type="checkbox" name="notice" id="notice" value="1" checked="checked"/>
                    </td>
                    <td style="border-top:0"></td>
                </tr>
                <tr>
                    <td width="120" style="border-top:0" align="right"><em>*</em>型号：</td>
                    <td width="210" align="left" style="border-top:0">
              			<input type="text"  id="part_no" name="part_no" style="width:200px;" class="nreg_input" value="<?=$this->keyword?>"/>
                    </td>
                    <td style="border-top:0"><div id="part_noTip"></div></td>
                </tr>
                <tr>
                    <td width="120" style="border-top:0" align="right"><em>*</em>品牌：</td>
                    <td width="210" align="left" style="border-top:0">
              			<select id="brand" name="brand" onchange="showother(this.value)" style="width:210px;">
                        <option value=''>请选择品牌</option>
                        <?php foreach($this->allbrand as $k=>$v){
						    $sel = '';if($_SESSION['brand']==$v['name']) $sel='selected="selected"';
			                echo "<option value='".$v['name']."' $sel>".$v['name']."</option>";
		                }?>
                        <option value="Other">其它</option>
                        </select>
                        <div id="brand_other_div"></div>
                    </td>
                    <td style="border-top:0"><div id="brandTip"></div></td>
                </tr>
                
                <tr>
                    <td width="120" align="right"><em>*</em>联系人：</td>
                    <td width="210" align="left">
                       <input type="text" name="contact_name" id="contact_name" style="width:200px;" class="nreg_input" value="<?=$this->reUser['truename']?>"/>
              
                    </td>
                    <td><div id="contact_nameTip"></div></td>
                </tr>
                <tr>
                    <td width="120" align="right"><em>*</em>联系方式：</td>
                    <td width="210" align="left">
                         <input type="text" name="contact" id="contact"  style="width:200px;" class="nreg_input" value="<?=$contact?>"/>
              
                    </td>
                    <td><div id="contactTip"></div></td>
                </tr>
              
              <tr>
                <td align="right">说明：</td>
                <td align="left">
               <textarea name="explanation" id="explanation" rows="5" cols="27"></textarea>
                </td><td></td>
              </tr>
                <tr>
                  <td>&nbsp;</td>
                  <td align="left">
                  <input type="submit" title="提交" value="提交" onclick="checklogin()" class="button bigbutton"/>
                  </td>
                </tr>
            </tbody></table>
            </div>
		</form>

        <script src="/js/jsplug/formcheck/formValidator-4.1.1.js" type="text/javascript"></script>
		<script src="/js/jsplug/formcheck/formValidatorRegex.js" type="text/javascript"></script>
        <script type="text/javascript">
		
function checklogin(){
	$.ajax({
            url: '/index/checklogin',
            data: {},
            type: 'post',
            dataType: 'json',
            success: function(arr) {
			   if(arr.code==100){
			   	  $.openPopupLayer({
		             name: "loginBox",
		             target: "login_box"
	              });
			   }else if(arr.code==200){
			   	   window.location.href ="/user/verification";
			   }
            }
    });
}
function submitsearch(){
	$.ajax({
            url: '/index/checklogin',
            data: {},
            type: 'post',
            dataType: 'json',
            success: function(arr) {
			   if(arr.code==0)
			   {  
			      document.getElementById('searchform').submit();
			   }else if(arr.code==100){
			   	  $.openPopupLayer({
		             name: "loginBox",
		             target: "login_box"
	              });
			   }else if(arr.code==200){
			   	   window.location.href ="/user/verification";
			   }
            }
    });
}

        <?php if(isset($_SESSION['code']) && $_SESSION['code']==404){?>
            $.openPopupLayer({
		        name: "loginBox",
		        target: "login_box"
	        });
        <?php }?>
        $(document).ready(function(){
               $.formValidator.initConfig({formID:"searchform",onSuccess:function(){submitsearch();}});
               $("#part_no").formValidator({onFocus:"请输入型号",onCorrect:"&nbsp;"}).inputValidator({min:2,empty:{leftEmpty:false,rightEmpty:false,emptyError:"不能有空符号"},onError:"请输入型号"});
			   $("#brand").formValidator({onFocus:"请选择品牌",onCorrect:"&nbsp;"}).inputValidator({min:1,empty:{emptyError:"不能有空符号"},onError:"请选择品牌"});
               $("#contact_name").formValidator({onFocus:"请输入联系人",onCorrect:"&nbsp;"}).inputValidator({min:2,empty:{leftEmpty:false,rightEmpty:false,emptyError:"不能有空符号"},onError:"请输入联系人"});
               $("#email").formValidator({onShow:"请输入邮箱",onFocus:"请输入邮箱地址",onCorrect:"&nbsp;"}).inputValidator({min:1,max:100,onError:"请输入邮箱"}).regexValidator({regExp:"^([\\w-.]+)@(([[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}.)|(([\\w-]+.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(]?)$",onError:"输入的邮箱格式不正确"});
               $("#contact").formValidator({onFocus:"请输入联系方式",onCorrect:"&nbsp;"}).inputValidator({min:2,empty:{leftEmpty:false,rightEmpty:false,emptyError:"不能有空符号"},onError:"请输入联系方式"});
        })
        </script>
    <?php } //if(empty($this->allProd)){?>
     
     <br/>
     <table cellspacing="0" cellpadding="0" class="table nodatatable">
       <tbody>
           <tr>
              <td width="120" align="right" style="border-top:0"></td>
                    <td width="210" align="left" style="border-top:0">
              			<a onclick="window.external.AddSearchProvider('<?='http://'.$_SERVER['HTTP_HOST']?>/index/opensearch'); return false;" href="javascript:;" class="logclick" rev="searchplugin" rel="" title="点击添加搜索插件">添加IC易站搜索插件</a>，这样会让您更快使用到IC易站的搜索服务。
                    </td>
      </tr>
     </tbody></table>
     
</div>
<script language="javascript">
//选择其它
function showother(value){
    var obj = document.getElementById("brand_other_div");
	if(value=='Other'){
		obj.innerHTML='<input  type="text" name="brand_other" id="brand_other" style="width:200px;" class="nreg_input" value="<?=$_SESSION['brand_other']?>" />';
		document.getElementById("brand_other").focus();
	}else{
	    obj.innerHTML='';
	}
}
<?php if(isset($_SESSION['brand']) && $_SESSION['brand']=='Other'){?>
showother('Other');
<?php }?>
</script>

<?php unset($_SESSION['code']);
unset($_SESSION['message']);
unset($_SESSION['brand']);
unset($_SESSION['brand_other']);
?>