<div>
   <?php if(count($this->items) < 1){?>
   <table border="0" cellpadding="0" cellspacing="0" class="toptiptable">
   <tr><td> 购物车暂时没有产品，赶紧挑选喜欢的产品吧</td></tr>
    <?php }else{?>
     <table border="0" cellpadding="0" cellspacing="0" class="toptiptable">
      <tbody>
      <tr>
        <th width="160">型号</th>
        <th width="80">品牌</th>
        <th width="80">购买数量</th>
        <th width="50">单价</th>
        <th width="50">小计</th>
        <th width="50">&nbsp;</th>
      </tr>
           <?php
			foreach($this->items as $item){
				if(is_array($item)){
			?>
      <tr>
        <td>
            <p><a href="/item-0-0-<?=$item['pord_id'];?>-<?=$this->fun->filterUrl($item['part_no'])?>.html" target="_blank" class="model"><?=$item['part_no'];?></a></p>
          </td>
        <td><?=$item['options']['brand'];?></td>
        <td><?=$item['qty'];?></td>
        <td><?=$item['unit'].number_format($item['byprice'],DECIMAL);?></td>
        <td><?=$item['unit'].number_format($item['qty']*$item['byprice'],DECIMAL);?></td>
        <td><a href="javascript:" onclick="delectcart('<?=$item['rowid']?>')"  class="fblue">删除</a></td>
      </tr>
      <?php }//end if(is_array($item))
		 }//end foreach
	  ?>
    </tbody></table>
    <div class="bottomtable">
       <p><a class="abutton" href="/cart">去结算</a></p>
    </div> 
    <?php }?>
</div>
<script type="text/javascript">
$(".cartnumber").html('<?=count($this->items)?>');
</script>
