<link rel="stylesheet" href="/js/kindeditor/themes/default/default.css" />
<script src="/js/kindeditor/kindeditor.js"></script>
<script src="/js/kindeditor/lang/zh_CN.js"></script>
<style type="text/css">
span.tag{
border: 1px solid #DDD;
background: #F6F6F6 ;
font-weight: bold;
padding:3px 3px 0 3px;
margin-right:5px;
}
.tag a{ padding-left:5px;}
#ic-box{ margin-bottom:10px;}
</style>
<div class="conmian">
  <h1><a href="<?=$this->indexurl;?>"><?php echo $this->AreaTitle;?></a> -> 编辑产品 -> 型号<?=$this->product['part_no']?></h1> 
  <!-- <a href="<?php //$this->editpropertyurl.'/id/'.$this->product['id']?>">编辑产品选型</a>-->
  
<table class="tableContent">
    <tr>
    <td bgcolor="#FFFFFF" align="left" valign="top" width="770"><table width="740" border="0" cellspacing="0" cellpadding="0">
        <tr>
          <td height="10" colspan="3" align="center"><div id="message_sess" style="display:none" class="message_sess"> 
          <div title="关闭" class="but" onClick="document.getElementById('message_sess').style.display='none'">&nbsp;</div>
          <div id="alert_message"></div> 
          </div></td>
        </tr>
      </table>
       <!-- 需要填写的区域-->
<form class="validate-form"  method="post" action=""> 
    <table border="0">
     <tr>
        <td align="right">型号：</td>
        <td><input type="text" name="part_no" class="input-medium" value="<?=$this->product['part_no'];?>" ></td>
		 </tr>
		 <tr>
       <td align="right" height="50px">图片：</td>
        <td>
        <input type="hidden" id="url1" name="part_img" value="<?=PRODUCTICON.$this->product['part_img'];?>" />
        <input type="button" id="image1" value="选择图片" />
        <img src="<?=PRODUCTICON.$this->product['part_img'];?>" id="showimage1"  width="80" height="80" alt="img"/></td>
      </tr>
      <tr>
        <td align="right">制造商：</td>
        <td><input type="text" name="manufacturer" class="input-medium" value="<?=$this->product['manufacturer'];?>" ></td>
        <td align="right">品牌：</td>
        <td><select name="brand_id" id="brand_id"  class="input-medium">
        <?php foreach($this->brand as $bd){?>
        <option value="<?=$bd['id']?>" <?=$bd['id']==$this->product['manufacturer']?'selected':''?>><?=$bd['name']?></option>
        <?php }?>
        </select></td>
      </tr>

       <tr>
        <td align="right">产品分类：</td>
        <td colspan="3">
        <span id="part_level1_Span">
        <select id="part_level1" name="part_level1"><option value="">请选择一级分类</option></select>
        </span>
        <span id="part_level2_Span">
         <select id="part_level2" name="part_level2"><option value="">请选择二级分类</option></select>
        </span>
        <span id="part_level3_Span">
         <select id="part_level3" name="part_level3"><option value="">请选择三级分类</option></select>
         </span>
        </td>
      </tr>
      <tr><td align="right">产品参数：</td>
      <td colspan="3">
      <textarea name="attribute" id="attribute" style="width: 500px;height: 100px;"><?php echo $this->product['attribute'];?></textarea>
      </td></tr>

      
    </table>
  <div class="control-group" style="margin-left:280px">
    <div class="controls">
     <input type="submit" value="编 辑"  class="btnabig"/>
      &nbsp;&nbsp;&nbsp;&nbsp;<a href="<?php echo $this->indexurl;?>">返 回&gt;&gt;</a>
    </div>
  </div>
</form>
      <!-- 结束区域-->
    </td>
  </tr>
</table>
</div>
<script src="/js/jsplug/My97DatePicker/WdatePicker.js" type="text/javascript"></script>
<script type="text/javascript">
function selectlevel1(){
	var part_level1=$("#part_level1").val();
	$("#part_level2_Span").load("/icwebadmin/common/getlevel2?part_level1="+part_level1);
	$("#part_level3_Span").html("<select id=\"part_level3\" name=\"part_level3\"><option value=\"\">请选择三级分类</option></select>");
}
function selectlevel2(){
	var part_level2=$("#part_level2").val();
	$("#part_level3_Span").load("/icwebadmin/common/getlevel3?part_level2="+part_level2);
}
function onloadlevel(part_level1,part_level2,part_level3)
{
	$("#part_level1_Span").load("/icwebadmin/common/getlevel1?part_level1="+part_level1);
	if(part_level1 && part_level2)
	   $("#part_level2_Span").load("/icwebadmin/common/getlevel2?part_level1="+part_level1+"&part_level2="+part_level2);
    if(part_level2 && part_level3)
	   $("#part_level3_Span").load("/icwebadmin/common/getlevel3?part_level2="+part_level2+"&part_level3="+part_level3);
}
onloadlevel('<?=$this->product['part_level1']?>','<?=$this->product['part_level2']?>','<?=$this->product['part_level3']?>');

KindEditor.ready(function(K) {
				var editorparameters = K.create('#attribute', {
					height:300,
                    items : ['source', '|', 'undo', 'redo']
                });
			//产品图片
			var spe_head_editor = K.editor({
					allowFileManager : true,
					uploadJson : '/icwebadmin/common/editoruplodimg?part=upload/default/product/icon/',
                    fileManagerJson : '/icwebadmin/common/filemanagerjson?part=upload/default/product/icon/'
			});
			K('#image1').click(function() {
				spe_head_editor.loadPlugin('image', function() {
					spe_head_editor.plugin.imageDialog({
						imageUrl :  K('#url1').val(),
						clickFn : function(url, title, width, height, border, align) {
							K('#url1').val(url);
							K('#showimage1').attr("src",url);
							spe_head_editor.hideDialog();
						}
					});
				});
			});
			var editor = K.editor({
				allowFileManager : true,
				uploadJson : '/icwebadmin/common/editoruplod?part=upload/default/datasheet/',
                fileManagerJson : '/icwebadmin/common/filemanagerjson?part=upload/default/datasheet/'
		});				
	});
<?php if(isset($_SESSION['message'])){?>

	 document.getElementById('message_sess').style.display = "block";
	 document.getElementById('alert_message').innerHTML = '<?=$_SESSION['message']?>';

<?php unset($_SESSION['message']);}?>
</script>
<script src="/js/bootstrap/bootstrap.min.js" type="text/javascript"></script>