<link href="/js/jsplug/ajaxselect/jquery.autocomplete.css" rel="stylesheet">
<script src="/js/jsplug/ajaxselect/jquery.autocomplete.js" type="text/javascript"></script>
<?php 
$selecturl = "&brand=$this->selectbrand&ats=$this->ats";
?>
<div class="conmian">
  <h1><?php echo $this->AreaTitle;?> <a href="<?=$this->addurl?>">添加+</a></h1>
  <?php if($this->mycommon->checkA($this->Staff_Area_ID) || $this->mycommon->checkW($this->Staff_Area_ID)) {?>
    <a style="margin-left:10px;" href="/icwebadmin/CpCpgl/import" id="batch_update">批量更新产品+</a>
    <a href="#" style="margin-left:10px;"  id="big_box">批量上传产品图片+</a>
  <?php }?>

<form id="myform"  class="form-search" name="myform" action="" method="get">
<input type="hidden" name="type" value="<?=$this->type?>" />

<select name="brand">
<option value="">产品线-全部</option>
<?php foreach($this->brand as $bd){?>
<option value='<?=$bd['id']?>' <?=$bd['id']==$this->selectbrand?'selected':''?>><?=$bd['name']?></option>
<?php }?>
</select>
<label>Part No.：</label>
<div class="input-append">
  <input type="text" class="span3 search-query" style="width:60px;" id="partno" value="<?=$this->partno?>" name="partno" />
</div>
<a href="/icwebadmin/CpCpgl"  id = "seachsub" class="btn" target="_self">查 找</a>

</form>
          
  <div class="message_sess" style="display:none" id="message_sess"> 
          <div onclick="document.getElementById('message_sess').style.display='none'" class="but" title="关闭">&nbsp;</div>
          <div id="alert_message"></div> 
  </div>
    <div class="fr u_right">
    <div class="tab_content">
    <div class="tab_tit1">
        <ul class="fl">
         <li <?php if($this->type=='on') echo 'class="on"';?>><a href="/icwebadmin/CpCpgl?type=on<?=$selecturl?>">在线产品</a></li>
          <li <?php if($this->type=='nstock') echo 'class="on"';?>><a href="/icwebadmin/CpCpgl?type=stock<?=$selecturl?>">自营产品</a></li>
        </ul>
        </div>
      </div>
      <div class="tab_con mb10">
       <table class="table ordertable"  border="0">
          <thead>
           <tr>
            <th>型号</th>
            <th>制造商</th>
            <th>品牌</th>
            <th>图片</th>
            <th>操作</th>
            </tr>
            </thead>
          <tbody>
            <?php  if(empty($this->product)){?>
            <tr><td colspan="19"><center>暂无记录。</center></td></tr>
            <?php }else{
				 		foreach($this->product as $k=>$data){
						if($k%2==0) $bg = '';
						else $bg='class="tablebg"';
 				 ?>
            <tr <?=$bg?>>
                <td><div class="productNO"><?=$data['part_no']?></div>
                </td>
                <td><?=$data['manufacturer']?></td>
                <td><?=$data['bname']?></td>
                <td><img src="<?php echo ($data['part_img']) ? PRODUCTICON.$data['part_img'] : PRODUCTICON."no.gif" ;?>"  width="50" height="50" alt="img"/></td>
                <td><a href="<?=$this->editurl.'/id/'.$data['id']?>">编辑</a>
                </td>
            </tr>
          <?php }}?>
          </tbody>
          
        </table>
    <div class="pagination divpage"><?=$this->page_bar;?></div>
  </div>
</div>
</div>

<link rel="stylesheet" href="/js/kindeditor/themes/default/default.css" />
<script src="/js/kindeditor/kindeditor.js"></script>
<script src="/js/kindeditor/lang/zh_CN.js"></script>
<script type="text/javascript" language="javascript">
$(function(){
	$('#derive').click(function(){
		$('#myform')[0].action = this.href;
		$('#myform')[0].target="_blank";
		$('#myform').submit();
		return false;
	});
	$('#seachsub').click(function(){
		$('#myform')[0].action = this.href;
		$('#myform')[0].target ="_self";
		$('#myform').submit();
		return false;
	});
	
});
				
KindEditor.ready(function(K) {
			 //datasheet
			var datasheet_editor = K.editor({
					allowFileManager : true,
					uploadJson : '/icwebadmin/common/editoruplod?part=upload/default/datasheet/',
                    fileManagerJson : '/icwebadmin/common/filemanagerjson?part=upload/default/datasheet/'
			});
			K('#datasheet_box').click(function() {
				datasheet_editor.loadPlugin('insertfile', function() {
					datasheet_editor.plugin.fileDialog({
						fileUrl : '',
						clickFn : function(url, title) {
							datasheet_editor.hideDialog();
						}
					});
				});
			});		
			
			//产品大图
			var spe_head_editor = K.editor({
					allowFileManager : true,
					uploadJson : '/icwebadmin/common/editoruplodimg?part=upload/default/product/big/',
                    fileManagerJson : '/icwebadmin/common/filemanagerjson?part=upload/default/product/big/'
			});
			K('#big_box').click(function() {
				spe_head_editor.loadPlugin('insertfile', function() {
					spe_head_editor.plugin.fileDialog({
						fileUrl : '',
						clickFn : function(url, title) {
							spe_head_editor.hideDialog();
						}
					});
				});
			});	
			
});
$('.colorbox').colorbox({ 
		'width':"60%",
		'opacity':0.1});
//查看订单
function openEdit(){
	$.openPopupLayer({
		name: "editBox",
		url: "<?=$this->editurl.'/id/'.$data['id']?>"
	});
}
	function check(){
		var partno = document.getElementById('partno').value;
		if(partno=="") {alert("请填入Part No.！");document.getElementById('partno').focus();return;}
		else $('#myform').submit();
	}

	$(document).ready(function() {
			$("#partno").autocomplete("<?=$this->ajaxtag?>",
			{
				delay:5,
            	minChars:3,
            	matchSubset:1,
            	matchContains:1,
            	cacheLength:10,
            	onItemSelect:selectItem,
            	onFindValue:findValue,
            	formatItem:formatItem,
            	autoFill:false
        	}
    		);
			});
			function findValue(li) {
    			if( li == null ) return alert("No match!");
				if( !!li.extra ) var sValue = li.extra[0];
				else var sValue = li.selectValue;
				}
			function selectItem(li) { findValue(li);}
			function formatItem(row) { return row[0];//return row[0] + " (id: " + row[1] + ")"//如果有其他参数调用row[1]，对应输出格式Sparta|896
			}
			function lookupAjax(){
			var oSuggest = $("#partno")[0].autocompleter;
			oSuggest.findValue();
			return false;
			}
</script>