
	<div class="conmian">
	<h1><?php echo $this->AreaTitle;?>
    <?php if($this->record){?>
   -> <a href="/icwebadmin/RepoLab/export?sdata=<?=$this->sdata?>&edata=<?=$this->edata?>" target="_blank" title="将搜索结果导出成Excel">导出Excel</a>
  <?php }?>
    </h1>
    
     <form id="myform"  class="form-search" name="myform" action="" method="get">
    <label>开始时间：</label>
    <input type="text"  style="width:80px;" name="sdata" value="<?=$this->sdata?>" onclick="WdatePicker({startDate:'',dateFmt:'yyyy-MM-dd',alwaysUseStartDate:true,lang:'sc'})"/>
    <label>结束时间：</label>
    <input type="text"  style="width:80px;" name="edata" value="<?=$this->edata?>" onclick="WdatePicker({startDate:'',dateFmt:'yyyy-MM-dd',alwaysUseStartDate:true,lang:'sc'})"/>
&nbsp;
    <input type="submit" class="btn" value="确 定"/>
  </form>
  
				<div id="message_sess" style="display:none" class="message_sess"> 
          <div title="关闭" class="but" onclick="document.getElementById('message_sess').style.display='none'">&nbsp;</div>
          <div id="alert_message"></div> 
          </div>
	  <!-- 需要填写的区域-->
      <br/>
      <table width="100%" cellspacing="0" cellpadding="0" border="1" align="center" style="border-collapse:collapse;font-size: 12px;border:1px #999 solid;padding-top:0px;">
    <tbody>
      <tr bgcolor="#00B0F0" style="color:#FFFFFF; font-weight:bold;">
      	<th >器材类型</th>
        <th >实验器材</th>
        <th >器材型号</th>
        <th >器材品牌</th>
        <th >地点</th>
        
        
		<th >项目名称</th>
        <th >项目描述</th>
        
        <th>申请客户</th> 
        <th>客户情况</th>
        <th>使用时间</th>  
        
        <th>联络人</th> 
        <th >电话</th>
        <th >邮箱</th>
        
        <th >协助人</th> 
        <th >协助人部门</th> 

      </tr>
    </tbody>
    <tbody>
      <?php if($this->record){
	    foreach($this->record as $v){
	  ?>
      <tr height="30px">
      <td><?=$v['inst']['roomname']?></td>
      <td><?=$v['inst']['ins_name']?></td>
      <td><?=$v['inst']['model']?></td>
      <td><?=$v['inst']['brand']?></td>
      <td><?=$v['city']?></td>
      
      <td><?=$v['project_name']?></td>
      <td><?=$v['project_des']?></td>
      
      <td><?=$v['company']?></td>
      <td><?=$v['customer']==2?$v['follow']:'新客户'?></td>
      <td><?=$v['vist_time']?></td>
      
      <td><?=$v['contact']?></td>
      <td><?=$v['phone']?></td>
      <td><?=$v['email']?></td>
      
      <td><?=$v['help_name']?></td>
	  <td><?=$v['help_dep']?></td>

      </tr>
      <?php }}else echo '<tr height="30px"><td colspan="21" align="center" style="color:#FF0000">请选择时间段查询</td></tr>';?>
        </tbody>
  </table>
      <!-- 结束区域-->
	</div>
 <script src="/js/jsplug/My97DatePicker/WdatePicker.js" type="text/javascript"></script>