<div id="myHiddenDiv">
<div class="popup" style="width:800px">
<div class="popup-header">
  <h2>编辑负责应用领域</h2>
  <a href="javascript:;" onclick="$.closePopupLayer('editBox');" title="关闭" class="dialogBoxClose">关闭</a> </div>
<div class="popup-body">
<!-- 需要填写的区域-->
<table width="700px" border="0" cellpadding="1">
<tr>
  <td height="10" align="center"><div id="message_sess_son" style="display:none" class="message_sess"> <span title="关闭" class="but" onclick="document.getElementById('message_sess_son').style.display='none'"></span> <span id="alert_message_son"></span> </div></td>
</tr>
<tr>
  <td><!---->
    <table width="700" border="0" cellspacing="0" cellpadding="0" bgcolor="#FFFFFF">
      <tr bgcolor="99FFFF">
        <td width="719" height="29" align="left" bgcolor="#FFFFFF"><table width="700" bgcolor="#FFFFCC" >
            <tr>
              <td width="126" align="right"><font color="#666600"><b>用户： </b></font></td>
              <td colspan="3" align="left"><?=$this->StaffInfo['staff_id']?></td>
            </tr>
            <tr>
              <td width="126" align="right"><font color="#666600"><b>姓名： </b></font></td>
              <td colspan="3" align="left"><?=$this->StaffInfo['lastname'].$this->StaffInfo['firstname']?></td>
            </tr>
            <tr>
              <td width="126" align="right" valign="top"><font color="#666600"><b>负责应用领域: </b></font></td>
              <td colspan="3"  align="left">
              <table width="100%"><tr height="30">
				<?php
                 foreach($this->provincearr as $i=>$apparr){
                        $app_rule = explode(",",$this->StaffInfo['app_rule']);
                        if(in_array($apparr['id'],$app_rule)) $checked = 'checked';
                        else $checked = '';
                        echo '<td align="left">
						<input type="checkbox" name="app_rule" value="'.$apparr['id'].'" '.$checked.'>'.$apparr['name'].'</td>';
                        if($i!=0 && ($i+1)%4==0) echo '<tr>';
                    }
                ?></table></td>
            </tr>
            <tr height="50px">
              <td colspan="4" align="center"><input type="button"  value="更新" onclick="editappaction('<?=$this->StaffInfo['staff_id']?>')"/></td>
            </tr>
          </table>
          <!---->
        </td>
      </tr>
    </table>
    <!-- 结束区域-->
</div>
</div>
</div>