<?php $lab = explode(",",$this->StaffInfo['lab_rule']);?>

<div class="popup" style="width:800px">
  <div class="popup-header">
    <h2>编辑实验室负责权限</h2>
    <a href="javascript:;" onclick="$.closePopupLayer('box');" title="关闭" class="dialogBoxClose">关闭</a> </div>
  <div class="popup-body">
    <table width="700" bgcolor="#FFFFCC" >
      <tr>
        <td width="126" align="right"><font color="#666600"><b>用户： </b></font></td>
        <td colspan="3" align="left"><?=$this->StaffInfo['staff_id']?></td>
      </tr>
      <tr>
        <td width="126" align="right"><font color="#666600"><b>姓名： </b></font></td>
        <td colspan="3" align="left"><?=$this->StaffInfo['lastname'].$this->StaffInfo['firstname']?></td>
      </tr>
      <tr>
        <td width="126" align="right" ><font color="#666600"><b>首页统计: </b></font></td>
        <td colspan="3"  align="left"><table width="100%">
            <tr>
            <tr>
              <?php foreach($this->place as $place){?>
   			<td><input type="checkbox" name="statistics" value="<?=$place['id']?>" <?=(in_array($place['id'],$lab)?'checked="checked"':'')?>><?=$place['city']?></td>
            <?php }?>
            </tr>
          </table></td>
      </tr>
      <tr height="50px">
        <td colspan="4" align="center"><input type="button"  value="更新" onclick="editstatistics()"/></td>
      </tr>
    </table>
  </div>
</div>
<script type="text/javascript" language="javascript">
function editstatistics()
{
    var  statistics = new Array();
	var statisticsobj = document.getElementsByName('statistics');
	for(i=0;i<statisticsobj.length;i++){
	  if(statisticsobj[i].checked){
	     statistics[i] = statisticsobj[i].value;
	  }
	}
	$.ajax({
            url: '<?=$this->indexurl?>/lab',
            data: {'staff_id':'<?=$this->StaffInfo['staff_id']?>','statistics':statistics},
            type: 'post',
            dataType: 'json',
            success: function(arr) {
              if(arr.code == 0){
            	  alert(arr.message);
				  $.closePopupLayer('box');
				  showMainInfo('<?=$this->StaffInfo['staff_id']?>');
               }else{
			      alert(arr.message);
			   }
			}
	});
}
</script>