<?php $statistics = explode(",",$this->StaffInfo['statistics']);?>

<div class="popup" style="width:800px">
  <div class="popup-header">
    <h2>编辑首页统计</h2>
    <a href="javascript:;" onclick="$.closePopupLayer('box');" title="关闭" class="dialogBoxClose">关闭</a> </div>
  <div class="popup-body">
    <table width="700" bgcolor="#FFFFCC" >
      <tr>
        <td width="126" align="right"><font color="#666600"><b>用户： </b></font></td>
        <td colspan="3" align="left"><?=$this->StaffInfo['staff_id']?></td>
      </tr>
      <tr>
        <td width="126" align="right"><font color="#666600"><b>姓名： </b></font></td>
        <td colspan="3" align="left"><?=$this->StaffInfo['lastname'].$this->StaffInfo['firstname']?></td>
      </tr>
      <tr>
        <td width="126" align="right" ><font color="#666600"><b>首页统计: </b></font></td>
        <td colspan="3"  align="left"><table width="100%">
            <tr>
            <tr>
              <td><label><input type="checkbox" name="statistics" value="quarterly"  <?=(in_array('quarterly',$statistics)?'checked="checked"':'')?>>季度统计</label></td>
              <td><label><input type="checkbox" name="statistics" value="income"  <?=(in_array('income',$statistics)?'checked="checked"':'')?>>交易总金额统计</label></td>
              <td><label><input type="checkbox" name="statistics" value="basic" <?=(in_array('basic',$statistics)?'checked="checked"':'')?>>基本数据统计</label></td>
              <td><label><input type="checkbox" name="statistics" value="product"  <?=(in_array('product',$statistics)?'checked="checked"':'')?>>产品统计</label></td>
              <td><label><input type="checkbox" name="statistics" value="online"  <?=(in_array('online',$statistics)?'checked="checked"':'')?>>在线人数统计</label></td>
            </tr>
          </table></td>
      </tr>
      <tr height="50px">
        <td colspan="4" align="center"><input type="button"  value="更新" onclick="editstatistics()"/></td>
      </tr>
    </table>
  </div>
</div>
<script type="text/javascript" language="javascript">
function editstatistics()
{
    var  statistics = new Array();
	var statisticsobj = document.getElementsByName('statistics');
	for(i=0;i<statisticsobj.length;i++){
	  if(statisticsobj[i].checked){
	     statistics[i] = statisticsobj[i].value;
	  }
	}
	$.ajax({
            url: '<?=$this->indexurl?>/statistics',
            data: {'staff_id':'<?=$this->StaffInfo['staff_id']?>','statistics':statistics},
            type: 'post',
            dataType: 'json',
            success: function(arr) {
              if(arr.code == 0){
            	  alert(arr.message);
				  $.closePopupLayer('box');
				  showMainInfo('<?=$this->StaffInfo['staff_id']?>');
               }else{
			      alert(arr.message);
			   }
			}
	});
}
</script>