<link rel="stylesheet" href="/js/jsplug/formvalidator/css/validationEngine.jquery.css" media="screen" type="text/css"/>
<link rel="stylesheet" href="/js/jsplug/formvalidator/css/template.css" media="screen" type="text/css"/>
<link rel="stylesheet" href="/css/default/login.css" media="screen" type="text/css"/>
<script src="/js/jsplug/formvalidator/js/jquery.validationEngine-en.js" type="text/javascript"></script>
<script src="/js/jsplug/formvalidator/js/jquery.validationEngine.js" type="text/javascript"></script>

<script language="javascript">	
		$(document).ready(function() {
			$("#formID").validationEngine()
		});
</script>
<div id="header" class="w">
  <div id="logo"><a hidefocus="true" href="/"><img alt="盛芯电子" src="/images/default/logo.jpg"></a></div>
  <h1>会员登录</h1>
</div>
<form id="formID" name="formID" method="post" action="">
  <!--content-->
  <div class="w">
    <div class="line"></div>
    <div class="fl loginad">
      	<img src="/images/default/ad/welcom.jpg" />
    </div>
    <div class="login fr" >
      <div class="f-box">
        <label class="f-label"> 账户名：</label>
        <div class="f-input">
          <input class="validate[required] f-txt" type="text" name="loginname" id="loginname" value="<?=$this->loginname==''?'用户名/邮箱':$this->loginname;?>" onfocus="inputFocus($(this),'用户名/邮箱');" onblur="inputBlur($(this),'用户名/邮箱')"/>
        </div>
      </div>
      <div class="f-box">
        <label class="f-label"> 密&nbsp;&nbsp;&nbsp;码：</label>
        <div class="f-input">
          <input type="password" class="validate[required,length[6,25]] f-txt pass-txt" value="" id="password" name="password">
        </div>
      </div>
      <?php if(isset($_SESSION['needcode']) && $_SESSION['needcode']>$this->needcodenum){?>
      <div class="f-box">
        <label class="f-label"> 验证码：</label>
        <div class="f-input">
          <input class="validate[required]" style=" width:50px; margin-right:5px;" type="text" name="verifycode" id="verifycode" />
          <div class="f-vcode"> <a onclick="getVerify()" href="javascript:;" title="看不清？换一张"><img src="" id="verify"/>&nbsp;看不清？换一张</a> </div>
        </div>
      </div>
<script language="javascript">
function getVerify(){
 var d = new Date();
 document.getElementById('verify').src="<?php echo $this->url(array('controller'=>'common','action'=>'createcode'));?>?t="+d.toTimeString();
}
$(document).ready(function(){
 getVerify();
})
<?php if(!empty($this->verifycodeMess)){?>
var verifycode=document.getElementById("verifycode");
$.validationEngine.buildPrompt(verifycode,"<?php echo $this->verifycodeMess;?>","error");
verifycode.focus();
<?php }?>
</script>
      <?php }?>
      <div class="login-btn">
      <input type="submit" value="登  录" class="button" onclick="loginaction()"/>
      <a href="/user/forgotpass">忘记密码？</a> </div>
      
      <div class="reg-box">
        <p>还不是盛芯电子会员？马上加入吧~~~</p>
        <div class="reg-btn"> <a class="buttongray" href="/user/register">免费注册 &raquo;</a> </div>
      </div>
    </div>
  </div>
</form>
<script language="javascript">
function loginaction(){
	var uname   =document.getElementById("loginname");
	var password=document.getElementById("password");
	
	if(uname.value=='' || uname.value=='用户名/邮箱'){
	   $.validationEngine.buildPrompt(uname,"*不能为空","error");
	   uname.focus();
	   return;
	}
	if(password.value==''){
	   $.validationEngine.buildPrompt(password,"*不能为空","error");
	   password.focus();
	   return;
	}else if(password.value.length<6){
	   $.validationEngine.buildPrompt(password,"*请输入 6 - 25 长度的字符","error");
	   password.focus();
	   return;
	}
 <?php if(isset($_SESSION['needcode']) && $_SESSION['needcode']>$this->needcodenum){?>	
	var verifycode=document.getElementById("verifycode");
	if(verifycode.value==''){
	   $.validationEngine.buildPrompt(verifycode,"*不能为空","error");
	   verifycode.focus();
	   return;
	}
 <?php }?>
}


<?php if(!empty($this->loginnameMess)){?>
var uname=document.getElementById("loginname");
$.validationEngine.buildPrompt(uname,"<?php echo $this->loginnameMess;?>","error");
uname.focus();
<?php }?>
<?php if(!empty($this->passwordMess)){?>
var password=document.getElementById("password");
$.validationEngine.buildPrompt(password,"<?php echo $this->passwordMess;?>","error");
password.focus();
<?php }?>
</script>
