<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<script src="/js/jsplug/jquery.1.8.2.min.js" type="text/javascript"></script>
<script src="/js/default/base.js" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" href="/css/default/base.css"/>

<link rel="stylesheet" href="/js/jsplug/formvalidator/css/validationEngine.jquery.css" media="screen" type="text/css"/>
<link rel="stylesheet" href="/js/jsplug/formvalidator/css/template.css" media="screen" type="text/css"/>
<script src="/js/jsplug/formvalidator/js/jquery.validationEngine-en.js" type="text/javascript"></script>
<script src="/js/jsplug/formvalidator/js/jquery.validationEngine.js" type="text/javascript"></script>
<script language="javascript">	
		$(document).ready(function() {
			$("#formID").validationEngine();
		});
</script>
<form id="formID" method="post" action="/user/login">
<!--content-->
<!--登录弹出框 弹出框-->

        <div class="popcon clearfix" style="margin-top:10px;">
          <div class="login ">
            <div class="f-box">
                <label class="f-label">账户名：</label>
                <div class="f-input">
                   <input class="validate[required] f-txt" type="text" name="loginname" id="loginname" value="用户名/邮箱" onfocus="inputFocus($(this),'用户名/邮箱');" onblur="inputBlur($(this),'用户名/邮箱')"/>
                </div>
                <div class="f-msg">
                    <div id="divLoginTip">
                    
                    </div>
                </div>
            </div>
            <div class="f-box">
                <label class="f-label">
                    密&nbsp;&nbsp;&nbsp;码：</label>
                <div class="f-input">
                    <input type="password" class="validate[required,length[6,25]] f-txt pass-txt" value="" id="password" name="password" onkeydown="enter(event)">
                </div>
                <div class="f-msg">
                    <div id="divPasswordTip">
                    </div>
                </div>
            </div>
           
            <div class="f-box"  id="verifycode_dl" style="display:none">
                <label class="f-label">
                    验证码：</label>
                <div class="f-input">
                    <input class="validate[required] f-txt" style=" width:50px; margin-right:5px;"  onkeydown="enter(event)" type="text" name="verifycode" id="verifycode" />
                    <div class="f-vcode">
                        <a style="cursor:pointer" onClick="getVerify()" title="看不清？换一张" ><img src="" id="verify"/></a>
                         <a style="cursor:pointer" onClick="getVerify()" >看不清？换一张</a></dd>
                    </div>
                </div>
            </div>
            
             <div class="f-box f-password">
                <label class="f-label">&nbsp;</label>
                <div class="f-input">
                    <!--<a href="/user/forgotpass"  target="_blank" onclick="javascript:parent.location.replace('/user/forgotpass');">忘记密码？</a>-->
                    <a href="/user/forgotpass"  target="_blank">忘记密码？</a>
                </div>
            </div>
            <div class="login-btn">
                <a class="button" href="javascript:;" onclick="loginaction()" >登  录</a>
                <a class="buttongray" href="/user/register" target="_blank" >注  册</a>
            </div>
    </div>
        </div>

</form>
<script language="javascript">
<?php if(isset($_SESSION['needcode']) && $_SESSION['needcode']>$this->needcodenum){?>	
	document.getElementById("verifycode_dl").style.display = 'block';
	getVerify();
 <?php }?>
function getVerify(){
 var d = new Date();
 document.getElementById('verify').src="<?php echo $this->url(array('controller'=>'common','action'=>'createcode'));?>?t="+d.toTimeString();
}
function enter(evt){
    evt=evt?evt:(window.event?window.event:null);
    var keyCode = evt.keyCode;
	if(keyCode==13) loginaction();
}
function loginaction(){
	var uname   =document.getElementById("loginname");
	var password=document.getElementById("password");
	var verifycode=document.getElementById("verifycode");
	if(uname.value=='' || uname.value=='用户名/邮箱'){
	   $.validationEngine.buildPrompt(uname,"*不能为空","error");
	   uname.focus();
	   return;
	}
	if(password.value==''){
	   $.validationEngine.buildPrompt(password,"*不能为空","error");
	   password.focus();
	   return;
	}else if(password.value.length<6){
	   $.validationEngine.buildPrompt(password,"*请输入 6 - 25 长度的字符","error");
	   password.focus();
	   return;
	}
	 $.ajax({
            url: '/user/ajaxlogin',
            data: {'loginname':uname.value,'password':password.value,'verifycode':verifycode.value},
            type: 'post',
            dataType: 'json',
            success: function(arr) {
			   if(arr.needcode > <?=$this->needcodenum?>){
			   		document.getElementById("verifycode_dl").style.display = 'block';
					verifycode.focus();
					getVerify();
			   }
			   if(arr.code==0)
			   {	
					parent.location.replace('<?=$this->parenturl?>&snsuser='+arr.uid);
			   }else if(arr.code==100){
			       $.validationEngine.buildPrompt(uname,arr.message,"error");
	               uname.focus();		   
			   }else if(arr.code==200){
			       $.validationEngine.buildPrompt(password,arr.message,"error");
	               password.focus();		
			   }else if(arr.code==300){
			       $.validationEngine.buildPrompt(verifycode,arr.message,"error");
				   verifycode.value='';
	               verifycode.focus();	
			   }else if(arr.code==1){
				   parent.location.replace('/user/verification');
			   }
         }
    });
}
</script>
