<link rel="stylesheet" href="/js/jsplug/formvalidator/css/validationEngine.jquery.css" media="screen" type="text/css"/>
<link rel="stylesheet" href="/js/jsplug/formvalidator/css/template.css" media="screen" type="text/css"/>
<link rel="stylesheet" href="/css/default/loginbase.css" media="screen" type="text/css"/>
<script src="/js/jsplug/formvalidator/js/jquery.validationEngine-en.js" type="text/javascript"></script>
<script src="/js/jsplug/formvalidator/js/jquery.validationEngine.js" type="text/javascript"></script>

<script language="javascript">	
		$(document).ready(function() {
			$("#formID").validationEngine()
		});
</script>
<style>
	.wrap-login{width:100%; min-height: 370px;padding-top: 10px; overflow: hidden;background-color: #9dcf88;}
	.login-wrap{padding-top:50px; background:url('/images/default/loginbg.png') no-repeat; height: 400px;}
	.login-form2{padding: 0px 20px 20px 20px; background-color: #ffffff;min-height:294px;}
	.cart-footer{margin-top:0px;}
</style>

<div class="s-bd e-bd2">

<div class="uc-hd2">
    <div class="wrap clearfix" style="padding-top: 10px;">
       <h1 class="hd-logo">
            <a hidefocus="true" href="/"><img alt="盛芯电子" src="/images/default/logo.jpg"></a>
            <em>会员登录</em>
        </h1>
        <span class="fr mr5 mt40">
        还没有账号？现在 <a href="/user/register" class="cblue"><strong>注册</strong></a>
    </span>
    </div>
</div>



<div class="wrap-login">
<div class="wrap clearfix login-wrap g-b-box">
    <div class="login-form2 fr">
        <form id="formID" name="formID" method="post" action="">
        	<div class="mt15 h2">盛芯电子会员登录</div>
            <div class="dl-tbl login-tbl jsClearCont" style="padding-top: 10px;">
                <div class="error-tips hide" id="errorTips" style="width:262px;">
                    <i></i>请输入账号和密码
                </div>
                <dl style="margin-top:5px;">
                    <dd class="ipt-user rel">
                    <input class="validate[required] ipt ipt-user jsinput" type="text" name="loginname" id="loginname" value="<?=$this->loginname==''?'用户名/邮箱':$this->loginname;?>" onfocus="inputFocus($(this),'用户名/邮箱');" onblur="inputBlur($(this),'用户名/邮箱')"/>
                    <i></i>
                    </dd>
                </dl>
                <dl>
                    <dd class="ipt-pwd rel">
                    <input type="password" class="validate[required,length[6,25]] ipt ipt-pwd jsinput" value="" id="password" name="password">
                    <i></i>
                </dd>
                </dl>
                <?php if(isset($_SESSION['needcode']) && $_SESSION['needcode']>$this->needcodenum){?>
                <dl id="loginCode">
                    <dd>
                        <input class="validate[required] ipt verify-code-ipt" style=" width:50px;" type="text" name="verifycode" id="verifycode" />
          <div class="f-vcode"> <a onclick="getVerify()" href="javascript:;" title="看不清？换一张"><img src="" id="verify"/>&nbsp;看不清？换一张</a> </div>
                    </dd>
                </dl>
                <script language="javascript">
function getVerify(){
 var d = new Date();
 document.getElementById('verify').src="<?php echo $this->url(array('controller'=>'common','action'=>'createcode'));?>?t="+d.toTimeString();
}
$(document).ready(function(){
 getVerify();
})
<?php if(!empty($this->verifycodeMess)){?>
var verifycode=document.getElementById("verifycode");
$.validationEngine.buildPrompt(verifycode,"<?php echo $this->verifycodeMess;?>","error");
verifycode.focus();
<?php }?>
</script>
      <?php }?>
                <dl style="margin-top:15px;">
                    <dd style="display:block;">
                        <div class="clearfix">
                            <a class="cblue mr5 fr" href="/user/forgotpass">忘记密码?</a>
                        </div>
                    </dd>
                </dl>
                <dl style="margin-top:20px;">
                    <dd>
                        <input type="submit" value="登 录" class="login-btn-blue"  onclick="loginaction()"/>
                    </dd>
                </dl>
            </div>
        </form>
    </div>
</div>
</div>
</div>
<script language="javascript">
function loginaction(){
	var uname   =document.getElementById("loginname");
	var password=document.getElementById("password");
	
	if(uname.value=='' || uname.value=='用户名/邮箱'){
	   $.validationEngine.buildPrompt(uname,"*不能为空","error");
	   uname.focus();
	   return;
	}
	if(password.value==''){
	   $.validationEngine.buildPrompt(password,"*不能为空","error");
	   password.focus();
	   return;
	}else if(password.value.length<6){
	   $.validationEngine.buildPrompt(password,"*请输入 6 - 25 长度的字符","error");
	   password.focus();
	   return;
	}
 <?php if(isset($_SESSION['needcode']) && $_SESSION['needcode']>$this->needcodenum){?>	
	var verifycode=document.getElementById("verifycode");
	if(verifycode.value==''){
	   $.validationEngine.buildPrompt(verifycode,"*不能为空","error");
	   verifycode.focus();
	   return;
	}
 <?php }?>
}


<?php if(!empty($this->loginnameMess)){?>
var uname=document.getElementById("loginname");
$.validationEngine.buildPrompt(uname,"<?php echo $this->loginnameMess;?>","error");
uname.focus();
<?php }?>
<?php if(!empty($this->passwordMess)){?>
var password=document.getElementById("password");
$.validationEngine.buildPrompt(password,"<?php echo $this->passwordMess;?>","error");
password.focus();
<?php }?>
</script>