<link href="/css/default/register.css" media="screen" rel="stylesheet" type="text/css" />
<div id="header" class="w">
    <div id="logo"><a hidefocus="true" href="/"><img alt="盛芯电子" src="/images/default/logo.jpg"></a></div>
    <h1>找回密码</h1>
</div>
<!--content-->
<div class="w forgotpassword">
	<div class="registerline"></div>
    <div class="steps step-3">
        <ol>
            <li>验证身份</li>
            <li>重置密码</li>
            <li>完成</li>
        </ol>
    </div>
    <div class="RG_mbox fl lh">
        <div class="fl step2">
            <h1>恭喜，密码修改成功！</h1>
        	<p><input type="button" class="button" onclick="window.location.href='/user/login'" value="马上去登录"></p>
        
        </div>      	
    </div>
	<div class="rtip fr">
    	<h2>盛芯电子欢迎您！</h2>
        <p>盛芯电子 —— 一站式的电子元器件电子商务交易平台！ 全程设计链、供应链支持，为您提供产品、技术、服务、知识等专业服务！</p>
    </div>
</div>