<div id="header" class="w">
    <div id="logo"><a hidefocus="true" href="/"><img alt="盛芯电子" src="/images/default/logo.jpg"></a></div>
    <h1>会员注册</h1>
</div>
<link href="/css/default/register.css" media="screen" rel="stylesheet" type="text/css" />
<!--registerted-->
<div class="w register ">

	<div class="registerline"></div>
    <div class="steps step-2">
        <ol>
            <li>填写注册信息</li>
            <li>验证邮箱</li>
            <li>注册成功</li>
        </ol>
    </div>
    
    <div class="RG_mbox fl lh msg">
	        <div class="fl step2 ">
        	<?php if(!$this->success){
			unset($_SESSION['resendAction']);
			?>
        	<h1>验证码已经失效，请重新发送验证邮件！</h1>
        	<p><input type="button" onclick="javascript:window.open('/user/resend','_self')" class="button"  value="重新发送验证邮件"/></p>
        <?php }else{?>
        	<h1>恭喜您已注册账号，还差一步！</h1>
            <p>系统已经向 <?php echo $_SESSION['userInfo']['emailSession'];?> 发送一封账号激活邮件；</p>
            <p>请查看该邮件并进行邮箱验证(请在1小时内完成)；</p>
            <p>没有收到？可能被作为垃圾邮件，请到垃圾箱里找找看，或者<a href="/user/resend" style="color:#1a66b3">重新发送验证邮件</a></p>
        	<p class="mtb20">
        	<?php if($this->emailurl){?>
        	<input type="button"  class="button"  onclick="javascript:window.open('<?php echo $this->emailurl;?>','_blank')" value="现在就去邮箱认证"/>
        	<?php }?>
        	</p>
        <?php }?>
        </div>   
        <?php if(isset($_SESSION['resendAction']) && $_SESSION['resendAction']==1) echo '<div class="ok">成功发送验证邮件。</div>';?>   	
    </div>
	<div class="rtip fr">
    	<h2>盛芯电子欢迎您！</h2>
        <p>盛芯电子 —— 一站式的电子元器件电子商务交易平台！ 全程设计链、供应链支持，为您提供产品、技术、服务、知识等专业服务！</p>
    </div>
</div>
<!--content-->