<link rel="stylesheet" type="text/css"
	href="/css/default/buyprocess.css" />
<div id="header" class="w">
  <div id="logo"> <a hidefocus="true" href="/"><img alt="IC易站"
			src="/images/default/logo.jpg"></a> </div>
  <h1>我的购物车</h1>
</div>
<?php
$deliveryArr = array('SZ'=>'国内','HK'=>'香港');
$currencyArr = array('RMB'=>'人民币 RMB','USD'=>'美元 USD','HKD'=>'港币 HKD');
$annexur_part = COM_ANNEX.$_SESSION['userInfo']['uidSession'].'/';
$annexurl = $annexur_part.$this->myinfo['annex1'];
$annexurl2= $annexur_part.$this->myinfo['annex2'];
?>
<!--content-->
<div class="w buyprocess">
  <div class="registerline"></div>
  <div class="steps step-2">
    <ol>
      <li>我的购物车</li>
      <li>填写核对信息单</li>
      <li>成功提交订单</li>
    </ol>
  </div>
</div>
<div class="w lh Order">
  <h1>订单详情</h1>
  <div class="Order_details">
    <!--运费与快递-->
    <div id="div_shipment"  class="lines">
      <h2>配送方式：</h2>
      <div class="add_address 1h">
        <dl>
          <dt>交货地： </dt>
          <dd><strong><?php echo $deliveryArr[$this->delivery];?></strong></dd>
        </dl>
        <dl>
          <dt>配送方式： </dt>
          <dd>
            <?php if($this->delivery=='SZ'){
			  $delivery_type_checked = 'checked="checked"';
			?>
            <label>
            <input type="radio" name="delivery_type" value="1" class="delivery_type" <?=$delivery_type_checked?> >国内快递</label>
            <?php }elseif($this->delivery=='HK'){$delivery_type_checked='checked="checked"';?>
            <label><input type="radio" name="delivery_type" value="2" class="delivery_type" checked="checked">公司配送</label>&nbsp;&nbsp;
            <label><input type="radio" name="delivery_type" value="3" class="delivery_type">客户自提<span style="color:#F5811F">（免运费）</span></label>
             <label>
            <input type="radio" name="delivery_type" value="4" class="delivery_type">
            客户提供账号</label>
            <?php }?>
          </dd>
        </dl>
        <dl class="freight_show_1_2" style="display:<?=$delivery_type_checked?'block':'none'?>">
          <dt>运费及包装费：</dt>
          <dd>
            <table>
              <tr>
                <td><b class="fontred"><?php echo $this->unit.number_format($this->freight,DECIMAL)?></b></td>
              </tr>
              <tr>
                <td><img src="/images/default/car_icon.gif" /> <span class="fontgreen" >
                  <?php if($this->freight==0) echo '您本次购买总金额达到免运费及包装费标准，我们将减免您的运费及包装费。';
		  else echo '您本次购买总金额没有达到免运费及包装费标准， 购物满('.($this->delivery=='SZ'?'RMB'.$this->freermb:'USD'.$this->freeusd).')免运费及包装费。';
		  ?>
                  </span></td>
              </tr>
            </table>
          </dd>
        </dl>
        <dl class="freight_show_3" style="display:none">
          <dt>运费及包装费：</dt>
          <dd><b class="fontred"><?php echo $this->unit.number_format($this->packageprice,DECIMAL)?></b></dd>
        </dl>
        <dl class="freight_show_3" style="display:none">
          <dt>取货信息：</dt>
          <dd>
            <table>
              <tr>
                <td> 1)提货地址：
                  <?php if($this->delivery=='SZ'){echo $this->delivery_add_sz." ；联系电：".$this->delivery_tel_sz;}
		                       elseif($this->delivery=='HK'){echo $this->delivery_add_hk." ；联系电：".$this->delivery_tel_hk;}?>
                </td>
              </tr>
              <tr>
                <td>2)提货时间：
                  <?php if($this->delivery=='SZ'){echo $this->delivery_workdate_sz;}
		                       elseif($this->delivery=='HK'){echo $this->delivery_workdate_hk;}?>
                </td>
              </tr>
              <tr>
                <td>3)
                  <?php if($this->delivery=='SZ'){echo $this->delivery_des_sz;}
		                      elseif($this->delivery=='HK'){echo $this->delivery_des_hk;}?></td>
              </tr>
            </table>
          </dd>
        </dl>
        
        <dl class="freight_show_4" style="display:none">
          <dt>运费及包装费：</dt>
          <dd><b class="fontred"><?php echo $this->inquiry['currency'].' '.number_format($this->packageprice,DECIMAL)?></b></dd>
        </dl>
        <dl class="freight_show_4" style="display:none">
          <dt>发货信息：</dt>
          <dd>
           <?php if($this->expressadd){
				   $address_4 = $this->expressadd['address'];
				   $name_4 = $this->expressadd['name'];
				   $tel_4 = $this->expressadd['tel'];
				   $express_name_4 = $this->expressadd['express_name'];
				   $express_account_4 = $this->expressadd['express_account'];
			}
			?>
            <table>
              <tr>
                <td>1)收货地址：
                  <input type="text" style="width:500px;" name="address_4" id="address_4" value="<?=$address_4?>"/>  
				</td>
              </tr>
              <tr>
                <td>2)收&nbsp;货&nbsp;人&nbsp;：
                  <input type="text" style="width:200px;" name="name_4" id="name_4" value="<?=$name_4?>"/>  
				</td>
              </tr>
              <tr>
                <td>3)联系方式：
                  <input type="text" style="width:200px;" name="tel_4" id="tel_4" value="<?=$tel_4?>"/>  
				</td>
              </tr>
              <tr>
                <td>4)快&nbsp;递&nbsp;商&nbsp;：
                  <input type="text" style="width:200px;" name="express_name_4" id="express_name_4" value="<?=$express_name_4?>"/>
                </td>
              </tr>
              <tr>
                <td>5)快递账号：
                  <input type="text" style="width:200px;" name="express_account_4" id="express_account_4" value="<?=$express_account_4?>"/>
                </td>
              </tr>
              <tr>
                <td>6)公司名称：
                  <input type="text" style="width:200px;" name="companyname_4" id="companyname_4" value="<?php if($this->expressadd['companyname']) echo $this->expressadd['companyname'];else echo $this->myinfo['companyname'];?>"/>
                </td>
              </tr>
            </table>
          </dd>
        </dl>
        
        <div class="clr"></div>
      </div>
      <!--end 运费与快递-->
      <!--收货地址-->
      <div id="div_consignee" class="lines"  style="display:<?=$delivery_type_checked?'block':'none'?>">
        <h2> <span>收货信息 (<?=($this->delivery=='HK'?'请填写香港地址':'请填写国内地址')?>)：</span><span id="addcshow" style="display:<?php if(empty($this->addressFirst['name']))echo 'none';else echo 'block';?>"><a href="javascript:" onclick="showCgAdd()" class="a_operation">[修改]</a></span> <span id="addclose" style="display:<?php if(empty($this->addressFirst['name']))echo 'block';else echo 'none';?>"><a href="javascript:" onclick="closeCgAdd()" class="a_operation">[关闭]</a></span> </h2>
        <div class="add_address 1h" id="showaddress" style="display:<?php if(empty($this->addressFirst['name']))echo 'none';else echo 'block';?>">
          <dl>
            <dt>收&nbsp;货&nbsp;人&nbsp;：</dt>
            <dd><?php echo $this->addressFirst['name'];?></dd>
          </dl>
          <dl>
            <dt>详细地址：</dt>
            <dd><?php echo $this->addressFirst['province']." ".$this->addressFirst['city']." ".$this->addressFirst['area']." ".$this->addressFirst['address'];?></dd>
          </dl>
          <dl>
            <dt>邮政编码：</dt>
            <dd><?php echo $this->addressFirst['zipcode'];?></dd>
          </dl>
          <dl>
            <dt>公司名称：</dt>
            <dd><?php echo $this->addressFirst['companyname'];?></dd>
          </dl>
          <dl>
            <dt>入&nbsp;仓&nbsp;号&nbsp;：</dt>
            <dd><?php echo $this->addressFirst['warehousing'];?></dd>
          </dl>
          <dl>
            <dt>手&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;机：</dt>
            <dd><?php echo $this->addressFirst['mobile'];?></dd>
          </dl>
          <dl>
            <dt>固定电话：</dt>
            <dd><?php echo $this->addressFirst['tel'];?></dd>
          </dl>
        </div>
        <!--修改收货地址-->
        <div id="changeaddress" style="display:<?php if(empty($this->addressFirst['name']))echo 'block';else echo 'none';?>;">
          <form id='addressform' name="addressform" action='' method='post'>
            <input type="hidden" name="addressid" id="addressid" value="<?php echo $this->addressFirst['id'];?>" />
            <input type="hidden" name="tmp" id="tmp" value="<?php if(empty($this->addressFirst['name'])) echo 'add';else echo 'edit';?>" />
            <input type="hidden" name="addid" id="addid" value="<?php echo $this->addressFirst['id'];?>" />
            <div class="addresslist">
            <?php foreach($this->addressArr as $address){
			  if( ($this->delivery=='SZ' && $address['provinceid']!=810000)|| ($this->delivery=='HK' && $address['provinceid']==810000)){
			?>
            <input type="radio" name="addressradio" id="<?php echo $address['id'];?>" value="<?php echo $address['id'];?>" <?php if($this->addressFirst['id'] == $address['id']) echo "checked";?> onclick="editchange('<?php echo $address['id'];?>','edit')" />
            <span>
            <label for="<?php echo $address['id'];?>"><?php echo $address['name']." , ".$address['province']." ".$address['city']." ".$address['area']." ".$address['address']." , ".$address['zipcode']." , ".$address['mobile']." ".$address['tel'];?></label>
            </span> <a href="javascript:" onclick="deleteaddress('<?php echo $address['id'];?>')" class="fontblue ml10">[删除]</a><br />
            <?php }}?>
            <a href="javascript:" onclick="editchange('0','add')" class="a_operation">+添加新地址</a>
            </div>
            
            <div class="add_address 1h">
            <dl>
              <dt> <em>*</em>收&nbsp;货&nbsp;人&nbsp;： </dt>
              <dd>
                <input type="text" name="shrname" id="shrname" class="input120" value="<?php echo $this->addressFirst['name'];?>" />
                <div id="shrnameTip" style="position: absolute; top: 0; left: 250px;"></div>
              </dd>
            </dl>
            <dl>
              <dt> <em>*</em>地&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;区： </dt>
              <dd>
                <table>
                  <tr>
                    <td><span id="provinceSpan">
                      <select id="province" name="province">
                        <option value="">请选择省</option>
                      </select>
                      </span> <span id="citySpan">
                      <select id="city" name="city">
                        <option value="">请选择市</option>
                      </select>
                      </span> <span id="areaSpan" style="position: relative;">
                      <select id="area" name="area">
                        <option value="">请选择区</option>
                      </select>
                      </span>
                      <input type="hidden" id="areatmp" name="areatmp" value="<?php echo $this->addressFirst['areaid'];?>" /></td>
                    <td><div id="areatmpTip"></div></td>
                  </tr>
                </table>
              </dd>
            </dl>
            <dl>
              <dt> <em>*</em>详细地址： </dt>
              <dd>
                <textarea name="address" id="address" class="input340" rows="3" style="width:143px;"><?php echo $this->addressFirst['address'];?></textarea>
                <div id="addressTip" style="position: absolute; top: 0; left: 250px;"></div>
              </dd>
            </dl>
            <dl>
              <dt> 邮政编码： </dt>
              <dd>
                <input type="text" class="input120" name="zipcode" id="zipcode" value="<?php echo $this->addressFirst['zipcode'];?>" />
                <div id="zipcodeTip" style="position: absolute; top: 0; left: 250px;"></div>
              </dd>
            </dl>
            <dl>
              <dt>公司名称：</dt>
              <dd>
                <input type="text" class="input120" name="companyname" id="companyname" value="<?php if($this->addressFirst['companyname']) echo $this->addressFirst['companyname'];else echo $this->myinfo['companyname'];?>" />
                <div id="companynameTip" style="position: absolute; top: 0; left: 250px;"></div>
              </dd>
            </dl>
            <dl>
              <dt>入&nbsp;仓&nbsp;号&nbsp;：</dt>
              <dd>
                <input type="text" class="input120" name="warehousing" id="warehousing" value="<?php echo $this->addressFirst['warehousing'];?>"/>
           
              </dd>
            </dl>
            <dl>
              <dt> <em>*</em>手&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;机： </dt>
              <dd>
                <input type="text" class="input120" name="mobile" id="mobile" value="<?php echo $this->addressFirst['mobile'];?>" />
                或者 <span>固定电话：</span>
                <input type="text" class="input120" name="tel" id="tel" value="<?php echo $this->addressFirst['tel'];?>" />
                <span class="fontred" id="phomemsg"></span> </dd>
            </dl>
            <dl>
              <dt>设为默认：</dt>
              <dd>
                <input type="checkbox" name="default" id="default" value="1" <?php if($this->addressFirst['default']==1) echo "checked";?> />
              </dd>
            </dl>
            <p>
              <input type="submit" value="保存并送到这个地址" class="button" />
            </p> 
            </div>
          </form>
         
        </div>
      </div>
      <!--end修改收货地址-->
      <!--end 收货地址-->
      <!-- 付款-->
      <div id="div_shipment" class="lines">
        <h2>付款方式：</h2>
        <div class="addresslist" style="display: block">
          <div class="w_100" style="width: 840px;">
            <?php if($this->delivery=='SZ'){?>
            <p class="phover">
              <input type="radio" name="paymenttype" id="paymenttype2" value="online" onclick="payshow()" />
              <label for="paymenttype2"><b>在线支付</b></label>
              <span style="color: #878787">&nbsp;&nbsp;您需要预先拥有一张已开通网上支付功能的银行卡</span> </p>
            <div id="online_show" style="display: none;" class="openpayment">
              <p> 为了保证及时处理您的订单，请您于下单后<span style="color: #FF0000">&nbsp;24小时内&nbsp;</span>完成付款，否则订单将被自动取消 </p>
              <img src="/images/default/online.jpg"> </div>
            <?php }else {$paymenttype_checked = 'checked="checked"';}?>
            <p class="phover">
              <input type="radio" name="paymenttype" id="paymenttype1" value="transfer" <?=$paymenttype_checked?> onclick="payshow()" />
              <label for="paymenttype1"><b>银行汇款</b></label>
              <span style="color: #878787">&nbsp;&nbsp;您需要预先去银行转帐，所购商品将在款项到达IC易站帐户后发出</span> </p>
            <div class="openpayment" id="transfer_show" style="display:<?=($paymenttype_checked?'block':'none')?>;">
              <p> 请您及时汇款，<span class="fontred">48小时内</span>未完成汇款的订单将被自动取消。 </p>
              <div class="add_address 1h">
                 <?php if($this->delivery=='SZ'){?>
                <dl>
                  <dt>户名：</dt>
                  <dd>
                    <?=BANK_COM?>
                  </dd>
                </dl>
                <dl>
                  <dt>帐号：</dt>
                  <dd>
                    <?=BANK_ACCOUNT?>
                  </dd>
                </dl>
                <dl>
                  <dt>开户行：</dt>
                  <dd>
                    <?=BANK_NAME?>
                  </dd>
                </dl>
                  <?php }else{?>
                  <dl>
                  <dt>户名：</dt>
                  <dd>
                    <?=BANK_HK_COM?>
                  </dd>
                </dl>
                <dl>
                  <dt>帐号：</dt>
                  <dd>
                    <?=BANK_HK_ACCOUNT?>
                  </dd>
                </dl>
                <dl>
                  <dt>开户行：</dt>
                  <dd>
                    <?=BANK_HK_NAME?>
                  </dd>
                </dl>
                  <?php }?>
              </div>
            </div>
          </div>
          <div class="clr"></div>
        </div>
      </div>
      <!--end 付款-->
      <!--开发票-->
      <div class="invoice " style="display:<?=($this->delivery=='HK'?'none':'block')?>">
        <h2> <span>发票信息：</span> </h2>
        <input type="checkbox" name="needinvoice" id="needinvoice" value="yes" onclick="changeInvoice()" <?php if(isset($_SESSION['NeedInvoice']) && $_SESSION['NeedInvoice']=='yes') echo 'checked="checked"';?> />
        <label for="needinvoice"><b>需要发票</b></label>
        &nbsp;&nbsp;&nbsp;&nbsp;<span style="color: #878787">提供增值税发票和普通发票</span>
        <div id="changeinvoice">
          <h2> <span id="invcshow" style="display:<?php if(empty($this->invoiceFirst))echo 'none';else echo 'block';?>"> <a href="javascript:" onclick="showInvDiv()" class="a_operation">[修改]</a></span> <span id="invclose" style="display:<?php if(empty($this->invoiceFirst))echo 'block';else echo 'none';?>"> <a href="javascript:" onclick="closeInvDiv()" class="a_operation">[关闭]</a></span> </h2>
          <!---->
          <div class="add_address 1h" id="showinvoice" style="display:<?php if(empty($this->invoiceFirst))echo 'none';else echo 'block';?>">
            <dl>
              <dt>发票类型：</dt>
              <dd>
                <?php $typeArr = array ('1' => '普通发票','2' => '增值税发票' );
					echo $typeArr [$this->invoiceFirst ['type']];
			   ?>
              </dd>
            </dl>
            <?php if($this->invoiceFirst['type']==1){?>
            <dl>
              <dt>发票抬头：</dt>
              <dd><?php echo $this->invoiceFirst['name'];?></dd>
            </dl>
            <dl>
              <dt>发票内容：</dt>
              <dd>
                <?php $typeArr = array ('1' => '明细','2' => '电子元件','3' => '耗材' );
			echo $typeArr [$this->invoiceFirst ['contype']];
			?>
              </dd>
            </dl>
            <?php }else{?>
            <dl>
              <dt>单位名称：</dt>
              <dd>
                <?=$this->invoiceidTow['name'];?>
              </dd>
            </dl>
            <dl>
              <dt>纳税人识别号：</dt>
              <dd>
                <?=$this->invoiceidTow['identifier'];?>
              </dd>
            </dl>
            <dl>
              <dt>注册地址：</dt>
              <dd>
                <?=$this->invoiceidTow['regaddress'];?>
              </dd>
            </dl>
            <dl>
              <dt>注册电话：</dt>
              <dd>
                <?=$this->invoiceidTow['regphone'];?>
              </dd>
            </dl>
            <dl>
              <dt>开户银行：</dt>
              <dd>
                <?=$this->invoiceidTow['bank'];?>
              </dd>
            </dl>
            <dl>
              <dt>银行帐户：</dt>
              <dd>
                <?=$this->invoiceidTow['account'];?>
              </dd>
            </dl>
            <dl>
                <dt>营业执照：</dt>
                <dd>
                 <?php if(file_exists($annexurl) && $this->myinfo['annex1']){?><a href="<?='/'.$annexurl?>" target="_blank" title="查看">查看</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;营业执照如有更改，请点击 <a class="a_operation" onclick="showInvDiv()" href="javascript:">此处</a> 重新上传。
				 <?php }?>
                </dd>
             </dl>
             <dl>
                <dt>税务登记证：</dt>
                <dd>
                 <?php if(file_exists($annexurl2) && $this->myinfo['annex2']){?><a href="<?='/'.$annexurl2?>" target="_blank" title="查看">查看</a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;税务登记证如有更改，请点击 <a class="a_operation" onclick="showInvDiv()" href="javascript:">此处</a> 重新上传。
				 <?php }?>
                </dd>
             </dl>
            <?php }?>
            <!--发票地址-->
          <div id="add_address" class="address_invoiceid" style="margin-top:10px;">
            <dl>
              <dd><em>发票发送地址：</em> <span id="invaddvaule">默认为收货地址。</span> <span id="invadd"><a href="javascript:;" onclick="changeinvoiceadd('open')">修改</a></span></dd>
            </dl>
            <!--修改收货地址-->
            <div id="changeinvoiceadd" style="display:none">
              <div class="addresslist">
                <?php foreach($this->addressArr as $address){?>
                <p>
                  <input type="radio" name="invoiceaddressradio" id="<?php echo $address['id'];?>invoice" value="<?php echo $address['id'];?>" <?php if($this->addressFirst['id'] == $address['id']) echo "checked";?>/>
                  <span>
                  <label for="<?php echo $address['id'];?>invoice" id="<?php echo $address['id'];?>invoiceadd"><?php echo $address['name']." , ".$address['province']." ".$address['city']." ".$address['area']." ".$address['address']." , ".$address['zipcode']." , ".$address['mobile']." ".$address['tel'];?></label>
                  </span> </p>
                <?php }?>
                <p><a href="javascript:" onclick="saveinvoiceaddress()" class="button">保存</a> &nbsp;&nbsp; <a href="/center/address" target="_blank">去修改或添加收货地址&gt;&gt;</a> </p>
              </div>
            </div>
            <!--end修改收货地址-->
          </div>
          
          </div>
          <!--end 发票地址-->
        </div>
        <!-- -->
        <div class="invoice_box " id="div_invoice_box"  style="display:<?php if(empty($this->invoiceFirst)) echo 'block';else echo 'none';?>">
          <div class="invoice_tit">
            <p>请选择您需要的发票类型：</p>
            <p>
              <input type="radio" value="2" name="invoicetype" id="invoicetype2" <?php if($this->invoiceFirst['type']==2 || empty($this->invoiceFirst)) echo "checked";?> onclick="changeInvDiv(2)" />
              <label for="invoicetype2">增值税发票</label>
            </p>
            <p>
              <input type="radio" value="1" name="invoicetype" id="invoicetype1" <?php if($this->invoiceFirst['type']==1) echo "checked";?> onclick="changeInvDiv(1)" />
              <label for="invoicetype1">普通发票</label>
            </p>
          </div>
          <!--人民币增值税专用发票-->
          <form id='zengzhishuiform' name="zengzhishuiform" action='' method='post'>
            <div class="invoice_con "  style="display:<?php if($this->invoiceFirst['type']==2 || empty($this->invoiceFirst)) echo 'block';else echo 'none';?>" id="zengzhishui">
              <dl class="fore0">
                <dt><em>*</em>单位名称：</dt>
                <dd>
                  <input type="text" style="width:200px" name="dwname" id="dwname" value="<?php echo $this->invoiceidTow['name'];?>" />
                  <div id="dwnameTip" style="position: absolute; top: 0; left: 210px;"></div>
                </dd>
              </dl>
              <dl class="fore1">
                <dt><em>*</em>纳税人识别号：</dt>
                <dd>
                  <input type="text" style="width:200px" name="identifier" id="identifier" value="<?php echo $this->invoiceidTow['identifier'];?>" />
                  <div id="identifierTip" style="position: absolute; top: 0; left: 210px;"></div>
                </dd>
              </dl>
              <dl class="fore2">
                <dt><em>*</em>注册地址：</dt>
                <dd>
                  <input type="text" style="width:200px" name="regaddress" id="regaddress" value="<?php echo $this->invoiceidTow['regaddress'];?>" />
                  <div id="regaddressTip" style="position: absolute; top: 0; left: 210px;"></div>
                </dd>
              </dl>
              <dl class="fore3">
                <dt><em>*</em>注册电话：</dt>
                <dd>
                  <input type="text" style="width:200px" name="regphone" id="regphone" value="<?php echo $this->invoiceidTow['regphone'];?>" />
                  <div id="regphoneTip" style="position: absolute; top: 0; left: 210px;"></div>
                </dd>
              </dl>
              <dl class="fore4">
                <dt><em>*</em>开户银行：</dt>
                <dd>
                  <input type="text" style="width:200px" name="bank" id="bank" value="<?php echo $this->invoiceidTow['bank'];?>" />
                  <div id="bankTip" style="position: absolute; top: 0; left: 210px;"></div>
                </dd>
              </dl>
              <dl class="fore5">
                <dt><em>*</em>银行帐户：</dt>
                <dd>
                  <input type="text" style="width:200px" name="account" id="account" value="<?php echo $this->invoiceidTow['account'];?>" />
                  <div id="accountTip" style="position: absolute; top: 0; left: 210px;"></div>
                </dd>
              </dl>
              <dl class="fore6">
                <dt><em>*</em>营业执照：</dt>
                <dd>
                  <input type="file" name="fileToUpload" id="fileToUpload" class="w-200">
                  <div id="fileToUploadTip" style="position:absolute; top:0; left:250px;"></div>
				  <?php if(file_exists($annexurl) && $this->myinfo['annex1']){?><a href="<?='/'.$annexurl?>" target="_blank" title="查看">查看</a><?php }?>
                  
                </dd>
              </dl>
              <dl class="fore6">
                <dt><em>*</em>税务登记证：</dt>
                <dd>
                  <input type="file" name="fileToUpload2" id="fileToUpload2" class="w-200">
                  <div id="fileToUpload2Tip" style="position:absolute; top:0; left:250px;"></div>
				  <?php if(file_exists($annexurl2) && $this->myinfo['annex2']){?><a href="<?='/'.$annexur2?>" target="_blank" title="查看">查看</a><?php }?>
                </dd>
              </dl>
              <dl class="fore12" style="background: #efefef">
                <dt>&nbsp;</dt>
                <dd>
                  <input type="submit" class="button" value="保 存" />
                </dd>
              </dl>
              
              <div class="clr"></div>
              <div style="margin: 5px;"> <font color="#FF0000">如果您开具的是增值税专用发票，您在下单时需录入以下增值税专用发票资质信息：</font> <br />
                ——单位名称（必须是您公司营业执照上的全称）；<br />
                ——纳税人识别号（必须是您公司《税务登记证》的编号，一般为15位，请仔细核对后输入）；<br />
                ——注册地址（必须是您公司营业执照上的注册地址）；<br />
                ——注册电话（请提供能与您公司保持联系的有效电话）；<br />
                ——开户银行（必须是您公司银行开户许可证上的开户银行）；<br />
                ——银行账号（必须是您公司开户许可证上的银行账号）；<br />
                ——营业执照（必须真实，可以上传.JPG/.GIF/.PNG/.PDF/.ZIP/.RAR 格式的文件，单个文件大小不能超过1M）；<br />
                ——税务登记证（必须真实，可以上传.JPG/.GIF/.PNG/.PDF/.ZIP/.RAR 格式的文件，单个文件大小不能超过1M）。<br />
              </div>
            </div>
          </form>
          <!--end 人民币增值税专用发票-->
          <!--普通发票-->
          <form id='putongform' name="putongform" action='' method='post'>
            <input type="hidden" name="invoiceid" id="invoiceid" value="<?php echo $this->invoiceFirst['id'];?>" />
            <div class="invoice_con "  style="display:<?php if($this->invoiceFirst['type']==1) echo 'block';else echo 'none';?>"  id="putong">
              <dl class="fore0">
                <dt>发票抬头：</dt>
                <dd>
                  <input type="text" class="w-150" name="taitouname" id="taitouname" value="<?php echo $this->invoiceFirst['name'];?>" />
                  <div id="taitounameTip" style="position: absolute; top: 0; left: 160px;"></div>
                </dd>
              </dl>
              <dl class="fore10">
                <dt>发票内容：</dt>
                <dd>
                  <input type="radio" value="1" name="contype" id="contype1" <?php if($this->invoiceFirst['contype']==1 || empty($this->invoiceFirst)) echo "checked";?> />
                  <label for="contype1">明细</label>
                  <input type="radio" value="2" name="contype" id="contype2" <?php if($this->invoiceFirst['contype']==2) echo "checked";?> />
                  <label for="contype2">电子元件</label>
                  <input type="radio" value="3" name="contype" id="contype3" <?php if($this->invoiceFirst['contype']==3) echo "checked";?> />
                  <label for="contype3">耗材</label>
                </dd>
              </dl>
              <dl class="fore12" style="background: #efefef">
                <dt>&nbsp;</dt>
                <dd>
                  <input type="submit" class="button" value="保 存" />
                </dd>
              </dl>
            </div>
          </form>
        </div>
      </div>
      <!--end 普通发票-->
      
      <!-- 优惠券-->
      <?php if(!empty($this->coupon)){?>
      <div id="div_shipment">
        <h2><label><!--<input type="checkbox" name="usedcoupon" id="usedcoupon" value="yes" onclick="$('#coupon_show').toggle();"/>-->使用优惠券抵消部分总额：</label></h2>
           <div>
            <p class="phover"><b>提示：每张优惠券只能使用一次；优惠券可以多张同时使用，但总优惠金额如果超过购买产品金额，就按购买金额抵扣，优惠券剩余金额作废</b></p>
            <div class="add_address 1h" style="width:690px;">
                <div class="addresslist">
                <?php if(!empty($this->coupon)){
				$typearr = array('1'=>'型号数量优惠券','2'=>'通用金额优惠券','3'=>'品牌金额优惠券');
				foreach($this->coupon as $coupon){?>
                <span><label><input type="checkbox" name="coupon_check" class="coupon_check" value="<?=$coupon['code']?>">
                <font color="#006600"><?=$typearr[$coupon['type']]?></font>：
				<?php if($coupon['type']==1) {
				    echo "可以抵扣<em>".$coupon['buy_number']."</em>个<em>".$coupon['bname']."</em>的型号<em>".$coupon['part_no']."</em>";
			    }elseif($coupon['type']==2){
				    echo "可以抵扣金额：<em>RMB".$coupon['money_rmb']."</em>或者<em>USD".$coupon['money_usd']."</em>";
				}elseif($coupon['type']==3){
				    echo "可以抵扣品牌<em>".$coupon['bname2']."</em>金额：<em>RMB".$coupon['money_rmb']."</em>或者<em>USD".$coupon['money_usd']."</em>";
				}?>
                </label></span><br/>
                <?php } 
				}else{?>
                <span style="color:#FF0000">您暂时没有优惠券可以使用。</span><br/>
                <?php }?>
                <table><tr><td>使用工具客户名称<em>*</em>：</td><td><input type="text" value="" style="width:300px;"  id="customer" name="customer"></td></tr>
                <tr><td>预计产生的市场效益$/Y<em>*</em>：</td><td><input type="text" value="" style="width:300px;"  id="efficiency" name="efficiency"></td></tr>
                <tr><td>预计完成的效益时间<em>*</em>：</td><td><input type="text" value="" style="width:300px;"  id="effective_time" name="effective_time"></td></tr>
                </table>
                </div>
            </div>
          </div>
      </div>
      <?php }?>
      <!--end 优惠券-->  
      <div class="clr"></div>
    </div>
  </div>
  <div class="clr"></div>
  <!-- end 发票-->
  <!--产品详情-->
  <div class="Shopping_cart 1h">
    <h1>产品清单</h1>
    <div class="tipfree"> <img src="/images/default/car_icon.gif" alt="car_icon"><b class="fontgreen">购物满<?=$this->freetotl?>元免运费及包装费</b> </div>
    <table border="0" cellpadding="0" cellspacing="0" class="shopbox table ">
      <tbody>
        <tr>
          <th width="40%">型号</th>
          <th width="100">客户物料号</th>
          <th width="110">阶梯价格</th>
          <th>包装数</th>
          <th>购买数量</th>
          <th>单价</th>
          <th>小计</th>
        </tr>
        <?php foreach ( $this->items as $item ) {
		if (is_array ( $item )) {
		$rowid = $item ['rowid'];
		$inputid = 'pamount_' . $rowid;
		$priceid = 'price_' . $rowid;
		$itemtotalid = 'itemtotal_' . $rowid;
		?>
        <tr>
          <td style="border-right: 0"><div class="productinfo"> <img src="<?php echo PRODUCTICON.($item['options']['part_img']==''?'no.gif':$item['options']['part_img']);?>">
              <div class="productinfop">
                <p> <a href="/item-0-0-<?=$item['pord_id'];?>-<?=$this->fun->filterUrl($item['part_no'])?>.html" target="_blank"><?php echo $item['part_no'];?></a> </p>
                <p>
                  <?=$item['options']['brand'];?>
                </p>
                <p>
                  <?=$this->fun->utf_substr($item['options']['description'],68)?>
                </p>
              </div>
            </div></td>
          <td><input type="text" name="customer_material"/></td>
          <td><div class="price_btn_table">
              <?php if($item['options']['show_bprice']){echo $item['options']['show_bprice'];} else echo '--'?>
            </div></td>
          <td><?=$item['mpq'];?></td>
          <td><?php echo $item['qty'];?></td>
          <td><?php echo $item['unit'].number_format($item['byprice'],DECIMAL);?></td>
          <td><?php echo $item['unit'].number_format($item['byprice']*$item['qty'],DECIMAL);?></td>
        </tr>
        <?php
		} // end if(is_array($item))
	} // end foreach
	?>
        <tr>
          <td colspan="7" align="left" valign="center" height="30" style="background: #f9f9f9"><div class="rightp fr">
              <div id="total_need_freight" style="display:none">
                <p> 应付总额(含运费及包装费并减去优惠券金额)：<b class="price">
                  <?=$this->unit?>
                  <label name='cart_total' class="cart_total_freight"><?php echo number_format($this->total+$this->freight,DECIMAL);?></label>
                  </b> </p>

                  <p style="padding-top: 4px;"> 优惠券抵扣金额：<b class="fontred">
                  <?=$this->unit?><label class="deductions">0.00</label></b></p>
                  <p style="padding-top: 4px;"> 运费及包装费：<b class="fontred">
                  <?=$this->unit?>
                  <label name='freight'><?php echo number_format($this->freight,DECIMAL);?></label>
                  </b> - </p>
                  <p style="padding-top: 4px;"> 产品总金额：<b class="fontred">
                  <?=$this->unit?>
                  <label name='cart_total'><?php echo number_format($this->total,DECIMAL);?></label>
                  </b> + </p>
              </div>
              <div id="total_no_need_freight" style="display:none">
                <p> 应付总额(含包装费并减去优惠券金额)：<b class="price" >
                  <?=$this->unit?>
                  <label name='cart_total' class="cart_total_packageprice"><?php echo number_format($this->total+$this->packageprice,DECIMAL);?></label>
                  </b> 
                </p>
                </p>
                
                  <p style="padding-top: 4px;"> 优惠券抵扣金额：<b class="fontred">
                  <?=$this->unit?><label class="deductions">0.00</label></b></p>
                <p style="padding-top: 4px;"> 运费及包装费：<b class="fontred">
                  <?=$this->unit?>
                  <label name='freight'><?php echo number_format($this->packageprice,DECIMAL);?></label>
                  </b> -
                </p>
                <p style="padding-top: 4px;"> 产品总金额：<b class="fontred">
                  <?=$this->unit?>
                  <label name='cart_total'><?php echo number_format($this->total,DECIMAL);?></label>
                  </b> + 
                </p>
              </div>
              <div>
            </div></td>
        </tr>
        <tr height="38"><td align="left"  colspan="7">
          <label><input type="checkbox" name="needremark" id="needremark" value="1" onclick="$('#order_remark').toggle();"/>
          订单备注：</label><span id="order_remark" style="display:none">
         <input type="text" name="remark" id='remark' rows="3"  style="width:400px;" value="<?=trim($value[1])?>"></span></td></tr>
      </tbody>
    </table>
    <div class="bg_cart">
      <div class="fl"> <a href="/cart"><em></em>返回购物车，修改产品</a> </div>
      <div class="fr" id="orderbtn"> <a href="javascript:;" class="button" onclick="order()">提交订单</a> </div>
    </div>
  </div>
</div>
<script type="text/javascript">
var annexurl=0;
var annexurl2=0;
//没有营业执照
<?php if(!file_exists($annexurl) || !$this->myinfo['annex1']){?>annexurl = 1;<?php }?>
<?php if(!file_exists($annexurl2) || !$this->myinfo['annex2']){?>annexurl2 = 1;<?php }?>
var annexur_part='<?=$annexur_part?>';
var newname1='<?=md5(md5($_SESSION['userInfo']['uidSession']))."1"?>';
var newname2='<?=md5(md5($_SESSION['userInfo']['uidSession']))."2"?>';

$(function(){
		//配送方式
        $(".delivery_type").click(function(){
			if(this.value==1 || this.value==2){
			    
				$(".freight_show_1_2").css("display","block");
				$(".freight_show_3").css("display","none");
				$(".freight_show_4").css("display","none");
				//收货人信息
				$("#div_consignee").css("display","block");
				//金额总计
				$("#total_need_freight").css("display","block");
				$("#total_no_need_freight").css("display","none");
				$(".address_invoiceid").css("display","block");
			}else if(this.value==3){
			    
				$(".freight_show_1_2").css("display","none");
				$(".freight_show_3").css("display","block");
				$(".freight_show_4").css("display","none");
				//收货人信息
				$("#div_consignee").css("display","none");
				//金额总计
				$("#total_need_freight").css("display","none");
				$("#total_no_need_freight").css("display","block");
				$(".address_invoiceid").css("display","none");
			}else if(this.value==4){
				$(".freight_show_1_2").css("display","none");
				$(".freight_show_3").css("display","none");
				$(".freight_show_4").css("display","block");
				//收货人信息
				$("#div_consignee").css("display","none");
				//金额总计
				$("#total_need_freight").css("display","none");
				$("#total_no_need_freight").css("display","block");
				$(".address_invoiceid").css("display","none");
			}
        });
		<?php if($delivery_type_checked){?>
				//金额总计
				$("#total_need_freight").css("display","block");
				$("#total_no_need_freight").css("display","none");
				$(".address_invoiceid").css("display","block");
		<?php }?>
})
function order()
{
    var delivery_type_4_array = new Array();
    var customer_material       = new Array();
    var delivery_type = '';
    var needinvoice  = document.getElementById("needinvoice");
	var addressid    = document.getElementById("addressid").value;
	var invoiceid    = document.getElementById("invoiceid").value;
	var pyobj        = document.getElementsByName("paymenttype");
	var delivery_type_obj = document.getElementsByName("delivery_type");
	var paymenttype  ='';
	var coupon_code  ='';
	
	var customer_material_obj=document.getElementsByName("customer_material");
	for(var i=0;i<customer_material_obj.length;i++)
	{
		customer_material[i] = customer_material_obj[i].value;
    }
	var needremark = document.getElementById("needremark").checked;
	var remark = '';
	if(needremark){
	   remark  = document.getElementById("remark").value;
	   if(remark=='') {alert('请填写订单备注');document.getElementById("remark").focus();return;}
	}
	
	for (var i=delivery_type_obj.length-1;i>=0;i--)
	{
		if(delivery_type_obj[i].checked)  delivery_type = delivery_type_obj[i].value;
    }
	if(delivery_type=='') {alert('请选择配送方式');window.location.href="#";return;}
	for (var i=pyobj.length-1;i>=0;i--)
	{
		if(pyobj[i].checked)  paymenttype = pyobj[i].value;
    }
	if(delivery_type==1 || delivery_type==2){
		if(addressid=='') {alert('请选择收货人信息');window.location.href="#div_shipment";return;}
	}else if(delivery_type==4){
	   //客户提供账号
		delivery_type_4_array[0] = $("#address_4").val();
		if(delivery_type_4_array[0]==''){alert('请填写收货地址');$("#address_4").focus();return;}
		delivery_type_4_array[1] = $("#name_4").val();
		if(delivery_type_4_array[1]==''){alert('请填写收货人');$("#name_4").focus();return;}
		delivery_type_4_array[2] = $("#tel_4").val();
		if(delivery_type_4_array[2]==''){alert('请填写联系方式');$("#tel_4").focus();return;}
		delivery_type_4_array[3] = $("#express_name_4").val();
		if(delivery_type_4_array[3]==''){alert('请填写快递商');$("#express_name_4").focus();return;}
		delivery_type_4_array[4] = $("#express_account_4").val();
		if(delivery_type_4_array[4]==''){alert('请填写快递账号');$("#express_account_4").focus();return;}
		delivery_type_4_array[5] = $("#companyname_4").val();
		if(delivery_type_4_array[5]==''){alert('请填写公司名称');$("#companyname_4").focus();return;}
	}
	//发票地址
	var invoiceaddress='';
	var invaddobj  = document.getElementsByName("invoiceaddressradio");
	for (var i=invaddobj.length-1;i>=0;i--)
	{
		if(invaddobj[i].checked)  invoiceaddress = invaddobj[i].value;
    }
	if(paymenttype=='') {alert('请选择付款方式');window.location.href="#div_shipment";return;}
	
	var needinvoicevalue='';
	if(needinvoice.checked){
	    if(invoiceid=='') {alert('请选择发票信息');window.location.href="#div_invoice_box";return;}
		needinvoicevalue = needinvoice.value;
		
		var invoicetype='';
		var invoicetype_obj = document.getElementsByName("invoicetype");
		for (var i=invoicetype_obj.length-1;i>=0;i--){
		   if(invoicetype_obj[i].checked)  invoicetype = invoicetype_obj[i].value;
        }
		if(invoicetype==2){
		     if(annexurl==1)
			{alert('请上传营业执照');window.location.href="#div_invoice_box";return;}
			 if(annexurl2==1)
			{alert('请上传税务登记证');window.location.href="#div_invoice_box";return;}
		}
	}
	var coupon_check_obj = document.getElementsByName("coupon_check");
	var coupon = new Array();
	for (var i=coupon_check_obj.length-1;i>=0;i--)
    {
		if(coupon_check_obj[i].checked)  coupon[i] = coupon_check_obj[i].value;
	}

	//优惠券备注
	var customer   = '';
	var efficiency = '';
	var effective_time = '';
	<?php if(!empty($this->coupon)){?>
	customer        = document.getElementById("customer").value;
	efficiency      = document.getElementById("efficiency").value;
	effective_time  = document.getElementById("effective_time").value;
	<?php }?>
	
	var subtmp=document.getElementById("orderbtn");
	subtmp.innerHTML = '<a href="javascript:;" class="button">订单提交中...</a>';
	$.ajax({
            url: '/order/handle',
            data: {'delivery':'<?=$this->delivery?>','addressid':addressid,'delivery_type':delivery_type,'delivery_type_4_array':delivery_type_4_array,'invoiceaddress':invoiceaddress,'invoiceid':invoiceid,'paymenttype':paymenttype,'needinvoice':needinvoicevalue,'coupon':coupon,'remark':remark,'customer_material':customer_material,'customer':customer,'efficiency':efficiency,'effective_time':effective_time},
            type: 'post',
            dataType: 'json',
            success: function(arr) {
            	if(arr.code == 0)
                {
                    window.location.href='/order/success?hashkey='+arr.hashkey;
                }else{
				   alert(arr.message);
				   subtmp.innerHTML ='<a href="javascript:;" class="button"  onclick="order()">提交订单</a>';
				}
            }
	});
}
</script>
<script src="/js/jsplug/formcheck/formValidator-4.1.1.js" type="text/javascript"></script>
<script src="/js/jsplug/formcheck/formValidatorRegex.js" type="text/javascript"></script>
<script src="/js/default/order.js" type="text/javascript"></script>
<script type="text/javascript" src="/js/jsplug/AjaxFileUploader/ajaxfileupload.js"></script>
<script type="text/javascript">
//检查优惠券
$(document).ready(function(){
var couponcode = ''; 
var deductions = 0;
var totle_freight = <?=($this->total+$this->freight)?>;
var totle_packageprice = <?=($this->total+$this->packageprice)?>;
  $(".coupon_check").click(function(){
    var coupon_check_obj = document.getElementsByName("coupon_check");
	var checked = 0;
	if(this.checked) checked = 1;
	couponcode = this.value;
	$.ajax({
		url: '/order/checkcoupon',
		data: {'couponcode':this.value,'delivery':'<?=$this->delivery?>'},
		type: 'post',
		dataType: 'json',
		success: function(arr) {
		  if(arr.code == 0){
		      if(checked==1){
			    deductions = parseFloat(deductions) + parseFloat(arr.deductions);
			    if(deductions<0) deductions = 0;
				$(".deductions").html(number_format(deductions));
			    
				totle_freight = parseFloat(totle_freight)-parseFloat(arr.deductions);
				var showtotle_freight = totle_freight;
				if(totle_freight<0) var showtotle_freight = 0;
				$(".cart_total_freight").html(number_format(showtotle_freight));
				
				totle_packageprice = parseFloat(totle_packageprice)-parseFloat(arr.deductions);
				var showtotle_packageprice = totle_packageprice;
				if(totle_packageprice<0) var showtotle_packageprice = 0;
				$(".cart_total_packageprice").html(number_format(showtotle_packageprice));
		   	  }else{
			    deductions = parseFloat(deductions) - parseFloat(arr.deductions);
				if(deductions<0) deductions = 0;
			  	$(".deductions").html(number_format(deductions));
				
				totle_freight = parseFloat(totle_freight)+parseFloat(arr.deductions);
				var showtotle_freight = totle_freight;
				if(totle_freight<0) var showtotle_freight = 0;
				$(".cart_total_freight").html(number_format(showtotle_freight));
				
				totle_packageprice = parseFloat(totle_packageprice)+parseFloat(arr.deductions);
				var showtotle_packageprice = totle_packageprice;
				if(totle_packageprice<0) var showtotle_packageprice = 0;
				$(".cart_total_packageprice").html(number_format(showtotle_packageprice));
			  }
		   }else{
		      for (var i=coupon_check_obj.length-1;i>=0;i--)
			  {
				 if(coupon_check_obj[i].value==couponcode)  coupon_check_obj[i].checked = false;
			  }
			  alert(arr.message);
		   }
		}
	 });
  });
});
 //没有营业执照
<?php if((!file_exists($annexurl) || !$this->myinfo['annex1']) && $this->invoiceFirst['type']==2){?>showInvDiv(); <?php }?>
<?php if((!file_exists($annexurl2) || !$this->myinfo['annex2']) && $this->invoiceFirst['type']==2){?>showInvDiv(); <?php }?>
<?php if(isset($_SESSION['NeedInvoice']) && $_SESSION['NeedInvoice']=='yes') echo 'changeInvoice();';?>
//加载城市和地区
onloadadd('<?php echo $this->addressFirst['provinceid'];?>','<?php echo $this->addressFirst['cityid'];?>','<?php echo $this->addressFirst['areaid'];?>');
</script>
<?php
unset ( $_SESSION ['NeedInvoice'] );
?>
