<link rel="stylesheet" type="text/css" href="/css/default/buyprocess.css" />

<div id="header" class="w">
  <div id="logo"><a hidefocus="true" href="/"><img alt="盛芯电子" src="/images/default/logo.jpg"></a></div>
  <h1>我的购物车</h1>
</div>
<?php
$currency = array('RMB'=>'￥','USD'=>'$','HKD'=>'HK$');
?>
<!--content-->
<div class="w lh Order ">
	<div class="Order_details">
    <table cellpadding="0" cellspacing="0" class="tableorder table">
        
        <?php if($this->orderarr['total']>0){?><caption>感谢您的惠顾，订单已经提交成功，请尽快付款！</caption><?php }else{?>
        <caption>感谢您的惠顾，订单已经提交成功！</caption><?php }?>
        <thead>
            <tr>
                <th>订单号</th>
                <th>需支付金额</th>
                <th>支付方式</th>
                <th>收货人信息</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td><a href="/order/view?salesnumber=<?=$this->orderarr['salesnumber']?>" title="查看订单详细" target="_blank" style="color:#ff7800"><?php echo $this->orderarr['salesnumber'];?></a></td>
                <td class="fontred"><?php echo $currency[$this->orderarr['currency']].number_format($this->orderarr['total'],DECIMAL);?></td>
                <td><?php if($this->orderarr['paytype']=='transfer') echo '银行转账';
				           elseif($this->orderarr['paytype']=='online') echo '在线支付';
				           elseif($this->orderarr['paytype']=='coupon') echo '优惠券兑换';?></td>
                <td><?php 
				if($this->orderarr['delivery_type']==3){ echo '用户自提';}
				else{
				echo $this->orderarr['name'].'&nbsp;&nbsp;&nbsp;&nbsp;'.$this->orderarr['province'].$this->orderarr['city'].$this->orderarr['area'].$this->orderarr['address'].'&nbsp;&nbsp;&nbsp;&nbsp;'.$this->orderarr['mobile']."  ".$this->orderarr['tel'];
				}
				?></td>
            </tr>
        </tbody>
    </table>
    <!--银行转账-->
	<?php if($this->orderarr['paytype']=='transfer' && $this->orderarr['total']>0){?>

        <table cellpadding="0" cellspacing="0" class="order-tip table">
        <tr><td align="left" colspan="2"><h2>帐户信息：</h2></td></tr>
        
        <tr><td class="tableti">转账金额：</td><td class="price"><?=$currency[$this->orderarr['currency']].$this->orderarr['total'];?></td></tr>
        <?php if($this->orderarr['currency']=='RMB'){?>
        <tr><td class="tableti">户名：</td><td><?=BANK_COM?></td></tr>
        <tr><td  class="tableti">帐号：</td><td><?=BANK_ACCOUNT?></td></tr>
        <tr><td  class="tableti">开户行：</td><td><?=BANK_NAME?></td></tr>
        <?php }elseif($this->orderarr['currency']=='USD'){?>
        <tr><td class="tableti">户名：</td><td><?=BANK_HK_COM?></td></tr>
        <tr><td  class="tableti">帐号：</td><td><?=BANK_HK_ACCOUNT?></td></tr>
        <tr><td  class="tableti">开户行：</td><td><?=BANK_HK_NAME?></td></tr>
        <?php }?>
        <!--<tr><td  class="tableti">汇款识别码：</td><td><?=$this->orderarr['salesnumber'];?></td>-->
        </table>

       <table cellpadding="0" cellspacing="0" class="order-tip table">
        <tbody><tr>
        <td align="left" style="border-bottom:0">
        <h2>提示：</h2>
        <p>1.转账成功后请到我的订单上传转账凭证。</p>
        <p>2.支付成功后，我们可以立即安排工作人员处理订单。</p>
        <p>3.未完成支付的订单将保留48小时，如果您现在不方便支付，可于48小时内到<a href="/center/order">我的订单</a>中查看转账信息并支付。</p>
        </td>
        </tr>
        </tbody>
        </table>
   
    <?php }elseif($this->orderarr['paytype']=='online' && $this->orderarr['total']>0){?>
    <div class="pay-detail">
       <a href="/payment/orderpay?salesnumber=<?php echo $this->orderarr['salesnumber'];?>" class="button">立即去支付</a>
    </div>
    
    <table cellpadding="0" cellspacing="0" class="order-tip table">
        <tbody><tr>
        <td align="left" style="border-bottom:0">
        <h2>提示：</h2>
        <p>1.支付成功后，我们可以立即安排工作人员处理订单。</p>
        <p>2.未完成在线支付的订单将保留24小时，如果您现在不方便支付，可于24小时内到<a href="/center/order">我的订单</a>中完成支付。</p>
        </td>
        </tr>
        </tbody>
   </table>
    
   <?php }?>
        <div class="order-oprate">
         <div class="bg_cart">
            <div class="fl">
                <a href="/"><em></em>继续购物</a>
            </div>
            <div class="fr">
                <a href="/center/order" class="button"><?=$this->translate('Menu_MyOrder')?></a>
            </div>
        </div>
        </div>
    </div>
</div>
<script type="text/javascript">
function orderpay(){
  window.location.href='/payment/orderpay?salesnumber=<?php echo $this->orderarr['salesnumber'];?>';
}
</script>