<script type="text/javascript" language="javascript">
function deleteDep(ID)
{
	if(confirm('你确定删除："'+ID+'" 吗？'))
    {
		$.ajax({
            url: '<?php echo $this->deleteurl;?>',
            data: {'ID':ID},
            type: 'post',
            dataType: 'json',
            success: function(arr) {
            	if(arr.code == 0)
                {
				    alert(arr.message);
                    location.reload();
                }else{
				    document.getElementById('message_sess').style.display = "block";
	                document.getElementById('alert_message').innerHTML = arr.message;
				}
            }
	    });
	}
}
function openadd()
{
	$.openPopupLayer({
        name:'addBox',
        url:'<?php echo $this->addurl;?>'
    });
}
function openedit(DepID)
{
	$.openPopupLayer({
        name:'addBox',
        url:'<?php echo $this->editurl;?>'+'?DepID='+DepID
    });
}
</script>
<table class='tableContent'>
  <tr>
    <td bgcolor="#FFFFFF" align="left" valign="top" width="770">
          <table width="740" border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td height="10" colspan="3">&nbsp;</td>
              </tr>
              <tr>
                <td height="29" bgcolor="#FFFFFF" align="center"><table width="740" border="0" cellpadding="3" cellspacing="0">
                    <tr bgcolor="#334159">
                      <td height="7" align="left" colspan="6"><b><font color="#FFFFFF">
                        <?php echo $this->AreaTitle;?>
                        : </font>
                        <?php if($this->mycommon->checkA($this->Staff_Area_ID) || $this->mycommon->checkW($this->Staff_Area_ID)){?>
                        <a href="#add" onClick="openadd()"><font color="#CCCCCC">添加+</font></a>
                        <?php }?>
                        </b>
                      </td>
                    </tr>
                  </table></td>
              </tr>
              <tr>
                <td height="10" colspan="3" align="center">
                <div id="message_sess" style="display:none" class="message_sess">
                <span title="关闭" class="but" onclick="document.getElementById('message_sess').style.display='none'">&nbsp;</span>
                <span id="alert_message"></span>
                </div></td>
              </tr>
            </table>
            <!-- 需要填写的区域-->
            <table width="740" border="0" cellpadding="1">
              <tr bgcolor="#334159" height="30px">
                <td width="119"><div align="center"><strong><font color="#FFFFFF" face="Arial, Helvetica, sans-serif">部门编号</font></strong></div></td>
                <td width="150"><div align="center"><strong><font color="#FFFFFF" face="Arial, Helvetica, sans-serif">部门名称</font></strong></div></td>
                <td width="103"><div align="center"><strong><font color="#FFFFFF" face="Arial, Helvetica, sans-serif">更新日期</font></strong></div></td>         
                <?php if($this->mycommon->checkA($this->Staff_Area_ID) || $this->mycommon->checkW($this->Staff_Area_ID))
					echo '<td width="103"></td>';
				?>
              </tr>
              <?php
			  	  if(!empty($this->Department)){
                	 foreach ($this->Department as $k=>$data){
						$Dep_ID     = $data['department_id'];
						$Department = $data['department'];
						$updatedate = $data['updatedate'];
						if($k%2==0)$bg="#E4E4E4";
						else $bg="#D5C5FE";
						echo "<tr bgcolor=\"$bg\" height=\"25px\">";
						echo "<td>".$Dep_ID."</td>";
						echo "<td>".$Department."</td>";
						echo "<td>".$updatedate."</td>";								  
						if($this->mycommon->checkA($this->Staff_Area_ID) || $this->mycommon->checkW($this->Staff_Area_ID)){								
						echo "<td align=\"center\">
						<a href=\"#edit\" onClick=\"openedit('{$Dep_ID}')\">编辑</a>&nbsp;|&nbsp;
						<a href=\"#delete\" onclick=\"deleteDep('".$Dep_ID."')\">删除</a></td>";
						}
					    echo "</tr>\r\n";
				    }
				   }
	            ?>
            </table>
            <br/>
            <!-- 结束区域-->
          </td>
  </tr>
</table>