<!--content-->
<link rel="stylesheet" type="text/css" href="/<?=$_SESSION['new_version']?>/css/default/myself2013.css"/>
<link rel="stylesheet" type="text/css" href="/css/default/myself<?=$_SESSION['new_version']?>.css"/>
<script type="text/javascript" language="javascript"> center_css();</script>
<div class="w">
  <div class="breadcrumbs2013"> <span>
    <a  class="focs">我的盛芯电子</a>&nbsp;&nbsp;»&nbsp;&nbsp;<a href="/center/mylaboratory">我的实验室</a> &nbsp;&nbsp;»&nbsp;&nbsp; 申请实验室
  </div>
</div>

<div class="blank10"></div>
<div class="w clearfix ourbox">
  <!--左边导航-->
 <?php echo $this->render('center/leftmenu.phtml');?>
  		<div class="fr u_right msg24 mymainbox mylab">
        <?php if(isset($_SESSION['postsess']['message'])){?><div class="ok" id="message"> <?php echo $_SESSION['postsess']['message'];unset($_SESSION['postsess']);?></div>
		<script language="javascript">setTimeout("window.parent.location.href='/center/mylaboratory'",3000);</script>
		<?php }?>
         <form id='applyform' name="applyform" action='/center/applylaboratory' method='post' enctype="multipart/form-data">
		<div class="mymaincommon">
        
            <h2><a href="/center/mylaboratory">我的实验室</a> —— <span class="fontred">申请使用实验室</span></h2>
           
           <?php //if($this->waitnum>0){?>
           <!--<div class="mylab_table labelinput " >
           <h3>您有待审批的申请，不能再提交申请!<img src="/<?=$_SESSION['new_version']?>/css/img/mylabic.png" class="mylabic" /></h3>
           </div>-->
           <?php //}else
		   //if($this->passnum>0){?>
           <!--<div class="mylab_table labelinput " >
           <h3>您有待填写测试报告记录，请填写完成后再申请! <a href="/center/mylaboratory?type=pass" style="color:#FF0000">填写报告</a><img src="/<?=$_SESSION['new_version']?>/css/img/mylabic.png" class="mylabic" /></h3>
           </div>-->
           <?php //}else{?>
            <div class="mylab_table labelinput " >
                <h3>基本信息：<img src="/<?=$_SESSION['new_version']?>/css/img/mylabic.png" class="mylabic" /></h3>
                <div class="mylab_table_dl fore1">
                    <dl>
                      <dt><em>*</em>实验地点：</dt>
                      <dd>
                        <select id="place" name="place" onchange="changeplace(this)">
                   <?php foreach($this->place as $place){?>
                   <option value="<?=$place['id']?>"><?=$place['city']?></option>
                   <?php }?>
                </select>
                <span id="xxplace"><?=$this->place[0]['address']?></span>
                      </dd>
                    </dl>
                <dl>
              <dt><em>*</em>中电老客户：</dt>
              <dd>
                <label><input type="radio" name="customers" class="customers" value="1" <?php echo $this->customers==1?'checked':'';?>/>否</label>
                <label><input type="radio" name="customers" class="customers" value="2" <?php echo $this->customers==2?'checked':'';?>/>是</label>
                
                
              </dd>
            </dl>
            	<dl id="follow_dl" style="display:none"><dt><em>*</em>跟进部门：</dt>
                
                <dd><label><input type="radio" name="customers_bumen" class="customers_bumen" value="BMP" />BMP</label>
                <label><input type="radio" name="customers_bumen" class="customers_bumen" value="华南区" />华南区</label>
                <label><input type="radio" name="customers_bumen" class="customers_bumen" value="华北区" />华北区</label>
                <label><input type="radio" name="customers_bumen" class="customers_bumen" value="华东区" />华东区</label>
                <label><input type="radio" name="customers_bumen" class="customers_bumen" value="华中区" />华中区</label></dd>
                </dl>
            <dl>
              <dt><em>*</em>来访时间：</dt>
              <dd>
                <label><input type="text" name="vist_time" id="vist_time" onclick="WdatePicker({startDate:'',dateFmt:'yyyy-MM-dd',alwaysUseStartDate:true,lang:'sc'})" readonly="readonly" onchange="vist_time(this)"/></label>
                <label><input type="radio" name="vist_time_radio" class="vist_time_radio" value="9:00-12:00" />上午（9:00-12:00）</label>
                <label><input type="radio" name="vist_time_radio" class="vist_time_radio" value="13:00-17:00" />下午（13:00-17:00）</label>
                <label><input type="radio" name="vist_time_radio" class="vist_time_radio" value="9:00-17:00" />全天（9:00-17:00）</label>
              </dd>
            </dl>
            <dl>
              <dt><em>*</em>来访人数：</dt>
              <dd>
               <input type="text"  name="vist_number" id="vist_number" onkeyup="<?=ISNUMBER?>"/>
              </dd>
            </dl>
                </div>
                <h3>公司信息：<img src="/<?=$_SESSION['new_version']?>/css/img/mylabic.png" class="mylabic" /></h3>
                <div class="mylab_table_dl fore2">
                    <dl>
              <dt><em>*</em>公司全称：</dt>
              <dd>
               <input type="text" style="width:300px;" name="company" id="company" value="<?=$this->usrinfo['companyname']?>"/>
              </dd>
            </dl>
            <dl>
              <dt><em>*</em>公司地址：</dt>
              <dd>
               <input type="text" style="width:300px;" name="address" id="address"  value="<?php echo $this->fun->createAddress($this->usrinfo['province'],$this->usrinfo['city'],$this->usrinfo['area'],$this->usrinfo['address'])?>"/>
              </dd>
            </dl>
            <dl>
              <dt><em>*</em>联系人：</dt>
              <dd>
               <input type="text" style="width:300px;" name="contact" id="contact" value="<?=$this->usrinfo['truename']?>"/>
              </dd>
            </dl>
            <dl>
              <dt><em>*</em>联系电话：</dt>
              <dd>
               <input type="text" style="width:300px;" name="phone" id="phone" value="<?=$this->usrinfo['tel']?>"/>
              </dd>
            </dl>
            <dl>
              <dt><em>*</em>联系邮箱：</dt>
              <dd>
               <input type="text" style="width:300px;" name="email" id="email" value="<?=$this->usrinfo['email']?>"/>
              </dd>
            </dl>
                </div>
                <h3>实验器材：<img src="/<?=$_SESSION['new_version']?>/css/img/mylabic.png" class="mylabic" /></h3>
                <div class="mylab_table_dl fore3">
					<div id="room_instrument"><img src="/<?=$_SESSION['new_version']?>/css/img/mylabic.png" class="mylabic" /></div>
                </div>
                <h3>项目信息：<font color="#FF0000">提交的信息越全面，享受的服务更精确、更高效</font><img src="/<?=$_SESSION['new_version']?>/css/img/mylabic.png" class="mylabic" /></h3>
                <div class="mylab_table_dl fore4">
                   <dl>
              <dt><em>*</em>项目名称：</dt>
              <dd>
               <input type="text" style="width:300px;" name="project_name" id="project_name"/>
              </dd>
            </dl>
            <dl>
              <dt><em>*</em>主要器件：</dt>
              <dd>
              <font color="#999999">便于分配相关领域专业协同测试人员</font>
               <table cellpadding="0" cellspacing="0" border="0" style=" text-align:center;padding:5px;border:1px solid #ABADB3;"  id="SignFrame">
                <thead>
                  <tr id="trHeader">
                    <th width="120">型号<em>*</em></th>
                    <th width="120">品牌<em>*</em></th>
                    <th width="100"><a href="javascript:;" class="gbqfb" onclick="AddSignRow()">添加产品</a></th>
                    <input name='txtTRLastIndex' type='hidden' id='txtTRLastIndex' value="2" />
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td><input type="text" name="part_no[]" /></td>
                    <td><input type="text" name="brand_name[]"/></td>
                    <td>&nbsp;</td>
                  </tr>
                  
                </tbody>
              </table>
               
              </dd>
            </dl>
            <dl>
              <dt>预计量产时间：</dt>
              <dd>
                <input type="text" style="width:300px;" name="expected_time" id="expected_time" onclick="WdatePicker({startDate:'',dateFmt:'yyyy-MM-dd',alwaysUseStartDate:true,lang:'sc'})" readonly="readonly"/>
              </dd>
            </dl>
            <dl>
              <dt>项目简介：</dt>
              <dd>
                <textarea name="project_des" id="project_des" rows="3" cols="40"></textarea>
              </dd>
            </dl>
            <dl>
              <dt>项目框图：</dt>
              <dd>
               <input type="file" name="project_images" id="project_images" class="input200">
              </dd>
            </dl>
             <dl>
              <dt>BOM单：</dt>
              <dd>
               <input type="file" name="project_bom" id="project_bom" class="input200">
              </dd>
            </dl>
                    <dl>
                    <dt>申请须知条款：</dt>
                    <dd>
                    <div style="width:700px; height:200px; border:1px solid #ABADB3;overflow-y:auto">
                    <h4>1. 目的</h4>
本文件的目的是向每位前来萤火实验室的来访者提供实验室使用的相关信息、注意事项及管理条例。我们希望每位前来萤火实验室的来访者，在开始使用实验室进行实验之前，能够仔细阅读本须知，承诺已经完全了解并遵守其中的相关规定。
<h4>2. 来访者进出实验室的规定</h4>
1.	来访者须提前一周向萤火实验室提出使用申请，需在盛芯电子填写申请表，具体流程请参见流程图。在获得确认函后，按照确认函安排的时间前来实验室。其它时间或未提出申请的情况下，恕不接待。<br/>
2.	来访者在中国电子器材深圳有限公司前台接待处出示确认函，换取并佩带接待员分发的胸卡。接待员打电话通知实验室相关人员前来接待来访者。未佩戴胸卡的其它实验室来访者，不得擅自进出实验室。<br/>
3.	首次进入实验室需要携带能够证明身份的有效证件，并认真阅读&lt;萤火实验室来访者须知&gt;。<br/>
4.	实验室来访者如需进入公司其他工作区域，应由实验室工作人员全程陪同，直至来访者离开。
<h4>3. 实验室仪表及所属附件使用的规定</h4>
1.	根据研究的领域的不同，实验室从功能上划分了4个不同的实验室。原则上来访者只能使用所预定的实验室的相关测试仪表及所属附件。<br/>
2.	为了避免实验室附件的丢失，所有附件由实验室工作人员统一管理。如需使用，需向实验室工作人员申请。在实验进行期间，由申请人负责附件的保管。试验结束后，归还附件，在验证所有附件完好的情况下，并完成附件使用登记表。如有遗失，需原价进行赔偿。<br/>
3.	对于交叉研究的课题或项目，需要同时使用所属于不同实验室的仪表及附件的情况，需要按照确认函中明确信息，由实验室工作人员负责进行调配使用，不得擅自动用其它的非相关实验室的仪表及附件。<br/>
4.	实验室每次使用时间以半天为单位，一般连续不超过2个单位。请严格按照确认函规定的时间进行使用，不得超时强行占用而影响下面的用户使用。考虑到实验室更有效的服务于更多的用户，可以根据具体实验室使用状况，另择时间安排使用。<br/>
5.	按照萤火实验室的宗旨，实验室完全免费向广大用户开放，实验室不要求申请使用的用户和中电共享知识产权，用户可以真正完全免费地使用实验室的测试条件。
<h4>4. 拍照，摄像许可证管理</h4>
1.	严格控制在实验室内由访问者进行的拍照摄像活动。<br/>
2.	进行拍照 \ 摄像活动必须事先经由实验室管理人员批准后，在许可证限定的区域内进行拍照 \ 摄像活动。<br/>
<h4>6. 萤火实验室安全</h4>
1.	萤火实验室仪表安全：用户在实验室进行试验过程中，请遵守仪表使用手册中的注意事项。对于不清楚的情况下，请不要盲目进行试验，可以咨询实验室工作人员或中电工程师，按照指导进行使用。对于正常使用情况下的出现的仪表故障（故意损坏除外），实验室不追究用户任何责任。<br/>
2.	用户被测设备器件安全：用户自己妥善管理使用自己携带被测设备 / 器件，实验室不负责对其在实验过程中出现的任何损坏进行赔偿。<br/>
3.	用户自带仪表安全：如果根据用户测试的真实需要，且由于实验室的条件所限，无法提供部分测试仪表，用户可以携带自己的测试仪表来进行试验。用户需要自己负责自己携带仪表的使用，实验室不负责对其在实验过程中出现的任何损坏进行赔偿。<br/>
4.	人身安全：用户在实验室进行试验过程中，请注意自身安全，不清楚情况下，不要盲目进行试验。实验室不负责用户由于自己操作不慎造成的人身安全问题。
<h4>7.来访者个人财务保管</h4>
1.	来访者不要在实验室内存放个人贵重财物。对于任何个人财产的遗失、被窃和损坏实验室将不承担责任。<br/>
2.	来访者实验期间，如较长时间离开实验室，应收好重要文档及贵重物品。
                    </div>
                    </dd>
                    </dl>
                    <dl>
                    <dt>&nbsp;</dt>
                    <dd>
                     <label><input type="checkbox" name="accept" id="accept" value="1">接受条款</label>
                    </dd>
                    </dl>
                    <dl>
                    <dt>&nbsp;</dt>
                    <dd>
                    <div id="baojiabtn"><a href="javascript:;" class="gbqfbbig_h" title="提交申请" onclick="apply()">提交申请</a></div>
                    </dd>
                    </dl>
                </div>

        </div>
        
           <?php //}?>  
        
        </div>
        </form>
    </div>
</div>
<div class="clr"></div>
<script src="/js/jsplug/My97DatePicker/WdatePicker.js" type="text/javascript"></script>
<script type="text/javascript">
//实验室地址
function changeplace(obj){
	if(obj.value==1){$('#xxplace').html('<?=$this->place[0]['address']?>');
	    //if($('input[name="customers"]:checked').val()==2) $("#follow_dl").css("display","block");
	}else if(obj.value==2){$('#xxplace').html('<?=$this->place[1]['address']?>');//$("#follow_dl").css("display","none");
	}
	else if(obj.value==3){$('#xxplace').html('<?=$this->place[2]['address']?>');//$("#follow_dl").css("display","none");
	}
	else if(obj.value==4){$('#xxplace').html('<?=$this->place[3]['address']?>');//$("#follow_dl").css("display","none");
	}
	//更新器材
	rf(obj.value);
}
$(function(){
    //选择客户类型
	$(".customers").click(function(){
		if(this.value==1){
		   $("#follow_dl").css("display","none");
		}else if(this.value==2){
		   $("#follow_dl").css("display","block");
		}
	});
})
//ajax获取实验器材
$(function(){
    rf(1);
})
function rf(place){
	$("#room_instrument").html('<img src="/images/default/ajax-loader-s.gif">');
	$("#room_instrument").load("/center/ajaxinstrument?place="+place);
}
//提交
function apply(){
   var place = $("#place").val();
   var customers = $('input[name="customers"]:checked').val();
   var customers_bumen = '';
   if(customers=='' || typeof(customers)=="undefined") {
	  alert('请选择是否为中电器材老客户');$("#place").focus();return;
   }else if(customers==2){
   	  customers_bumen = $('input[name="customers_bumen"]:checked').val();
	  if(customers_bumen=='' || typeof(customers_bumen)=="undefined") {
	      alert('请选择跟进部门');$("#place").focus();return;
      }
   }
   var vist_time = $("#vist_time").val();
   var vist_time_radio = $('input[name="vist_time_radio"]:checked').val();

   if(vist_time=='' || typeof(vist_time)=="undefined") {
	  alert('请选择访问时间');$("#place").focus();return;
   }else if(vist_time < '<?=date("Y-m-d")?>'){
   	  alert('访问时间不能小于今天');$("#place").focus();return;
   }
   if(vist_time_radio=='' || typeof(vist_time_radio)=="undefined") {
	  alert('请选择访问时间段');$("#place").focus();return;
   }
   var vist_number = $("#vist_number").val();
   if(vist_number=='' || typeof(vist_number)=="undefined") {
	  alert('请填写来访人数');$("#place").focus();return;
   }
   var company = $("#company").val();
   if(company=='' || typeof(company)=="undefined") {
	  alert('请填写公司全称');$("#place").focus();return;
   }
   var address = $("#address").val();
   if(address=='' || typeof(address)=="undefined") {
	  alert('请填写公司地址');$("#place").focus();return;
   }
   var contact = $("#contact").val();
   if(contact=='' || typeof(contact)=="undefined") {
	  alert('请填写联系人');$("#place").focus();return;
   }
   var phone = $("#phone").val();
   if(phone=='' || typeof(phone)=="undefined") {
	  alert('请填写联系电话');$("#place").focus();return;
   }
   var email = $("#email").val();
   if(email=='' || typeof(email)=="undefined") {
	  alert('请填写联系邮箱');$("#place").focus();return;
   }
   var instrument=''; 
	$("input[name='instrument[]']:checkbox").each(function(){ 
		if($(this).attr("checked")){
			instrument += $(this).val()+",";
		}
	})
	if(instrument=='' || typeof(instrument)=="undefined") {
	  alert('请选择实验器材');$("#email").focus();return;
   }
   var project_name = $("#project_name").val();
   if(project_name=='' || typeof(project_name)=="undefined") {
	  alert('请填写项目名称');$("#room_instrument").focus();return;
   }
   var project_device = '';
   var part_no        = new Array();
   var brand_name = new Array();
   var part_no_obj     = document.getElementsByName("part_no[]");
   var brand_name_obj  = document.getElementsByName("brand_name[]");
   for (var i=0;i < part_no_obj.length;i++)
   {
	   if(i==0 && part_no_obj[i].value=='') {alert('请输入主要器件');part_no_obj[i].focus();return;}
	   if(i==0 && brand_name_obj[i].value=='') {alert('请输入主要器件品牌');brand_name_obj[i].focus();return;}
   }
   var accept = $('input[name="accept"]:checked').val();
   if(accept=='' || typeof(accept)=="undefined") {
	  alert('请阅读”申请须知条款“');$("#project_name").focus();return;
   }
   $("#baojiabtn").html('<a href="javascript:;" class="gbqfbbig_h" >提交中...</a>');
   document.getElementById('applyform').submit();
}
</script>
<script language="javascript">// Example: obj = findObj("image1");
for(i=0;i<4;i++){
	AddSignRow();
}
function findObj(theObj, theDoc)
{ 
   var p, i, foundObj; 
   if(!theDoc) theDoc = document; 
   if( (p = theObj.indexOf("?")) > 0 && parent.frames.length) 
   {    
       theDoc = parent.frames[theObj.substring(p+1)].document;
	   theObj = theObj.substring(0,p); 
   } 
   if(!(foundObj = theDoc[theObj]) && theDoc.all) foundObj = theDoc.all[theObj]; 
   for (i=0; !foundObj && i < theDoc.forms.length; i++)
   foundObj = theDoc.forms[i][theObj]; 
   for(i=0; !foundObj && theDoc.layers && i < theDoc.layers.length; i++) 
	 foundObj = findObj(theObj,theDoc.layers[i].document); 
   if(!foundObj && document.getElementById) 
   foundObj = document.getElementById(theObj);    
   return foundObj;
}
//添加一个参与人填写行

function AddSignRow(){ //读取最后一行的行号，存放在txtTRLastIndex文本框中 
   var txtTRLastIndex = findObj("txtTRLastIndex",document);
   var rowID = parseInt(txtTRLastIndex.value);
   var signFrame = findObj("SignFrame",document);
   //添加行
   var newTR = signFrame.insertRow(signFrame.rows.length);
   newTR.id = "SignItem" + rowID;
   //添加列:型号
   var newNameTD=newTR.insertCell(0);
   newNameTD.innerHTML = '<input type="text" name="part_no[]" />';
   //添加列:品牌(产品线)
   var newNameTD=newTR.insertCell(1);
   newNameTD.innerHTML = '<input type="text" name="brand_name[]"/>';

    //添加列:删除按钮
   var newDeleteTD=newTR.insertCell(2);
   newDeleteTD.innerHTML = "<a href='javascript:;' class='gbqfb' onclick=\"DeleteSignRow('SignItem" + rowID + "')\">删除</a>";
   //将行号推进下一行
   txtTRLastIndex.value = (rowID + 1).toString() ;
}
//删除指定行
function DeleteSignRow(rowid){
  var signFrame = findObj("SignFrame",document);
  var signItem = findObj(rowid,document);
  //获取将要删除的行的Index
  var rowIndex = signItem.rowIndex;
  //删除指定Index的行
  signFrame.deleteRow(rowIndex);
}
</script>