<link rel="stylesheet" type="text/css" href="/<?=$_SESSION['new_version']?>/css/default/myself2013.css"/>
<link rel="stylesheet" type="text/css" href="/css/default/myself<?=$_SESSION['new_version']?>.css"/>
<script type="text/javascript" language="javascript"> center_css();</script>
<!--content-->
<div class="w">
  <div class="breadcrumbs2013"> <span>
    <a  class="focs">我的盛芯</a>&nbsp;&nbsp;»&nbsp;&nbsp;<a ><?=$this->translate('Menu_MyInfo')?></a>
  </div>
</div>

<div class="blank10"></div>
<div class="w clearfix ourbox">
  <!--左边导航-->
  <?php echo $this->render('center/leftmenu.phtml');?>
  <div class="fr u_right msg24">
    <div class="<?php if(isset($_SESSION['postsess']['message']) && $_SESSION['postsess']['message']){
	  if($_SESSION['postsess']['error']>0) echo 'error';
	  else echo "ok";}?>" id="message">
	<?php echo $_SESSION['postsess']['message'];$_SESSION['postsess']['message']='';$_SESSION['postsess']['error']='';?></div>
    <div class="col_main" id="onlineorder">
      <div class="order_tab_head">
        <ul>
          <li <?php if($_SESSION['postsess']['ptype']=='1'|| empty($_SESSION['postsess']['ptype'])) echo 'class="on"'?>><a href="javascript:">基本资料<b class="blank3"></b></a></li>
          
          <li <?php if($_SESSION['postsess']['ptype']=='3') echo 'class="on"'?>><a href="javascript:">修改密码<b class="blank3"></b></a></li>
        </ul>
      </div>
      <div>
        <div class="table_box" <?php if($_SESSION['postsess']['ptype']=='1' || empty($_SESSION['postsess']['ptype'])) echo 'style="display:block;"'; else echo 'style="display:none;"';?>>
          <form id='basis' name="basis" action='' method='post'>
            <input type="hidden" name="ptype" value="1"/>
            <div class="add_address" >
              <dl>
                <dt>性别：</dt>
                <dd>
                  <input type="radio" value="m" name="memberSex" <?php if($this->myinfo['gender']!='w') echo 'checked';?> />
                  男
                  <input type="radio" value="w" name="memberSex" <?php if($this->myinfo['gender']=='w') echo 'checked';?> />
                  女 </dd>
              </dl>
              <?php if($this->myinfo['backedit']){?>
              <dl>
                <dt>用户名：</dt>
                <dd> <input type="text" class="input120" name="uname" id="uname" value="<?php echo $this->myinfo['uname'];?>"/></dd>
              </dl>
              <dl>
                <dt>注册邮箱：</dt>
                <dd> <input type="text" class="input120" name="email" id="email" value="<?php echo $this->myinfo['email'];?>"/></dd>
              </dl>
              <dl>
              <?php }else{?>
              <dl>
                <dt>用户名：</dt>
                <dd> <?php echo $this->myinfo['uname'];?> </dd>
              </dl>
              <dl>
                <dt>注册邮箱：</dt>
                <dd> <?php echo $this->myinfo['email'];?> </dd>
              </dl>
              <dl>
              <?php }?>
                <dt><font color="#FF0000">* </font>手机：</dt>
                <dd>
                  <input type="text" class="input120" name="mobile" id="mobile" value="<?php echo $this->myinfo['mobile'];?>"/>
                  <div id="mobileTip" style="position:absolute; top:0; left:220px;"></div>
                </dd>
              </dl>
              <dl>
                <dt><font color="#FF0000">* </font>出生日期：</dt>
                <dd>
                  <input type="text" class="input120" name="birthday" id="birthday"  value="<?php echo $this->myinfo['birthday'];?>" onclick="WdatePicker({startDate:'',dateFmt:'yyyy-MM-dd',alwaysUseStartDate:true,lang:'sc'})"/>
                  <div id="birthdayTip" style="position:absolute; top:0; left:220px;"></div>
                </dd>
              </dl>
              <dl>
                <dt>&nbsp;</dt>
                <dd>
                  <input type="submit"  value="保 存" class="button"/>
                </dd>
              </dl>
            </div>
          </form>
          <div class="clr"></div>
        </div>
        
        <div class="table_box" <?php if($_SESSION['postsess']['ptype']!='3') echo 'style="display:none;"'?>>
          <form id="changepass" name="changepass" action="" method='post' >
            <input type="hidden" name="ptype" value="3"/>
            <div class="add_address 1h" >
              <dl>
                <dt>旧密码：</dt>
                <dd>
                  <input type="password" name="oldpass" id="oldpass" class="input120" value=""/>
                  <div id="oldpassTip" style="position:absolute; top:0; left:210px;"></div>
                </dd>
              </dl>
              <dl>
                <dt>新密码：</dt>
                <dd>
                  <input type="password" name="newpass" id="newpass" class="input120" value=""/>
                  <div id="newpassTip" style="position:absolute; top:0; left:210px;"></div>
                </dd>
              </dl>
              <dl>
                <dt>确认新密码：</dt>
                <dd>
                  <input type="password" name="newpass2" id="newpass2" class="input120" value=""/>
                  <div id="newpass2Tip" style="position:absolute; top:0; left:210px;"></div>
                </dd>
              </dl>
              <dl>
                <dt>&nbsp;</dt>
                <dd>
                  <input type="submit"  value="保 存" class="button" name="but3" id="but3"/>
                </dd>
              </dl>
            </div>
          </form>
          <div class="clr"></div> 
        </div>
      </div>
    </div>
  </div>
</div>
<div class="clr"></div>
<script src="/js/jsplug/formcheck/formValidator-4.1.1.js" type="text/javascript"></script>
<script src="/js/jsplug/formcheck/formValidatorRegex.js" type="text/javascript"></script>
<script src="/js/jsplug/My97DatePicker/WdatePicker.js" type="text/javascript"></script>
<script src="/js/default/info.js" type="text/javascript"></script>
<script type="text/javascript">
//加载城市和地区
onloadadd('<?php echo $this->myinfo['province'];?>','<?php echo $this->myinfo['city'];?>','<?php echo $this->myinfo['area'];?>');
setTimeout('hidMessage()',3000);
function hidMessage(){
	document.getElementById("message").style.display = 'none';
}

<?php if($this->myinfo['industry'] == 'other'){?>
   showother('other');
<?php }?>
//选择其它
function showother(value){
    var obj = document.getElementById("industry_other_div");
	if(value=='other')
	{
	   obj.innerHTML='<input  type="text" name="industry_other" id="industry_other" value="<?=$this->myinfo['personaldesc']?>" class="validate[required] reinput input200"/>';
	   <?php if(empty($this->myinfo['personaldesc'])) echo 'document.getElementById("industry_other").focus();';?>
	}else{
	    obj.innerHTML='';
	}
}
</script>
<?php $_SESSION['postsess']['ptype'] = 1;?>
