<div class="submenu">
    <h2><a href="/center">我的盛芯</a></h2>
    <ul class="submenu_ul">
        <li class="seminar <?php if(in_array($_SESSION['leftmenu_select'],array('order','inqorder'))) echo 'on';?>" ><s></s><a href="/center/order"><span>我的订单</span><b class="fore1"></b></a>
            <ul class="submenu_ul_ul">
                <li class="seminar <?php if($_SESSION['leftmenu_select']=='order') echo 'subon';?>"  ><a href="/center/order">在线订单</a></li>
                <li class="seminar <?php if($_SESSION['leftmenu_select']=='inqorder') echo 'subon';?>"  ><a href="/center/inqorder">询价订单</a></li>
            </ul>
        </li>
        <li class="seminar <?php if($_SESSION['leftmenu_select']=='inquiry') echo 'on';?>" ><s></s><a href="/center/inquiry"><span>我的询价</span><b class="fore2"></b></a></li>
        <li class="seminar <?php if($_SESSION['leftmenu_select']=='bom') echo 'on';?>" ><s></s><a href="/center/bom"><span>BOM采购</span><b class="fore3"></b></a></li>
        <li class="seminar <?php if($_SESSION['leftmenu_select']=='info') echo 'on';?>" ><s></s><a href="/center/info"><span>个人资料</span><b class="fore7"></b></a></li>
        <li class="seminar <?php if($_SESSION['leftmenu_select']=='address') echo 'on';?>" ><s></s><a href="/center/address"><span>收货地址</span><b class="fore8"></b></a></li>
    </ul>
</div>
