<div class="submenu">
    <h2><a href="/center">我的IC易站</a></h2>
    <ul class="submenu_ul">
        <li class="seminar <?php if(in_array($_SESSION['leftmenu_select'],array('order','inqorder'))) echo 'on';?>" ><s></s><a href="/center/order"><span>我的订单</span><b class="fore1"></b></a>
            <ul class="submenu_ul_ul">
                <li class="seminar <?php if($_SESSION['leftmenu_select']=='order') echo 'subon';?>"  ><a href="/center/order">在线订单</a></li>
                <li class="seminar <?php if($_SESSION['leftmenu_select']=='inqorder') echo 'subon';?>"  ><a href="/center/inqorder">询价订单</a></li>
            </ul>
        </li>
        <li class="seminar <?php if($_SESSION['leftmenu_select']=='inquiry') echo 'on';?>" ><s></s><a href="/center/inquiry"><span>我的询价</span><b class="fore2"></b></a></li>
        <li class="seminar <?php if($_SESSION['leftmenu_select']=='bom') echo 'on';?>" ><s></s><a href="/center/bom"><span>BOM采购</span><b class="fore3"></b></a></li>
        <li class="seminar <?php if($_SESSION['leftmenu_select']=='coupon') echo 'on';?>" ><s></s><a href="/center/coupon"><span>我的优惠券</span><b class="fore4"></b></a></li>
        <li class="seminar <?php if($_SESSION['leftmenu_select']=='delivery') echo 'on';?>" ><s></s><a href="/center/delivery"><span>交期变更</span><b class="fore5"></b></a></li>
        <li class="seminar <?php if($_SESSION['leftmenu_select']=='invoice') echo 'on';?>" ><s></s><a href="/center/invoice"><span>发票申请</span><b class="fore6"></b></a></li>
        <li class="seminar <?php if($_SESSION['leftmenu_select']=='info') echo 'on';?>" ><s></s><a href="/center/info"><span>个人资料</span><b class="fore7"></b></a></li>
        <li class="seminar <?php if($_SESSION['leftmenu_select']=='address') echo 'on';?>" ><s></s><a href="/center/address"><span>收货地址</span><b class="fore8"></b></a></li>
        <li class="seminar <?php if($_SESSION['leftmenu_select']=='favorites') echo 'on';?>" ><s></s><a href="/center/favorites"><span>收藏夹</span><b class="fore9"></b></a></li>
        <li class="seminar <?php if($_SESSION['leftmenu_select']=='exchange') echo 'on';?>" ><s></s><a href="/center/exchange"><span>礼品兑换</span><b class="fore8"></b></a></li>
        <li class="seminar <?php if($_SESSION['leftmenu_select']=='samples') echo 'on';?> " ><s></s><a href="/center/samples"><span>样片申请</span><b class="fore8"></b></a></li>
        <li class="seminar <?php if($_SESSION['leftmenu_select']=='mylaboratory') echo 'on';?> borderbottomlast" ><s></s><a href="/center/mylaboratory"><span>我的实验室</span><b class="fore10"></b></a></li>
    </ul>
</div>
