
<link rel="stylesheet" type="text/css"
	href="/<?=$_SESSION['new_version']?>/css/default/dir2013.css" />
<link rel="stylesheet" href="/js/jsplug/lightbox/css/lightbox.css"
	type="text/css" media="screen" />
<script type="text/javascript" language="javascript"> widescreen_css();</script>
<?php 
	//过滤产品
	$prodarr = $this->fun->filterProduct($this->prodarr);
	//echo '<pre>';print_r($prodarr);exit;
	//获得零售价
	$partid = $prodarr['id'];
	$moq    = $prodarr['stockInfo']['moq'];
	$mpq    = $moq;
	//开始显示的交货地
	$show_price = 0;
	$checked_sz  = $checked_hk = '';
	$stock      = $prodarr['stockInfo']['stock'];
	if($prodarr['f_show_price_sz']){
	    $show_price = $prodarr['f_show_price_sz'];
	    $sell_price = $prodarr['f_sell_price_sz'];
	    $sell_total = $sell_price*$moq;
		$lead_time  = $prodarr['lead_time_sz'];
		$checked_sz = 'checked';
		$unit = $prodarr['f_rmb'];
		$break_price = $prodarr['f_break_price_new_d_sz'];
		$break_price_title = '含税(17%)';
	}elseif($prodarr['f_show_price_hk']){
	    $show_price = $prodarr['f_show_price_hk'];
	    $sell_price = $prodarr['f_sell_price_hk'];
	    $sell_total = $sell_price*$moq;
		$lead_time  = $prodarr['lead_time_hk'];
		$checked_hk  = 'checked';
		$unit = $prodarr['f_usd'];
		$break_price = $prodarr['f_break_price_new_d_hk'];
		$break_price_title = '美元';
	}elseif($prodarr['f_break_price_notitle_sz']){
		$break_price_title = '含税(17%)';
		$break_price = $prodarr['f_break_price_new_d_sz'];
	}elseif($prodarr['f_break_price_notitle_hk']){
		$break_price_title = '美元';
		$break_price = $prodarr['f_break_price_new_d_hk'];
	}
?>
<div class="w">
	<div class="breadcrumbs2013"></div>
</div>

<input type="hidden" name="part_no" id="part_no"
	value="<?=$prodarr['part_no'];?>" />
<input type="hidden" name="partid" id="partid" value="<?=$partid?>" />
<input type="hidden" name="collection_id" id="collection_id"
	value="<?=$prodarr['stockInfo']['collection_id']?>" />
<input type="hidden" name="supplier_id" id="supplier_id"
	value="<?=$prodarr['stockInfo']['supplier_id']?>" />
<?php  
if($prodarr['part_img']=='' || $prodarr['part_img']=='no.gif') {
    $img_url = PRODUCTICON.'no_big.gif';
}else {
    $img_url = PRODUCTICON.$prodarr['part_img'];
	$big_url = PRODUCTICONBIG.$prodarr['part_img'];
}
?>
<div class="prode">
	<div class="w">
		<div class="prodetail2013 clearfix boxshadow">
			<div class="proimg fl">
  <?php if(isset($big_url) && $big_url && $this->fun->checkFile($big_url)){?>
  <a href="<?=$big_url?>" rel="lightbox"
					title="<?=$prodarr['part_no'];?>"><img src="<?=$img_url?>"
					alt="<?=$prodarr['part_no'];?>" title="<?=$prodarr['part_no'];?>" /></a>
  <?php }else{?>
  <img src="<?=$img_url?>" alt="<?=$prodarr['part_no'];?>"
					title="<?=$prodarr['part_no'];?>" />
  <?php }?>  
   <p class="fontgray">图片仅供参考，请以实物为准</p>
   <?php if(isset($big_url) && $big_url && $this->fun->checkFile($big_url)){?>
  <span class="bigicon png_ie6"></span>
  <?php }?>
  
            <?php if($this->stime && $this->oldprice && $prodarr['f_last_price_sz']){?>
  			<div class="sale_price">
					<p class="sale_pricemm">惊爆价低至</p>
					<p>
						<span class="fuhao">￥</span><span class="price"><?=number_format($prodarr['f_last_price_sz'],2)?></span>
					</p>
				</div>
            <?php }?>
            </div>
			<div class="proinfo_btn_1">

				<a href="javascript:;" title="收藏该商品"
					onclick="favorites('<?=$this->prodarr['id']?>')" class="gbqfb"><i
					class="icon_save"></i>收藏该商品</a>
				</p>
			</div>
			<div class="proinfo fl">
				<div class="proinfo_m fl">
					<h1 class="model" title="<?=$prodarr['part_no'];?>"><?=$prodarr['part_no'];?></h1>
					<img src="<?=$prodarr['stockInfo']['supplierInfo']['img']?>"
						height="36"
						title="<?=$prodarr['stockInfo']['supplierInfo']['name']?>"
						class="png_ie6" />
				</div>
				<div class="proinfo_data fl dl2013">
                
                    <?php if($show_price){?>         
                    <dl class="dl100">
						<dt>零&nbsp;&nbsp;&nbsp;售&nbsp;&nbsp;&nbsp;价：</dt>
						<dd>
							<strong class="price"><span class="price_unit"><?=$unit?></span><span
								id="sell_price"><?php  echo number_format($sell_price,5);?></span></strong>
						</dd>
					</dl>

                    <?php }?>

                    <dl>
						<dt>库&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;存：</dt>
						<dd>
                    <?php 
					if($stock > 0){echo '<b class="fontgreen">'.$stock.'</b>';}
					else {echo '<b class="fontorange">订货</b>';}
					?></dd>
					</dl>
                    <?php if(!$show_price){?>
                    <dl>
						<dt>参考交期：</dt>
						<dd class="lead_time_change"><?=('国内'.$prodarr['lead_time_sz'].'/香港'.$prodarr['lead_time_hk'])?></dd>
					</dl>
                    <?php if(!isset($prodarr['f_bpp_stock_id'])){?>
                    <dl>
						<dt>发&nbsp;&nbsp;&nbsp;货&nbsp;&nbsp;&nbsp;地：</dt>
						<dd>国内/香港</dd>
					</dl>
                    <?php }?>
                    <?php }?>
                    <dl>
						<dt>制造商：</dt>
						<dd><?=($prodarr['manufacturer'])?></dd>
					</dl>

					<dl>
						<dt>最小起订量：</dt>
						<dd><?=$moq?$moq:'--';?></dd>
					</dl>

				</div>
                
                <?php if($show_price){//可以购买?>
                <div class="proinfo_s labelinput dl2013 ">
					<!--jamie 注意：当无法购买时proinfo_s  下面的proinfo_btn加上样式 MT40-->
					<dl class="dl100">
						<dt>数&nbsp;&nbsp;&nbsp;量：</dt>
						<dd>
							<input type="button" name="reducebut" value="-" class="gbqfb_i"
								onclick="setAmountBase.reduce('#goodnum','#multiple','<?=$partid?>','<?=$moq?>','<?=$mpq?>','<?=$stock?>')" />
    <?php if(($moq%$mpq)==0 && $mpq!=0){ echo $mpq.'*';?>
    <input type="text" id="multiple" name="multiplebut"
								value="<?=($moq/$mpq)?>" size="1"
								onkeyup="setAmountBase.multiple('#goodnum','#multiple','<?=$partid?>','<?=$moq?>','<?=$mpq?>','<?=$stock?>')" />
							&nbsp;= <input type="text" id="goodnum" name="pamountbut"
								value="<?=$moq;?>" size="5" disabled="disabled" />
    <?php }else{?>
    <input type="hidden" id="multiple" name="multiplebut" /> <input
								type="text" id="goodnum" name="pamountbut" value="<?=$moq;?>"
								onkeyup="setAmountBase.modify('#goodnum','<?=$partid?>','<?=$moq?>','<?=$mpq?>','<?=$stock?>')"
								size="4" />
    <?php }?>
    <input type="button" name="addbut" value="+" class="gbqfb_i"
								onclick="setAmountBase.add('#goodnum','#multiple','<?=$partid?>','<?=$moq?>','<?=$mpq?>','<?=$stock?>')" />

						</dd>

						<dd>
							<p class="smdata">
								小计：<strong class="price"><span class="price_unit"><?=$unit?></span><span
									id="sell_total"><?=number_format($sell_total,DECIMAL);?></span></strong>
							</p>
						</dd>

					</dl>
					<dl class="dl100">
						<dt>发货地：</dt>
						<dd>
                            <?php if($prodarr['f_show_price_sz']){?>
    <label> <input type="radio" name="delivery_place" value="SZ"
								<?=$checked_sz?> class="delivery_place"
								onclick="subtotal('#goodnum');changeStock('SZ');"> 国内(含增税)
							</label>
    <?php }
			if($prodarr['f_show_price_hk']){?>
   <!--  <label> <input type="radio" name="delivery_place" value="HK"
								<?=$checked_hk?> class="delivery_place"
								onclick="subtotal('#goodnum');changeStock('HK');"> 香港(美元)
							</label> -->
    <?php }?>
                            <span class="tipifo">(标准交期：<span
								class="lead_time_show"><?=$lead_time?></span>)
							</span>
						</dd>
					</dl>
				</div>
                <?php }?>
                
                
                <div class="proinfo_btn ">
                <?php if(!$this->prodarr['noinquiry']){?>
                
    <a href="javascript:"
						onclick="openInquiry('<?=$this->prodarr['id']?>')" title="询价"
						class="btnok-new1 logclick" rev="prodderails_part_id"
						rel="<?=$this->prodarr['id']?>"><i class="icon_buy"></i>询价看看</a>
    <?php }?>
    <?php if($show_price){?>
    <a href="javascript:"
						onclick="buy_details('#goodnum','<?=$this->prodarr['id']?>','<?=$moq?>')"
						title="加入购物车" class="btnok-new1 logclick"
						rev="prodderails_part_id" rel="<?=$this->prodarr['id']?>"><i
						class="icon_xun"></i>立即购买</a>
    <?php }?>	
					
                </div>



		</div>
		<!--梯形价格-->
		<div class="fr  LadderPrice">
               <?php if($show_price){?>
               <h2>产品阶梯价格</h2>
			<div class="LadderPrice_c" id="break_price_show">
				<ul>
					<li class="w30">数量</li>
					<li class="w70"><?=$break_price_title?></li>
				</ul>
                    <?=$break_price;?>
               </div>
              <?php }else{?>
              <h2>询价提示</h2>
			<ul>
				<li>1、24小时内快速提供报价</li>
				<li>2、提交询价后立即发送确认邮件</li>
				<li>3、登录我的询价实时查看处理情况</li>
			</ul>
           <?php }?>

            </div>

	</div>
</div>
<div class="w ">
	<div class="prodetail2013_c fl ">

		<div class="pos_reltab MT20">
			<ul class="tabbar clearfix">
				<li class="selected"><a href="javascript:">产品信息<b class="blank3"></b></a></li>
			</ul>
		</div>
		<div>
			<div id='prodattribute' class="tab_con"
				style="margin-left: 20px;: block;">
				<div style="margin: 20px;">
					<img src="/images/admin/ajax-loader.gif" />
				</div>
			</div>
		</div>
	</div>


	<div class="fr rightbox boxshadow  pos-re">
		<!--热销推荐-->
		<div id='hotpord'></div>
	</div>
</div>
</div>
<script type="text/javascript">
function openFav(type) {
   var name = 'myexist';
   if(type=='ok')  name = 'myok';
	$.openPopupLayer({
		name: "favAlert",
		target: name
	});
}
</script>
<div class="pop pop_save" id="myok" style="display: none">
	<div class="popbox">
		<div class="popcon clearfix msg">
			<h3>
				<div class="ok">该商品已成功放入收藏夹</div>
			</h3>
			<p class="spbbtndiv">
				<a href="javascript:" onClick="$.closePopupLayer('favAlert')">继续购物</a>
				<a class="abutton" href="/center/favorites" target="_parent">
        <?=$this->translate('Menu_MyFavorites')?>
        </a>
			</p>
		</div>
	</div>
</div>
<div class="pop pop_save" id="myexist" style="display: none">
	<div class="popbox">
		<div class="popcon clearfix msg">
			<h3>
				<div class="tips">你已经收藏过该商品</div>
			</h3>
			<p class="spbbtndiv">
				<a href="javascript:" onClick="$.closePopupLayer('favAlert')">继续购物</a>
				<a class="abutton" href="/center/favorites" target="_parent">
        <?=$this->translate('Menu_MyFavorites')?>
        </a>
			</p>
		</div>
	</div>
</div>
<script src="/js/jsplug/lightbox/js/lightbox.js"></script>
<script type="text/javascript">

$(function(){
	$('.pprice201312').hover(function(){
		$(this).addClass("item-hover");
	},function(){
		$(this).removeClass("item-hover");
	});
	//加载产品参数信息
	$("#prodattribute").load("/publicbox/prodattribute?partNo=<?php echo $prodarr['part_no']?>");
});

var break_price_sz = '<ul><li class="w30">数量</li><li class="w70"  class="titbg1ts">含税(17%)</li></ul><?=$prodarr['f_break_price_new_d_sz']?>';
var break_price_hk = '<ul><li class="w30">数量</li><li class="w70"  class="titbg1ts">美元</li></ul><?=$prodarr['f_break_price_new_d_hk']?>';

$(function(){
//价格
          var tab = $(".subhot .goodsprice");
           tab.hover(function(){
		       $(this).find(".price").addClass("hover");
			   $(this).find(".tipprice").addClass("block");
           },function(){
		       $(this).find(".price").removeClass("hover");
			   $(this).find(".tipprice").removeClass("block");
           });
		//不同交货地
        $(".delivery_place").click(function(){
			if(this.value=='SZ'){
				
				$(".price_unit").html('<?=$prodarr['f_rmb']?>');
				$("#break_price_show").html(break_price_sz);
				$(".freetotl").html("满<?=$this->freetotl?>");
				$(".lead_time_change").html("<?=$prodarr['lead_time_cn']?>");
				
			}else if(this.value=='HK'){

				$(".price_unit").html('<?=$prodarr['f_usd']?>');
				$("#break_price_show").html(break_price_hk);
				$(".freetotl").html("满<?=$this->freetotl_hk?>");
				$(".lead_time_change").html("<?=$prodarr['lead_time_hk']?>");
			}
        });
})


//轮转
    $(function(){
        var tab = $(".tabbar li");
        tab.hover(function(){
            $(this).addClass("selected").siblings().removeClass("selected");		
            var index = tab.index(this);
            $(".tab_con").eq(index).show().siblings().hide();	
        });
     })

function favorites(prodid){
	$.ajax({
            url: '/index/checklogin',
            data: {},
            type: 'post',
            dataType: 'json',
            success: function(arr) {
			   if(arr.code==0)
			   {  
			   		$.ajax({
					url: '/proddetails/addfavorites',
					data: {'partid':prodid},
					type: 'post',
					dataType: 'json',
					success: function(arr) { 
					   if(arr.code==0) openFav('ok');
					   else if(arr.code==1) openFav('exist');
					   else alert(arr.message);
					   setTimeout('hidAlert()',1500);
					}
					});
			   }else if(arr.code==100){
			   	 $.openPopupLayer({
		             name: "loginBox",
		             target: "login_box"
	              });
			   }else if(arr.code==200){
			   	   window.location.href ="/user/verification";
			   }
            }
    });
}
//加载热销
$(function(){

		$("#hotpord").load("/publicbox/hotpord");

	})
	
function hidAlert(){
	$.closePopupLayer('favAlert');
	$.closePopupLayer('cartshowBox');
}

//改变库存
function changeStock(dv){
	if(dv=="SZ"){
	    $(".showstock").html("<?=$prodarr['f_stock_sz']?>");
	}else if(dv=="HK"){
		$(".showstock").html("<?=$prodarr['f_stock_hk']?>");
	}
}
</script>
<script src="/js/jsplug/My97DatePicker/WdatePicker.js"
	type="text/javascript"></script>