<div id="myHiddenDiv">
  <div class="popup">
    <div class="popup-header">
      <h2>添加属性</h2>
      <a href="javascript:;" onclick="$.closePopupLayer('box');" title="关闭" class="dialogBoxClose">关闭</a> </div>
    <div class="popup-body">
      <!-- 需要填写的区域-->
      <table width="700px" border="0" cellpadding="1">
        <tr>
          <td height="10" colspan="3" align="center"><div id="message_sess_son" style="display:none" class="message_sess"> <span title="关闭" class="but" onclick="document.getElementById('message_sess_son').style.display='none'"></span> <span id="alert_message_son"></span> </div></td>
        </tr>
        <tr>
          <td colspan="2"><table bgcolor="#CCCCCC" width="100%">
              
               <tr>
                <td width="50" align="right"><font color="#666600"><b>状态 : </b></font></td>
                <td colspan="3" align="left"> <label><input type="radio" name="status" value="1" checked="checked"/>
                 <font color="#339900"><b>ON</b></font></label>
                  <label><input type="radio" name="status" value="0"/>
                  <font color="#CC3333"><b>OFF</b></font></label>
                </td>
              </tr>
              <tr>
                <td width="126" align="right"><font color="#666600"><b>名称<em>*</em>: </b></font></td>
                <td colspan="3"  align="left">
                <input type="text" name="cname" id="cname"/></td>
              </tr>
              <tr>
                <td width="126" align="right"><b><font color="#666600">英文名称 : </font></b></td>
                <td align="left" colspan="3"><input type="text" name="ename" id="ename"/></td>
              </tr>
              <tr>
                <td width="126" align="right"><font color="#666600"><b> 排序 : </b></font></td>
                <td align="left" colspan="3"><input type="text" name="displayorder" id="displayorder" value="" onKeyUp="<?php echo ISNUMBER;?>"/></td>
              </tr>
              <tr>
                <td align="center" colspan="2"><input type="button"  value="添加" onclick="addaction()" class="btnabig"/>
                </td>
              </tr>
            </table></td>
        </tr>
      </table>
      <!-- 结束区域-->
    </div>
  </div>
</div>
<script type="text/javascript" language="javascript">
function addaction()
{
	var statusobj = document.getElementsByName('status');
	for(i=0;i<statusobj.length;i++){
	  if(statusobj[i].checked){
	     var status = statusobj[i].value;
	     break;
	  }
	}
	var cname = document.getElementById('cname').value;
	if(cname == '') {alert("请填写名称");document.getElementById('cname').focus();return;}
	var ename    = document.getElementById('ename').value;
	var displayorder   = document.getElementById('displayorder').value;
	
	$.ajax({
            url: '<?=$this->indexurl?>/addproperty',
            data: {'status':status,'cname':cname,'ename':ename,'displayorder':displayorder},
            type: 'post',
            dataType: 'json',
            success: function(arr) {
              if(arr.code == 0){
            	  alert(arr.message);
				  location.reload();
               }else{
			      document.getElementById('message_sess_son').style.display = "block";
	              document.getElementById('alert_message_son').innerHTML = arr.message;
			   }
			}
	});
}
</script>
