<link rel="stylesheet" type="text/css" href="/css/default/buyprocess2014.css" />
<div id="header" class="w">
    <div id="logo"><a hidefocus="true" href="/"><img alt="IC易站" src="/images/default/logo.jpg"></a></div>
    <h1>我的购物车</h1>
</div>
<!--registerted-->
<div class="w buyprocess">
	<div class="registerline"></div>
    <div class="steps step-1">
        <ol>
            <li>我的购物车</li>
            <li>填写核对信息单</li>
            <li>成功提交订单</li>
        </ol>
    </div>
</div>
<?php $delivery_place_arr=array('SZ'=>'国内','HK'=>'香港');?>
<div class="w lh">
    <div class="Shopping_cart 1h">
    <h1><img src="/images/default/cart.jpg" />我的购物车</h1>
    <div class="tipfree"><b class="fontgreen">IC易站根据不同交货地，自动为您分开两张不同交货地订单</b></div>
    <?php if(empty($this->items)){?>
     <table border="0" cellpadding="0" cellspacing="0" class="listtable boxshadow_h">
      <tr>
        <td colspan="9" height="50px" style="font-size:16px;">购物车内暂时没有商品，您可以去<a href="/">首页挑选喜欢的商品</a></td>
      </tr>
    </table>
    <?php }else{
	      foreach($this->items as $delivery_place=>$items){
	   ?>
      <table border="0" cellpadding="0" cellspacing="0" class="shopbox table ">
      <tbody>
      <tr>
        <th>交货地</th>
        <th>型号</th>
        <th>阶梯价格</th>
        <th>最少购买数</th>
        <th>购买数量</th>
        <th>单价</th>
        <th>小计</th>
        <th>操作</th>
      </tr>
      	<?php
			foreach($items as $key=>$item){
				$rowid       = $item['rowid'];
				$moq         = $item['moq'];
				$mpq         = $item['mpq'];
				$multipleid  = 'multiple_'.$rowid;
				$inputid     = 'pamount_'.$rowid;
				$priceid     = 'price_'.$rowid;
				$itemtotalid = 'itemtotal_'.$rowid;
			?>
      <tr>
        <?php if($key==0){?><td rowspan="<?=count($items)?>" style="background-color:#FFFFFF"><b><?=$delivery_place_arr[$delivery_place]?></b></td><?php }?>
        <td>
        	<div class="productinfo">
                <img src="<?=PRODUCTICON.($item['options']['part_img']==''?'no.gif':$item['options']['part_img']);?>">
                <div class="productinfop">
                    <p><a href="/item-0-0-<?=$item['pord_id'];?>-<?=$this->fun->filterUrl($item['part_no'])?>.html" target="_blank"  class="model"><?=$item['part_no'];?></a></p>
                    <p><?=$item['options']['brand'];?></p>
                    <p><p title="<?=$item['options']['description']?>"><?=$this->fun->utf_substr($item['options']['description'],68)?></p>
                </div>
            </div>
           
        </td>
        <td>
        	<div class="price_btn_table"><?=$item['options']['show_bprice'];?></div>
        </td>
        <td><?=$item['moq'];?></td>
        <td>  
        <div class="add_sub">
            
            <?php if(($moq%$mpq)==0 && $mpq!=0){?>
                <div class="fl addspan">
                	<span><?=$mpq;?>*</span>
                </div>
                
                <div class="fl add_sub_btn">
                    <input type="button" name="reducebut" value="-"  class="btn_sub" onclick="setAmount.reduce('#<?=$inputid;?>','#<?=$multipleid;?>','<?=$rowid;?>','<?=$moq;?>','<?=$mpq;?>')"/>
                    <input type="text" id="<?=$multipleid;?>" name="multiplebut" value="<?=(int)$item['qty']/$mpq;?>" size="1" onkeyup="setAmount.multiple('#<?=$inputid;?>','#<?=$multipleid;?>','<?=$rowid;?>','<?=$moq;?>','<?=$mpq;?>')" class="textshort"/>
                    <input type="button" name="addbut" value="+" class="btn_and" onclick="setAmount.add('#<?=$inputid;?>','#<?=$multipleid;?>','<?=$rowid;?>','<?=$moq;?>','<?=$mpq;?>')"/>
                </div>
                <div class="fr results">
                	<span>=</span>
                    <input type="text" id="<?=$inputid;?>" name="pamountbut" class="textlong" value="<?=$item['qty'];?>" size="4" disabled="disabled"/>
                </div>

            <?php }else{?>
    
                <div class="fl add_sub_btn add_sub_btn1">
            <div style="display:none"><input type="text" id="<?=$multipleid;?>" name="multiplebut"/></div>
            <input type="button" name="reducebut" value="-"  onclick="setAmount.reduce('#<?=$inputid;?>','#<?=$multipleid;?>','<?=$rowid;?>','<?=$moq;?>','<?=$mpq;?>')" class="btn_sub" />
            <input type="text" id="<?=$inputid;?>" name="pamountbut"  onkeyup="setAmount.modify('#<?=$inputid;?>','<?=$rowid;?>','<?=$moq;?>','<?=$mpq;?>')" value="<?=$item['qty'];?>" size="4"  class="textshort"/>
            <input type="button" name="addbut" value="+" class="btn_and" onclick="setAmount.add('#<?=$inputid;?>','#<?=$multipleid;?>','<?=$rowid;?>','<?=$moq;?>','<?=$mpq;?>')"/>
                </div>

            <?php }?>
          </div>  
          </td>
        <td class="price"><?=$item['unit']?><label name='<?=$priceid;?>'><?=number_format($item['byprice'],DECIMAL);?></label></td>
        <td class="price"><?=$item['unit']?><label name='<?=$itemtotalid;?>'><?=number_format($item['byprice']*$item['qty'],DECIMAL);?></label></td>
        <td><a href="javascript:" onclick="delectcart('<?=$rowid;?>')">删除</a><br/>
        <a href="javascript:" onclick="changeplace('<?=$rowid;?>')">更换交货地</a>
        </td>
       </tr>
       <?php }?>
       </tbody></table>
 
        <div class="bg_cart">
            <div class="fl">
                <a href="/"><em></em>继续购物</a>
            </div>
            <div class="fr" id="buyaction">
            	<a class="button" onclick="order('<?=$delivery_place?>')">去结算</a>
            </div>
        </div>
           <?php }//end foreach($this->items as $delivery_place=>$item)?>
        <?php }//end if?>
      </div> 
</div>
<script src="/js/default/cart.js" type="text/javascript"></script>