<?php $paytypearr = array('transfer'=>'银行转账','online'=>'在线支付','cod'=>'货到付款','mts'=>'款到发货');?>
	<div class="conmian">
<h1><?php echo $this->AreaTitle;?> 
<?php if($this->sellprod){?>
   -> <a href="/icwebadmin/RepoSell/export?type=<?=$this->type?>&sdata=<?=$this->sdata?>&edata=<?=$this->edata?>&property=<?=$this->property?>&brand=<?=$this->selectbrand?>&xsname=<?=$this->xsname?>&ordertype=<?=$this->ordertype?>" target="_blank" title="将搜索结果导出成Excel">导出Excel</a>
  <?php }?>
</h1>

<form id="myform"  class="form-search" name="myform" action="" method="get">

<label>开始时间：</label>
<input type="text"  style="width:80px;" name="sdata" value="<?=$this->sdata?>" onclick="WdatePicker({startDate:'',dateFmt:'yyyy-MM-dd',alwaysUseStartDate:true,lang:'sc'})"/>
<label>结束时间：</label>
<input type="text"  style="width:80px;" name="edata" value="<?=$this->edata?>" onclick="WdatePicker({startDate:'',dateFmt:'yyyy-MM-dd',alwaysUseStartDate:true,lang:'sc'})"/>
    
<select name="property">
<option value="">客户性质-全部</option>
<option value='merchant' <?=($this->property=='merchant'?'selected':'')?>>贸易商</option>
<option value='enduser' <?=($this->property=='enduser'?'selected':'')?>>终端用户</option>
</select>
   
<select name="brand">
<option value="">产品线-全部</option>
<?php foreach($this->brand as $bd){?>
<option value='<?=$bd['id']?>' <?=$bd['id']==$this->selectbrand?'selected':''?>><?=$bd['name']?></option>
<?php }?>
</select>

<?php if($_SESSION['staff_sess']['level_id']!='XS'){?>
<div class="input-append">
<select name="xsname" id="xsname">
      <option value="" <?=$this->xsname==''?'selected':''?>>跟进销售-全部</option>
      <option value="alina.shang" <?=$this->xsname=='alina.shang'?'selected':''?>>尚玉(alina.shang)</option>
      <?php for($i=0;$i<count($this->xs_staff);$i++){?>
      <option value="<?=$this->xs_staff[$i]['staff_id']?>" <?=$this->xsname==$this->xs_staff[$i]['staff_id']?'selected':''?>><?=$this->xs_staff[$i]['lastname'].$this->xs_staff[$i]['firstname']."(".$this->xs_staff[$i]['staff_id'].")"?></option>
      <?php }?>
</select>
</div>
<?php }?>
    		
    <select name="type" id="type">
      <option value="all" <?=$this->type=='all'?'selected':''?>>订单类型-全部</option>
      <option value="sqs" <?=$this->type=='sqs'?'selected':''?>>SQS Code</option>
      <option value="normal" <?=$this->type=='normal'?'selected':''?>>正常流程</option>
</select>

    <select name="ordertype" id="ordertype">
      <option value="online" <?=$this->ordertype=='online'?'selected':''?>>线上订单</option>
      <option value="outline" <?=$this->ordertype=='outline'?'selected':''?>>线下订单</option>
      <option value="all" <?=$this->ordertype=='all'?'selected':''?>>全部</option>
</select>

    &nbsp;
    <input type="submit" class="btn" value="确 定"/>
  </form>
				<div id="message_sess" style="display:none" class="message_sess"> 
          <div title="关闭" class="but" onclick="document.getElementById('message_sess').style.display='none'">&nbsp;</div>
          <div id="alert_message"></div> 
          </div>       
	  <!-- 需要填写的区域-->
      <div class="contentmia">
      <table class="table ordertable"  border="1" style=" margin-top:-1px;">
          <thead>
           <tr>
            <th>月份</th>
            <th>销售人员代码</th>
            <th>销售人员名称</th>
            <th>部门</th>
            <th>客户名称</th>
            <th>盛芯电子订单号</th>
            <th>产品线</th>
            <th>型号</th>
            <th>销售数量</th>
            <th>单价</th>
            <th>收入合计(RMB)</th>
            <th>收入合计(USD)</th>
            <th>收入合计(HKD)</th>
            <th>SAP订单号</th>
            <th>SAP订单类型</th>
            <th>SAP客户</th>
            <?php if($this->logtype){?>
            <th>付款方式</th>
            <th>支付时间</th>
            <th>下单时间</th>
            <th>释放订单时间</th>
            <th>释放订单人员</th>
            <th>释放原因</th>
            <th>发货时间</th>	
            <th>发货录入人员</th>
			<?php }?>
            </tr>
            </thead>
          <tbody>
            <?php  if(empty($this->sellprod)){?>
            <tr><td colspan="19" style="color:#FF0000"><center>请选择时间段查询</center></td></tr>
            <?php }else{
				 	foreach($this->sellprod as $k=>$data){
					$rmbtotal = $usdtotal = $hkdtotal = '';
					if($data['currency']=='RMB') $rmbtotal = $data['buynum']*$data['buyprice'];
					elseif($data['currency']=='USD') $usdtotal = $data['buynum']*$data['buyprice'];
					elseif($data['currency']=='HKD') $hkdtotal = $data['buynum']*$data['buyprice'];
 			?>
            <tr>
                <td><?=date('Y/m/d',$data['created'])?></td>
                <td></td>
                <td><?=$data['lastname'].$data['firstname']?></td>
                <td><?=$data['department']?></td>
                <td><?php if($data['companyname']) echo $data['companyname'];
				          elseif($data['invtype']==2 && $data['invname']) echo $data['invname'];
						  else echo $data['uname'];?></td>
                <td><?=$data['salesnumber']?></td>
                <td><?=$data['brand']?></td>
                <td><?=$data['part_no']?></td>
                <td><?=$data['buynum']?></td>
                <td><?=$data['buyprice']?></td>
                <td><?=$rmbtotal?></td> 
                <td><?=$usdtotal?></td>  
                <td><?=$hkdtotal?></td>
                <td><?=$data['order_no']?></td>
                <td><?=$data['auart']?></td>
                <td><?=$data['cname']?></td>
                <?php if($this->logtype){?>
                <td><?=$paytypearr[$data['paytype']]?></td>
                <td><?=$data['pay_time']?date('Y/m/d H:i',$data['pay_time']):'--'?></td>
                <td><?=date('Y/m/d H:i',$data['created'])?></td>
                <td><?=date('Y/m/d H:i',$data['log1'][0]['log1created'])?></td>
                <td><?=$data['log1'][0]['st1lname'].$data['log1'][0]['st1fname']?></td>
                <td></td>
                  <td><?=date('Y/m/d H:i',$data['log2'][0]['log2created'])?></td>
                <td><?=$data['log2'][0]['st2lname'].$data['log2'][0]['st2fname']?></td>
                <?php }?>
                
            </tr>
          <?php }}?>
          </tbody>
        </table>
        </div>
      <!-- 结束区域-->
	</div>
    <script src="/js/jsplug/My97DatePicker/WdatePicker.js" type="text/javascript"></script>