<link rel="stylesheet" type="text/css" href="css/myself.css" />
<div id="header" class="w">
  <div id="logo"><a hidefocus="true" href="/"><img alt="IC易站" src="/images/default/logo.jpg"></a></div>
  <h1>在线支付订单</h1>
</div>
<!--content-->
<div class="w mtb20 lh">
    <div class="regstep3">
        <ul>
            <li>1.我的购物车</li>
            <li>2.填写核对信息单</li>
            <li class="Current">3.成功提交订单</li>
        </ul>
    </div>
    
<div class="order wborder w-958 mtb20">
    <table cellpadding="0" cellspacing="0" >
        <caption>订单已经提交成功，请尽快付款！</caption>
        <thead>
            <tr>
                <th>订单号</th>
                <th>需支付金额（元）</th>
                <th>支付方式</th>
                <th>发货仓库</th>
                <th>预计到货时间</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td class="fontblue">656565565121</td>
                <td class="fontred">￥192.00</td>
                <td>在线支付-支付宝</td>
                <td>广州仓库</td>
                <td>1-2（2-3天备货）</td>
            </tr>
        </tbody>
    </table>
    <div class="pay-detail">
    <div class="pay-detail">
    <input type="radio" name="paymenttype" id="paymenttype1" value="online" checked="checked"/>
            <label for="paymenttype1">支付宝支付</label>
            <img src="/images/default/bank/01.jpg" /></p>
        <p><input type="button"  value="立即支付"  class="btnred1"/></p>
    </div>
		<p>你可以点击“立即支付”完成网上支付。支付成功后，我们可以立即为您发货。</p>
        <p><input type="button"  value="立即支付"  class="btnred1"/></p>
    </div>
    <div class="order-oprate">
        <a href="#" target="_blank" >修改订单</a> | <a href="#" target="_blank">订单详情</a> | <a href="#" target="_blank" >继续购物</a>
    </div>
    <div class="order-tip">
        <p>提示：</p>
        <p>1、您的订单已经在处理中，请稍后查看您的订单详情，发货后订单配送信息会显示配送人员联系方式，如有必要您可以主动联系配送人员。</p>
        <p>2、未完成在线支付的订单将保留24小时，如果您现在不方便支付，可于24小时内到<a href="#" class="fontblue">我的IC易购</a>中完成支付或者<a href="#" class="fontred">立即支付</a>。</p>
    </div>
    
</div>