<link rel="stylesheet" type="text/css" href="/css/default/buyprocess.css" />
<div id="header" class="w">
  <div id="logo"><a hidefocus="true" href="/"><img alt="盛芯电子" src="/images/default/logo.jpg"></a></div>
  <h1>在线支付订单</h1>
</div>
<!--content-->
<div class="w lh Order ">
	<div class="Order_details">
    <table cellpadding="0" cellspacing="0" class="tableorder table">
        <caption>订单已经支付完成了吗？</caption>
        <thead>
            <tr>
                <th>订单号</th>
                <th>需支付金额</th>
                <th>收货人信息</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <tr>
                            <td><a href="/order/view?salesnumber=<?=$this->orderarr['salesnumber']?>" title="查看订单详细" target="_blank">
		  <?php echo $this->orderarr['salesnumber'];?></a></td>
                            <td class="fontred">￥<?php echo number_format($this->orderarr['total'],DECIMAL);?></td>
                            <td><?php echo $this->orderarr['name'];?>&nbsp;&nbsp;&nbsp;&nbsp; <?php echo $this->orderarr['province'].$this->orderarr['city'].$this->orderarr['area'].$this->orderarr['address'];?>&nbsp;&nbsp;&nbsp;&nbsp; <?php echo $this->orderarr['mobile']."  ".$this->orderarr['tel'];?></td>
                        </tr>
            </tr>
        </tbody>
    </table>
     <div class="pay-detail">
     <p><input type="button"  value="已支付成功"  class="button" onclick="javascript:gotoorder();"/>
        &nbsp;&nbsp;&nbsp;&nbsp;<input type="button"  value="支付遇到问题"  class="button" onclick="javascript:gotoorder2();"/></p>
    </div>
        <div class="order-oprate">
       
         <div class="bg_cart">
            <div class="fl">
                <a href="/"><em></em>继续购物</a>
            </div>
            <div class="fr">
                <a href="/center/order" class="button"><?=$this->translate('Menu_MyOrder')?></a>
            </div>
        </div>
        </div>
    </div>
</div>
<script type="text/javascript">
<?php if($this->ordertype=='online'){?>
var url = '/center/order';
<?php }else{?>
var url = '/center/inqorder';
<?php }?>
function gotoorder(){
   window.location.href=url+'?type=send';
}
function gotoorder2(){
   window.location.href=url+'?type=wpay';
}
</script>