<link rel="stylesheet" type="text/css" href="/css/default/shop.css" />
<!--content-->
<div class="w mtb20 lh">
    
    <div class="order wborder w-958 mtb20">
    <table cellpadding="0" cellspacing="0" >
        <caption>支付成功！</caption>
        <thead>
            <tr>
                <th><a href="/center/order"><?=$this->translate('Menu_MyOrder')?>&gt;&gt;</a> | <a href="/">继续购物&gt;&gt;</a></th>
            </tr>
        </thead>
    </table>
      </div>
</div>
