<link rel="stylesheet" type="text/css" href="/js/jsplug/advanced_docking/css/docking.css" />
<!--滚动-->
<style type="text/css">
.up_zzjs {
	border:0px solid #ccc;
	padding-top:3px;
	height:22px;
	line-height:22px;
	overflow:hidden;
}
.updiv {
	background-color:#F5F5F5;
}
</style>
<script type="text/javascript">
function startmarquee(lh,speed,delay,div_id) {
		var p=false;
		var t;
		var o=document.getElementById(div_id);
		o.innerHTML+=o.innerHTML;
		o.style.marginTop=0;
		o.onmouseover=function(){p=true;}
		o.onmouseout=function(){p=false;}
	
		function start(){
			t=setInterval(scrolling,speed);
			if(!p) o.style.marginTop=parseInt(o.style.marginTop)-1+"px";
		}
	
	    function scrolling(){
		    if(parseInt(o.style.marginTop)%lh!=0){
			   o.style.marginTop=parseInt(o.style.marginTop)-1+"px";
			   if(Math.abs(parseInt(o.style.marginTop))>=o.scrollHeight/2) o.style.marginTop=0;
		    }else{
			   clearInterval(t);
			   setTimeout(start,delay);
			}
		}
		setTimeout(start,delay);
	}
</script>
<div style="width:870px;float:left;margin-left:5px;margin-bottom:5px">
  <!--移动块-->
  <?php //print_r($this->inq['oainq']);?>
  <!--左边-->
  <div class="column" id="column1">
    <?php if($this->inqcan){?>
    <div class="dragbox" id="item1" >
      <h2><span class="configure" ><a href="/icwebadmin/QuoInq" target="_blank">更多</a></span>客户询价</h2>
      <div class="dragbox-content" >
        <p><a href="/icwebadmin/QuoInq?type=oainq" title="查看" target="_blank">待处理</a>（<em><?=count($this->inq['oainq'])?></em>）</p>
        <div class="up_zzjs">
          <div id="upbox_inq_oainq">
            <?php foreach($this->inq['oainq'] as $oainq){
			 		$partnos = '';
			        foreach($oainq['detaile'] as $detaile){$partnos .=','.$detaile['part_no'];}
				$title = $oainq['companyname'].' '.$partnos;
				$tourl = '<a href="/icwebadmin/QuoInq?type=oainq&keyword='.$oainq['inq_number'].'" target="_blank" title="去处理">'.$oainq['inq_number'].'</a>';
			?>
            <div class="updiv">
              <?=$this->fun->utf_substr($title,40)?>
              <?=$tourl?>
            </div>
            <?php }
			if(empty($this->inq['oainq'])) echo '<div>暂无待处理项</div>';?>
          </div>
        </div>
        <p><a href="/icwebadmin/QuoInq?type=wait" title="查看" target="_blank">待报价</a>（<em><?=count($this->inq['wait'])?></em>）</p>
        <div class="up_zzjs">
          <div id="upbox_inq_wait">
            <?php foreach($this->inq['wait'] as $oainq){
			 		$partnos = '';
			        foreach($oainq['detaile'] as $detaile){$partnos .=','.$detaile['part_no'];}
				$title = $oainq['companyname'].' '.$partnos;
				$tourl = '<a href="/icwebadmin/QuoInq?type=wait&keyword='.$oainq['inq_number'].'" target="_blank" title="去处理">'.$oainq['inq_number'].'</a>';
			?>
            <div class="updiv">
              <?=$this->fun->utf_substr($title,40)?>
              <?=$tourl?>
            </div>
            <?php }
			if(empty($this->inq['wait'])) echo '<div>暂无待处理项</div>';?>
          </div>
        </div>
      </div>
    </div>
    <script language="javascript">
		<?php if(count($this->inq['oainq'])>1){?>
		startmarquee(22,20,8000,'upbox_inq_oainq');
		<?php }?>
		<?php if(count($this->inq['wait'])>1){?>
		startmarquee(22,20,8000,'upbox_inq_wait');
		<?php }?>
	</script>
    <?php }?>
    <?php if($this->sqscan){?>
    <div class="dragbox" id="item3" >
      <h2><span class="configure" ><a href="/icwebadmin/OrOrgl" target="_blank">更多</a></span>在线订单</h2>
      <div class="dragbox-content" >
        <p><a href="/icwebadmin/OrOrgl?type=rel" title="查看" target="_blank">待审核</a>（<em><?=count($this->sqsso['rel'])?></em>）</p>
        <div class="up_zzjs">
          <div id="upbox_sqsso_rel">
            <?php foreach($this->sqsso['rel'] as $relsqsso){
				$title = ($relsqsso['companyname']?$relsqsso['companyname']:$relsqsso['uname']).' , '.$relsqsso['partnos'];
				$tourl = '<a href="/icwebadmin/OrOrgl?type=rel&salesnumber='.$relsqsso['salesnumber'].'" target="_blank" title="去处理">'.$relsqsso['salesnumber'].'</a>';
			?>
            <div class="updiv">
              <?=$this->fun->utf_substr($title,40)?>
              <?=$tourl?>
            </div>
            <?php }
			if(empty($this->sqsso['rel'])) echo '<div>暂无待处理项</div>';?>
          </div>
        </div>
        <p><a href="/icwebadmin/OrOrgl?type=wpay"  title="查看" target="_blank">待付款</a>（<em><?=count($this->sqsso['wpay'])?></em>）</p>
        <div class="up_zzjs">
          <div id="upbox_sqsso_wpay">
            <?php foreach($this->sqsso['wpay'] as $wpaysqsso){
				$title = ($wpaysqsso['companyname']?$wpaysqsso['companyname']:$wpaysqsso['uname']).' , '.$wpaysqsso['partnos'];
				$tourl = '<a href="/icwebadmin/OrOrgl?type=wpay&salesnumber='.$wpaysqsso['salesnumber'].'" target="_blank" title="去处理">'.$wpaysqsso['salesnumber'].'</a>';
			?>
            <div class="updiv">
              <?=$title?>
              <?=$tourl?>
            </div>
            <?php }
			if(empty($this->sqsso['wpay'])) echo '<div>暂无待处理项</div>';?>
          </div>
        </div>
        <p><a href="/icwebadmin/OrOrgl?type=ema"  title="查看" target="_blank">待释放订单</a>（<em><?=count($this->sqsso['ema'])?></em>）</p>
        <div class="up_zzjs">
          <div id="upbox_sqsso_ema">
            <?php foreach($this->sqsso['ema'] as $emasqsso){
				$title = ($emasqsso['companyname']?$emasqsso['companyname']:$emasqsso['uname']).' , '.$emasqsso['partnos'];
				$tourl = '<a href="/icwebadmin/OrOrgl?type=ema&salesnumber='.$emasqsso['salesnumber'].'" target="_blank" title="去处理">'.$emasqsso['salesnumber'].'</a>';
			?>
            <div class="updiv">
              <?=$title?>
              <?=$tourl?>
            </div>
            <?php }
			if(empty($this->sqsso['ema'])) echo '<div>暂无待处理项</div>';?>
          </div>
        </div>
      </div>
    </div>
    <script language="javascript">
		<?php if(count($this->sqsso['rel'])>1){?>
		startmarquee(22,20,8000,'upbox_sqsso_rel');
		<?php }?>
		<?php if(count($this->sqsso['wpay'])>1){?>
		startmarquee(22,20,8000,'upbox_sqsso_wpay');
		<?php }?>
		<?php if(count($this->sqsso['ema'])>1){?>
		startmarquee(22,20,8000,'upbox_sqsso_ema');
		<?php }?>
	</script>
    <?php }?>

  </div>
  <!--end 左边-->
  <!--右边-->
  <div class="column" id="column2" >
    <?php if($this->inqsocan){?>
    <div class="dragbox" id="item2" >
      <h2><span class="configure" ><a href="/icwebadmin/OrInqo" target="_blank">更多</a></span>询价订单</h2>
      <div class="dragbox-content">
        <p><a href="/icwebadmin/OrInqo?type=rel" target="_blank" title="查看">待审核</a>（<em><?=count($this->inqso['rel'])?></em>）</p>
        <div class="up_zzjs">
          <div id="upbox_inqso_rel">
            <?php foreach($this->inqso['rel'] as $inqso){
				  $title = $inqso['companyname'].' , '.$inqso['partnos'];
				  $tourl = '<a href="/icwebadmin/OrInqo?type=rel&&salesnumber='.$inqso['salesnumber'].'" target="_blank" title="去处理">'.$inqso['salesnumber'].'</a>';
			?>
            <div class="updiv">
              <?=$this->fun->utf_substr($title,40)?>
              <?=$tourl?>
            </div>
            <?php }
			if(empty($this->inqso['rel'])) echo '<div>暂无待处理项</div>';?>
          </div>
        </div>
        <p><a href="/icwebadmin/OrInqo?type=wpay" target="_blank" title="查看">待付款</a>（<em><?=count($this->inqso['wpay'])?></em>）</p>
        <div class="up_zzjs">
          <div id="upbox_inqso_wpay">
            <?php foreach($this->inqso['wpay'] as $inqso){
				  $title = $inqso['companyname'].' , '.$inqso['partnos'];
				  $tourl = '<a href="/icwebadmin/OrInqo?type=rel&&salesnumber='.$inqso['salesnumber'].'" target="_blank" title="去处理">'.$inqso['salesnumber'].'</a>';
			?>
            <div class="updiv">
              <?=$this->fun->utf_substr($title,40)?>
              <?=$tourl?>
            </div>
            <?php }
			if(empty($this->inqso['wpay'])) echo '<div>暂无待处理项</div>';?>
          </div>
        </div>
        <p><a href="/icwebadmin/OrInqo?type=ema" target="_blank" title="查看">待释放订单</a>（<em><?=count($this->inqso['ema'])?></em>）</p>
        <div class="up_zzjs">
          <div id="upbox_inqso_ema">
            <?php foreach($this->inqso['ema'] as $inqso){
				  $title = $inqso['companyname'].' , '.$inqso['partnos'];
				  $tourl = '<a href="/icwebadmin/OrInqo?type=rel&&salesnumber='.$inqso['salesnumber'].'" target="_blank" title="去处理">'.$inqso['salesnumber'].'</a>';
			?>
            <div class="updiv">
              <?=$this->fun->utf_substr($title,40)?>
              <?=$tourl?>
            </div>
            <?php }
			if(empty($this->inqso['ema'])) echo '<div>暂无待处理项</div>';?>
          </div>
        </div>
        <p><a href="/icwebadmin/OrInqo?type=proc" target="_blank" title="查看">待反馈交期</a>（<em><?=count($this->inqso['proc'])?></em>）</p>
        <div class="up_zzjs">
          <div id="upbox_inqso_proc">
            <?php foreach($this->inqso['proc'] as $inqso){
				  $title = $inqso['companyname'].' , '.$inqso['partnos'];
				  $tourl = '<a href="/icwebadmin/OrInqo?type=rel&&salesnumber='.$inqso['salesnumber'].'" target="_blank" title="去处理">'.$inqso['salesnumber'].'</a>';
			?>
            <div class="updiv">
              <?=$this->fun->utf_substr($title,40)?>
              <?=$tourl?>
            </div>
            <?php }
			if(empty($this->inqso['proc'])) echo '<div>暂无待处理项</div>';?>
          </div>
        </div>
        <p><a href="/icwebadmin/OrInqo?type=over" target="_blank" title="查看">待付余款</a>（<em><?=count($this->inqso['over'])?></em>）</p>
        <div class="up_zzjs">
          <div id="upbox_inqso_over">
            <?php foreach($this->inqso['over'] as $inqso){
				  $title = $inqso['companyname'].' , '.$inqso['partnos'];
				  $tourl = '<a href="/icwebadmin/OrInqo?type=rel&&salesnumber='.$inqso['salesnumber'].'" target="_blank" title="去处理">'.$inqso['salesnumber'].'</a>';
			?>
            <div class="updiv">
              <?=$this->fun->utf_substr($title,40)?>
              <?=$tourl?>
            </div>
            <?php }
			if(empty($this->inqso['over'])) echo '<div>暂无待处理项</div>';?>
          </div>
        </div>
        
        <p><a href="/icwebadmin/OrInqo?type=over" target="_blank" title="查看">待通知发货</a>（<em><?=count($this->inqso['send'])?></em>）</p>
        <div class="up_zzjs">
          <div id="upbox_inqso_over">
            <?php foreach($this->inqso['send'] as $inqso){
				  $title = $inqso['companyname'].' , '.$inqso['partnos'];
				  $tourl = '<a href="/icwebadmin/OrInqo?type=rel&&salesnumber='.$inqso['salesnumber'].'" target="_blank" title="去处理">'.$inqso['salesnumber'].'</a>';
			?>
            <div class="updiv">
              <?=$this->fun->utf_substr($title,40)?>
              <?=$tourl?>
            </div>
            <?php }
			if(empty($this->inqso['send'])) echo '<div>暂无待处理项</div>';?>
          </div>
        </div>
      </div>
    </div>
    <script language="javascript">
	   <?php if(count($this->inqso['rel'])>1){?>
	   startmarquee(22,20,8000,'upbox_inqso_rel');
	   <?php }?>
	   <?php if(count($this->inqso['wpay'])>1){?>
	   startmarquee(22,20,8000,'upbox_inqso_wpay');
	   <?php }?>
	   <?php if(count($this->inqso['ema'])>1){?>
	   startmarquee(22,20,8000,'upbox_inqso_ema');
	   <?php }?>
	   <?php if(count($this->inqso['proc'])>1){?>
	   startmarquee(22,20,8000,'upbox_inqso_proc');
	   <?php }?>
	   <?php if(count($this->inqso['over'])>1){?>
	    startmarquee(22,20,8000,'upbox_inqso_over');
	   <?php }?>
	</script>
    <?php }?>
  </div>
  <!--end 右边-->
  <!--end 移动块-->
</div>
<?php if(empty($_SESSION['statistics_rule']['value'])){?>
<!-- Area Output Starts -->
<div style="width:870px;float:left;margin-left:5px;margin-bottom:5px">
  <table border="0">
    <tr>
      <td><div style="margin-left:30px; margin-top:10px">
          <?php
				$area_count = $section_count=0;
				
                foreach($this->Section as $section_array){
				   $area_string_temp =array();
				   $section_id=$section_array["section_area_id"];	

				   if(!empty($this->Area[$section_id]))
				   {
				   		foreach($this->Area[$section_id] as $v){ 
                       		$area_string_temp[] = $v["staff_area_id"];
                   		}
				   }
				   if(count(array_intersect($area_string_temp,$_SESSION['staff_area']['value']))){
                     $temp_count = $row_count =0;
					 if($area_count%3 == 0) echo "<div class=\"row\">";
                        ?>
          <div class="areabox">
            <h4 class="well-small well">
              <?=$section_array["section_area_des"]?>
            </h4>
            <ul>
              <?php 
										   foreach($this->Area[$section_id] as $area_array){ 
											 $area_id=$area_array["staff_area_id"]; 
                                             
											if(in_array($area_id,$_SESSION['staff_area']['value'])){ 
											  if(!$row_count)?>
              <li><a href="<?=$area_array["url"]?>"><font color="#005CB9">
                <?=$area_array["staff_area_des"]?>
                </font></a></li>
              <?php $temp_count++;$row_count++; }
											   }//End for 
              				      			?>
            </ul>
          </div>
          <?php  
							  $area_count++;
							   if($area_count%3 == 0) echo "</div>";
					 } 
 
			  	} ?>
        </div></td>
    </tr>
  </table>
</div>
<!-- Area Output Ends -->
<?php }?>
<script type="text/javascript" src="/js/jsplug/advanced_docking/js/jquery-1.3.2.js" ></script>
<script type="text/javascript" src="/js/jsplug/advanced_docking/js/jquery-ui-1.7.2.custom.min.js" ></script>
<script type="text/javascript" >
$(function(){
	$('.dragbox')
	.each(function(){
		$(this).hover(function(){
			$(this).find('h2').addClass('collapse');
		}, function(){
			$(this).find('h2').removeClass('collapse');
		})
		.find('h2').hover(function(){
			$(this).find('.configure').css('visibility', 'visible');
		}, function(){
			$(this).find('.configure').css('visibility', 'hidden');
		})
		.click(function(){
			$(this).siblings('.dragbox-content').toggle();
		})
		.end()
		.find('.configure').css('visibility', 'hidden');
	});
	$('.column').sortable({
		connectWith: '.column',
		handle: 'h2',
		cursor: 'move',
		placeholder: 'placeholder',
		forcePlaceholderSize: true,
		opacity: 0.4,
		stop: function(event, ui){
			$(ui.item).find('h2').click();
			var sortorder='';
			$('.column').each(function(){
				var itemorder=$(this).sortable('toArray');
				var columnId=$(this).attr('id');
				sortorder+=columnId+'='+itemorder.toString()+'&';
			});
			//alert('SortOrder: '+sortorder);
			/*Pass sortorder variable to server using ajax to save state*/
		}
	})
	.disableSelection();
});
</script>
<script src="/js/jsplug/highcharts/highcharts.js"></script>
<script src="/js/jsplug/highcharts/modules/exporting.js"></script>
<script type="text/javascript" src="/js/jsplug/highcharts/themes/grid.js"></script>
