<?php 
//状态
$statusArr = array (
		'1' => '<font color="#FF0000">待报价</font>',
		'2' => '<font color="#009944">已报价</font>',
		'3' => '<font color="#FF912F">议价审核中</font>',
		'4' => '<font color="#FF912F">审核不通过</font>',
		'5' => '<font color="#FF912F">已下单</font>',
		'6' => '<font color="#FF912F">成功下单</font>'
);
$deliveryArr = array('HK'=>'香港','SZ'=>'国内');
$currencyArr = array('RMB'=>'RMB','USD'=>'USD','HKD'=>'HKD');

$selecturl = "&select=$this->select&sdata=$this->sdata&edata=$this->edata&edata=$this->edata&xsname=$this->xsname&delivery=$this->delivery&keyword=$this->keyword";
$orderurl = "/icwebadmin/QuoBom?type=$this->type".$selecturl;

$oa_status = array('100'=>'<p class="fontred">未提交</p>','101'=>'<p class="fontgreen">已提交</p>','102'=>'<p class="fontgreen">已报价</p>');
?>
<script type="text/javascript">
function showinquiry(id)
{
  var trobj = document.getElementById("show_inquiry_"+id);
  if(trobj.style.display=='none'){
     trobj.style.display = 'block';
  }
  else trobj.style.display = 'none';
  

  var show_v =  document.getElementById("show_v_"+id);
  var show_but     =  document.getElementById("show_but_"+id);
  var type         =  show_v.value;
  if(type=='1') {show_but.innerHTML = '+';show_v.value=0;}
  else {show_but.innerHTML = '-';show_v.value=1;}
  
}
</script>
<div class="conmian">
  <h1><?php echo $this->AreaTitle;?>列表 <?php if($this->select=='select') echo "-> 搜索结果 <a href='/icwebadmin/QuoBom'>返回&gt;&gt;</a>";?></h1>
<form id="myform"  name="myform" class="form-search"  action="" method="get">
<input type="hidden" name="select" value="select" />

<label>开始时间：</label><input type="text"  style="width:80px;" name="sdata" value="<?=$this->sdata?>" onclick="WdatePicker({startDate:'',dateFmt:'yyyy-MM-dd',alwaysUseStartDate:true,lang:'sc'})"/>
<label>结束时间：</label><input type="text"  style="width:80px;" name="edata" value="<?=$this->edata?>" onclick="WdatePicker({startDate:'',dateFmt:'yyyy-MM-dd',alwaysUseStartDate:true,lang:'sc'})"/>

<label>编号：</label>
<div class="input-append">
  <input type="text" class="search-query ac_input" id="keyword" style="width:135px"  value="<?=$this->keyword?>" name="keyword" autocomplete="off"/>
</div>

<?php if($_SESSION['staff_sess']['level_id']!='XS'){?>
<div class="input-append">
<select name="xsname" id="xsname">
      <option value="" <?=$this->xsname==''?'selected':''?>>跟进销售-全部</option>
      <option value="alina.shang" <?=$this->xsname=='alina.shang'?'selected':''?>>尚玉(alina.shang)</option>
      <?php for($i=0;$i<count($this->xs_staff);$i++){?>
      <option value="<?=$this->xs_staff[$i]['staff_id']?>" <?=$this->xsname==$this->xs_staff[$i]['staff_id']?'selected':''?>><?=$this->xs_staff[$i]['lastname'].$this->xs_staff[$i]['firstname']."(".$this->xs_staff[$i]['staff_id'].")"?></option>
      <?php }?>
</select>
</div>
<?php }?>
<div class="input-append">
<select name="delivery" id="delivery">
      <option value="" <?=$this->delivery==''?'selected':''?>>交货地-全部</option>
      <option value="HK" <?=$this->delivery=='HK'?'selected':''?>>香港</option>
      <option value="SZ" <?=$this->delivery=='SZ'?'selected':''?>>国内</option>
</select>
</div>
<input type="submit" class="btn" value="查 找"/>         

</form>

  <div class="fr u_right">
    <div class="tab_content">
    	<div class="tab_tit1">
        <ul class="fl">
          <li <?=$this->type=='pending'?'class="on"':''?>><a href="?type=pending<?=$selecturl?>" style="width:120px;">待处理<em>(<?=$this->pendingnum?>)</em><b class="blank3"></b></a></li>
          <li <?=$this->type=='wait'?'class="on"':''?>><a href="?type=wait<?=$selecturl?>" style="width:120px;">待添加型号<em>(<?=$this->waitnum?>)</em><b class="blank3"></b></a></li>
          <li <?=$this->type=='already'?'class="on"':''?>><a href="?type=already<?=$selecturl?>" style="width:120px;">已转询价<em>(<?=$this->alreadynum?>)</em><b class="blank3"></b></a></li>
          <li <?=$this->type=='no'?'class="on"':''?>><a href="?type=no<?=$selecturl?>" style="width:120px;">审核未通过<em>(<?=$this->nonum?>)</em><b class="blank3"></b></a></li>
        </ul>
        </div>
    </div>
    <div class="tab_con ">
        <table class="tableanew" border="0" cellspacing="0" cellpadding="0"  width="100%"  >
            <tr>
                <th width="140"  align="center">BOM编号</th>
                <th width="200">型号</th>
                <th width="200">客户名称</th>
                <th width="60">客户类别</th>
                <th width="60" align="center">销售</th>
                <th width="150" align="center">说明</th>
                <th width="50">交货地</th>
                <th width="50">货币</th>
                <th width="100">提交日期</th>
                <?php if($this->type=='no'){?>
                 <th width="100">回复说明</th>
                 <th width="100">回复时间</th>
                <?php }?>
                <th width="100" align="center">操作</th>
            </tr>
             <?php 
				if(empty($this->inquiry)){?>
                <tr>
                  <td colspan="14"><center>
                      暂无记录。
                    </center></td>
                </tr>
                <?php }else{
			   foreach($this->inquiry as $k=>$v){
						$companyname = $v['companyname'];
						$propertyArr = array('merchant'=>'贸易商','enduser'=>'终端用户');
						$property    = $propertyArr[$v['property']];
						$staff = $v['lastname'].$v['firstname'];
							$remark   = $v['remark']?$v['remark']:'--';
							$delivery = $deliveryArr[$v['delivery']];
							$currency = $currencyArr[$v['currency']];
							$created  = "<p>".date('Y/m/d',$v['created'])."</p><p>".date('H:i',$v['created'])."</p>";
							$status   = $statusArr[$v['status']];
							$result_remark   = $v['result_remark']=='--'?'':$v['result_remark'];
							$modified = $v['modified']==0?'':date('Y/m/d H:i',$v['modified']);
							$detaile = $v['detaile'];
						    $detnum = count($detaile);
				?>
                 <tr valign="top">
                <td align="left"><p><a href="javascript:;" onclick="openbox('/icwebadmin/QuoBom/view/id/<?=$v['id']?>')" class="xunjiano"  title="查看详情"><strong class="fontorange"><?=$v['bom_number']?></strong><b class="tipicon"></b></a></p>
                <p><a class="gbqfbb" href="javascript:;" onclick="openbox('/icwebadmin/QuoBom/view/id/<?=$v['id']?>')" title="查看详情">查看详情</a></p>
                </td>
                <td align="left">
				<?php 
				  for($j=0;$j<$detnum;$j++){
				  	echo '('.($detaile[$j]['brand_name']).')';
					if($detaile[$j]['part_id']) echo '<strong ><a title="查看产品信息" target="_blank" href="/proddetails?partid='.$detaile[$j]['part_id'].'">'.$detaile[$j]['part_no'].'</a></strong><br/>';
					else echo '<strong >'.$detaile[$j]['part_no'].'</strong><br/>';
				  }
				  ?>
                </td>
                <td align="left">
                    <p><a href="javascript:;" onclick="viewUser('<?=$v['uid']?>')" title="用户详情" class="company"><?=$companyname?><b class="tipicon"></b></a></p>
                </td>
                <td align="center"><p><?=$property?></p></td>
                <td align="center"><p><?=$staff?></p></td>
                <td align="center"><p><?=$remark?></p></td>
                <td><p><?=$delivery?></p></td>
                <td><p><?=$currency?></p></td>
                <td align="center"><p><?=$created?></p></td>
                <?php if($this->type=='no'){?>
                 <td width="100"><?=$v['result_remark']?></td>
                 <td width="100"><?=date('Y/m/d',$v['modified'])?></td>
                <?php }?>
                <td valign="top">
<?php if($this->mycommon->checkA($this->Staff_Area_ID) || $this->mycommon->checkW($this->Staff_Area_ID)){?>
                <?php if($v['status']==1){?>
                	<p><a  class="gbqfb" href="javascript:;" onclick="showbox('/icwebadmin/QuoBom/edit/id/<?=$v['id']?>')">转询价</a></p>
                    <p><a  class="gbqfb" href="javascript:;" onclick="showbox('/icwebadmin/QuoBom/cancel/id/<?=$v['id']?>')">不通过</a></p>
                <?php }?>
                
                <?php if($v['status']==2){?>
				<p><a  class="gbqfb" href="javascript:;" onclick="showbox('/icwebadmin/QuoBom/edit/id/<?=$v['id']?>')">修改转询价</a></p>
				<?php }?>
                
                <?php if($v['status']==3){?>
                	<p><a  class="gbqfb" href="javascript:;" onclick="showbox('/icwebadmin/QuoBom/edit/id/<?=$v['id']?>')">再转询价</a></p>
               <?php }?>
               
               <?php if(in_array($v['status'],array(2,3))){
			    if($v['bomscore']==0){
			   ?>
				<p><a  class="gbqfb" href="javascript:;" onclick="showbox('/icwebadmin/QuoBom/jifen/id/<?=$v['id']?>')">发放积分</a></p>
				<?php }else{?>
               
               <p>已获积分：<?=$v['bomscore']?></p>
               <?php }}?>
                <p><a class="gbqfb" href="/icwebadmin/QuoBom/export?id=<?=$this->fun->encryptVerification($v['id'])?>" target="_blank" href="javascript:;" title="点击下载BOM单Excel">下载BOM单</a></p>
<?php }//end check?>
                </td>
            </tr>
		<?php }
		}?> 
        </table>
    <div class="pagination divpage">
       <?=$this->page_bar;?>
  </div>
</div>

</div>

<link href="/js/jsplug/ajaxselect/jquery.autocomplete.css" rel="stylesheet">
<script src="/js/jsplug/ajaxselect/jquery.autocomplete.js" type="text/javascript"></script>
<script src="/js/jsplug/My97DatePicker/WdatePicker.js" type="text/javascript"></script>
<script type="text/javascript">

$(function(){
        var tab = $(".tab_tb .hover_tr");
        tab.hover(function(){
		    var id = $(this).attr('rel');
			$("#ftr_"+id).addClass("hover_tr_color");
			$("#tr_show_inquiry_"+id).addClass("hover_tr_color");
        },function(){
		    var id = $(this).attr('rel');
		    $("#ftr_"+id).removeClass("hover_tr_color");
			$("#tr_show_inquiry_"+id).removeClass("hover_tr_color");
        });
})
function check(){
		var salesnumber = document.getElementById('keyword').value;
		if(salesnumber=="") {alert("请输入询价编号！");document.getElementById('keyword').focus();return;}
		else $('#myform').submit();
	}

	$(document).ready(function() {
			$("#keyword").autocomplete("/icwebadmin/QuoBom/getajaxtag",
			{
				delay:5,
            	minChars:3,
            	matchSubset:1,
            	matchContains:1,
            	cacheLength:10,
            	onItemSelect:selectItem,
            	onFindValue:findValue,
            	formatItem:formatItem,
            	autoFill:false
        	}
    		);
			});
			function findValue(li) {
    			if( li == null ) return alert("No match!");
				if( !!li.extra ) var sValue = li.extra[0];
				else var sValue = li.selectValue;
				}
			function selectItem(li) { findValue(li);}
			function formatItem(row) { return row[0];//return row[0] + " (id: " + row[1] + ")"//如果有其他参数调用row[1]，对应输出格式Sparta|896
			}
			function lookupAjax(){
			var oSuggest = $("#keyword")[0].autocompleter;
			oSuggest.findValue();
			return false;
			}
function showbox(url)
{
	 $.openPopupLayer({
        name:'box',
        url:url
    });
}
function showbox2(url)
{
	 $.openPopupLayer({
        name:'box2',
        url:url
    });
}
//查看订单
	function viewInqSo(salesnumber){
		$.openPopupLayer({
			name: "box",
			url: "/icwebadmin/OrInqo/viewso?salesnumber="+salesnumber
		});
	}
    

function getinqorder(salesnumber){
 $.ajax({
            url: '/icwebadmin/OrInqo/ajaxorderinfo?salesnumber='+salesnumber,
            data: {},
            type: 'post',
            dataType: 'html',
            success: function(html) {
            	document.getElementById('soinfo').innerHTML = html;
				$("#soinfo").height($("#ajaxorderinfo").height()+10);
            }
	});
}
</script>
