<table class="table table-hover"  border="0" style=" margin-top:-1px;">
                <thead>
                <tr>
                <th>MFR</th>
                <th>料号</th>
                <th>数量</th>
                <th>说明</th>
                </tr>
                </thead>
                <tbody>
				<?php foreach($this->data as $data) : ?>
				<tr>
				<td><?php echo $data['mfr'];?></td>
				<td><?php echo $data['part_no'];?></td>
				<td><?php echo $data['qty'];?></td>
				<td><?php echo $data['remarks'];?></td>
				</tr>
				<?php endforeach ; ?>
                </tbody>
            </table>      