<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<?php 
$statusarr = array('101'=>'<font color="#FF0000">待付预付款</font>',
'102'=>'<font color="009944">处理中</font>',
'103'=>'<font color="#FF0000">待支付余款</font>',
'201'=>'<font color="009944">待发货</font>',
'202'=>'<font color="009944">待确认收货</font>',
'301'=>'已完成',
'302'=>'已完成',
'401'=>'订单被取消','501'=>'退款',
'502'=>'退货退款');

$codarr = array('101'=>'<font color="#FF0000">等待审核</font>',
'102'=>'<font color="009944">处理中</font>',
'103'=>'<font color="#FF0000">待支付余款</font>',
'201'=>'<font color="009944">待发货</font>',
'202'=>'<font color="009944">待确认收货</font>',
'301'=>'已完成',
'302'=>'已完成',
'401'=>'订单被取消','501'=>'退款',
'502'=>'退货退款');

if($this->orderarr['total'] != $this->orderarr['down_payment']){
			$paystatus = array('101'=>'<font color="#fd2323">待付款</font>',
				'102'=>'<font color="#03b000">已付定金</font>',
				'103'=>'<font color="#03b000">已付定金</font>',
				'201'=>'<font color="#03b000">已付全款</font>',
				'202'=>'<font color="#03b000">已付全款</font>',
				'301'=>'<font color="#03b000">已付全款</font>',
				'302'=>'<font color="#03b000">已付全款</font>',
				'401'=>'<font color="#03b000">订单被取消</font>');
		}elseif($this->orderarr['paytype']=='cod'){
			$paystatus = array('101'=>'<font color="#fd2323">待付款</font>',
					'102'=>'<font color="#03b000">待付款</font>',
					'103'=>'<font color="#03b000">待付款</font>',
					'201'=>'<font color="#03b000">待付款</font>',
					'202'=>'<font color="#03b000">待付款</font>',
					'301'=>'<font color="#03b000">待付款</font>',
					'302'=>'<font color="#03b000">待付款</font>',
					'401'=>'<font color="#03b000">订单被取消</font>');
		}else{
			$paystatus = array('101'=>'<font color="#fd2323">待付款</font>',
					'102'=>'<font color="#03b000">已付全款</font>',
					'103'=>'<font color="#03b000">已付全款</font>',
					'201'=>'<font color="#03b000">已付全款</font>',
					'202'=>'<font color="#03b000">已付全款</font>',
					'301'=>'<font color="#03b000">已付全款</font>',
					'302'=>'<font color="#03b000">已付全款</font>',
					'401'=>'<font color="#03b000">订单被取消</font>');
		}

$annexur_part = COM_ANNEX.$this->orderarr['uid'].'/';
$annexurl = $annexur_part.$this->orderarr['annex1'];
$annexurl2= $annexur_part.$this->orderarr['annex2'];
$annexurl_a = $annexurl2_a = '未上传';
if(file_exists($annexurl) && $this->orderarr['annex1']){
  $annexurl_a = '<a href="/'.$annexurl.'" target="_blank" title="查看">查看&gt;&gt;</a>';
}
if(file_exists($annexurl2) && $this->orderarr['annex2']){
  $annexurl2_a = '<a href="/'.$annexurl2.'" target="_blank" title="查看">查看&gt;&gt;</a>';
}  
if(in_array($this->orderarr['paytype'],array('transfer','online')))
{ 
 $down_payment = number_format($this->orderarr['down_payment'],DECIMAL);
 $surplus = number_format($this->orderarr['total']-$this->orderarr['down_payment'],DECIMAL);
 $statusarr = $statusarr;
}
else{
 $down_payment = '--';
 $surplus = '--';
 $statusarr = $codarr;
}
$paytypearr = array('transfer'=>'银行汇款','online'=>'在线支付','cod'=>'货到付款','mts'=>'款到发货','other'=>'其他');
$deliveryArr = array('HK'=>'香港','SZ'=>'国内');
$type = array('spot'=>'现货','order'=>'订货');
$expressarr = array('1'=>'国内快递','2'=>'公司配送');
$currency = array('RMB'=>'￥','USD'=>'$','HKD'=>'HK$');
$invtypearr = array('1'=>'明细','2'=>'电子元件','3'=>'耗材');
?>
<div id="ajaxorderinfo">
<h2>IC易站订单</h2>
<!--订单详情-->
<div class="publicOne" id="ajaxorderinfo">
  <div class="Publictit"> <span class="Publictit_tit">订单详情</span> </div>
  <table border="0" cellspacing="0" cellpadding="0" class="Publictable">
    <tbody>
      <tr>
        <td width="100">询价单号：</td>
        <td>
		<a href="javascript:;" onclick="openbox2('<?php echo $this->url(array('controller'=>'QuoInq', 'action'=>'viewinq', 'id'=>$this->orderarr['inquiry_id']));?>')" class="xunjiano"  title="查看详情"><strong class="fontorange"><?=$this->orderarr['inq_number']?></strong></a></td>
        <td width="100">订单状态：</td>
        <td><strong><?=$statusarr[$this->orderarr['status']].($this->orderarr['back_status']==102?'<font style="color:#FF0000"> 审核不通过</font>':'')?></strong></td>
      </tr>
      <tr>
        <td>订单金额：</td>
        <td><strong class="fontred"><span class="fuhao"><?=$this->orderarr['currency']?></span> <?=$this->orderarr['total']?></strong></td>
        <td>下单时间：</td>
        <td><strong><?=date('Y/m/d H:i:s',$this->orderarr['created'])?></strong></td>
      </tr>
      <?php if(($this->orderarr['total'] != $this->orderarr['down_payment'])){?>
      <tr>
        <td>预付款：</td>
        <td><strong class="fontred"><span class="fuhao"><?=$this->orderarr['currency']?></span> <?=$down_payment?></strong></td>
        <td>剩余货款：</td>
        <td><strong class="fontred"><span class="fuhao"><?=$this->orderarr['currency']?></span> <?=$surplus?></strong></td>
      </tr>
      <?php }?>
      <tr>
        <td>付款方式：</td>
        <td><strong><?=$paytypearr[$this->orderarr['paytype']]?></strong></td>
        <td>付款状态：</td>
        <td><strong><?=$paystatus[$this->orderarr['status']]?></strong></td>
      </tr>
      <tr>
        <td>交货地：</td>
        <td><strong><?=$deliveryArr[$this->orderarr['delivery_place']]?></strong></td>
        <td>标准交期：</td>
        <td><strong><?=$this->orderarr['delivery_time']==0?'--':date('Y/m/d',$this->orderarr['delivery_time'])?></strong></td>
      </tr>
      <tr>
        <td>订单流程：</td>
        <td><strong><?=($this->orderarr['sqs_code']?'SQS Code':'正常SAP流程')?></strong></td>
        <td>销售：</td>
        <td><strong><?=$this->owner['lastname'].$this->owner['firstname']?></strong></td>
      </tr>
      <tr>
        <td>税务登记证：</td>
        <td><?=$annexurl2_a?></td>
        <td>营业执照：</td>
        <td><?=$annexurl_a?></td>
      </tr>
      <?php if($this->orderarr['paytype']=='transfer'){?>
	   <tr>
          <td>银行汇款凭证：</td>
          <td colspan="3">
	 	<?php if($this->orderarr['total']==$this->orderarr['down_payment']){ 
             if(!empty($this->orderarr['receipt']) && file_exists(UP_RECEIPT.$this->orderarr['receipt'])){
				   echo '<a href="'.RECEIPT.$this->orderarr['receipt'].'" target="_blank" title="查看">汇款凭证</a>';
			 }
		}else{
			if(!empty($this->orderarr['receipt']) && file_exists(UP_RECEIPT.$this->orderarr['receipt'])){
                echo '<a href="'.RECEIPT.$this->orderarr['receipt'].'" target="_blank" title="查看">预款凭证</a>';
			}
            if(!empty($this->orderarr['receipt_2']) && file_exists(UP_RECEIPT.$this->orderarr['receipt_2'])){
                echo '&nbsp;&nbsp;&nbsp;<a href="'.RECEIPT.$this->orderarr['receipt_2'].'" target="_blank" title="查看">余款凭证</a>';
			}
		}?>
		   </td>
        </tr>
	 <?php }?>
        <tr>
        <td>订单备注：</td>
        <td colspan="3"><p><strong><?=$this->orderarr['remark']?$this->orderarr['remark']:'--'?></strong></p></td>
        </tr>
        <?php if($this->orderarr['ship_salesnumber']){?>
        <tr>
        <td>合并订单：</td>
        <td colspan="3"><p><strong class="fontorg">此订单与订单#： <?=$this->orderarr['ship_salesnumber']?> 一起发货。</strong></p></td>
        </tr>
        <?php }?>	  
    </tbody>
  </table>
  <table border="0" cellspacing="0" cellpadding="0" class="producttable1">
    <tbody>
      <tr>
        <th width="35">项次</th>
        <th>产品型号</th>
        <th>品牌</th>
        <th width="30">单位</th>
        <th>数量</th>
        <th>单价(<?=$this->orderarr['currency']?>)</th>
        <th>金额(<?=$this->orderarr['currency']?>)</th>
        <th>需求日期</th>
      </tr>
      <?php 
      foreach($this->pordarr as $k=>$v){
	    $supsale =  '';
	    if($v['staged']) $supsale .= '<sup><span title="Date Code：'.$v['datecode'].'" class="sup_SALE HOT">特卖</span></sup>';
		if($v['pdnpcn']['pdn']) $supsale .= '<sup><span class="sup_PDN HOT">PDN</span></sup>';
		if($v['pdnpcn']['pcn']) $supsale .= '<sup><span class="sup_PCN HOT">PCN</span></sup>';
		 if($v['prod_id']){
           $part_no = '<a href="/proddetails?partid='.$v['prod_id'].'" target="_blank" title="查看产品信息">'.$v['part_no'].'</a>';
		}else $part_no = $v['part_no'];
        echo '
        <tr>
          <td>'.($k+1).'</td>
          <td><div class="productNO">'.$part_no.$supsale.'</div></td>
          <td>'.$v['brand'].'</td>
          <td>PCS</td>
          <td>'.$v['buynum'].'</td>
          <td><strong class="fontred">'.$currency[$this->orderarr['currency']].($v['buyprice']).'</strong></td>
          <td><strong class="fontred">'.$currency[$this->orderarr['currency']].($v['buyprice']*$v['buynum']).'</strong></td>
          <td bgcolor="#FFFFFF" style="border:1px #dfdfdf solid;font-weight:bold">'.($v['needs_time']?date('Y/m/d',$v['needs_time']):($this->orderarr['needs_time']?date('Y/m/d',$this->orderarr['needs_time']):'--')).'</td>
        </tr>
        ';
        }
	 ?>
      <tr>
        <td colspan="8" align="right"> 商品金额：<strong style="color:#fd2323; margin-left:5px;"><?=$currency[$this->orderarr['currency']].($this->orderarr['total']-$this->orderarr['freight'])?></strong> 
        <strong style="font-size:16px; color:#000000">+</strong> 
        运费及包装费：<strong style="color:#fd2323; margin-left:5px;"><?=$currency[$this->orderarr['currency']].$this->orderarr['freight']?></strong> 
        <strong style="font-size:16px; color:#000000">=</strong>
         合计:<b style="color:#fd2323; margin:0 5px;font-size:14px;"><span style="color:#000000"><?=$this->orderarr['currency']?></span> <?=$this->orderarr['total']?></b> </td>
      </tr>
    </tbody>
  </table>
</div>
<!--PMSC报价 -->
<?php if($this->inqinfo && $this->inqinfo['oa_rfqnumber']){?>
        <div class="publicOne">
            <div class="Publictit">
                <span class="Publictit_tit">PMSC报价</span><strong class="fontgreen">OA BQ#：<?=$this->inqinfo['oa_rfqnumber']?> </strong>
            </div>
            <table border="0" cellspacing="0" cellpadding="0" class="producttable1 producttable2" >
                    <tr>
                        <th width="35">项次</th>
                        <th>产品型号</th>
                        <th width="100">品牌</th>
                        <th width="100">PMSC报价(RMB)</th>
                        <th width="80">有效期</th>
                        <th>报价备注</th>
                        <th width="50">报价专员</th>
                    </tr>
                    <?php foreach($this->inqinfo['detaile'] as $k=>$inqdetaile){ ?>
                    <tr >
                      <td ><?=($k+1)?></td>
                      <td ><strong><?=$inqdetaile['part_no']?></strong></td>
                      <td ><?=$inqdetaile['brand']?></td>
                      <td ><strong class="fontred"><?=$inqdetaile['oa_result_price']>0?$currency[$this->orderarr['currency']].' '.$inqdetaile['oa_result_price']:'--'?></strong></td>
                      <td ><?=($inqdetaile['expiration_time']?date("Y/m/d",$inqdetaile['expiration_time']):'--')?></td>
                      <td ><?=$inqdetaile['oa_inqd_remark']?$inqdetaile['oa_inqd_remark']:'--'?></td>
                      <td ><?=($inqdetaile['oa_pmsc_name']?$inqdetaile['oa_pmsc_name']:'--')?></td>
                    </tr>
                    <?php }?>
              </table>
        </div>
<?php }?>
<!--收货信息-->
<div class="publicOne">
  <div class="Publictit"> <span class="Publictit_tit">收货信息</span> </div>
  <?php  if(in_array($this->orderarr['delivery_type'],array(1,2))){?>
  <table border="0" cellspacing="0" cellpadding="0" class="Publictable">
    <tbody>
      <tr>
        <td width="100">公司名称：</td>
        <td><strong><?=$this->orderarr['companyname']?></strong></td>
        <td width="100">收货人：</td>
        <td><strong><?=$this->orderarr['name']?></strong></td>
      </tr>
      <tr>
        <td>货运方式：</td>
        <td><strong><?=$expressarr[$this->orderarr['delivery_type']]?></strong></td>
        <td>手机：</td>
        <td><strong><?=$this->orderarr['mobile']?></strong></td>
      </tr>
      <tr>
        <td>固定电话：</td>
        <td><strong><?=$this->orderarr['tel']?></strong></td>
        <td>邮编：</td>
        <td><strong><?=$this->orderarr['zipcode']?></strong></td>
      </tr>
      <tr>
        <td>详细地址：</td>
        <td><strong><?=$this->fun->createAddress($this->orderarr['province'],$this->orderarr['city'],$this->orderarr['area'],$this->orderarr['address'])?></strong></td>
        <td>入仓号：</td>
        <td><strong><?=$this->orderarr['warehousing']?></strong></td>
      </tr>
    </tbody>
  </table>
  <?php }elseif($this->orderarr['delivery_type']==3){?>
  <table border="0" cellspacing="0" cellpadding="0" class="Publictable">
    <tbody>
      <tr>
        <td width="100">公司名称：</td>
        <td><strong><?=$this->orderarr['companyname']?></strong></td>
        <td width="100">用户：</td>
        <td><strong><?=$this->orderarr['uname']?></strong></td>
      </tr>
      <tr>
        <td>取货方式：</td>
        <td><strong>用户上门自取</strong></td>
        <td>可取货时间：</td>
        <td><strong><?=($this->orderarr['delivery_place']=='SZ'?$this->delivery_workdate_sz:$this->delivery_workdate_hk)?></strong></td>
      </tr>
      <tr>
        <td>取货地址：</td>
        <td><strong><?=($this->orderarr['delivery_place']=='SZ'?$this->delivery_add_sz:$this->delivery_add_hk)?></strong></td>
        <td>联系电话：</td>
        <td><strong><?=($this->orderarr['delivery_place']=='SZ'?$this->delivery_tel_sz:$this->delivery_tel_hk)?></strong></td>
      </tr>
      <tr>
        <td>备注：</td>
        <td colspan="3"><strong><?=($this->orderarr['delivery_place']=='SZ'?$this->delivery_des_sz:$this->delivery_des_hk)?></strong></td>
      </tr>
    </tbody>
  </table>
  <?php }elseif($this->orderarr['delivery_type']==4){?>
  <table border="0" cellspacing="0" cellpadding="0" class="Publictable">
    <tbody>
      <tr>
        <td width="100">公司名称：</td>
        <td><strong><?=$this->orderarr['companyname']?></strong></td>
        <td width="100">快递商：</td>
        <td><strong><?=$this->orderarr['express_name']?></strong></td>
      </tr>
      <tr>
        <td>货运方式：</td>
        <td><strong>客户提供账号</strong></td>
        <td>快递账号：</td>
        <td><strong><?=$this->orderarr['express_account']?></strong></td>
      </tr>
      <tr>
        <td>收货人：</td>
        <td><strong><?=$this->orderarr['name']?></strong></td>
        <td>联系方式：</td>
        <td><strong><?=$this->orderarr['tel']?></strong></td>
      </tr>
      <tr>
        <td>收货地址：</td>
        <td colspan="3"><strong><?=$this->orderarr['address']?></strong></td>
      </tr>
    </tbody>
  </table>
  <?php }?>
</div>
<!--发票信息-->
<?php  if($this->orderarr['invoiceid']>0){ 
   $i_address = $this->fun->createAddress($this->orderarr['province_i'],$this->orderarr['city_i'],$this->orderarr['area_i'],$this->orderarr['address_i']);
   if($this->orderarr['addressid']!=$this->orderarr['invoiceaddress']){
  		$i_address .=' ; '.$this->orderarr['name_i'].' '.$this->orderarr['tel_i'].'  '.$this->orderarr['mobile_i'];
   }?>
<div class="publicOne">
  <div class="Publictit"> <span class="Publictit_tit">发票信息</span> </div>
  <?php if($this->orderarr['itype']==1){
  
  ?>
  <table border="0" cellspacing="0" cellpadding="0" class="Publictable">
    <tbody>
      <tr>
        <td width="100">发票类型：</td>
        <td colspan="3"><strong>普通发票</strong></td>
      </tr>
      <tr>
        <td width="100">发票抬头：</td>
        <td><strong><?=$this->orderarr['iname']?></strong></td>
        <td>发票内容：</td>
        <td><strong><?=$invtypearr[$this->orderarr['contype']]?></strong></td>
      </tr>
      
      <tr>
        <td>收发票地址：</td>
        <td colspan="3"><strong><?=$i_address?></strong></td>
      </tr>
    </tbody>
  </table>
  <?php }elseif($this->orderarr['itype']==2){?>
  <table border="0" cellspacing="0" cellpadding="0" class="Publictable">
    <tbody>
      <tr>
        <td width="100">发票类型：</td>
        <td colspan="3"><strong>增值税发票(17%)</strong></td>
        
        
      </tr>
      <tr>
        <td width="100">单位名称：</td>
        <td><strong><?=$this->orderarr['iname']?></strong></td>
        <td>纳税人识别号：</td>
        <td><strong><?=$this->orderarr['identifier']?></strong></td>
      </tr>
      <tr>
      <td>注册地址：</td>
        <td><strong><?=$this->orderarr['regaddress']?></strong></td>
        <td>注册电话：</td>
        <td><strong><?=$this->orderarr['regphone']?></strong></td>
      </tr>
      <tr>
        <td>开户银行：</td>
        <td><strong><?=$this->orderarr['bank']?></strong></td>
        <td>银行账户：</td>
        <td><strong><?=$this->orderarr['account']?></strong></td>
      </tr>
      <tr>
        <td>收发票地址：</td>
        <td colspan="3"><strong><?=$i_address?></strong></td>
      </tr>
    </tbody>
  </table>
  <?php }?>
</div>
<?php }?>
</div> <!-- end <div id="ajaxorderinfo">-->