<div class="popup" style="width:770px;">
    <div class="popup-header">
    <h2>审核订单 订单编号#：<?=$this->salesnumber?></h2>
    <a href="javascript:;" onclick="$.closePopupLayer('box');" title="关闭" class="dialogBoxClose">关闭</a>
     </div>
    <div class="popup-body">
        <!--订单详情-->
        <div id='soinfo' style="height:900px;"><img src="/images/admin/ajax-loader.gif" /></div>
    	<!-- end 订单详情-->
        
        <div class="passorno ">
            <dl class="PublicDl">
                <dt>审核：</dt>
                <dd>
                    <label><input type="radio" name="status" id="status_yes" value="201" checked="checked" onclick="changediv(this.value)"/><b style="color:#339900">通过</b></label>
                </dd>
                <dd>
                   <label><input type="radio" name="status" id="status_no" value="102"  onclick="changediv(this.value)"/><b style="color:#CC3333">不通过</b></label>
                </dd>
            </dl>

			<?php if($this->cansqs){?>
            <dl class="PublicDl" id="yes_release">
                <dt>&nbsp;</dt>
                <dd>
            <label><input type="checkbox" name="sqscode" id="sqscode" value="1" />此订单走SQS Code流程</label>
                </dd>
                <dd>
                    <em>提示：订单走SQS Code流程不需要在SAP中添加客户，可以简化订单流程。</em>
                </dd>
            </dl>
		    <?php }else{?>
               <input type="hidden" name="sqscode" id="sqscode" value="" />
			<?php }?>
            <dl class="PublicDl"  id="no_release"  style="display:none">
                <dt>说明：</dt>
                <dd>
                    <textarea name="notpass" id="notpass" rows="3"  style="width:400px;"></textarea>(客户可以看到的)
                </dd>
            </dl>
        </div>
        <div class="clear"></div>
        <div class="bottombutton">
            <input type="button"  class="btnabig"  value="确认" onclick="release('<?=$this->salesnumber?>')"/>
			<?php if($this->soinfo['invoiceid']){?>发票信息有误？<a href="javascript:;" onclick="invoicebox('<?=$this->soinfo['invoiceid']?>')">点击修改</a><?php }?>
        </div>
        
        <?php if(!$this->cansqs){?>
        <div>
            订单能走SQS Code流程必须满足的条件：<br/>
            1、必须通过IC易站向PMSC报价，并且PMSC报回有效价格；<br/>
            2、订单总金额必须小于：RMB5000，USD1000，HKD5000；<br/>
            3、订单必须是预付全款；<br/>
            4、购买产品数量必须小于包装数。</br>
            (如有特殊情况需要走SQS流程，请联系IC易站工作人员)
        </div>
        <?php }?>
        
        
<div class="clear"></div>
    </div>
    
</div>
<script type="text/javascript">
function invoicebox(invoiceid)
{
	 $.openPopupLayer({
        name:'invoicebox',
        url:'/icwebadmin/OrInqo/editinvoice/invoiceid/'+invoiceid
    });
}
function changediv(value)
{
	if(value==201){
        document.getElementById("no_release").style.display    = 'none';
	}else{
        document.getElementById("no_release").style.display    = 'block';
	}
}
//审核订单
function release(salesnumber){
var status='';
var notpass='';
var status_obj = document.getElementsByName("status");
	   for(i=0;i<status_obj.length;i++){
	      if(status_obj[i].checked){
	         status = status_obj[i].value; break;
	      }
	   }

var sqscode=''; 
var sqscodeobj   = document.getElementById("sqscode");
if(sqscodeobj.checked)  sqscode = 1;

if(status==201) {
   if(!confirm('你确定通过此订单吗？'+salesnumber)){return;}
}else if(status==102) {
  notpass =  document.getElementById('notpass').value;
  if(notpass==''){alert('请填写说明！');document.getElementById('notpass').focus();return;}
  else{
  	if(!confirm('你确定不通过此订单吗？'+salesnumber)){return;}
  }
}else{
	alert('状态参数错误！');return;
}
	$.ajax({
            url: '<?=$this->release?>',
            data: {'salesnumber':salesnumber,'status':status,'notpass':notpass,'sqscode':sqscode},
            type: 'post',
            dataType: 'json',
            success: function(arr) {
            	alert(arr.message);
				if(arr.code == 0) location.reload();
            }
	});
   
}
getinqorder('<?=$this->salesnumber?>');
</script>