<div class="dBox p15">
    <div class="dBoxTitleS">产品资讯</div>
    <div class="dBoxConS">
      <ul class="pmListS">
      <?php foreach($this->hotArr as $k=>$hotarr){
	  ?>
        <li><a href="/news-<?=$hotarr['id']?>.html"  title="<?=$hotarr['title']?>" onclick="logclickaction($(this))" rev="hotpord_solution" rel="<?=$hotarr['id']?>"><?=$this->fun->utf_substr($hotarr['title'],22)?></a></li>
        <?php }?>
      </ul>
    </div>
  </div>