<div class="subhot  pos-re">
            	<h2>热卖产品</h2>
                <div class="subshop">
    				<?php for($i=0;$i<count($this->hotArr);$i++){
                     $hotProd = $this->hotArr[$i];
                    ?>
                  <div class="por_box2013 item ">
                  <a href="/search?keyword=<?php echo $hotProd['part_no'];?>&st=searchall" 
                  title="<?=$hotProd['part_no']?>" class="s-img logclick" rev="related_part_id" 
                  rel="<?=$hotProd['id']?>" target="_blank">
                  <img alt="img" src="<?=PRODUCTICON.($hotProd['part_img']==''?'no.gif':$hotProd['part_img'])?>"  title="<?=$hotProd['part_no']?>"></a>
                            <div class="pbox201312">
                                <div class="spot201312"></div>
                                <div class="pmodel201312">
                                <a href="/search?keyword=<?php echo $hotProd['part_no'];?>&st=searchall"  title="<?=$hotProd['part_no']?>" class="logclick" rev="related_part_id" rel="<?=$hotProd['id']?>" target="_blank">
                                <?=$this->fun->utf_substr(($hotProd['part_no']),11,'...')?></a></div>
                                <p class="fs-12 c-999"><?php echo $hotProd['manufacturer'];?>
								</p>
                            </div>
                        </div>
                  <?php }//end foreach($this->relevance as $i=>$prod)?> 	
                        
                        
                        
                </div>
                
            </div>