<div class="dBox p15">
    <div class="dBoxTitleS">行业新闻</div>
    <div class="dBoxConS">
      <ul class="pmListS">
        <?php 
		$arr = array();
		foreach($this->hotArr as $k=>$hotarr){
		if(!in_array($hotarr['id'],$arr)){$arr[]=$hotarr['id'];
		?>
        <li><a href="/solution-<?=$hotarr['id']?>.html"  title="<?=$hotarr['title']?>" onclick="logclickaction($(this))" rev="hotpord_solution" rel="<?=$hotarr['id']?>"><?=$this->fun->utf_substr($hotarr['title'],23)?></a></li>
        <?php }}?>
      </ul>
    </div>
  </div>