<div class="dBox p15" >
    <div class="dBoxTitleS">热门研讨会</div>
    <div class="dBoxConS">
      <ul class="pmListS">
      <?php foreach($this->hotArr as $k=>$hotarr){?>
        <li><i class="icon-s icon-s3"></i><a href="/webinar-<?=$hotarr['id']?>.html"  title="<?=$hotarr['title']?>" onclick="logclickaction($(this))" rev="hotpord_solution" rel="<?=$hotarr['id']?>"><?=$this->fun->utf_substr($hotarr['title'],23)?></a></li>
        <?php }?>
      </ul>
    </div>
  </div>