 <?php 
				 
				 foreach($this->solution as $sol){?>
                 
                 <div class="fl top5tab_201407">
                        <div class="fl w_100">
                <?=$sol['solution_no']?'<span class="gay12line201407">方案编号：</span>'.$sol['solution_no'].'<span class="fontgray"> |</span>':'';?>
                <?=$sol['source']?'<span class="color_gray201407">来源：</span>'.$sol['source'].'<span class="fontgray"> |</span>':''?>
				<?=$sol['author']?'<span class="color_gray201407">作者：</span>'.$sol['author'].'<span class="fontgray"> |</span>':''?>
                <span  class="gay12line201407">标签：</span><?php 
					$tip = explode(',',$sol['tags']);
					for($i=0;$i<count($tip);$i++){
						echo $tip[$i].' ';
					}?>   
                    
                        </div>
                        <div class="fl w_100">
                            <div class="fl top5tabl_201407">
                            <a href="/solution-<?=$sol['id']?>.html" title="<?=$sol['title']?>" class="logclick" rev="solution" rel="<?=$sol['id']?>" target="_blank">
                            <img src="<?=($sol['sol_img'])?(APPICON.$sol['sol_img']):(SOLUTIONICON.$pricearr[0])?>"  alt="<?=$sol['title']?>" width="200" height="125">
                            </a>
                            </div>
                            <div class="fr top5tabr_201407">
                            
                                <h2><span class="ifotip2014"><em><?=$sol['appname']?></em><i></i></span><a href="/solution-<?=$sol['id']?>.html" title="<?=$sol['title']?>" class="logclick" rev="solution" rel="<?=$sol['id']?>" target="_blank"><?=$sol['title']?></a></h2>
                                
                                <p><?=$sol['description']?></p>
                            </div>
                        </div>
                    </div>
                    
                <?php }?>