<?php 
$statusarr = array('101'=>'<font color="#FF0000"><p class="orange_payment">待付款</p></font>',
'201'=>'<font color="009944"><p class="orange_shipments">待发货</p></font>',
'202'=>'<p class="orange_harvest">待确认收货</p>',
'301'=>'<p class="green_ok">已完成</p>',
'302'=>'<p class="green_evaluate">已评价</p>',
'401'=>'<p class="gray_cancel">订单被取消</p>',
'501'=>'<p class="gray_return">退款</p>',
'502'=>'<p class="gray_returngoods">退货退款</p>');				
//301代表待评价，第一阶段没有评价功
$paytypearr = array('transfer'=>'银行汇款','online'=>'在线支付','coupon'=>'优惠券兑换');
$currency = array('RMB'=>'￥','USD'=>'$','HKD'=>'HK$');
$statustmp = array('202','301','302');
$deliveryArr = array('HK'=>'香港','SZ'=>'国内');
$type = array('spot'=>'现货','order'=>'订货');
$delivery_type = array('1'=>'国内快递','2'=>'公司配送','3'=>'上门自取');
$selecturl = "&sdata=$this->sdata&edata=$this->edata&edata=$this->edata&paytype=$this->paytype&delivery=$this->delivery&shipments=$this->shipments&xsname=$this->xsname";
$orderurl = "/icwebadmin/OrOrgl?type=$this->type".$selecturl;

?>
<script src="/js/jsplug/bettertip/jquery.bettertip.js" type="text/javascript"></script>
<link href="/js/jsplug/bettertip/jquery.bettertip.css" rel="stylesheet">
<link href="/js/jsplug/ajaxselect/jquery.autocomplete.css" rel="stylesheet">
<script src="/js/jsplug/ajaxselect/jquery.autocomplete.js" type="text/javascript"></script>

<div class="conmian">
<h1><?php echo $this->AreaTitle;?> </h1>
<form id="myform"  class="form-search" name="myform" action="" method="get">
<input type="hidden" name="type" value="select" />
<input type="hidden" name="ordertype" value="<?=$this->ordertype?>" />
<input type="hidden" name="orderby" value="<?=$this->orderby?>" />

<label>开始时间：</label><input type="text"  style="width:80px;" name="sdata" value="<?=$this->sdata?>" onclick="WdatePicker({startDate:'',dateFmt:'yyyy-MM-dd',alwaysUseStartDate:true,lang:'sc'})"/> 
<label>结束时间：</label><input type="text"  style="width:80px;" name="edata" value="<?=$this->edata?>" onclick="WdatePicker({startDate:'',dateFmt:'yyyy-MM-dd',alwaysUseStartDate:true,lang:'sc'})"/>

<label>订单号：</label>
<div class="input-append">
  <input type="text" class="search-query ac_input" id="salesnumber" style="width:135px" value="<?=$this->salesnumber?>" name="salesnumber" autocomplete="off"/>
</div>
<!--<div class="input-append">
<select name="shipments" id="shipments">
      <option value="" <?=$this->shipments==''?'selected':''?>>货物情况-全部</option>
      <option value="spot" <?=$this->shipments=='spot'?'selected':''?>>现货</option>
      <option value="order" <?=$this->shipments=='order'?'selected':''?>>订货</option>
</select>
</div>-->
<?php if($_SESSION['staff_sess']['level_id']!='XS'){?>
<div class="input-append">
<select name="xsname" id="xsname">
      <option value="" <?=$this->xsname==''?'selected':''?>>跟进销售-全部</option>
      <option value="alina.shang" <?=$this->xsname=='alina.shang'?'selected':''?>>尚玉(alina.shang)</option>
      <?php for($i=0;$i<count($this->xs_staff);$i++){?>
      <option value="<?=$this->xs_staff[$i]['staff_id']?>" <?=$this->xsname==$this->xs_staff[$i]['staff_id']?'selected':''?>><?=$this->xs_staff[$i]['lastname'].$this->xs_staff[$i]['firstname']."(".$this->xs_staff[$i]['staff_id'].")"?></option>
      <?php }?>
</select>
</div>
<?php }?>
<div class="input-append">
<select name="delivery" id="delivery">
      <option value="" <?=$this->delivery==''?'selected':''?>>交货地-全部</option>
      <option value="SZ" <?=$this->delivery=='SZ'?'selected':''?>>国内</option>
      <option value="HK" <?=$this->delivery=='HK'?'selected':''?>>香港</option>
</select>
</div>
<div class="input-append">
<select name="paytype" id="paytype">
      <option value="" <?=$this->paytype==''?'selected':''?>>支付类型-全部</option>
      <option value="transfer" <?=$this->paytype=='transfer'?'selected':''?>>银行转账</option>
      <option value="online" <?=$this->paytype=='online'?'selected':''?>>在线支付</option>
      <option value="coupon" <?=$this->paytype=='coupon'?'selected':''?>>优惠券兑换</option>
</select>
</div>
<input type="submit" class="btn" value="查 找"/>
</form>
<div id="message_sess" style="display:none" class="message_sess">
          <div title="关闭" class="but" onclick="document.getElementById('message_sess').style.display='none'">&nbsp;</div>
          <div id="alert_message"></div>
</div>
<?php if($this->type == 'select'){?>搜索结果（<?=$this->selnum?>）<a href="/icwebadmin/OrOrgl">返回&gt;&gt;</a><?php }?>
<div class="contentmia">
    <div class="leftSwitching">
        <ul>
        <li <?php if($this->type=='rel') echo 'class="on"';?>><a href="/icwebadmin/OrOrgl?type=rel<?=$selecturl?>">待审核<em>(<?=$this->relnum?>)</em><b class="blank3"></b></a></li>
          <li <?php if($this->type=='wpay') echo 'class="on"';?>><a href="/icwebadmin/OrOrgl?type=wpay<?=$selecturl?>">待付款<em>(<?=$this->wpaynum?>)</em><b class="blank3"></b></a></li>
          <li <?php if($this->type=='ema') echo 'class="on"';?>><a href="/icwebadmin/OrOrgl?type=ema<?=$selecturl?>">待释放订单<em>(<?=$this->emanum?>)</em><b class="blank3"></b></a></li>
          <li <?php if($this->type=='rec') echo 'class="on"';?>><a href="/icwebadmin/OrOrgl?type=rec<?=$selecturl?>">待发货<em>(<?=$this->recnum?>)</em><b class="blank3"></b></a></li>
          <li <?php if($this->type=='shou') echo 'class="on"';?>><a href="/icwebadmin/OrOrgl?type=shou<?=$selecturl?>">待收货<em>(<?=$this->shounum?>)</em><b class="blank3"></b></a></li>
          <li <?php if($this->type=='eva') echo 'class="on"';?>><a href="/icwebadmin/OrOrgl?type=eva<?=$selecturl?>">已完成<em>(<?=$this->evanum?>)</em><b class="blank3"></b></a></li>
          <li <?php if($this->type=='can') echo 'class="on"';?>><a href="/icwebadmin/OrOrgl?type=can<?=$selecturl?>">已取消<em>(<?=$this->cannum?>)</em><b class="blank3"></b></a></li>
            <li <?php if($this->type=='not') echo 'class="on"';?>><a href="/icwebadmin/OrOrgl?type=not<?=$selecturl?>">审核不通过<em>(<?=$this->notnum?>)</em><b class="blank3"></b></a></li>
            <li <?php if($this->type=='back') echo 'class="on"';?>><a href="/icwebadmin/OrOrgl?type=back<?=$selecturl?>">退款退货<em>(<?=$this->backnum?>)</em><b class="blank3"></b></a></li>
          <li <?php if($this->type=='all') echo 'class="on"';?>><a href="/icwebadmin/OrOrgl?type=all<?=$selecturl?>">全部订单<em>(<?=$this->allnum?>)</em><b class="blank3"></b></a></li>
        </ul>
    </div>
    <div class="conright" >

<table class="table ordertable" border="1" cellpadding="0" cellspacing="0">
    <thead>
        <tr>
            <th width="130">订单号</th>
            <th width="50">订单流程</th>
            <th width="120">订单商品</th>
            <th width="40">交货地</th> 
            <th width="70"><a href="<?=$orderurl?>&ordertype=total&orderby=<?php if($this->orderby=='ASC' && $this->ordertype=='total') echo 'DESC';else echo 'ASC';?>" title="排序">订单金额</a>
            <div class="aorder">
                <a href="<?=$orderurl?>&ordertype=total&orderby=ASC" class="aorder_up <?php if($this->orderby=='ASC' && $this->ordertype=='total') echo 'onaorder';else echo '';?>"  title="升排序"></a>
                <a href="<?=$orderurl?>&ordertype=total&orderby=DESC" class="aorder_down <?php if($this->orderby=='DESC' && $this->ordertype=='total') echo 'onaorder';else echo '';?>" title="降排序">倒序</a>
            </div></th>
            <th width="65">支付类型</th> 
            <th width="60">发货方式</th>
            <th width="70">销售</th>
            <th width="100"><a href="<?=$orderurl?>&ordertype=created&orderby=<?php if($this->orderby=='ASC' && $this->ordertype=='created') echo 'DESC';else echo 'ASC';?>" title="排序">下单时间</a>
            <div class="aorder">
                <a href="<?=$orderurl?>&ordertype=created&orderby=ASC" class="aorder_up <?php if($this->orderby=='ASC' && $this->ordertype=='created') echo 'onaorder';else echo '';?>"  title="升排序"></a>
                <a href="<?=$orderurl?>&ordertype=created&orderby=DESC" class="aorder_down <?php if($this->orderby=='DESC' && $this->ordertype=='created') echo 'onaorder';else echo '';?>" title="降排序">倒序</a>
            </div></th>
            
            <th width="50">客户</th>
            <th width="70">状态</th>
            <th width="80">操作</th>
            <th width="30">备注</th>
        </tr>
    </thead>
    <tbody>
    	<?php  if(empty($this->salesorder)){?>
            <tr>
              <td colspan="11"><span style="text-align:center; width:100%;  float:left">暂无记录。</span></td>
            </tr>
            <?php }else{
				foreach($this->salesorder as $sodata){
			?>
    	<tr>
            <td> 
            <p><?php if($sodata['so_type']==102) echo '<img src="/2014/css/img/MS.gif" />';?><a href="javascript:;" onclick="viewSo('<?=$sodata['salesnumber']?>')" title="查看订单"><?=$sodata['salesnumber']?></a></p>
            <p><!--<a href="/icwebadmin/OrOrgl/iccontract/key/<?=md5(session_id())?>/salesnumber/<?=$sodata['salesnumber']?>/<?=$sodata['salesnumber'].'_'.($sodata['companyname']?$sodata['companyname']:$sodata['uname'])?>" target="_blank">纸质合同</a>
             |-->
           <a href="/icwebadmin/OrOrgl/digitalcontract/key/<?=md5(session_id())?>/salesnumber/<?=$sodata['salesnumber']?>/<?=$sodata['salesnumber'].'_'.($sodata['companyname']?$sodata['companyname']:$sodata['uname'])?>" target="_blank" class="gbqfb">电子合同</a>
            </p>
           
           </td>
           <td>SQS流程</td>
            <td class="productNO">
			<?php foreach($sodata['prodarr'] as $partarr){
			   if($partarr['prod_id']){ ?>
              <a href="/proddetails?partid=<?=$partarr['prod_id'];?>" target="_blank" title="查看产品信息"><?=$partarr['part_no']?></a>
			  <?php }else echo '<p>'.$partarr['part_no'].'</p>';?>
              
			  <?php if($partarr['staged']) echo '<sup><span title="Date Code：'.$partarr['datecode'].'" class="sup_SALE HOT">特卖</span></sup>';
			    if($partarr['pdnpcn']['pdn']) echo '<sup><span class="sup_PDN HOT">PDN</span></sup>';
				if($partarr['pdnpcn']['pcn']) echo '<sup><span class="sup_PCN HOT">PCN</span></sup>';
				if(in_array($partarr['id'],$this->tongyong)) echo '<sup><span class="sup_TY">通用</span></sup>';
				
				if($partarr['bpp_stock_id']) echo "<br/>".$partarr['vendor_name'].":".$partarr['location']."_".$partarr['location_code']."<br/>";
				
				}
			  ?>
              
            </td>
            <td class="price"><?=$deliveryArr[$sodata['delivery_place']]?><!--<br/>(<?=$type[$sodata['shipments']]?>)--></td>
            <td class="price"><?=$sodata['currency'].' '.number_format($sodata['total'],DECIMAL)?></td>
            <td><?=$paytypearr[$sodata['paytype']];?>
            <br/><?php if(!empty($sodata['receipt']) && file_exists(UP_RECEIPT.$sodata['receipt'])){?>
            <a href="<?=RECEIPT.$sodata['receipt']?>" target="_blank" title="查看">汇款凭证</a>
            <?php }?>
            </td>
            <td><?=$delivery_type[$sodata['delivery_type']]?></td>
            <td><?=$sodata['lastname'].$sodata['firstname']?></td>
           
            <td class="time"><?=date('Y/m/d H:i',$sodata['created'])?></td>
            <td class="name"><a href="javascript:;" onclick="viewUser('<?=$sodata['uid']?>')" title="查看详细资料" ><?=($sodata['companyname']?$sodata['companyname']:$sodata['uname'])?></a></td> 
            <td><?php if($sodata['back_status']!=102) echo '<div class="order_status">'.$statusarr[$sodata['status']].'</div>';else echo '<p style="color:#FF0000">审核不通过</p>';?></td>
            <td> <?php if($this->mycommon->checkA($this->Staff_Area_ID) || $this->mycommon->checkW($this->Staff_Area_ID)){
			
			  if($sodata['paytype']=='transfer' && $sodata['status']=='101' && $sodata['back_status']==201){?>
                <div style="margin-top:2px"><a href="javascript:" onclick="transfer('<?=$sodata['salesnumber']?>')" class="gbqfb">上传转账凭证</a></div>
                <div style="margin-top:2px"><a href="javascript:" onclick="canOrder('<?=$sodata['salesnumber']?>')" class="gbqfb">取消订单</a></div>
              <?php }?>

                <?php if($sodata['back_status']==101 && $sodata['status']!=401){?>
                <div style="margin-top:2px"><a href="javascript:" onclick="openrelease('<?=$sodata['id']?>','<?=$sodata['salesnumber']?>','yes')" class="gbqfb">审核订单</a></div>
              <?php }?>
              
               <?php if($sodata['back_status']==101 && $sodata['status']==101 && $_SESSION['staff_sess']['level_id']!='XS'){?>
                <div style="margin-top:2px"><a href="javascript:" onclick="openbox('/icwebadmin/OrOrgl/modifyshipping?key=<?=$this->fun->encryptVerification($sodata['salesnumber'])?>')" class="gbqfb">修改运费</a></div>
              <?php }?>
              
                <?php if($sodata['status']=='201' && $sodata['back_status']==201){?>
                <div style="margin-top:2px"><a href="javascript:" onclick="mailsend('<?=$sodata['id']?>','<?=$sodata['salesnumber']?>')" class="gbqfb">释放订单</a></div>
                <?php }?>
                
                <?php if(!$sodata['invoiceid'] && $sodata['currency']=='RMB' && $sodata['status']!='401' && in_array($sodata['back_status'],array('101','201'))){?>
                 <div style="margin-top:2px"><a class="gbqfb" href="javascript:" onclick="openbox2('/icwebadmin/OrOrgl/addinvoice/salesnumber/<?=$sodata['salesnumber']?>')">添加发票</a></div>
              <?php }?>
                
                <?php 
				if(in_array($sodata['status'],$statustmp)){?>
                <div style="margin-top:2px"><a href="javascript:" onclick="courier('<?=$sodata['id']?>','<?=$sodata['salesnumber']?>')" class="gbqfb">查看物流</a></div>
                <?php }?>
                
                <?php
				if($sodata['status']=='201' && $sodata['back_status']==202 && $sodata['shipments']=='order'){
				    if(!$sodata['delivery_time'] || $_SESSION['staff_sess']['level_id']!='XS'){?>
                <div style="margin-top:2px"><a href="javascript:" onclick="deliverytime('<?=$sodata['salesnumber']?>','<?=$sodata['delivery_time']?>')" class="gbqfb">交期反馈</a></div>
                <?php }}?>
                
                 <?php if($sodata['status']==201 && $sodata['back_status'] != 102){?>
                <div style="margin-top:2px"><a href="javascript:" onclick="backorder('<?=$sodata['id']?>','<?=$sodata['salesnumber']?>','reimburse')"  class="gbqfb">退款</a></div>
				<?php }elseif(in_array($sodata['status'],array(202,301,302)) && $sodata['back_status'] != 102){?>
                <div style="margin-top:2px"><a href="javascript:" onclick="backorder('<?=$sodata['id']?>','<?=$sodata['salesnumber']?>','returns')"  class="gbqfb">退货退款</a></div>
				<?php }?>
<?php }?> 
			 <?php if($_SESSION['staff_sess']['level_id']!='XS' && $this->mycommon->checkA($this->Staff_Area_ID)){?>
             <a href="/icwebadmin/OrOrgl/digitalcontract/type/up/key/<?=md5(session_id())?>/salesnumber/<?=$sodata['salesnumber']?>/<?=$sodata['salesnumber'].'_'.($sodata['companyname']?$sodata['companyname']:$sodata['uname'])?>" class="gbqfb" target="_blank">更新电子合同</a>
             <?php }?>
            </td>
            <td class="ourreply">
            	<?php if($sodata['back_status']==102 || in_array($sodata['status'],array(501,502))){?>
                <a href="javascript:" class="tipa"><b class="tipicon"></b>
                    <div class="bubblebox hide">
                        <div class="uparrow"></div>
                        <div class="popbox">
                           <div class="popcon" >
                               <p><?=$sodata['admin_notes']?></p>
                            </div>
                        </div>
                    </div>	
                </a>
                <?php }?>
            </td>
        </tr>
        <?php }}?>
    </tbody>
    </table>
    <div class="pagination divpage mt10 fr" >
        <?=$this->page_bar;?>
      </div>
    </div> 
</div>
</div>
<script src="/js/jsplug/My97DatePicker/WdatePicker.js" type="text/javascript"></script>
<script type="text/javascript">
$(function(){
    //查看备注
	var tab = $(".tipa");
	tab.hover(function(){
		$(this).find(".bubblebox").removeClass("hide");
	},function(){
		$(this).find(".bubblebox").addClass("hide");
	});
})

function openeamil() {
	$.openPopupLayer({
		name: "myopeneamil",
		target: "myHiddenDiv"
	});
}
</script>
<div id="myHiddenDiv" style="display:none">
  <div class="popup">
    <div class="popup-body" style="width:550px;">
      <!-- 需要填写的区域-->
      <div><img src="/images/admin/ajax-loader.gif" />正在发送邮件，请不要关闭。如果等待时间过长(超过1分钟)请刷新页面。</div>
      <!-- 结束区域-->
    </div>
  </div>
</div>
<script type="text/javascript">

function theform_menu()
{
	document.getElementById('myform').submit();
}

//确认发货
function delivery(id,salesnumber){
	$.openPopupLayer({
        name:'deliveryBox',
        url:'<?php echo $this->deliveryurl;?>?sonum='+salesnumber+'&sonid='+id
    });
}
//弹出不通过审核订单
function openrelease(id,salesnumber){
	$.openPopupLayer({
        name:'box',
        url:'<?php echo $this->release;?>?sonum='+salesnumber+'&sonid='+id
    });
}

//确认收款
function receivables(id,salesnumber){
if(confirm('你确定订单：'+salesnumber+'，已付款吗？'))
 {
	$.ajax({
            url: '/icwebadmin/OrOrgl/receivables',
            data: {'id':id,'salesnumber':salesnumber},
            type: 'post',
            dataType: 'json',
            success: function(arr) {
            	document.getElementById('message_sess').style.display = "block";
	            document.getElementById('alert_message').innerHTML = arr.message;
				setTimeout('hidMessage()',3000);
				if(arr.code == 0) location.reload();
            }
	});
  }
}
//释放，确认可发货
function mailsend(id,salesnumber){
  $.openPopupLayer({
        name:'viewsoBox',
        url:'/icwebadmin/OrOrgl/mailsend?salesnumber='+salesnumber+'&id='+id
  });
}

//查看物流
function courier(id,salesnumber){
    $.openPopupLayer({
        name:'courierBox',
        url:'/icwebadmin/OrOrgl/courier?sonum='+salesnumber+'&sonid='+id
    });
}
//弹出退款退货窗口
function backorder(id,salesnumber,type){
	$.openPopupLayer({
        name:'notreleaseBox',
        url:'/icwebadmin/OrOrgl/backorder?sonum='+salesnumber+'&sonid='+id+'&type='+type
    });
}
function hidMessage(){
	document.getElementById("message_sess").style.display = 'none';
}
//反馈交期
function deliverytime(salesnumber,deliverytime_old){
	$.openPopupLayer({
        name:'deliverytimeBox',
        url:'<?php echo $this->indexurl;?>/deliverytime?salesnumber='+salesnumber+'&deliverytime_old='+deliverytime_old
    });
}
//取消订单
function canOrder(salesnumber){
if(confirm('你确定取消此订单：'+salesnumber+'？'))
	  {
	$.ajax({
            url: '/icwebadmin/OrOrgl/cancel',
            data: {'salesnumber':salesnumber},
            type: 'post',
            dataType: 'json',
            success: function(arr) {
			    alert(arr.message);
            	if(arr.code == 0)
                {
                    location.reload();
                }
            }
	 });
}
}

//上传回执单
function transfer(salesnumber){
	$.openPopupLayer({
		name: "transferBox",
		url: "/icwebadmin/OrOrgl/transfer?salesnumber="+salesnumber+'&ordertype=online'
	});
}

//查看订单
function viewSo(salesnumber){
	$.openPopupLayer({
		name: "viewsoBox",
		url: "<?=$this->viewsourl?>?salesnumber="+salesnumber
	});
}
	function check(){
		var salesnumber = document.getElementById('salesnumber').value;
		if(salesnumber=="") {alert("订单号！");document.getElementById('salesnumber').focus();return;}
		else $('#myform').submit();
	}

	$(document).ready(function() {
			$("#salesnumber").autocomplete("/icwebadmin/OrOrgl/getajaxtag",
			{
				delay:5,
            	minChars:3,
            	matchSubset:1,
            	matchContains:1,
            	cacheLength:10,
            	onItemSelect:selectItem,
            	onFindValue:findValue,
            	formatItem:formatItem,
            	autoFill:false
        	}
    		);
			});
			function findValue(li) {
    			if( li == null ) return alert("No match!");
				if( !!li.extra ) var sValue = li.extra[0];
				else var sValue = li.selectValue;
				}
			function selectItem(li) { findValue(li);}
			function formatItem(row) { return row[0];//return row[0] + " (id: " + row[1] + ")"//如果有其他参数调用row[1]，对应输出格式Sparta|896
			}
			function lookupAjax(){
			var oSuggest = $("#salesnumber")[0].autocompleter;
			oSuggest.findValue();
			return false;
			}
function getorder(salesnumber){
 $.ajax({
            url: '/icwebadmin/OrOrgl/ajaxorderinfo?salesnumber='+salesnumber,
            data: {},
            type: 'post',
            dataType: 'html',
            success: function(html) {
            	document.getElementById('soinfo').innerHTML = html;
				$("#soinfo").height($("#ajaxorderinfo").height()+10);
            }
	});
}
</script>