<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<div class="popup" style="width:770px;margin:10px 100px ">
    <div class="popup-header">
    <h2>查看订单 订单编号#：<?=$this->salesnumber?></h2>
    <a href="javascript:;" onclick="$.closePopupLayer('viewsoBox');" title="关闭" class="dialogBoxClose">关闭</a>
     </div>
    <div class="popup-body">
    	<div id='soinfo'  style="height:900px;"><img src="/images/admin/ajax-loader.gif" /></div>
    </div>
</div>
<script type="text/javascript">
getorder('<?=$this->salesnumber?>');
</script>