
	<div class="conmian">
	<h1><?php echo $this->AreaTitle;?></h1>
				<div id="message_sess" style="display:none" class="message_sess"> 
          <div title="关闭" class="but" onclick="document.getElementById('message_sess').style.display='none'">&nbsp;</div>
          <div id="alert_message"></div> 
          </div>
	  <!-- 需要填写的区域-->
      <div style=" margin-bottom:5px; margin-top:5px;"><?php echo $this->filemanager;?></div>
      <br/>
      <!-- 结束区域-->
	</div>