<style>
.right-bar {
    height: 214px;
    position: fixed;
    right: 0;
    top: 60%;
    width: 42px;
    z-index: 999;
}
.right-bar a {
    background: #006db7 url("../images/default/nx/icon-server.png") no-repeat scroll 0 0;
    display: block;
    height: 42px;
    margin-bottom: 1px;
    position: relative;
    width: 42px;
}
.right-bar a.sgin {
    background-position: 0 -43px;
}
.right-bar a.service {
    background-position: 0 -86px;
}
.right-bar a.dimensions-code {
    background-position: 0 -129px;
}
.right-bar a.feedback {
    background-position: 0 -172px;
}
.right-bar a.gotop {
    background-position: 0 -215px;
}
.right-bar a:hover {
    background-color: #ffc300;
}
.right-bar a.sgined {
    background-position: 0 0;
}
.right-bar .bar-label {
    background: #c0ebff none repeat scroll 0 0;
    color: #006db7;
    height: 42px;
    left: -100px;
    line-height: 42px;
    padding: 0;
    position: absolute;
    text-align: center;
    top: 0;
    width: 100px;
}
.right-bar .erweima-label {
    background: #fff url("../images/default/nx/erweima.png") no-repeat scroll center center;
    border: 1px solid #d8d8d8;
    height: 170px;
    left: -172px;
    top: -85px;
    width: 170px;
}
.right-bar .tel-label {
    background: rgba(0, 0, 0, 0) url("../images/default/nx/tel-serves.png") no-repeat scroll center center;
    height: 171px;
    left: -150px;
    top: -43px;
    width: 150px;
}
.right-bar .bar-label i {
    -moz-border-bottom-colors: none;
    -moz-border-left-colors: none;
    -moz-border-right-colors: none;
    -moz-border-top-colors: none;
    border-color: transparent transparent transparent #c0ebff;
    border-image: none;
    border-style: dashed dashed dashed solid;
    border-width: 8px;
    display: none;
    font-size: 0;
    height: 0;
    margin-top: -8px;
    position: absolute;
    right: -16px;
    top: 64px;
    width: 0;
}
.right-bar .erweima-label i {
    border-left: 8px solid #fff;
    margin-top: 10px;
    top: 85px;
}
</style>

<div class="right-bar jsRightBar">

<a class="service jsService" id="qqOnline4" href="javascript:void(0);">
	<span class="bar-label tel-label" style="display: none;"><i></i></span></a>
<a class="dimensions-code" id="wxLine" href="javascript:void(0)">
	<span class="bar-label erweima-label" style="display: none;"><i></i></span></a> 
<a class="feedback jsFeedBack" href="#" title="意见反馈">
	<span class="bar-label" style="display: none;"><i></i></span></a>
<a class="gotop" id="goScrollTop" style="bottom: 0px; top: auto;" href="#"></a>
</div>

<script language="JavaScript" type="text/javascript">

$("#qqOnline4").mouseenter(function(){
	$(this).find(".bar-label").css("display","block");
  });
$("#qqOnline4").mouseleave(function(){
	$(this).find(".bar-label").css("display","none");
  });
$("#wxLine").mouseenter(function(){
	$(this).find(".bar-label").css("display","block");
  });
$("#wxLine").mouseleave(function(){
	$(this).find(".bar-label").css("display","none");
  });

function changestyle(objName,objValue,objHours){
	var re = addCookie(objName,objValue,objHours);
	if(re=='widescreen' || re=='standard') location.reload();
}

function addCookie(objName,objValue,objHours){//添加cookie
var str = objName + "=" + escape(objValue);
if(objHours > 0){//为0时不设定过期时间，浏览器关闭时cookie自动消失
var date = new Date();
var ms = objHours*3600*1000;
date.setTime(date.getTime() + ms);
str += "; expires=" + date.toGMTString();
}
  document.cookie = str;
  return getCookie("style");
  
}

function getCookie(objName){//获取指定名称的cookie的值
var arrStr = document.cookie.split("; ");
for(var i = 0;i < arrStr.length;i ++){
var temp = arrStr[i].split("=");
if(temp[0] == objName) return unescape(temp[1]);
}
}
</script>
<?php 
/*if (isset($_COOKIE['style'])) {
	if($_COOKIE['style']=='widescreen'){
		echo '<link rel="stylesheet" type="text/css" href="'.$_SESSION['new_version'].'/css/default/w1190.css"/>';
	}
}*/
?>

<!---------------------------------------------------------------------公用页脚 开始--------------------------------------------------------------------->
<div class="clr"></div>
<div id="footer">
	<div class="clr"></div>
    <div class="w">
        <div class="footer_pic" style="display: none">
              <li class="fore1"><a><i class="fi_icon i_icon01"></i>100%原厂正品保证</a></li>
              <li class="fore2"><a><i class="fi_icon i_icon02"></i>丰富的设计资源</a></li>
              <li class="fore3"><a><i class="fi_icon i_icon03"></i>便捷下单与快速物流</a></li>
              <li class="fore4"><a><i class="fi_icon i_icon04"></i>一站式产品技术支持</a></li>
        </div>
   <!-------------友情链接------------->
   <?php echo $this->frindsLinks();?>
   <!-------------end 友情链接------------->
            
    <div class="copyRight ">
              <p class="fr"> <span>
     <p class="fl"><a href="<?php echo $this->companyUrl?>" target="_blank"><?php echo $this->company;?></a> 版权所有 <span style="font-family:Arial">©</span> 2012-<?=date('Y')?> 
       <a href="http://www.miibeian.gov.cn" target="_blank"><?php echo $this->PIC?></a></p>
      <p class="blank10"></p>
            </div>
        <!--备案--> 
        <div class="w ac " style="display: none">
          <ul class="filing">
             <li >
              <a href="http://www.ebs.gov.cn" target="_blank">
                  <img width="108" height="40" title="工商网监" alt="工商网监" src="/images/default/filing/ebsIcon.jpg" ></a>
          </li>
          <li >
              <a href="http://www.sznet110.gov.cn/netalarm/index.jsp" target="_blank">
                  <img width="108" height="40" title="深圳网络警察报警平台" alt="深圳网络警察报警平台" src="/images/default/filing/beian2Icon.jpg" ></a>
          </li>
          </ul>
         
        </div>
    </w>
</div>

<!--登录弹出框-->
<div id="login_box" style="display:none;">
  <div class="pop pop_login" style="width:440px; height:280px;">
	<div class="popbox">
    	<div class="poptit1">
            <input type="button" onclick="$.closePopupLayer('loginBox')" class="closebtn" title="关闭">
        </div>
        <iframe width="95%" scrolling="no" height="280px" style="position:relative" frameborder="0" name="popupIframe" src="<?=ALERTURLHOST?>/user/loginbox?parenturl=<?=urlencode($_SERVER["REQUEST_URI"])?>"></iframe>
     </div>
  </div>
</div>
<!--end 登录弹出框-->
<!-- jbox-->
<script type="text/javascript" src="/js/jsplug/jBox/jquery.jBox-2.2.min.js"></script>
<script src="/js/jsplug/jmpopups/jquery.jmpopups.js" type="text/javascript"></script>
<script type="text/javascript">
//搜索框
$(function(){
        $(".ac_results").hover(function(){
			$("#searchboxtmp").removeClass("searchTxt");
			$("#searchboxtmp").addClass("searchTxtHover");
        },function(){
		    $("#searchboxtmp").removeClass("searchTxtHover");
			$("#searchboxtmp").addClass("searchTxt");
        });	
})
</script>

<div style="display:none">
<script src="<?=HTTPHOST?>/common/logjs" language="JavaScript"></script>

</div>
<?php  
//记录在线人数
require_once 'Iceaclib/common/fun.php';
try{
  $this->fun = new MyFun();
  $this->fun->setOnline();
} catch (Exception $e) {}
unset($_SESSION['no_logbar_event']);
unset($_SESSION['no_menu_event']);
?>

