
<script language="JavaScript" type="text/javascript">

function changestyle(objName,objValue,objHours){
	var re = addCookie(objName,objValue,objHours);
	if(re=='widescreen' || re=='standard') location.reload();
}

function addCookie(objName,objValue,objHours){//添加cookie
var str = objName + "=" + escape(objValue);
if(objHours > 0){//为0时不设定过期时间，浏览器关闭时cookie自动消失
var date = new Date();
var ms = objHours*3600*1000;
date.setTime(date.getTime() + ms);
str += "; expires=" + date.toGMTString();
}
  document.cookie = str;
  return getCookie("style");
  
}

function getCookie(objName){//获取指定名称的cookie的值
var arrStr = document.cookie.split("; ");
for(var i = 0;i < arrStr.length;i ++){
var temp = arrStr[i].split("=");
if(temp[0] == objName) return unescape(temp[1]);
}
}
</script>
<?php 
/*if (isset($_COOKIE['style'])) {
	if($_COOKIE['style']=='widescreen'){
		echo '<link rel="stylesheet" type="text/css" href="'.$_SESSION['new_version'].'/css/default/w1190.css"/>';
	}
}*/
?>

<!---------------------------------------------------------------------公用页脚 开始--------------------------------------------------------------------->
<div class="clr"></div>
<div id="footer">
	<div class="clr"></div>
    <div class="w">
        <div class="footer_pic" style="display: none">
              <li class="fore1"><a><i class="fi_icon i_icon01"></i>100%原厂正品保证</a></li>
              <li class="fore2"><a><i class="fi_icon i_icon02"></i>丰富的设计资源</a></li>
              <li class="fore3"><a><i class="fi_icon i_icon03"></i>便捷下单与快速物流</a></li>
              <li class="fore4"><a><i class="fi_icon i_icon04"></i>一站式产品技术支持</a></li>
        </div>
   <!-------------友情链接------------->
   <?php echo $this->frindsLinks();?>
   <!-------------end 友情链接------------->
            
    <div class="copyRight ">
              <p class="fr"> <span>
     <p class="fl"><a href="<?php echo $this->companyUrl?>" target="_blank"><?php echo $this->company;?></a> 版权所有 <span style="font-family:Arial">©</span> 2012-<?=date('Y')?> 
       <a href="http://www.miibeian.gov.cn" target="_blank"><?php echo $this->PIC?></a></p>
      <p class="blank10"></p>
            </div>
        <!--备案--> 
        <div class="w ac " style="display: none">
          <ul class="filing">
             <li >
              <a href="http://www.ebs.gov.cn" target="_blank">
                  <img width="108" height="40" title="工商网监" alt="工商网监" src="/images/default/filing/ebsIcon.jpg" ></a>
          </li>
          <li >
              <a href="http://www.sznet110.gov.cn/netalarm/index.jsp" target="_blank">
                  <img width="108" height="40" title="深圳网络警察报警平台" alt="深圳网络警察报警平台" src="/images/default/filing/beian2Icon.jpg" ></a>
          </li>
          </ul>
         
        </div>
    </w>
</div>

<!--登录弹出框-->
<div id="login_box" style="display:none;">
  <div class="pop pop_login" style="width:440px; height:280px;">
	<div class="popbox">
    	<div class="poptit1">
            <input type="button" onclick="$.closePopupLayer('loginBox')" class="closebtn" title="关闭">
        </div>
        <iframe width="95%" scrolling="no" height="280px" style="position:relative" frameborder="0" name="popupIframe" src="<?=ALERTURLHOST?>/user/loginbox?parenturl=<?=urlencode($_SERVER["REQUEST_URI"])?>"></iframe>
     </div>
  </div>
</div>
<!--end 登录弹出框-->
<!-- jbox-->
<script type="text/javascript" src="/js/jsplug/jBox/jquery.jBox-2.2.min.js"></script>
<script src="/js/jsplug/jmpopups/jquery.jmpopups.js" type="text/javascript"></script>
<script type="text/javascript">
//搜索框
$(function(){
        $(".ac_results").hover(function(){
			$("#searchboxtmp").removeClass("searchTxt");
			$("#searchboxtmp").addClass("searchTxtHover");
        },function(){
		    $("#searchboxtmp").removeClass("searchTxtHover");
			$("#searchboxtmp").addClass("searchTxt");
        });	
})
</script>

<div style="display:none">
<script src="<?=HTTPHOST?>/common/logjs" language="JavaScript"></script>
<!--<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-34705065-1']);
  _gaq.push(['_trackPageview']);
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>

<script type="text/javascript">
var _bdhmProtocol = (("https:" == document.location.protocol) ? " https://" : " http://");
document.write(unescape("%3Cscript src='" + _bdhmProtocol + "hm.baidu.com/h.js%3Ff8e7da29ec9c4e17446651e82f6a9b14' type='text/javascript'%3E%3C/script%3E"));
</script>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-53113773-1', 'auto');
  ga('send', 'pageview');

</script>
<script src="http://s22.cnzz.com/stat.php?id=4545212&web_id=4545212" language="JavaScript"></script>-->
</div>
<?php  
//记录在线人数
require_once 'Iceaclib/common/fun.php';
try{
  $this->fun = new MyFun();
  $this->fun->setOnline();
} catch (Exception $e) {}
unset($_SESSION['no_logbar_event']);
unset($_SESSION['no_menu_event']);
?>

