<!--footer-->
<div id="footer">
  <div class="clr"></div>
  <div class="footerbg"></div>
  <div class="footerAear">
    <div class="footerinfo">
      <div class="helpCol_01">
        <h3><?=$this->translate('Foot_GettingStarted')?></h3>
        <ul>
          <li><a class="track" href="/help/index/type/login"><?=$this->translate('Foot_Login')?></a></li>
          <li><a class="track" href="/help/index/type/my"><?=$this->translate('Foot_My')?></a></li>
          <li><a class="track" href="/help/index/type/terms"><?=$this->translate('Foot_Terms')?></a></li>
          <li><a class="track" href="/help/index/type/clause"><?=$this->translate('Foot_Clause')?></a></li>
        </ul>
        <p class="line1"></p>
      </div>
      <div class="helpCol_02">
        <h3><?=$this->translate('Foot_Purchase')?></h3>
        <ul>
          <li><a class="track" href="/help/index/type/find"><?=$this->translate('Foot_Find')?></a></li>
          <li><a class="track" href="/help/index/type/online"><?=$this->translate('Foot_Online')?></a></li>
          <li><a class="track" href="/help/index/type/inq"><?=$this->translate('Foot_Inq')?></a></li>
          <li><a class="track" href="/help/index/type/stock"><?=$this->translate('Foot_Stock')?></a></li>
        </ul>
        <p class="line1"></p>
      </div>
      <div class="helpCol_03">
        <h3><?=$this->translate('Foot_Delivery')?></h3>
        <ul>
          <li><a class="track" href="/help/index/type/pay"><?=$this->translate('Foot_Pay')?></a></li>
          <li><a class="track" href="/help/index/type/shipping"><?=$this->translate('Foot_Shipping')?></a></li>
          <li><a class="track" href="/help/index/type/inspection"><?=$this->translate('Foot_Inspection')?></a></li>
          <li><a class="track" href="/help/index/type/delivery"><?=$this->translate('Foot_Delivery')?></a></li>
        </ul>
        <p class="line1"></p>
      </div>
      <div class="helpCol_04">
        <h3><?=$this->translate('Foot_Services')?></h3>
        <ul>
          <li><a class="track" href="/help/index/type/technical"><?=$this->translate('Foot_Technical')?></a></li>
          <li><a class="track" href="/help/index/type/bom"><?=$this->translate('Foot_Bom')?></a></li>
          <li><a class="track" href="/help/index/type/invoice"><?=$this->translate('Foot_Invoice')?></a></li>
          <li><a class="track" href="/help/index/type/exchange"><?=$this->translate('Foot_Exchange')?></a></li>
        </ul>
        <p class="line1"></p>
      </div>
      <div class="helpCol_05">
        <h3><?=$this->translate('Foot_Help')?></h3>
        <ul>
          <li><a class="track" href="/help/index/type/aboutus"><?=$this->translate('Foot_Aboutus')?></a></li>
          <li><a class="track" href="/help/index/type/question"><?=$this->translate('Foot_Question')?></a></li>
          <li><a class="track" href="/help/index/type/customer"><?=$this->translate('Foot_Customer')?></a></li>
          <li><a class="track" href="/help/index/type/privacy"><?=$this->translate('Foot_Privacy')?></a></li>
        </ul>
      </div>
      
    </div>
     <div class="servicetel"></div>
    <div class="footer_pic"> <a class="footer_pic01" href="/help/index/type/aboutus">100%正品保证</a> 
    <a class="footer_pic02" href="/help/index/type/aboutus">发票</a>
     <a class="footer_pic03" href="/help/index/type/aboutus">下单</a>
      <a class="footer_pic04" href="/help/index/type/aboutus">技术</a>
  </div>
   
   <div class="clr"></div>
         <!-------------友情链接------------->
   <?php echo $this->frindsLinks();?>
   <!-------------end 友情链接------------->
    <div class="copyRight ">
      <p class="fr"> <span>
      <a href="/help/index/type/aboutus"><?=$this->translate('Foot_Aboutus')?></a></span> <span>|</span> <span>
      <a href="/help/index/type/customer"><?=$this->translate('Foot_ContactUs')?></a></span> <span>|</span> <span>
      <a href="http://www.ceacsz.com.cn/jobs/" target="_blank"><?=$this->translate('Foot_Recruitment')?></a></span> <span>|</span> <span>
      <a href="http://www.ceacsz.com.cn/" target="_blank"><?=$this->translate('Foot_Links')?></a></span> </p>
      <p class="fl"><a href="http://www.ceacsz.com.cn/" target="_blank">中国电子器材深圳有限公司</a> 版权所有 <span style="font-family:Arial">©</span> 2012-<?=date('Y')?> 
       <a href="http://www.miibeian.gov.cn" target="_blank">粤ICP备05143739号-2</a>
       增值电信业务经营许可证：<a href="/upload/B2-20130478.pdf" target="_blank">粤B2-20130478</a></p>
      <p class="blank10"></p>
    </div>
  </div>
  
   <!--备案--> 
    <div class="w ac " >
      <ul class="filing">
         <li >
              <a href="http://www.ebs.gov.cn/EntCertificate.aspx?domainId=86d51bd6-bb60-49e9-b5bf-747be227f9ab" target="_blank">
                  <img width="108" height="40" title="工商网监" alt="工商网监" src="/images/default/filing/ebsIcon.jpg" ></a>
          </li>
          <li >
              <a href="http://www.sznet110.gov.cn/netalarm/index.jsp" target="_blank">
                  <img width="108" height="40" title="深圳网络警察报警平台" alt="深圳网络警察报警平台" src="/images/default/filing/beian2Icon.jpg" ></a>
          </li>
      </ul>
    </div>
  
</div>
<!--登录弹出框-->
<div id="login_box" style="display:none">
  <div class="pop pop_login" style="width:440px; height:280px;">
	<div class="popbox">
    	<div class="poptit1">
            <input type="button" onclick="$.closePopupLayer('loginBox')" class="closebtn" title="关闭">
        </div>
        <iframe width="95%" scrolling="no" height="280px" style="position:relative" frameborder="0" name="popupIframe" src="<?=ALERTURLHOST?>/user/loginbox?parenturl=<?=urlencode($_SERVER["REQUEST_URI"])?>"></iframe>
     </div>
  </div>
</div>
<!--end 登录弹出框-->
<!-- jbox-->
<script type="text/javascript" src="/js/jsplug/jBox/jquery.jBox-2.2.min.js"></script>
<script src="/js/jsplug/jmpopups/jquery.jmpopups.js" type="text/javascript"></script>
<script type="text/javascript" src="/js/jsplug/totop/manhuatoTop.1.0.js"></script>
<script type="text/javascript">
$(function (){
	$(window).manhuatoTop({
		showHeight : 200,
		speed : 500
	});
});
//搜索框
$(function(){
        $(".ac_results").hover(function(){
			$("#searchboxtmp").removeClass("searchTxt");
			$("#searchboxtmp").addClass("searchTxtHover");
        },function(){
		    $("#searchboxtmp").removeClass("searchTxtHover");
			$("#searchboxtmp").addClass("searchTxt");
        });	
})
</script>

<div style="display:none">
<script src="<?=HTTPHOST?>/common/logjs" language="JavaScript"></script>
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-34705065-1']);
  _gaq.push(['_trackPageview']);
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>
<script type="text/javascript">
var _bdhmProtocol = (("https:" == document.location.protocol) ? " https://" : " http://");
document.write(unescape("%3Cscript src='" + _bdhmProtocol + "hm.baidu.com/h.js%3Ff8e7da29ec9c4e17446651e82f6a9b14' type='text/javascript'%3E%3C/script%3E"));
</script>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-53113773-1', 'auto');
  ga('send', 'pageview');

</script>
<script src="http://s22.cnzz.com/stat.php?id=4545212&web_id=4545212" language="JavaScript"></script>
</div>
<?php  
//记录在线人数
require_once 'Iceaclib/common/fun.php';
try{
  $this->fun = new MyFun();
  $this->fun->setOnline();
} catch (Exception $e) {}
unset($_SESSION['no_logbar_event']);
unset($_SESSION['no_menu_event']);
?>
