 <style type="text/css">
  #searchTab li:hover{ background:#eee;}
  </style>

<script language="javascript">
$(function(){
     var searchdiv = $("#searchTab");
     //搜索类型
        $(".searchMenu").hover(function(){
			searchdiv.css("display","block");
        },function(){
		    searchdiv.css("display","none");
        });	
	  //点击选择
	  var searchli = $("#searchTab li");
	  searchli.click(function(){
	     $("#st").val($(this).attr("id"));
		 $("#searchSelected").html($(this).html());
		 searchdiv.css("display","none");
		 $("#searchTab li").attr("class", "");
		 $(this).attr("class", "selected");
      });	
})
</script>
<div class="w" id="header"  style="z-index:102">
    
    <?php if(isset($_SESSION['change_logo']) && $_SESSION['change_logo']){ 
        echo $_SESSION['change_logo'];
        unset($_SESSION['change_logo']);}else{?>
  <div id="logo" ><a href="/" hidefocus="true"><img src="/images/default/logo.jpg" title="<?php echo $this->siteTitle?>" alt="<?php echo $this->siteTitle?>"></a></div>
  <?php }?>
    
    <form action="/search" id="searchForm" >
  <div class="searchbox">
    <div id="searchboxtmp" class="searchTxt" onmouseover="this.className='searchTxtHover';" onmouseout="this.className='searchTxt';">
      
      <input type="text" name="keyword" id="keyword" class="searchtext" value="<?=$this->keyword==''?'请输入搜索型号':$this->keyword;?>" onfocus="inputFocus($(this),'请输入搜索型号');" onblur="inputBlur($(this),'请输入搜索型号')" onkeydown="enter(event)" onclick="$('.ac_results').css('display','block');">
       <input type="hidden" name="st" id="st" value="<?=$this->st?$this->st:'searchall'?>" />
      <a href="#"><span class="searchicon"></span></a> </div>
    <div class="searchBtn">
      <input type="button" value="搜索" class="searchbottom" onclick="searchaction()"/>
    </div>
  </div>
  </form>
      
	<div class="headbtn2013 ">
    	<dl class="myself2013 iconA "><s></s>	
            <dt class="icon_t myself2013dt userinfo_load_menu">
              <span class="icon"></span>
              <a href="/center" target="_top" class="name">&nbsp;</a><i><em></em><span></span></i>
            </dt>
            <dd>
            <div class="hoverbox2013 boxshadow" >
            	<div class="menu-bd-name menu-bd-con" >
                    <div id="userinfo_drowm_menu"><img src="/images/admin/ajax-loader.gif" /> 加载中...</div>
                    <div class="clr"></div>
                </div>
                
            </div>
            </dd>
          </dl>
          <dl class="buybox2013 iconA"><s></s>	
            <dt class="icon_t buybox2013dt cartdropdown_hover">
              <span class="icon"></span>
              <a href="/cart">去购物车结算</a><i><em></em><span></span></i>
              <div class="bubble2013 sleter"><b></b><span class="cartnumber"><?php if(!isset($_SESSION['cartnumber'])) echo 0;else echo $_SESSION['cartnumber'];?></span></div>
            </dt>
            <dd>
            	<div id="cartdropdown">
                <div class="hoverbox2013_tip boxshadow "><img src="/images/admin/ajax-loader.gif" /> 加载中...</div>
                </div>
            </dd>
          </dl>
          <dl class="xunbox2013 iconA"><s></s>	
            <dt class="icon_t xunbox2013dt inquirydropdown_hover">
              <span class="icon"></span>
              <a href="/inquiry">提交询价篮</a><i><em></em><span></span></i>
              <div class="bubble2013 sleter"><b></b><span class="inquirynumber"><?php if(!isset($_SESSION['inquirynumber'])) echo 0;else echo $_SESSION['inquirynumber'];?></span></div>
            </dt>
            <dd>
            <div id="inquirydropdown">
                <div class="hoverbox2013_tip boxshadow "><img src="/images/admin/ajax-loader.gif" /> 加载中...</div>
                </div>
            </dd>
          </dl>
          
		 <div class="clr"></div>
        
    </div>
</div>
<script src="/js/jsplug/persontooltip/popup_cart.js" type="text/javascript"></script>
<script language="javascript">
function enter(evt){
    evt=evt?evt:(window.event?window.event:null);
    var keyCode = evt.keyCode;
	if(keyCode==13) searchaction();
}
function searchaction(){
	var keywordobj = document.getElementById('keyword');
	var keyword = keywordobj.value.replace(/[ ]/g,"");
	if(keyword=='' || keyword=='请输入搜索型号') {keywordobj.value='';keywordobj.focus();return;}
	else document.getElementById('searchForm').submit();
}
</script>
<!--end topmenu-->