<!--banner-->
<!--<div class="maintopbanner">
<a href="/jifen/event">&nbsp;</a>
</div>-->
<!--end banner-->
 <style type="text/css">
  #searchTab li:hover{ background:#eee;}
  </style>
  <script language="javascript">
$(function(){
     var searchdiv = $("#searchTab");
     //搜索类型
        $(".searchMenu").hover(function(){
			searchdiv.css("display","block");
        },function(){
		    searchdiv.css("display","none");
        });	
	  //点击选择
	  var searchli = $("#searchTab li");
	  searchli.click(function(){
	     $("#st").val($(this).attr("id"));
		 $("#searchSelected").html($(this).html());
		 searchdiv.css("display","none");
		 $("#searchTab li").attr("class", "");
		 $(this).attr("class", "selected");
      });	
})
</script>
<div class="w" id="header"  style="z-index:102">
  <?php if(isset($_SESSION['change_logo']) && $_SESSION['change_logo']){ 
        echo $_SESSION['change_logo'];
        unset($_SESSION['change_logo']);}else{?>
  <div id="logo" ><a href="/" hidefocus="true"><img src="/images/default/logo.jpg" title="盛芯电子" alt="盛芯电子"></a></div>
  <?php }?>
  <form action="/search" id="searchForm" >
  <div class="searchbox">
    <div id="searchboxtmp" class="searchTxt" onmouseover="this.className='searchTxtHover';" onmouseout="this.className='searchTxt';">
      <div class="searchMenu">
        <div class="searchSelected" id="searchSelected">
		<?php if($this->st=='searchmodel') echo '型号';
		else if($this->st=='searchsolution') echo '方案';
		else if($this->st=='searchnews') echo '资讯';
		else if($this->st=='searchwebinar') echo '研讨会';
		else if($this->st=='searchcode') echo '代码库';
		else echo '全站';?></div>
        <div class="searchTab" id="searchTab" style="z-index:1000">
          <ul>
            <li <?php if(!$this->st || $this->st=='searchgoogle') echo 'class="selected"';?>id="searchgoogle">全站</li>
            <li <?=($this->st=='searchmodel'?'class="selected"':'')?> id="searchmodel">型号</li>
            <li <?=($this->st=='searchsolution'?'class="selected"':'')?> id="searchsolution">方案</li>
            <li <?=($this->st=='searchnews'?'class="selected"':'')?> id="searchnews">资讯</li>
            <li <?=($this->st=='searchwebinar'?'class="selected"':'')?> id="searchwebinar">研讨会</li>
            <li <?=($this->st=='searchcode'?'class="selected"':'')?> id="searchcode">代码库</li>
            <li id="searchall" style="display:none">全站</li>
          </ul>
        </div>
      </div>
      <input type="text" name="keyword" id="keyword" class="searchtext" value="<?=$this->keyword==''?'请输入搜索内容':$this->keyword;?>" onfocus="inputFocus($(this),'请输入搜索内容');" onblur="inputBlur($(this),'请输入搜索内容')" onkeydown="enter(event)" onclick="$('.ac_results').css('display','block');">
       <input type="hidden" name="st" id="st" value="<?=$this->st?$this->st:'searchgoogle'?>" />
      <a href="#"><span class="searchicon"></span></a> </div>
    <div class="searchBtn">
      <input type="button" value="搜索" class="searchbottom" onclick="searchaction()"/>
    </div>
  </div>
  </form>

  <div class="headbtn">
    <div class="headbtnbg buy personPopupCart" rel="Cart" rev="/cart/dropdown" style="z-index:2">
      <dl class="buyson">
        <dt> <span class="icon"></span> <a href="/cart">去购物车结算</a><em></em> <b class="bubble"><b></b><span class="cartnumber"><?php if(!isset($_SESSION['cartnumber'])) echo 0;else echo $_SESSION['cartnumber'];?></span></b> </dt>
        <dd>
          <div id="contentCart" class="hoverbox"><span><img src="/images/admin/ajax-loader.gif" /><br/>购物车中还没有商品，赶紧选购吧！</span></div>
        </dd>
      </dl>
    </div>
    <div class="headbtnbg question personPopupCart" rel="Inquiry" rev="/inquiry/dropdown" style="z-index:1">
      <dl class="questionson">
        <dt> <span class="icon"></span> <a href="/inquiry">提交询价篮</a> <em></em> <b class="bubble"><b></b><span class="inquirynumber"><?php if(!isset($_SESSION['inquirynumber'])) echo 0;else echo $_SESSION['inquirynumber'];?></span></b></dt>
        <dd>
          <div class="hoverbox" id="contentInquiry"><span><img src="/images/admin/ajax-loader.gif" /><br/>询价篮还没有商品，赶紧挑选吧！</span></div>
        </dd>
      </dl>
    </div>
  </div>
  <!--<div style="position:absolute; top:38px; left:375px; line-height:26px; vertical-align:middle;z-index:105; font-size:15px; font-weight:bold; "><a href="/event/201302211" target="_blank" style=" color:#ff7600;" alt="飞思卡尔MCU创意大奖赛" >飞思卡尔MCU创意大奖赛<img src="/images/default/hot.gif" style="margin-left:2px; margin-top:-3px"/></a></div>-->
</div>
<script src="/js/jsplug/persontooltip/popup_cart.js" type="text/javascript"></script>
<script language="javascript">
function enter(evt){
    evt=evt?evt:(window.event?window.event:null);
    var keyCode = evt.keyCode;
	if(keyCode==13) searchaction();
}
function searchaction(){
	var keywordobj = document.getElementById('keyword');
	var keyword = keywordobj.value.replace(/[ ]/g,"");
	if(keyword=='' || keyword=='请输入搜索内容') {keywordobj.value='';keywordobj.focus();return;}
	else document.getElementById('searchForm').submit();
}
	/*$(document).ready(function() {
			$("#keyword").autocomplete("/search/getajaxtag",
			{
				delay:5,
            	minChars:1,
            	matchSubset:1,
            	matchContains:1,
            	cacheLength:10,
            	onItemSelect:selectItem,
            	onFindValue:findValue,
            	formatItem:formatItem,
            	autoFill:false,
				width:450
        	}
    		);
			});
			function findValue(li) {
    			if( li == null ) return alert("No match!");
				if( !!li.extra ) var sValue = li.extra[0];
				else var sValue = li.selectValue;
				}
			function selectItem(li) { findValue(li);}
			function formatItem(row) { return row[0];//return row[0] + " (id: " + row[1] + ")"//如果有其他参数调用row[1]，对应输出格式Sparta|896
			}
			function lookupAjax(){
			var oSuggest = $("#keyword")[0].autocompleter;
			oSuggest.findValue();
			return false;
			}*/
</script>
<!--end topmenu-->