<!--菜单-->

<script type="text/javascript">
$(function(){
	//商品分类下拉菜单
	$('.catelist2013 .catelist2013item').hover(function(){
		$(this).addClass('active');
		$(this).find('.product_wrap2013').show();
		var topvar = 0;
		var h = $(this).find('.product_wrap2013').height();
		var h2 = h/2;
		var ftop   = $(this).offset().top;
		var ttop = $('.catelist2013item').offset();
		topvar = ftop-ttop.top-h2/2;
		if(topvar<0) topvar = 0;
		else {var dtop = topvar+h;
		 var catelist2013h = $('.catelist2013').height();
		 if(dtop>catelist2013h) topvar = topvar - (dtop-catelist2013h)+2;
		}
		$(this).find('.product_wrap2013').css("top",topvar); 
	},function(){
		$(this).removeClass('active');
		$(this).find('.product_wrap2013').hide();
	});
	<?php if($_SESSION['menu']!='index'){?>
	$('.categorys2013_good').hover(function(){
		$(this).find('.catelist2013').slideDown();
		$(this).find(".categorys2013_icon").removeClass("categorys2013_arrowdown");
		$(this).find(".categorys2013_icon").addClass("categorys2013_arrowup");		
	},function(){
		$(this).find('.catelist2013').hide();
		$(this).find(".categorys2013_icon").removeClass("categorys2013_arrowup");
		$(this).find(".categorys2013_icon").addClass("categorys2013_arrowdown");	
	});
	<?php }?>
	$('#newshudi').hover(function(){

		$(this).find(".navigation_sub").removeClass("hide");
	
	},function(){

		$(this).find(".navigation_sub").addClass("hide");	
	});
	
});
</script>

<div id="newmenu2013" class="newmenu201312">
  <div class="w pos-re sleter" >
    <div class="categorys2013">
      <div class="categorys2013_good">
        <div class="categorys2013_t">
          <div class="categorys2013_c">产品分类</div>
          <i class="categorys2013_icon <?=$_SESSION['menu']!='index'?'categorys2013_arrowdown':'categorys2013_arrowup'?>"></i> </div>		
        <div class="catelist2013 homemenu201312" style="display:<?=$_SESSION['menu']!='index'?'none':'block'?>;">
          
          <?php foreach($this->first as $farr){
				$fid = $farr['id'];
				?>
          <div class="catelist2013item">
            <div class="product2013">
              <h3><a href="/list-<?=$farr['id']?>.html" onclick="logclickaction($(this))" class="nav" rev="mainmenu_category" rel="<?=$farr['id']?>"><?=$farr['name']?></a></h3>
              <s></s> </div>
            <div class="product_wrap2013 pos01" >
              <div class="fl">
							<div class="show_sort2013">
								<div class="menudl2013">
								<?php   
								  foreach($this->second[$fid] as $k=>$sarr){
								  $sid = $sarr['id'];
								  ?>
								<dl <?=(count($this->second[$fid])==($k+1)?'class="last"':'')?>>
									<dt><a href="/list-<?=$fid?>-<?=$sid?>.html" onclick="logclickaction($(this))" rev="mainmenu_category" rel="<?=$sid?>"><?=$sarr['name']?></a></dt>
									<dd>
										<ul>
										<?php  foreach($this->third[$sid] as $tarr){
										 $tid=$tarr['id'];
										 ?>
											<li><a href="/list-<?=$fid?>-<?=$sid?>-<?=$tid?>.html"  onclick="logclickaction($(this))" rev="mainmenu_category" rel="<?=$tid?>"><?=$tarr['name']?></a></li>
									   <?php }?>
										</ul>
									</dd>
								</dl>
								<?php }//end foreach($this->second[$fid] as $sarr){?>
								</div>
								<?php 
							  $cbarnd = $this->categorybarnd[$fid];
								if($cbarnd){
							  ?>
								<div class="menubrand2013">
									<h3>推荐品牌</h3>
									<ul>
									<?php foreach($cbarnd as $cbarndarr){?>
									  <li><a href="/pl/<?=$cbarndarr['name']?>"  onclick="logclickaction($(this))" rev="mainmenu_brand" rel="<?=$tid?>"><img src="/images/default/brand/<?=$cbarndarr['comid']?>_h.png"></a></li>
									  <?php }?>
									</ul>
								</div>
							   <?php }?>
							</div>
						</div>
            </div>
          </div>
          <?php }?>
        </div>
        
      </div>
      
    </div>
    <div class="main-nav wrap">
	    <ul class="main-nav-ul">
	    			<li>
			        	<a href="/" >首页</a>
			        </li>
			        <li>
			        	<a href="/bompurchase" >批量询价</a>
			        </li>
			        <li>
			        	<a href="/brand" >品牌列表</a>
			        </li>
			        <li>
			        	<a href="/category">产品目录</a>
			        </li>
			        <li>
			        	<a href="/market">行业新闻</a>
			        </li>
			        <li>
			        	<a href="/company">企业动态</a>
			        </li>
			        <li>
			        	<a href="/news">产品资讯</a>
			        </li>
	    </ul>
	    </div>
  </div>
    
  
  <div class="menushadow2013"></div>
</div>