<!--mainmenu-->
<script src="/js/jsplug/menu/main/CJL.0.1.min.js" type="text/javascript"></script>
<script src="/js/jsplug/menu/main/FixedMenu.js" type="text/javascript"></script>
<script src="/js/jsplug/menu/main/RelativePosition.js" type="text/javascript"></script>
<script type="text/javascript">
<?php if($_SESSION['menu']!='index'){?>
$(function(){
//产品分类
        var tab = $(".categorys");
        tab.hover(function(){
			$(this).find(".cate_box").removeClass("hide");
			$(this).find(".stmp").addClass("hide");
			$(this).find(".btmp").removeClass("hide");
        },function(){
			$(this).find(".cate_box").addClass("hide");
			$(this).find(".stmp").removeClass("hide");
			$(this).find(".btmp").addClass("hide");	
        });	
})
<?php }?>
</script>
<div class="mainmenu ">
  <div class="w" style="z-index:101;">
    <div class="categorys">
      <div class="cate_tit"><div class="cate_tit_t">产品分类</div>
      <s class="stmp <?=$_SESSION['menu']!='index'?'':'hide'?>"></s>
      <b class="btmp <?=$_SESSION['menu']!='index'?'hide':''?>"></b></div>
      <div class="cate_box <?php if($_SESSION['menu']!='index') echo 'hide';?>" >
        <ul id="idContainer2" class="allsort">
        <?php 
		foreach($this->first as $farr){
		   if($farr['show_home']==1){
				if($this->second[$farr['id']][0]['id']!='')
				{
				   $strtmp = '<strong>&gt;</strong>';
				}else{
				   $strtmp = '';
				}
		?>
           <li id="idMenu_<?=$farr['id']?>">
           <a href="/list-<?=$farr['id']?>.html" title="<?=$farr['name']?>" onclick="logclickaction($(this))" class="nav" rev="mainmenu_category" rel="<?=$farr['id']?>">
           <h2><?=$farr['name']?></h2><?=$strtmp?></a></li>
       <?php }
	   }?>
        </ul>
        <div id="idContainer2_2" class="container2_2"  style="display:none">
          <div class="shadow"></div>
          <dl>
            <dt id="idTitle"></dt>
            <dd id="idMenu2">
              	<?php
		  $i=0;
		  foreach($this->first as $farr){
		    if($farr['show_home']==1){
			   $fid = $farr['id'];
				
				$idMenu2_block = 'block';
			   if($this->second[$farr['id']][0]['id']=='') $idMenu2_block = 'hide';
			   $i++;
			   if($fid==452){ 
				  $top = $ie6top = 11;
			   }else{
				if($i==1){
					$top = 5;
					$ie6top = 11;
				}else{ $top = $i*6;
					$ie6top = $i*10;
				}
			   }
 		  ?>
            <div id="idMenu2_<?=$farr['id']?>">
            <div class="show_sort <?=$idMenu2_block?>" style="display:block;top:-<?=$top?>px;_top:-<?=$ie6top?>px;">
              <div>
                <?php   
		          foreach($this->second[$fid] as $sarr){
				  $sid = $sarr['id'];
		        ?>
                <dl>
                  <dt><a href="/list-<?=$fid?>-<?=$sid?>.html"  title="<?=$sarr['name']?>" onclick="logclickaction($(this))" rev="mainmenu_category" rel="<?=$sid?>"><?=$sarr['name']?></a></dt>
                     <?php  foreach($this->third[$sid] as $tarr){
					 $tid=$tarr['id'];
					 ?>
                     <dd><a href="/list-<?=$fid?>-<?=$sid?>-<?=$tid?>.html"  title="<?=$tarr['name']?>" onclick="logclickaction($(this))" rev="mainmenu_category" rel="<?=$tid?>"><?=$tarr['name']?></a></dd>
					 <?php }?>
                </dl>
               <?php }?>
              </div>
              <?php 
			  $cbarnd = $this->categorybarnd[$fid];
			  	if($cbarnd){
			  ?>
              <div class="hot_brand">
                <h3>推荐品牌</h3>
                <ul>
                  <?php foreach($cbarnd as $cbarndarr){?>
                  <li><a href="/pl/<?=$cbarndarr['name']?>"  onclick="logclickaction($(this))" rev="mainmenu_brand" rel="<?=$tid?>"><?=$cbarndarr['name']?></a></li>
                  <?php }?>
                </ul>
              </div>
              <?php }?>
            </div>
            <div class="clr"></div>
          </div>
         <?php }
		 }?>
            </dd>
          </dl>
        </div>
      </div>
    </div>
<script type="text/javascript">
var menu2 = [
	<?php
	foreach($this->first as $farr){
	if($farr['show_home']==1){
	$fid = $farr['id'];
	?> 
	   { id: '<?=$fid?>', parent: 0, elem: 'idMenu_<?=$fid?>',rank:<?php echo $farr['displayorder'];?> },
       { id: '<?=$this->second[$fid][0]['id']==''?'0':$this->second[$fid][0]['id']?>', parent: '<?=$fid?>', elem: 'idMenu2_<?=$fid?>' },

	<?php }
	}?>
];
var container2 = [ "idContainer2", { id: "idContainer2_2", menu: "idMenu2" } ];
new FixedMenu(container2, { menu: menu2,
	relative: { align: "clientleft", vAlign: "clienttop", customTop: 5, customLeft: 176 },
	onBeforeShow: function(container, menu){ $$("idTitle").innerHTML = menu._elem.innerHTML;}
});
</script>
    <div id="nav"> <span class="bleft"></span>
      <ul id="navitems" class="navul201312_da">
        <li><a href="/" class="index <?php if($_SESSION['menu']=='index') echo 'on';?>"><?=$this->translate('Menu_Home')?></a><s></s></li>
        <li><a href="/category" class="category <?php if($_SESSION['menu']=='category') echo 'on';?>"><?=$this->translate('Menu_ProductCategory')?></a><s></s></li>
        <li><a href="/solutionlist" class="applications <?php if($_SESSION['menu']=='applications') echo 'on';?>"><?=$this->translate('Menu_Applications')?></a><s></s></li>
        <li><a href="/news" class="seminar <?php if($_SESSION['menu']=='news') echo 'on';?>"><?=$this->translate('Menu_News')?></a><s></s></li>
        <li><a href="/webinarlist" class="seminar <?php if($_SESSION['menu']=='seminar') echo 'on';?>"><?=$this->translate('Menu_Seminar')?></a><s></s></li>
        <li><a href="/bompurchase" class="bompurchase <?php if($_SESSION['menu']=='bom') echo 'on';?>"><?=$this->translate('Menu_Bom')?></a><s></s></li>
        <li><i class="newtip_icon"></i><a href="/code"  class="seminar <?php if($_SESSION['menu']=='appcode') echo 'on';?>" style="color:#ffea00; font-weight:800; ">代码库</a><s></s></li>

        <li class="newmenu"><!--<i class="newtip_icon"></i>--><a href="/event/201308012">难寻器件</a></li>
        <!--<li class="blankmenuli"><span>&nbsp;</span></li>
        <li class="lastmenu"><a href="/center" class="center <?php if($_SESSION['menu']=='center') echo 'on';?>"><?=$this->translate('Menu_Center')?></a><s></s></li>-->
      </ul>
      <a href="/?t=2014" style="position:absolute; top:0px; right:5px; color:#fff; filter: alpha(opacity:80);KHTMLOpacity: 0.8;MozOpacity: 0.8;opacity: 0.8; ">新版&gt;</a>
      <p class="lastmenu fr hide"><a href="/center" class="center <?php if($_SESSION['menu']=='center') echo 'on';?>"><?=$this->translate('Menu_Center')?></a><s></s></p>
      <span class="bright"></span> </div>
      
      
  </div>
</div>
<!--end mainmenu-->