<div class="lotteryResult lotteryResultsmall" id="lotteryResult2" style="">
    <div class="resultArea">
        <div class="result">
            <h3>很抱歉，您的积分不够</h3>
            <div class="resultBtnWrap clearfix">
                <div class="resultBtnInner">
                    <a class="resultBtn" href="/jifen/rule">去看看怎么赚积分</a>
                </div>
            </div>
        </div>
    </div>
    <a class="ResultClose" href="#nohash" onclick="$.closePopupLayer('box')"></a>
</div>