<?php echo $this->render('jifen/menu.phtml');?>
<!-------------------------------------------------活动主体------------------------------------------------->
<div class="con-full pos-re rule">
	<div class="full-banner-rule"></div>
    <div class="full-menu-rule">
    	<div class="w w-menu-rule pos-re">
        	<ul>
            	<li class="fore1 on" ><s></s><a href="#ruleboxsub1">赚积分</a></li>
                <li class="fore2" ><s></s><a href="#ruleboxsub2">花积分</a></li>
                <li class="fore3" ><s></s><a href="#ruleboxsub3">积分有效期</a></li>
                <li class="fore4" ><s></s><a href="#ruleboxsub4">积分查询</a></li>
                <li class="fore5" ><s></s><a href="#ruleboxsub5">推荐用户注册</a></li>
            </ul>
        </div>
    </div>
    <div class="w rulebox" >
        <div class="ruleboxsub clearfix pos-re ruleboxsub1" id="ruleboxsub1">
            <div class="fl">
                <div class="slogen"> 
                    <span class="font42"><strong>赚积分</strong></span><br> 
                    <span class="font22">轻松赚积分</span><br> 
                </div>
                <div class="conte font16"> 
                    新用户注册、推荐注册送积分<br />
                    签到、浏览、分享都有积分拿<br />
                    询价、下单赚积分，首单额外大放送
                </div>
            </div>
            <div class="fr">
              <table class="table_rule" border="0" cellpadding="0" cellspacing="0" width="100%">
                <colgroup>
                    <col width="9%">
                    <col width="35%">
                    <col width="11%">
                    <col width="11%">
                    <col width="34%">
                </colgroup>
                <tbody>
                    <tr>
                        <th>类型</th>
                        <th>行为</th>
                        <th>奖励分值</th>
                        <th>周期范围</th>
                        <th>备注</th>
                    </tr>
                    <tr>
                        <td rowspan="2">注册</td>	
                        <td align="left">注册，新用户成功注册为IC易站用户</td>
                        <td class="tableno">+20</td>
                        <td>首次</td>
                        <td align="left" class="trlast">须通过邮箱验证</td>
                    </tr>
                    <tr>
                        <td align="left">推荐注册，每推荐一位好友注册</td>
                        <td class="tableno">+20</td>
                        <td>不限周期</td>
                        <td align="left" class="trlast">被推荐用户须在邀请链接下注册，并通过邮箱验证</td>
                    </tr>
                    <tr>
                        <td rowspan="3">活跃度</td>	
                        <td align="left">登录签到</td>
                        <td class="tableno">+1</td>
                        <td>每天</td>
                        <td align="left" class="trlast">仅限一次</td>
                    </tr>
                    <tr>
                        <td align="left">登录后，每次浏览≥6个页面</td>
                        <td class="tableno">+2</td>
                        <td>每天</td>
                        <td align="left" class="trlast">每日上限2分</td>
                    </tr>
                    <tr>
                        <td align="left">每分享一款产品、一篇产品资讯、技术研讨会或应用方案</td>
                        <td class="tableno">+1</td>
                        <td>每天</td>
                        <td align="left" class="trlast">每日上限5分</td>
                    </tr>
                    <tr>
                        <td rowspan="4">下单</td>	
                        <td align="left">首次询价</td>
                        <td class="tableno">+10</td>
                        <td>首次</td>
                        <td align="left" class="trlast">注册后首次</td>
                    </tr>
                    <tr>
                        <td align="left">首次下单</td>
                        <td class="tableno">+100</td>
                        <td>首次</td>
                        <td align="left" class="trlast">额外赠送，需确认收货</td>
                    </tr>
                    <tr>
                        <td align="left">询价下单</td>
                        <td>&nbsp;</td>
                        <td>不限周期</td>
                        <td align="left">每100元可获赠1分，需确认收货</td>
                    </tr>
                    <tr>
                        <td align="left" class="trlast">在线下单</td>
                        <td>&nbsp;</td>
                        <td>不限周期</td>
                        <td align="left" class="trlast">每100元可获赠10分，需确认收货</td>
                    </tr>
                </tbody>
          </table>
            </div>
            <div class="rule_shadow"></div>
        </div>	
        <div class="ruleboxsub clearfix pos-re ruleboxsub2" id="ruleboxsub2">
            <div class="fr">
                <div class="slogen"> 
                    <span class="font42"><strong>花积分</strong></span><br> 
                    <span class="font22">豪华奖品 等你来换</span><br> 
                </div>
                <div class="conte font16"> 
                    豪华大奖不是梦，精美礼品轻松拿<br />
                    电子礼券，手到擒来，让您轻松购物<br />
                    IC易站优惠券，畅享购“芯”优惠<br />
                    小积分抽大奖 
                </div>
            </div>
            <div class="fl rule2bg"></div>
            <div class="rule_shadow"></div>
        </div>					
        <div class="ruleboxsub clearfix pos-re ruleboxsub3" id="ruleboxsub3">
            <div class="fl ">
                <div class="slogen"> 
                    <span class="font42"><strong>积分有效期</strong></span><br> 
                    <span class="font22">把握时机，轻松兑换</span><br> 
                </div>
                <div class="conte font16"> 
                    您在IC易站的积分是可以累积的，积分有效期为<span class="font20">1</span>年，<br />
从第一次获得积分的日期往后推<span class="font20">365</span>天为过期作废时间。<br />
如果发现存在违规刷分行为，IC易站有权将违规获得的积分清零。 
                </div>
            </div>
            <div class="fr rule3bg"></div>
            <div class="rule_shadow"></div>
        </div>	
        <div class="ruleboxsub clearfix pos-re ruleboxsub4" id="ruleboxsub4">
            <div class="fr">
                <div class="slogen"> 
                    <span class="font42"><strong>积分查询</strong></span><br> 
                    <span class="font22">积分动态，随时掌握</span><br> 
                </div>
                <div class="conte font16"> 
                    登录后，您可以在“我的IC易站—我的积分”中，<br />
                    查看您的积分及兑奖信息，也可以在积分商城的<br />用户中心查看。 
                </div>
            </div>
            <div class="fl rule4bg"></div>
            <div class="rule_shadow"></div>
        </div>			
        <div class="ruleboxsub clearfix pos-re ruleboxsub5 " id="ruleboxsub5">
            <div class="fl ">
                 <div class="slogen"> 
                    <span class="font42"><strong>推荐好友</strong></span><br> 
                    <span class="font22">推荐好友有积分送</span><br> 
                </div>
                <div class="conte font16"> 
                    所有已注册用户可通过发送链接的方式邀请好友注册，好友<br />
在邀请链接下注册成功后，老注册用户可获得积分20分。<br />
            
				</div>
                <div class="conte font16"> 
                	同一个邀请链接可发送给多位好友。<br />    
                	<span class="font20">这是您的邀请链接：</span><span class="font12">（可复制邀请链接发送给好友）</span>
				</div>
                <div class="conte font16"> 
               <?php if(isset($_SESSION['userInfo']['unameSession'])){?>
               <input type="text" title="复制" class="rulelink" name="inviteurl" id="inviteurl" value="<?php echo HTTPHOST."/user/register?invitekey=".$_SESSION['userInfo']['uidSession'];?>" />
              <a href="javascript:void(0);" title="复制" class="gbqfb gbqfbbig" onclick="copyinvite('inviteurl')"><b>复 制</b></a>
              <?php }else{?>
              <a href="javascript:void(0);" title="登录" onclick="openlogin()" class="gbqfb gbqfbbig"><b>登录获取链接</b></a>
              <?php }?>
				</div>
                <div class="fr rule5bg"></div>
                <div class="rule_shadow"></div>
            </div>
            
            
            <div class="sec-share clearfix">
                    <i></i>
                    <!--<em class="bold">发给qq空间、微博好友，更多好朋友看到，更多机会获得奖励！</em>-->
                    <div id="J-sns-share" class="fshare clearfix">
                        <div class="fshare-item J-sns-share-type1">
                            <?php if(isset($_SESSION['userInfo']['unameSession'])){?>
                            <a data-fid="share_qq" class="fs-tqq" title="分享到腾讯微博" href="javascript:;" onclick="shareBaidu('tqq','<?=$_SESSION['userInfo']['uidSession'];?>');">tqq</a>
                            <a data-fid="share_sina" class="fs-tsina" title="分享到新浪微博" href="javascript:;" onclick="shareBaidu('tsina','<?=$_SESSION['userInfo']['uidSession'];?>');">tsina</a>
                            <a data-fid="share_renren" class="fs-renren" title="分享到人人" href="javascript:;" onclick="shareBaidu('renren','<?=$_SESSION['userInfo']['uidSession'];?>');">renren</a>
                            <a data-fid="share_qqzone" class="fs-qq" title="分享到QQ好友" href="javascript:;" onclick="shareBaidu('qq','<?=$_SESSION['userInfo']['uidSession'];?>');">QQ</a>
                            <a data-fid="share_qqzone" class="fs-qzone" title="分享到QQ空间" href="javascript:;" onclick="shareBaidu('qzone','<?=$_SESSION['userInfo']['uidSession'];?>');">qzone</a>
                            <?php }else{?>
                            <a class="fs-tqq" title="分享到腾讯微博" href="javascript:void(0)" onclick="openlogin()">tqq</a>
                            <a class="fs-tsina" title="分享到新浪微博" href="javascript:void(0)" onclick="openlogin()">tsina</a>
                            <a class="fs-renren" title="分享到人人" href="javascript:void(0)" onclick="openlogin()">renren</a>
                            <a class="fs-qq" title="分享到QQ好友" href="javascript:void(0)" onclick="openlogin()">QQ</a>
                            <a class="fs-qzone" title="分享到QQ空间" href="javascript:void(0)" onclick="openlogin()">qzone</a>
                            <?php }?>
                        </div>
                    </div>
                </div>
        </div>	
    </div>