<!--content-->
<link rel="stylesheet" type="text/css" href="/css/default/myself.css" />

<div class="w">
    <div class="breadcrumbs">		
    	<span><?=$this->translate('Menu_CurrentPosition')?></span><a href="/"><?=$this->translate('Menu_Home');?></a>&nbsp;&nbsp;»&nbsp;&nbsp;<a href="/center" ><?=$this->translate('Menu_Center')?></a>&nbsp;&nbsp;»&nbsp;&nbsp;<span>COD资格申请</span>        
    </div>
</div>
<div class="blank10"></div>
<div class="w clearfix ">
        <!--左边导航-->
        <div id='leftmenu'></div>

	<div class="fr u_right msg24">
	 <div class="<?php if(isset($_SESSION['inqmessage']) && $_SESSION['inqmessage']) echo "ok";?>" id="inqmessage"><?php echo $_SESSION['inqmessage'];unset($_SESSION['inqmessage']);?></div>
     	
         <div class="col_main" id="onlineorder">
         <h1>COD资格申请</h1>
            <div class="order_tab_head">
                <ul>
        <li <?php if(!$this->type) echo 'class="on"';?>><a style="width:130px" href="/center/inquiry">全部Bom采购记录<em>(<?=$this->allnum?>)</em><b class="blank3"></b></a></li>
       
                </ul>
            </div>
            <div class="table_box " >
                <table class="vac_table" cellpadding="0" cellspacing="0">   
                <thead>    
                    <tr>
                          <th>编号</th>
                          <th>说明</th>
                          <th>交货地</th>
                          <th>结算货币</th>
                          <th>提交日期</th>
                          <th></th>
                    </tr>   
                </thead>            
                <tbody>  
                    <?php if (empty ( $this->bom )) { ?><tr><td colspan="10"><center>暂无记录</center></td></tr>
            <?php }else{
				        foreach ( $this->bom as $k => $v ) {
							$bgclass = '';
							if ($k % 2 == 1)
							$bgclass  = 'tabletrf9';
							$inqkey   = $this->fun->encryptVerification($v['id']);
							$remark   = $v['remark'];
							$delivery = $deliveryArr[$v['delivery']];
							$currency = $currencyArr[$v['currency']];
							$created  = date('Y-m-d H:i',$v['created']);
							$detaile = $v['detaile'];
						
					?>
          <tr class="hover_tr <?=$bgclass?>" rel="<?=$k?>" id="ftr_<?=$k?>" onclick="showinquiry('<?=$k?>')" style="cursor: pointer">
            <td height="25"><?php echo $v['id'];?></td>
            <td width="100"><?php echo $remark;?></td>
            <td width="50"><?php echo $delivery;?></td>
            <td width="50"><?php echo $currency;?></td>
            <td><?php echo $created;?></td>

            <td><span id="show_but_<?=$k?>" class="show_but"><a href="javascript:">查看详细</a></span></td>
          </tr>
          <tr class="hover_tr <?=$bgclass?> tr_show_inquiry" rel="<?=$k?>" style="display: none;" id="tr_show_inquiry_<?=$k?>">
                  <td colspan="10" class="openprice"><div class="subtal" id="show_inquiry_<?=$k?>">
                      <div class="up"></div>
                      <table width="100%" cellpadding="0" cellspacing="0" class="subtablei">
                        <tr>
                          <th>MFR</th>
                          <th>Requested P/N</th>
                          <th>Required Qty</th>
                          <th>Item Remarks</th>
                        </tr>
                        <?php for($j=0;$j<count($detaile);$j++){?>
                        <tr><td><?=$detaile[$j]['mfr']?></td>
                        <td><?=$detaile[$j]['part_no']?></td>
                        <td><?=$detaile[$j]['number']?></td>
                        <td><?=$detaile[$j]['description']?></td></tr>
                        <?php }?>
                      </table>
                    </div></td>
          </tr>
          <?php }}?>  
                </tbody>         
                </table>
            </div> 
            <div class="pagination fr"> <?=$this->page_bar;?></div>
        </div>
        
        
   </div>
</div>
<div class="clr"></div>
<script type="text/javascript">
$(document).ready(function(){
  onloadleftmenu('cod');
});
</script>
