<div class="pop pop_company">
<div class="popbox" style="width:560px;">
  <div class="poptit"> 
  	<span class="titbg1ts">企业资料填写</span>
    <input type="button" title="关闭" class="closebtn" onclick="$.closePopupLayer('companyinfoBox')">
  </div>
  <div class="popcon clearfix msg">
    <div class="ok" id="message" style="display: none;"></div>
    <div id="show_inquiry_1" class="poptable">
	  <input type="hidden" name="ptype" value="2"/>
      <table cellpadding="0" cellspacing="0" class="table01">
        <tbody>
        <tr>
          <td  class="tableti"><em>* </em>公司名称：</td>
          <td ><input type="text" style="width:300px;" name="companyname" id="companyname" value="<?php echo $this->myinfo['companyname'];?>"/></td>
        </tr>
       <tr>
          <td class="tableti"><em>*</em>企业性质：</td>
          <td> <select name="property" id="property">
            <option value="enduser" <?=$this->myinfo['property']=='enduser'?'selected':'';?>>终端用户</option>
            <option value="merchant" <?=$this->myinfo['property']=='merchant'?'selected':'';?>>贸易商</option>
          </select></td>
        </tr>
        <tr>
          <td class="tableti"><em>*</em>行业领域：</td>
          <td> <select id="industry" name="industry" id="industry">
                <?php foreach($this->appLevel1 as $k=>$v){
			    $sel='';
			    if($this->myinfo['industry'] == $v['id']) $sel = 'selected="selected"';
			    echo "<option value='".$v['id']."' $sel>".$v['name']."</option>";
		        }?>
               </select></td>
        </tr>
        
        <tr>
          <td class="tableti"><em>*</em>常用币种：</td>
          <td><select name="currency" id="currency">
                                <option value="RMB" <?=$this->myinfo['currency']=='RMB'?'selected':'';?>>人民币(RMB)</option>
    							<option value="USD" <?=$this->myinfo['currency']=='USD'?'selected':'';?>>美元(USD)</option>
                                <option value="HKD" <?=$this->myinfo['currency']=='HKD'?'selected':'';?>>港币(HKD)</option>
                            </select></td>
        </tr> 
         <tr >
          <td class="tableti"><em>*</em>联系人：</td>
          <td><input type="text" class="input150" name="contact" id="contact" value="<?php echo $this->myinfo['truename'];?>"/></td>
        </tr>
         <tr >
          <td class="tableti"><em>*</em>部门：</td>
          <td><select name="department_id" id="department_id">
                  <?php foreach($this->office as $v){?>
                  <option value="<?=$v['id']?>" <?=$this->myinfo['department_id']==$v['id']?'selected':'';?>><?=$v['department']?></option>
                  <?php }?>
             </select></td>
        </tr>
        <tr >
          <td class="tableti">联系人手机：</td>
          <td><input type="text" class="input150" name="mobile" id="mobile" value="<?php echo $this->myinfo['mobile'];?>"/></td>
        </tr>
        <tr>
          <td class="tableti"><em>*</em>公司电话：</td>
          <td><input type="text" class="input150" name="tel" id="tel" value="<?php echo $this->myinfo['tel'];?>"/></td>
        </tr>
        <tr>
          <td class="tableti"><em>*</em>公司传真：</td>
          <td><input type="text" class="input150" name="fax" id="fax" value="<?php echo $this->myinfo['fax'];?>"/></td>
        </tr>
        <tr>
          <td class="tableti"><em>*</em>所在地区：</td>
          <td><span id="provinceSpan">
          <select id="province" name="province">
            <option value="">请选择省</option>
          </select>
          </span> <span id="citySpan">
          <select id="city" name="city">
            <option value="">请选择市</option>
          </select>
          </span> <span id="areaSpan" style="position:relative;">
          <select id="area" name="area">
            <option value="">请选择区</option>
          </select>
          </span></td>
        </tr>
        <tr>
          <td class="tableti"><em>*</em>详细地址：</td>
          <td><input type="text" style="width:300px;" name="address" id="address" value="<?php echo $this->myinfo['address'];?>"/></td>
        </tr>
        <tr>
          <td class="tableti">邮政编码：</td>
          <td><input type="text" class="input150" name="zipcode" id="zipcode" value="<?php echo $this->myinfo['zipcode'];?>"/></td>
        </tr>
        <tr>
          <td></td>
          <td><input type="button" onClick="tijiaocominfo()" value="提 交"  title="提交企业资料" class="button"/>
          
          &nbsp;&nbsp;&nbsp;&nbsp;<input type="button" onClick="cancel()" value="取 消"  title="取消提交，关闭窗口" class="buttongray"/>
        
          </td>
        </tr>
      </tbody></table>
    </div>
  </div>
</div>
<script type="text/javascript">
document.getElementById("message").style.display = 'none';
function cancel(){
	$.closePopupLayer('companyinfoBox');
	<?php if($this->opbox && $this->opurl && $this->opcancel){?>
	   $.openPopupLayer({
		 name: "<?=$this->opbox?>",
		 url: "<?=$this->opurl?>?key=<?=$this->key?>"
	   });
   <?php }?>
}
function tijiaocominfo() 
{
	var companyname= document.getElementById('companyname').value;
	var property = document.getElementById('property').value;
	var industry = document.getElementById('industry').value;
	var currency = document.getElementById('currency').value;
	var contact = document.getElementById('contact').value;
	var department_id =  document.getElementById('department_id').value;
	var mobile = document.getElementById('mobile').value;
	var tel = document.getElementById('tel').value;
	var fax = document.getElementById('fax').value;
	var province = document.getElementById('province').value;
	var city = document.getElementById('city').value;
	var area = document.getElementById('area').value;
	var address = document.getElementById('address').value;
	var zipcode = document.getElementById('zipcode').value;
	isTel(document.getElementById('tel'));
	if(companyname==''){$('#companyname').focus();tishi('请输入公司名称。',false);return;}
	if(contact==''){$('#contact').focus();tishi('请输入联系人。',false);return;}
	if(tel=='') {$('#tel').focus();tishi('请输入公司电话。',false);return;}
	else{if(!isTel(tel)){$('#tel').focus();tishi('公司电话格式不正确，格式：0577-88888888-111。',false);return;}}
	
	if(fax=='') {$('#fax').focus();tishi('请输入公司传真。',false);return;}
	else{if(!isTel(fax)){$('#fax').focus();tishi('公司传真格式不正确，格式：0577-88888888。',false);return;}}
	
	if(province=='') {tishi('请选择省份。',false);return;}
	if(city=='') {tishi('请选择城市。',false);return;}
	if(area=='') {tishi('请选择区。',false);return;}
	if(address=='') {$('#address').focus();tishi('请填入详细地址。',false);return;}

    $.ajax({
            url: '/center/companyinfo',
            data: {'companyname':companyname,'contact':contact,'industry':industry,'department_id':department_id,'mobile':mobile,'property':property,'currency':currency,'tel':tel,'fax':fax,'province':province,'city':city,'area':area,'address':address,'zipcode':zipcode},
            type: 'post',
            dataType: 'json',
            success: function(arr) {
			   if(arr.code==0)
			   {   
			       $.closePopupLayer('companyinfoBox');
			       alert(arr.message);
			   	   <?php if($this->opbox && $this->opurl){?>
				   $.openPopupLayer({
		             name: "<?=$this->opbox?>",
		             url: "<?=$this->opurl?>?key=<?=$this->key?>"
	               });
				   <?php }?>
			   }else tishi(arr.message,false);
            }
    });
}
function tishi(title,model)
{
	var messobj = document.getElementById("message");
	if(model){
		messobj.className = 'ok';
		messobj.style.display = 'block';
		messobj.innerHTML = title;
	}else{
	    messobj.className = 'error';
		messobj.style.display = 'block';
		messobj.innerHTML = title;
	}
	setTimeout('hidMessage()',2000);
}
function hidMessage(){
	document.getElementById("message").style.display = 'none';
}
//加载城市和地区
onloadadd('<?php echo $this->myinfo['province'];?>','<?php echo $this->myinfo['city'];?>','<?php echo $this->myinfo['area'];?>');
function selectCity(){
		var provinceid=$("#province").val();
		$("#citySpan").load("/common/getcity?provinceid="+provinceid);
	}
	function selectArea(){
		var cityid=$("#city").val();
		$("#areaSpan").load("/common/getarea?cityid="+cityid);
	}
	function setArea(value){
	}
	function onloadadd(provinceid,cityid,areaid)
	{
		$("#provinceSpan").load("/common/getprovince?provinceid="+provinceid);
		if(provinceid && cityid)
			$("#citySpan").load("/common/getcity?provinceid="+provinceid+"&cityid="+cityid);
		if(cityid && areaid)
		    $("#areaSpan").load("/common/getarea?cityid="+cityid+"&areaid="+areaid);
	}
</script>
