<?php 
$statusarr = array('101'=>'<p class="orange_payment">待付款</p>',
'102'=>'<p class="orange_ing">处理中</p>',
'103'=>'<p class="orange_residualpayment">待支付余款</p>',
'201'=>'<p class="orange_shipments">待发货</p>',
'202'=>'<p class="orange_harvest">待确认收货</p>',
'301'=>'<p class="green_ok">已完成</p>',
'302'=>'<p class="green_evaluate">已评价</p>',
'401'=>'<p class="gray_cancel">订单被取消</p>',
'501'=>'<p class="gray_return">退款</p>',
'502'=>'<p class="gray_returngoods">退货退款</p>');

$codarr = array('101'=>'<p class="orange_approv">等待审核</p>',
'102'=>'<p class="orange_ing">处理中</p>',
'103'=>'<p class="orange_residualpayment">待支付余款</p>',
'201'=>'<p class="orange_shipments">待发货</p>',
'202'=>'<p class="orange_harvest">待确认收货</p>',
'301'=>'<p class="green_ok">已完成</p>',
'302'=>'<p class="green_evaluate">已评价</p>',
'401'=>'<p class="gray_cancel">订单被取消</p>',
'501'=>'<p class="gray_return">退款</p>',
'502'=>'<p class="gray_returngoods">退货退款</p>');

//301代表待评价，第一阶段没有评价功能
$paytypearr = array('transfer'=>'银行转账','online'=>'在线支付','cod'=>'货到付款','mts'=>'款到发货');
$wuliuarr = array('202','301','302');
$currency = array('RMB'=>'￥','USD'=>'$','HKD'=>'HK$');
$deliveryArr = array('HK'=>'香港','SZ'=>'国内');
$type = array('spot'=>'现货','order'=>'订货');
?>
<link rel="stylesheet" type="text/css" href="/css/default/myself.css"/>
<link href="/js/jsplug/persontooltip/popup.css" media="all" rel="stylesheet" type="text/css"/>
<script src="/js/jsplug/persontooltip/popup.js" type="text/javascript"></script>

<div class="w">
    <div class="breadcrumbs">		
    	<span><?=$this->translate('Menu_CurrentPosition')?></span><a href="/" ><?=$this->translate('Menu_Home');?></a>&nbsp;&nbsp;»&nbsp;&nbsp;<a href="/center" ><?=$this->translate('Menu_Center')?></a>&nbsp;&nbsp;»&nbsp;&nbsp;<a href="/center/order" ><?=$this->translate('Menu_MyOrder')?></a>&nbsp;&nbsp;»&nbsp;&nbsp;<span>询价订单</span>        
    </div>
</div>

<div class="blank10"></div>
<div class="w clearfix ">
       <!--左边导航-->
        <?php echo $this->render('center/leftmenu.phtml');?>
		<div class="fr u_right msg24">
         <div class="<?php if(isset($_SESSION['postsess']['code'])){if($_SESSION['postsess']['code']>0) echo "error";else echo "ok";}?>" id="message"> <?php if(isset($_SESSION['postsess']['message'])) {echo $_SESSION['postsess']['message'];unset($_SESSION['postsess']);}?></div>
    <div class="Switching w_100" >
    	<ul>
        	<li><a href="/center/order">在线订单(<?=$this->onlineSoNum?>)</a><em class="emtrianglebottom5px"></em></li>
            <li class="on"><a href="/center/inqorder">询价订单(<?=$this->inqSoNum?>)</a><em class="emtrianglebottom5px"></em></li>
        </ul>
     </div>
     <div class="tiporder fontorange">注意：银行转账订单请您在<b class="fontred">48小时</b>之内转账、在线支付订单请您在<b class="fontred">24小时</b>之内支付，否则订单可能会被取消。</div>
     
     <div class="col_main" id="onlineorder">
            <h1 style=" display:none">询价订单</h1>
            <div class="order_tab_head">
                <ul>
                   <li <?php if($this->type=='') echo 'class="on"';?>><a href="/center/inqorder">全部订单<em>(<?=$this->allnum?>)</em><b class="blank3"></b></a></li>
          <li <?php if($this->type=='wpay') echo 'class="on"';?>><a href="/center/inqorder?type=wpay">待付款<em>(<?=$this->wpaynum?>)</em><b class="blank3"></b></a></li>
          <li <?php if($this->type=='proc') echo 'class="on"';?>><a href="/center/inqorder?type=proc">处理中<em>(<?=$this->procnum?>)</em><b class="blank3"></b></a></li>
          <li <?php if($this->type=='over') echo 'class="on"';?>><a href="/center/inqorder?type=over">待付余款<em>(<?=$this->overnum?>)</em><b class="blank3"></b></a></li>
          <li <?php if($this->type=='send') echo 'class="on"';?>><a href="/center/inqorder?type=send">待发货<em>(<?=$this->sendnum?>)</em><b class="blank3"></b></a></li>
          <li <?php if($this->type=='rec') echo 'class="on"';?>><a href="/center/inqorder?type=rec">待收货<em>(<?=$this->recnum?>)</em><b class="blank3"></b></a></li>
          <li <?php if($this->type=='eva') echo 'class="on"';?>><a href="/center/inqorder?type=eva">已完成<em>(<?=$this->evanum?>)</em><b class="blank3"></b></a></li>
          <li <?php if($this->type=='can') echo 'class="on"';?>><a href="/center/inqorder?type=can">已取消<em>(<?=$this->cannum?>)</em><b class="blank3"></b></a></li>
          <li <?php if($this->type=='not') echo 'class="on"';?>><a href="/center/inqorder?type=not">审核未通过<em>(<?=$this->notnum?>)</em><b class="blank3"></b></a></li>
                </ul>
            </div>
            <div class="table_box order" >
            <?php  if(empty($this->salesorder)){?>
             	<div class="nodata">暂无记录</div> 
            <?php }else{
				 foreach($this->salesorder as $k=>$sodata){
				 $zindx = 800 - $k;
 			?>
                <div class="A_order" style="z-index:<?=$zindx?>">
                    <div class="numberbox">
                    	<em class="emtrianglebottom5px"></em>
                        <p>订单号：<a href="/inquiryorder/view?salesnumber=<?=$sodata['salesnumber']?>" title="查看订单详细" target="_blank" class="number"><?=$sodata['salesnumber']?></a><span class="time">下单时间：<?=date('Y-m-d H:i:s',$sodata['created'])?></span></p>  									                                
                        
               <div class="orderbtn">
               <?php if($sodata['status']=='401'  && $sodata['back_status']!=102 ){?>
              <!--<a href="javascript:" onclick="resOrder('<?=$sodata['id']?>','<?=$sodata['salesnumber']?>')"  class="fontGray">恢复订单</a>-->
              <?php }elseif($sodata['status']==101  && $sodata['back_status']!=102 && empty($sodata['receipt'])){?>
              <a href="javascript:" onclick="canOrder('<?=$sodata['id']?>','<?=$sodata['salesnumber']?>')" title="取消订单" class="fontGray">取消订单</a>
              <?php }?>
              
              <?php if($sodata['ufid']){?>
              <?php if($sodata['total']==$sodata['down_payment']){?>
              <a href="/upload/default/pi/<?=md5('down'.$sodata['salesnumber'])?>.pdf" target="_blank" title="查看订单PI" class="button">订单PI</a>
              <?php }else{?>
                <a href="/upload/default/pi/<?=md5('down'.$sodata['salesnumber'])?>.pdf" target="_blank" title="查看预付款PI" class="button">预付款PI</a>
                <a href="/upload/default/pi/<?=md5('surplus'.$sodata['salesnumber'])?>.pdf" target="_blank" title="查看余款PI" class="button">余款PI</a>
              <?php }?>
              <?php }?>
              
              <?php echo '<a href="/inquiryorder/orderinqpdf?pdfkey='.md5(session_id()).'&part='.$this->fun->encryptVerification($sodata['salesnumber']).'" target="_blank" class="button" title="查看报价单">报价单</a>';?>
              
                <?php if(!in_array($sodata['status'],array(401,501,502)) && $sodata['back_status']!=102){?>
               
                 <?php if($sodata['paper_contract']){?>
                <a href="<?php echo $this->url(array('controller'=>'inquiryorder', 'action'=>'iccontract', 'key'=>md5(session_id()),'item'=>$this->fun->encryptVerification($sodata['salesnumber'])))?>" target="_blank" title="查看合同"  class="button">合同</a>
                <?php }else{?>
                <a href="<?php echo $this->url(array('controller'=>'inquiryorder', 'action'=>'digitalcontract', 'key'=>md5(session_id()),'item'=>$this->fun->encryptVerification($sodata['salesnumber'])))?>" target="_blank" title="查看合同" class="button">合同</a>
                <?php }?>

                <?php }?>
                
				<?php if(($sodata['status']=='101' || $sodata['status']=='103') && $sodata['back_status']!=102){?>
                
                <?php if($sodata['paytype']=='online'){?>
                <a href="/payment/orderpay?salesnumber=<?=$sodata['salesnumber']?>" class="button"  title="去付款" target="_blank">立即支付</a>
                <?php }elseif($sodata['paytype']=='transfer'){?>
			   
				
                <?php if($sodata['status']=='101' && $sodata['back_status']!=102){//首付?>
                <a href="javascript:" onclick="transfer('<?=$sodata['salesnumber']?>')" class="button"> 
				<?php if(!empty($sodata['receipt']) && file_exists(UP_RECEIPT.$sodata['receipt'])) echo '重传转账凭证'; else echo '上传转账凭证';?></a>
                <?php }else{//余款?>
                <a href="javascript:" onclick="transfer2('<?=$sodata['salesnumber']?>')" class="button"> 
				<?php if(!empty($sodata['receipt_2']) && file_exists(UP_RECEIPT.$sodata['receipt_2'])) echo '重传余款转账凭证'; else echo '上传余款转账凭证';?></a>
                <?php }?>

                <a href="javascript:" rel="<?=$sodata['id']?>,<?=$sodata['salesnumber']?>" rev="/inquiryorder/transfer" title="转账信息" class="button personPopupTrigger" >转账信息</a>
                  <div class="bubblebox transfer" id="personPopupContainer<?=$sodata['id']?>" style="display:none">
                         <div class="uparrow"></div>
                         <div class="popbox">
                              <div id="personPopupContent<?=$sodata['id']?>"></div>
                         </div>
                  </div>
                  
                  
			  <?php }
			   }?>
               
               <?php if(in_array($sodata['status'],array('102')) && $sodata['back_status']!=102 && $sodata['paytype']=='transfer'){ ?>
                <a href="javascript:" onclick="transfer('<?=$sodata['salesnumber']?>')" class="button"> 
				<?php if(!empty($sodata['receipt']) && file_exists(UP_RECEIPT.$sodata['receipt'])) echo '重传转账凭证'; else echo '上传转账凭证';?></a>
                <?php }?>
                
                <?php if(in_array($sodata['status'],array('201')) && $sodata['back_status']!=102 && $sodata['paytype']=='transfer' && $sodata['total'] != $sodata['down_payment']){?>
                <a href="javascript:" onclick="transfer2('<?=$sodata['salesnumber']?>')" class="button"> 
				<?php if(!empty($sodata['receipt']) && file_exists(UP_RECEIPT.$sodata['receipt'])) echo '重传余款转账凭证'; else echo '上传余款转账凭证';?></a>
                <?php }?>
                
               
                <?php if(in_array($sodata['status'],array('102','103','201','202')) && $sodata['back_status']==202){?>
                <span id="receiptbot"><a href="javascript:" onclick="receipt('<?=$sodata['id']?>','<?=$sodata['salesnumber']?>')" class="button">确认收货</a></span>
                <?php }?>
                <?php 
                 if(in_array($sodata['status'],$wuliuarr)){?>
                <!--<span style="position:relative">--> 
                <a href="javascript:" rel="<?=$sodata['id']?>,<?=$sodata['salesnumber']?>" rev="/inquiryorder/courier" title="查看物流" class="button personPopupTrigger" >查看物流</a>
                  <div class="bubblebox transfer" id="personPopupContainer<?=$sodata['id']?>" style="display:none">
                         <div class="uparrow"></div>
                         <div class="popbox">
                              <div id="personPopupContent<?=$sodata['id']?>"></div>
                         </div>
                  </div>
                <!--</span>-->
                <?php }?>
                        </div>	
                     </div>
                    <table class="vac_table table" cellpadding="0" cellspacing="0">   
                        <thead>    
                            <tr>            
                                <th width="18%">订单商品</th>
                                <th width="8%">交货地</th>
                                <!--<th width="10%">货物情况</th>-->
                                <th width="11%">需求日期</th>
                                <th width="10%">预计交期</th>                        
                                <th width="8%">币种</th>
                                <th width="16%">订单金额</th>
                                <th width="10%">支付类型</th>
                                <th width="8%">订单状态<?php if($sodata['back_status']==102  || in_array($sodata['status'],array(501,502))){
				 if($sodata['admin_notes']){?>
          						<a href="javascript:" class="tipa desshow"><?=$this->fun->utf_substr($result_remark,20)?>
                                <b class="tipicon"></b>
                                    <div class="bubblebox heiauto " style="width:200px;">
                                        <div class="uparrow"></div>
                                        <div class="popbox">
                                           <div class="popcon clearfix" style="text-align:left; width:190px;">
                                               <p><?php echo $sodata['admin_notes'];?></p>
                                            </div>
                                        </div>
                                    </div>	
                                </a>
                <?php } 
				}?></th>
                            </tr>   
                        </thead>            
                        <tbody>  
                            <tr>
                              <td class="modeltable" align="center">
                              <?php foreach($sodata['prodarr'] as $pid=>$partarr){?><p class="model"><?=$partarr['part_no']?></p><?php }?>
                              </td>
                              <td><?=$deliveryArr[$sodata['delivery_place']]?></td>
                             <!-- <td><?=$type[$sodata['shipments']]?></td>-->
                              <td><?=$sodata['needs_time']==0?'':date('Y-m-d',$sodata['needs_time'])?></td>
			  <td class="centerp"><p class="time"><?=$sodata['delivery_time']==0?'':date('Y-m-d',$sodata['delivery_time'])?></p>
              <p>
              <?php
			  if($sodata['delivery_status']>0 && $sodata['back_status']!=102){?>
                    <?php if($sodata['delivery_status']==101) echo '<span style="color:#FF8920" title="申请更改的交货期：'.date("Y-m-d",$sodata['delivery_change_date']).'">申请审批中</span>';
						elseif($sodata['delivery_status']==201) echo '<span  style="color:#009944" title="原来交期：'.date("Y-m-d",$sodata['delivery_time_back']).'">申请通过</span>';
						elseif($sodata['delivery_status']==301) echo '<span  style="color:#FF0000" title="申请更改的交货期：'.date("Y-m-d",$sodata['delivery_change_date']).'">申请不通过</span>';
				}
		     ?></p>
              </td>
                              <td class="en"><strong><?=$sodata['currency']?></strong></td> 
                              <td class="centerp">
                                <?php if($sodata['total']==$sodata['down_payment']){?>
                                <span style="color:#CC0000; font-weight:bold"><?=$currency[$sodata['currency']].number_format($sodata['total'],DECIMAL)?></span>
                                <?php }else{?>
                               总&nbsp;&nbsp;&nbsp;计：<span style="color:#CC0000; font-weight:bold"><?=$currency[$sodata['currency']].number_format($sodata['total'],DECIMAL)?></span><br/>预付款：<span style="color:#CC0000; font-weight:bold"><?=$currency[$sodata['currency']].number_format($sodata['down_payment'],DECIMAL)?></span><br/>剩余款：<span style="color:#CC0000; font-weight:bold"><?=$currency[$sodata['currency']].number_format($sodata['total'] - $sodata['down_payment'],DECIMAL)?></span>
                 <?php }?>
                              </td>
                              <td><?=$paytypearr[$sodata['paytype']];?></td>                  
                              <td>
                  <div class="inquiry_status">
				  <?php if($sodata['back_status']!=102){
				    if(in_array($sodata['paytype'],array('transfer','online')))
			       		echo $statusarr[$sodata['status']];
			      	 else echo $codarr[$sodata['status']];
				   }else echo '<p class="gray_no">审核不通过</p>';?>
                   </div>
                   </td>
                            </tr>  
                        </tbody>         
                        </table>                              
                </div> <?php }}?>                          
              
             </div>
            <div class="pagination fr"><?=$this->page_bar;?></div>
        </div>
      </div>
</div>
<div class="clr"></div>
<script src="/js/jsplug/My97DatePicker/WdatePicker.js" type="text/javascript"></script>
<script type="text/javascript" src="/js/jsplug/AjaxFileUploader/ajaxfileupload.js"></script>
<script type="text/javascript">
//取消订单
function canOrder(id,salesnumber){

	$.ajax({
            url: '/inquiryorder/cancel',
            data: {'id':id,'salesnumber':salesnumber},
            type: 'post',
            dataType: 'json',
            success: function(arr) {
            	if(arr.code == 0)
                {
                    location.reload();
                }else{
				    alert(arr.message);
				}
            }
	 });

}
//恢复订单
function resOrder(id,salesnumber){
	$.ajax({
            url: '/inquiryorder/restoration',
            data: {'id':id,'salesnumber':salesnumber},
            type: 'post',
            dataType: 'json',
            success: function(arr) {
            	if(arr.code == 0)
                {
                    location.reload();
                }else{
				    alert(arr.message);
				}
            }
	});
}
//删除订单
function delOrder(id,salesnumber){
if(confirm('你确定删除订单：'+salesnumber+'？'))
 {
	$.ajax({
            url: '/inquiryorder/delete',
            data: {'id':id,'salesnumber':salesnumber},
            type: 'post',
            dataType: 'json',
            success: function(arr) {
            	if(arr.code == 0)
                {
                    location.reload();
                }else{
				    alert(arr.message);
				}
            }
	});
  }
}
//确认收货
function receipt(id,salesnumber){
if(confirm('你确定订单：'+salesnumber+'已经收货？'))
 {
 	$("#receiptbot").html('<a href="javascript:" class="button">确认中...</a>');
	$.ajax({
            url: '/inquiryorder/receipt',
            data: {'id':id,'salesnumber':salesnumber},
            type: 'post',
            dataType: 'json',
            success: function(arr) {
            	if(arr.code == 0)
                {
                    location.reload();
                }else{
				    alert(arr.message);
					$("#receiptbot").html('<a href="javascript:" onclick="receipt(\''+id+'\',\''+salesnumber+'\')" class="button">确认收货</a>');
				}
            }
	});
 }
}
//上传回执单
function transfer(salesnumber){
	$.openPopupLayer({
		name: "transferBox",
		url: "/center/transfer?salesnumber="+salesnumber+'&ordertype=inq'
	});
}
//上传余款回执单
function transfer2(salesnumber){
	$.openPopupLayer({
		name: "transferBox",
		url: "/center/transfer2?salesnumber="+salesnumber+'&ordertype=inq'
	});
}
//交货期申请
function deliverychange(salesnumber)
{
	 $.openPopupLayer({
		name: "deliverychangeBox",
		url: "/inquiryorder/deliverychange?salesnumber="+salesnumber
	});
}
setTimeout('hidMessage()',3000);
function hidMessage(){
	document.getElementById("message").style.display = 'none';
}
</script>
