<div class="conmian">
  <h1><a href="<?=$this->indexurl?>"><?php echo $this->AreaTitle;?></a> -> 注册OA客户审核</h1>
  <div class="contentmia">
    <?php if (isset($_SESSION['messages'])) : ?><div class="alert fade in">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <p class="message"><strong><?php echo $_SESSION['messages'];unset($_SESSION['messages']);?></strong></p></div><?php endif; ?> 
    <table width="100%" cellpadding="1" border="1" class="producttable table">
      <thead>
        <tr>
          <th>用户名</th>
          <th>公司名称</th>
          <th>申请人</th>
          <th>备注</th>
          <th>申请时间</th>
          <th>审批人</th>
           <th>审批时间</th>
          <th>审批说明</th>
          <th>操作</th>
        </tr>
      </thead>
      <tbody>
        <?php
			  	  if(!empty($this->user)){
                	 foreach ($this->user as $k=>$data){
						echo "<tr>";
						echo "<td>".$data['uname']."</td>";
						echo "<td>".$data['client_cname']."</td>";
						echo "<td>".$data['lastname'].$data['firstname']."</td>";	
						echo "<td>".$data['remark']."</td>";
						echo "<td>".date("Y-m-d H:i",$data['created'])."</td>";
						echo "<td>".$data['applastname'].$data['appfirstname']."</td>";
						echo "<td>".($data['modified']?date("Y-m-d H:i",$data['modified']):'--')."</td>";
						echo "<td>".$data['result_remark']."</td>";
						echo '<td>';
						if($data['status']==100 && $data['approval_staffid']==$_SESSION['staff_sess']['staff_id']) 
						   echo '<a href="/icwebadmin/UsUsgl/appview/uid/'.$data['uid'].'">审核</a>';
						elseif($data['status']==100) echo '待审核'.' | <a href="/icwebadmin/UsUsgl/appview/uid/'.$data['uid'].'">查看</a>';
						elseif($data['status']==101){
						    echo '<font color="#006600">通过</font>'.' | <a href="/icwebadmin/UsUsgl/appview/uid/'.$data['uid'].'">查看</a>';
						}elseif($data['status']==102){ 
						  echo '<font color="#FF0000">不通过</font>'.' | <a href="/icwebadmin/UsUsgl/appview/uid/'.$data['uid'].'">查看</a>';
						   if($data['apply_staffid']==$_SESSION['staff_sess']['staff_id']){
						       echo ' | <a href="/icwebadmin/UsUsgl/application/uid/'.$data['uid'].'" class="colorbox">再申请</a>';
						   }
						}
						echo '</td>';
					    echo "</tr>";
				    }
				   }
	            ?>
      </tbody>
    </table>
    <div class="pagination">
      <?=$this->page_bar;?>
    </div>
  </div>
</div>
<script type="text/javascript">
function appview(uid){
    $.openPopupLayer({
        name:'appviewBox',
        url:'/icwebadmin/UsUsgl/appview/uid/'+uid
    });
}
</script>
