<?php 
$property_tmp = array('enduser'=>'终端用户','merchant'=>'贸易商');
$annexur_part = COM_ANNEX.$this->user['uid'].'/';
$annexurl = $annexur_part.$this->user['annex1'];
$annexurl2= $annexur_part.$this->user['annex2'];
$annexurl_a = $annexurl2_a = '--';
if(file_exists($annexurl) && $this->user['annex1']){
  $annexurl_a = '<a href="/'.$annexurl.'" target="_blank" title="查看">查看&gt;&gt;</a>';
}
if(file_exists($annexurl2) && $this->user['annex2']){
  $annexurl2_a = '<a href="/'.$annexurl2.'" target="_blank" title="查看">查看&gt;&gt;</a>';
}  ?>

<div class="conmian">
  <h1><a href="<?=$this->indexurl?>" title="返回"><?php echo $this->AreaTitle;?></a> ->
    <?=$this->user['companyname']?>
    -> 添加新账号</h1>
    <?php if ($this->messages) : ?>
<div class="alert alert-error">
     <button type="button" class="close" data-dismiss="alert">×</button>
    <strong><?php echo ($this->messages); ?></strong>
 </div>
<?php endif; ?>  

  <div class="popup-body" style="width:800px;">
      <div class="publicOne">
      <div class="Publictit"> <span class="Publictit_tit">基本信息</span> </div>
        <form id='company' name="company" action='' method='post' enctype="multipart/form-data">
        <input type="hidden" name="father_uid"  value="<?=$this->user['uid']?>"/>
        <table border="0" cellspacing="0" cellpadding="0" class="Publictable" >
          <tr>
            <td  width="100">公司名：</td>
            <td colspan="3"><strong>
              <?=$this->user['companyname']?$this->user['companyname']:'--'?>
              </strong></td>
          </tr>
          <tr>
            <td width="100">公司性质：</td>
            <td ><strong>
              <?=$property_tmp[$this->user['property']]?>
              </strong></td>
            <td width="100">行业领域：</td>
            <td ><strong>
              <?=$this->user['appname']==''?$this->user['personaldesc']:$this->user['appname']?>
              </strong></td>
          </tr>
          <tr>
            <td >营业执照：</td>
            <td ><?=$annexurl_a?></td>
            <td >税务登记证：</td>
            <td ><?=$annexurl2_a?></td>
          </tr>
          <tr>
            <td >常用货币：</td>
            <td ><strong>
              <?=$this->user['currency']?$this->user['currency']:'--'?>
              </strong></td>
            <td >邮政编码：</td>
            <td ><strong>
              <?=$this->user['zipcode']?>
              </strong></td>
          </tr>
          <tr>
            <td >地址：</td>
            <td colspan="3"><strong>
              <?=$this->fun->createAddress($this->user['province'],$this->user['city'],$this->user['area'],$this->user['address'])?>
              </strong></td>
          </tr>
          <tr><td><em>*</em>用户名：</td>
          <td colspan="3"><input type="text" style="width:200px;" name="uname" id="uname" value="<?=$this->processData['uname']?>"/>
          <span id="unameTip" style="float:right"></span></td></tr>
          <tr><td><em>*</em>Email：</td>
          <td colspan="3"><input type="text" style="width:200px;" name="email" id="email" value="<?=$this->processData['email']?>"/>
          <span id="emailTip" style="float:right"></span></td></tr>
          <tr><td><em>*</em>联系人：</td>
          <td colspan="3"><input type="text" style="width:200px;" name="contact" id="contact" value="<?=$this->processData['contact']?>"/>
          <span id="contactTip" style="float:right"></span></td></tr>
          <tr >
          <td class="tableti"><em>*</em>部门：</td>
          <td colspan="3"><select name="department_id" id="department_id">
                  <?php foreach($this->office as $v){?>
                  <option value="<?=$v['id']?>" <?=$this->myinfo['department_id']==$v['id']?'selected':'';?>><?=$v['department']?></option>
                  <?php }?>
             </select></td>
        </tr>
          <tr><td>手机：</td>
          <td colspan="3"><input type="text" style="width:200px;" name="mobile" id="mobile" value="<?=$this->processData['mobile']?>"/></td></tr>
          <tr><td>固定电话：</td>
          <td colspan="3"><input type="text" style="width:200px;" name="tel" id="tel" value="<?=$this->processData['tel']?>"/></td></tr>
          <tr><td>传真：</td>
          <td colspan="3"><input type="text" style="width:200px;" name="fax" id="fax" value="<?=$this->processData['fax']?>"/></td></tr>
          <td colspan="4" align="center"> <input type="submit" value="添 加" class="btnabig"></td></tr>
        </table>
        </form>
        </div>
  </div>
</div>
<script src="/js/jsplug/formcheck/formValidator-4.1.1.js" type="text/javascript"></script>
<script src="/js/jsplug/formcheck/formValidatorRegex.js" type="text/javascript"></script>
<script type="text/javascript">
 $(document).ready(function(){ 
        $.formValidator.initConfig({formID:"company",onSuccess:function(){submit();}});
        $("#uname").formValidator({onFocus:"请输入用户名，可以用于登录",onCorrect:"&nbsp;"}).inputValidator({min:3,empty:{leftEmpty:false,rightEmpty:false,emptyError:"不能有空符号"},onError:"不能为空，请输入用户名"});
		$("#email").formValidator({onFocus:"请输入Email，可以用于登录",onCorrect:"&nbsp;"}).inputValidator({min:6,max:100,onError:"请输入正确的Email"}).regexValidator({regExp:"^([\\w-.]+)@(([[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}.)|(([\\w-]+.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(]?)$",onError:"你输入的Email格式不正确"});
		$("#contact").formValidator({onFocus:"请输入联系人姓名",onCorrect:"&nbsp;"}).inputValidator({min:3,empty:{leftEmpty:false,rightEmpty:false,emptyError:"不能有空符号"},onError:"不能为空，联系人姓名"});
	})
</script>