<?php 
$property_tmp = array('enduser'=>'终端用户','merchant'=>'贸易商');
$annexur_part = COM_ANNEX.$this->user['uid'].'/';
$annexurl = $annexur_part.$this->user['annex1'];
$annexurl2= $annexur_part.$this->user['annex2'];
$annexurl_a = $annexurl2_a = '未上传';
if(file_exists($annexurl) && $this->user['annex1']){
  $annexurl_a = '<a href="/'.$annexurl.'" target="_blank" title="查看">查看&gt;&gt;</a>';
}
if(file_exists($annexurl2) && $this->user['annex2']){
  $annexurl2_a = '<a href="/'.$annexurl2.'" target="_blank" title="查看">查看&gt;&gt;</a>';
}  ?>
<div class="popup" style="width:800px; margin:10px 100px">
<div class="popup-header">
    <h2>用户资料</h2>
    <a href="javascript:;" onclick="$.closePopupLayer('viewBox');" title="关闭" class="dialogBoxClose">关闭</a> 
</div>
<div class="popup-body">
<!--客户信息-->
<div class="publicOne">
    <div class="Publictit">
        <span class="Publictit_tit">客户信息</span>
    </div>
    <table border="0" cellspacing="0" cellpadding="0" class="Publictable" >
            <tr>
              <td  width="100">用户名：</td>
              <td ><strong><?=$this->user['uname']?></strong></td>
              
              <td  width="100">公司名：</td>
              <td ><strong><?=$this->user['companyname']?$this->user['companyname']:'--'?></strong></td>
            </tr>
            <tr>
              <td >公司性质：</td>
              <td ><strong><?=$property_tmp[$this->user['property']]?></strong></td>
              <td >行业领域：</td>
              <td ><strong><?=$this->user['appname']==''?$this->user['personaldesc']:$this->user['appname']?></strong></td>
            </tr>
            <tr >
              <td >联系人：</td>
              <td ><strong><?=$this->user['truename']?$this->user['truename']:'--'?></strong></td>
              <td>部门</td>
               <td ><strong><?=$this->user['department']?$this->user['department']:'--'?></strong></td>
              
            </tr>
            <tr >
              <td >联系电话：</td>
              <td ><strong><?=$this->user['tel']?$this->user['tel']:'--'?></strong></td>
              <td >手机：</td>
              <td ><strong><?=$this->user['mobile']?$this->user['mobile']:'--'?></strong></td>
              
            </tr>
            <tr>
              <td >Email：</td>
              <td ><strong><a href="mailto:<?=$this->user['email']?>"><?=$this->user['email']?></a></strong></td>
              <td >传真：</td>
              <td ><strong><?=$this->user['fax']?$this->user['fax']:'--'?></strong></td>
            </tr>
            <tr>
              <td >常用货币：</td>
              <td ><strong><?=$this->user['currency']?$this->user['currency']:'--'?></strong></td>
              <td >邮编：</td>
              <td ><strong><?=$this->user['zipcode']?$this->user['zipcode']:'--'?></strong></td>
            </tr>
            <tr>
              <td >营业执照：</td>
              <td ><?=$annexurl_a?></td>
              <td >税务登记证：</td>
              <td ><?=$annexurl2_a?></td>
            </tr>
            
            <tr >
              <td >注册时间：</td>
              <td ><strong><?=date("Y-m-d H:i:s",$this->user['utime'])?></strong></td>
              <td >注册IP：</td>
              <td ><strong><?=$this->user['ip']?></strong></td>
              
            </tr>
            <tr >
              <td >最后登录时间：</td>
              <td ><strong><?=date("Y-m-d H:i:s",$this->user['lasttime'])?></strong></td>
              <td >最后登录IP：</td>
              <td ><strong><?=$this->user['lastip']?></strong></td>
            </tr>
            <tr>
              <td >地址：</td>
              <td colspan="3"><strong><?=$this->fun->createAddress($this->user['province'],$this->user['city'],$this->user['area'],$this->user['address'])?></strong></td>
            </tr>
      </table>
</div>
<!--询价统计-->
<div class="publicOne">
    <div class="Publictit">
        <span class="Publictit_tit">询价统计</span>
    </div>
    <!-- ，0被删除，1等待回复，2已报价，3议价审核中，4审核不通过，5已经下单等处理，6成功下单-->  
      <table border="0" cellspacing="0" cellpadding="0" class="tablelistPrice tablexunjia" >
            <tr>
              <th>删除</th>
              <th>等待回复</th>
              <th>已报价</th>
              <th>议价审核中</th>
              <th>审核不通过</th>
              <th>已经下单等处理</th>
              <th>成功下单</th>
              <th>总计</th>
            </tr>
            <tr >
              <?php 
		  	$inqtotal = 0;
		  for($i=0;$i<count($this->inqre);$i++){
		  			$inqtotal +=$this->inqre[$i];
		  			 echo '<td>'.$this->inqre[$i].'</td>';
			}?>
            <td><?=$inqtotal?></td>
            </tr>
      </table>
      <!--/**
	 * 用户询价订单统计
	 * 括号的代表是cod状态 101待付预付款（cod:等待审核） 102 需要订货，订单处理中(转账:已支付预付款) 
	 * 103已经订货并返回交货期（转账:等待付剩余货款）
	 * 201待发货（转账:已付剩余货款） 202已发货,待确认收货 
	 * 301已确认收货,待评价 302已确认收货 401客户取消订单
	 */--> 
</div>

<!--询价订单统计-->
<div class="publicOne">
    <div class="Publictit">
        <span class="Publictit_tit">询价订单统计</span>
    </div>
      <table border="0" cellspacing="0" cellpadding="0" class="tablelistPrice tablexunjia" >
            <tr>
              <th>审核不通过</th>
              <th>待付预付款</th>
              <th>订单处理中</th>
              <th>等待付剩余货款</th>
              <th>待发货</th>
              <th>已发货</th>
              <th>已确认收货</th>
              <th>已评价</th>
              <th>客户取消订单</th>
              <th>总计</th>
            </tr>
            <tr >
               <?php $inqsototal = 0;for($i=0;$i<count($this->inqsore);$i++){
		          $inqsototal +=$this->inqsore[$i];
		  		  echo '<td>'.$this->inqsore[$i].'</td>';
				 }?>
            <td><?=$inqsototal?></td>
            </tr>
      </table><!--101待付款201已付款待发货202已配送,待确认收货301已确认收货,待评价302已确认收货,已评价401客户取消订单单-->     
</div>

<!--在线订单统计-->
<div class="publicOne">
    <div class="Publictit">
        <span class="Publictit_tit">在线订单统计</span>
    </div>
      <table border="0" cellspacing="0" cellpadding="0" class="tablelistPrice tablexunjia" >
            <tr>
              <th>审核不通过</th>
              <th>待付预付款</th>
              <th>待发货</th>
              <th>已发货</th>
              <th>已确认收货</th>
              <th>已评价</th>
              <th>客户取消订单</th>
              <th>总计</th>
            </tr>
            <tr >
              <?php $sototal = 0;for($i=0;$i<count($this->sore);$i++){
		          $sototal +=$this->sore[$i];
		  		  echo '<td>'.$this->sore[$i].'</td>';
				 }?>
            <td><?=$sototal?></td>
            </tr>
      </table>
</div>

</div>
</div>