
<div class="conmian">
  <h1><?php echo $this->AreaTitle;?></h1>

  <div class="fr u_right">
    <div class="tab_content">
    	<div class="tab_tit1">
        <ul class="fl">
          <li <?=$this->type=='wait'?'class="on"':''?>><a href="?type=wait" style="width:120px;">待处理<em>(<?=$this->waittotal?>)</em><b class="blank3"></b></a></li>
          <li <?=$this->type=='pass'?'class="on"':''?>><a href="?type=pass" style="width:120px;">处理中<em>(<?=$this->passtotal?>)</em><b class="blank3"></b></a></li>
          <li <?=$this->type=='com'?'class="on"':''?>><a href="?type=com" style="width:120px;">已完成<em>(<?=$this->comtotal?>)</em><b class="blank3"></b></a></li>
          <li <?=$this->type=='notpass'?'class="on"':''?>><a href="?type=notpass" style="width:120px;">不通过<em>(<?=$this->notpasstotal?>)</em><b class="blank3"></b></a></li>
        </ul>
        </div>
    </div>
    <div class="tab_con ">
        <table class="tableanew" border="0" cellspacing="0" cellpadding="0"  width="100%"  >
                <thead>    
                    <tr>
                        <th width="300px;">申请客户</th>
                        <th>来访情况</th>
                        <th width="160">实验器材</th>

                        <th width="200">项目信息</th>
                        
                        
                        <?php if($this->type=='pass' || $this->type=='com'){?>
                        <th width="200">协助人</th>
                        <?php }?>
                        
                        <th>审批情况</th>
  
                        <th>操作</th>
                    </tr>   
                </thead>            
                <tbody>  
            <?php if(empty($this->applyall)){echo '<tr><td colspan="11">暂无记录</td></tr>';}
		  	else{
				foreach($this->applyall as $key=>$data){
				$bg='';
				if($key%2==1) $bg = '#F1EEFD';
		    ?>
			  <tr bgcolor="<?=$bg?>">
                <td align="left"><a href="javascript:;" onclick="viewUser('<?=$data['uid']?>')" title="查看详细资料" ><?=($data['companyname']?$data['companyname']:$data['uname'])?></a><br/>
                <table>
                <tr><td>老客户：</td><td><?=$data['customer']==1?'不是':'是('.$data['follow'].')';?></td></tr>
                <tr><td width="60">公司名称:</td><td><?=$data['company'];?></td></tr>
                <tr><td>地址：</td><td><?=$data['address'];?></td></tr>
                <tr><td>联络人：</td><td><?=$data['contact'];?></td></tr>
                <tr><td>电话：</td><td><?=$data['phone'];?></td></tr>
                <tr><td>邮箱：</td><td><?=$data['email'];?></td></tr>
                <tr><td>申请时间:</td><td><?=date('Y-m-d H:i',$data['created'])?></td></tr>
                
               </table>
                </td>

                <td align="left">来访地点：<?=$data['city'];?>
                <br/>
                来访时间：<?=$data['vist_time'];?><br/>
				来访人数：<?=$data['vist_number'];?><br/>
                <?php if($this->type=='com'){?>
                     测试报告：<table><tr><td width="70">测试情况:</td><td><?=$data['test_case'];?></td></tr>
                <tr><td>后续安排：</td><td><?=$data['followup'];?></td></tr>
                <tr><td>后续意愿：</td><td><?=$data['wish'];?></td></tr>
               </table>
               <?php }?>
                </td>
                
                <td align="left"><table><?php 
				  $showarr = array();
				  foreach($this->instrument as $v){ 
					 foreach($this->room as $rid=>$rname){
					 	if($v['room']==$rid && in_array($v['id'],explode(',',$data['instruments']))) $showarr[$rname][] = $v['ins_name'].($v['model']?'('.$v['model'].')':'');
					 }
				} 
				foreach($showarr as $rname=>$arr){
				   echo "<tr><th>$rname:</th></tr>";
				   foreach($arr as $n){
				   	  echo "<tr><td>$n ;</td></tr>";
				   }
				}?></table></td>
                <td>
                <table><tr><td width="70">项目名称:</td><td><?=$data['project_name'];?></td></tr>
                <tr><td>主要器件：</td><td><?php if($data['project_device']){
					$arr = explode('|',$data['project_device']);
					foreach($arr as $v) echo $v.'<br/>';
				}?></td></tr>
                <tr><td>项目简介：</td><td><?=$data['project_des']?$data['project_des']:'--';?></td></tr>
                <tr><td>量产时间：</td><td><?=$data['expected_time']?$data['expected_time']:'--';?></td></tr>
                <tr><td>BOM单：</td><td><?php if($data['project_bom']){?><a href="<?=$data['project_bom'];?>" target="_blank">下载</a><?php }?></td></tr>
                <tr><td>项目框图：</td><td><?php if($data['project_images']){?><a href="<?=$data['project_images'];?>" target="_blank">下载</a><?php }?></td></tr></table>
                </td>

                <?php if($this->type=='pass' || $this->type=='com'){?>
                    <td><table><tr><td width="70">协助人:</td><td><?=$data['help_name'];?></td></tr>
                <tr><td>部门：</td><td><?=$data['help_dep'];?></td></tr>
                <tr><td>电话：</td><td><?=$data['help_tel'];?></td></tr>
                <tr><td>邮箱：</td><td><?=$data['help_email'];?></td></tr>
                <tr><td>报告：</td><td><span title="<?=$data['followremark'];?>"><?=$data['followremark']?'查看':'--';?></span></td></tr>
               </table></td>
                <?php }?>
                
                <td align="left">时间：<br/><?=$data['status']>100?($data['modify']?date('Y-m-d H:i',$data['modify']):'--'):'--';?><br/>
				备注：<?=$data['remark']?$data['remark']:'--';?></td>
				<td><?php if($this->type=='wait'){?>
                <div style="margin-top:2px"><a href="javascript:" onclick="openbox('<?=$data['id']?>')" class="gbqfb">审批</a></div>
                <?php }else{?>
                <div style="margin-top:2px"><a href="javascript:" onclick="openbox2('<?=$data['id']?>')" class="gbqfb">填写报告</a></div>
                <?php }?>
                </td> 
              </tr>
		    <?php		
				}
			}
		    ?>
                </tbody>         
                </table>
    <div class="pagination divpage">
       <?=$this->page_bar;?>
  </div>
</div>

</div>


<link href="/js/jsplug/ajaxselect/jquery.autocomplete.css" rel="stylesheet">
<script src="/js/jsplug/ajaxselect/jquery.autocomplete.js" type="text/javascript"></script>
<script src="/js/jsplug/My97DatePicker/WdatePicker.js" type="text/javascript"></script>
<script type="text/javascript">
function openbox(id){
		$.openPopupLayer({
			name: "box",
			url: "/icwebadmin/OlabAppl/approval?id="+id
		});
	}
function openbox2(id){
		$.openPopupLayer({
			name: "box",
			url: "/icwebadmin/OlabAppl/report?id="+id
		});
	}
</script>
