<div class="popup" style="width:600px;margin:10px 100px" >
    <div class="popup-header">
        <h2>请填写报价跟进：</h2>
        <a href="javascript:;" onclick="$.closePopupLayer('box')" title="关闭" class="dialogBoxClose">关闭</a>
    </div>
    <div class="popup-body">
    <table  cellpadding="0" border="0" cellspacing="0">
    <tbody>
    <?php foreach($this->reasonlog as $reasonlog){?>
    <tr>
    <td valign="top" align="right" style="font-weight:bold"><?=date("Y/m/d H:i",$reasonlog['created'])?>&nbsp;</td>
    <td><?=nl2br($reasonlog['description'])?>
    </td>
    </tr>
    <?php }?>
    <tr>
    <td  valign="top" align="right"><em>*</em>报价跟进：</td>
    <td><textarea name="reason" id="reason" rows="3" style="width:350px;"></textarea>
    </td>
    </tr>
    </tbody></table>
        <div class="pbtn" id="baojiabtn2"><input type="button" onClick="reasonAction()" value="提 交" class="btnabig"></div>
        <div class="clear"></div>
    </div>
</div>
<script type="text/javascript">
function reasonAction() {
	   var reason = document.getElementById('reason').value;
	   if(reason==''){alert('请选择报价跟进');document.getElementById('reason').focus();return;}
	   
	   var subtmp = document.getElementById("baojiabtn2");
	   subtmp.innerHTML = '<input type="button" class="btnabig" value="提交中..."/>';
	   $.ajax({
		url: '/icwebadmin/QuoInq/reason',
		data: {'id':'<?=$this->id;?>','reason':reason},
		type: 'post',
		dataType: 'json',
		success: function(arr) {
		    alert(arr.message);
			if(arr.code == 0){
				  location.reload();
             }
			subtmp.innerHTML = '<input type="button" onClick="reasonAction()" value="提 交" class="btnabig">';
		}
		});
		
}
</script>