<div class="conmian">
  <h1><?php echo $this->AreaTitle;?></h1>
  <div id="message_sess" style="display:none" class="message_sess"> 
          <div title="关闭" class="but" onclick="document.getElementById('message_sess').style.display='none'">&nbsp;</div>
          <div id="alert_message"></div> 
 </div>
	  <!-- 需要填写的区域-->
	<div class="fr u_right">
    <div class="tab_content">
      <div class="tab_tit1">
        <ul class="fl">
          <li><a href="/icwebadmin/ReadHome">滚动图片<b class="blank3"></b></a></li>
          <li><a href="/icwebadmin/ReadHome/newprod">精品 • 新品<b class="blank3"></b></a></li>
          <li><a href="/icwebadmin/ReadHome/actingbrand">代理品牌<b class="blank3"></b></a></li>
          <li class="on"><a href="/icwebadmin/ReadHome/app">应用分类<b class="blank3"></b></a></li>
          <li><a href="/icwebadmin/ReadHome/recbrand">产品分类推荐品牌<b class="blank3"></b></a></li>
          <li><a href="/icwebadmin/ReadHome/hotprod">热销产品推荐<b class="blank3"></b></a></li>
        </ul>
        <div class="tab_con mb10">
        	<table class="tab_tb"  border="0" style=" margin-top:-1px;">
        	<tr><td style="padding:10px;">
                	<?php 
			         foreach($this->appArr as $appid=>$app){
					  //标题
					  $par = $app['par'];
					  //热门方案
					  $solution = $app['solution'][0];
					  //推荐产品
					  $prodvalue= $app['value'];
					  //推荐品牌
					  $brand    = $app['brand'];
					 ?>
					<table width="100%">
                    <tr><td><b><?=$par['name']?></b>
                    &nbsp;&nbsp;&nbsp;&nbsp;
                    <?php if($app['status']==1) {?> 
                     <a href="javascript:;" onclick="changestatus(<?=$appid?>,0)" title="点击下线"><font color="#006600">已上线</font></a>
				    <?php }else {?>
                     <a href="javascript:;" onclick="changestatus(<?=$appid?>,1)" title="点击上线"><font color="#FF0000">已下线</font></font></a> <?php }?>
                    &nbsp;&nbsp;&nbsp;&nbsp;
                    <a href="<?php echo $this->url(array('controller'=>'ReadHome', 'action'=>'appedit', 'appid'=>$appid));?>">修改</a>
                    <tr><td>
                    	
                        <table>
                        	<tr><td width="350">
                            <!-- 应用方案-->
                            <a href="/applications/details?solid=<?=$solution['solid']?>"><?=$solution['title']?> : <br/>
                            <img src="<?=APPICON.$solution['sol_img']?>" width="150" height="100"/></a>
                            </td>
                            <td  width="350">
                            <!-- 推荐产品-->
                             <?php for($i=0;$i<count($prodvalue);$i++){$data = $prodvalue[$i];?>
                              <a href="/proddetails?partid=<?=$data['comid']?>" target="_blank">
                              <img src="<?=PRODUCTICON.($data['part_img']==''?'no.gif':$data['part_img'])?>" height="50" width="50"/>
					          <?=$data['part_no']?></a><br/>
                             <?php }?>
                            </td>
                            <td  width="350">
                            <!-- 推荐品牌-->
                             <?php for($i=0;$i<count($brand);$i++){?>
                                <a href="/prodlist?brand=<?=$brand[$i]['id']?>" title="<?=$brand[$i]['name']?>"><img width="85" height="50" src="/images/default/brand/<?=$brand[$i]['id']?>_c.jpg"></a> 
                             <?php }?>
                            </td>
                            </tr>
                            
                        </table>
                    </td></tr>
                    </td></tr>
                    </table>
		   	        <?php }?>
            </td></tr>
            </table>
        </div>
      </div>
     </div>
     </div>
      <!-- 结束区域-->
</div>
<script type="text/javascript">
function changestatus(cat_id,status)
{
	 $.ajax({
            url: '/icwebadmin/ReadHome/app',
            data: {'cat_id':cat_id,'status':status},
            type: 'post',
            dataType: 'json',
            success: function(arr) {
			    document.getElementById('message_sess').style.display = "block";
	            document.getElementById('alert_message').innerHTML = arr.message;
            	if(arr.code == 0)
                {
                    location.reload();
                }
            }
	  });
}
</script>