<div class="conmian">
  <h1><?php echo $this->AreaTitle;?> -> 编辑应用分类 <a href="/icwebadmin/ReadHome/app">返回&gt;&gt;</a></h1>
  <div id="message_sess" style="display:none" class="message_sess"> 
          <div title="关闭" class="but" onclick="document.getElementById('message_sess').style.display='none'">&nbsp;</div>
          <div id="alert_message"></div> 
 </div>
<?php if (isset($_SESSION['messages'])) : ?><div class="alert fade in">
     <button type="button" class="close" data-dismiss="alert">×</button>
    <p class="message"><strong><?php echo $_SESSION['messages'];unset($_SESSION['messages']);?></strong></p></div><?php endif; ?>

	  <!-- 需要填写的区域-->
      <form class="form-horizontal form-validate" style="text-align:left" method="post" action="/icwebadmin/ReadHome/appedit/">
          <input type="hidden" name="appid" value="<?=$this->appid?>" />
            <?php 
			//热门方案
			$solution = $this->app['solution'][0];
			//推荐产品
			$prodvalue= $this->app['value'];
			//推荐品牌
			$brand    = $this->app['brand'];
			?>
            <div class="control-group">
              <label class="control-label" for="contents">推荐方案ID:</label>
              <div class="controls">
                <input type="hidden" name="solution_id" value="<?=$solution['id']?>" />
                <input type="text" name="solution" value="<?=$solution['comid']?>" >
              </div>
            </div>
			<?php foreach($prodvalue as $v){?>
            <input type="hidden" name="prod[]" value="<?=$v['id']?>" />
            <div class="control-group">
              <label class="control-label" for="contents">产品ID:</label>
              <div class="controls">
                <input type="text" name="prod_<?=$v['id']?>" value="<?=$v['comid']?>" >
              </div>
            </div>
            <?php }?>
            <?php foreach($brand as $v){?>
            <input type="hidden" name="brand[]" value="<?=$v['id']?>" />
            <div class="control-group">
              <label class="control-label" for="contents">品牌ID:</label>
              <div class="controls">
                <input type="text" name="brand_<?=$v['id']?>" value="<?=$v['comid']?>" >
              </div>
            </div>
            <?php }?>
            <div class="control-group">
              <div class="controls">
                <input type="submit" class="btn" value="更 新">
              </div>
            </div>
          </form>
      <!-- 结束区域-->
</div>