<div class="conmian">
  <h1><?php echo $this->AreaTitle;?></h1>
  <div id="message_sess" style="display:none" class="message_sess"> 
          <div title="关闭" class="but" onclick="document.getElementById('message_sess').style.display='none'">&nbsp;</div>
          <div id="alert_message"></div> 
 </div>
	  <!-- 需要填写的区域-->
	<div class="fr u_right">
    <div class="tab_content">
      <div class="tab_tit1">
        <ul class="fl">
          <li><a href="/icwebadmin/ReadHome">滚动图片<b class="blank3"></b></a></li>
          <li><a href="/icwebadmin/ReadHome/newprod">精品 • 新品<b class="blank3"></b></a></li>
          <li><a href="/icwebadmin/ReadHome/actingbrand">代理品牌<b class="blank3"></b></a></li>
          <li><a href="/icwebadmin/ReadHome/app">应用分类<b class="blank3"></b></a></li>
          <li><a href="/icwebadmin/ReadHome/recbrand">产品分类推荐品牌<b class="blank3"></b></a></li>
          <li class="on"><a href="/icwebadmin/ReadHome/hotprod">热销产品推荐<b class="blank3"></b></a></li>
        </ul>
        <div class="tab_con mb10">
        <font color="#FF0000">*</font>产品ID：<input type="text" name="prod_id" id="prod_id" onkeyup="value=value.replace(/[^\d]/g,'')"/>
        <span title="数字越小排序越前">排序：</span><input type="text" value="0" name="displayorder" id="displayorder" onkeyup="value=value.replace(/[^\d]/g,'')" style="width:50px;"/>
        <a href="javascript:" onclick="addhotprod('<?=$data['id']?>')" class="btna">添加热销产品+</a>&nbsp;&nbsp;<a href="/icwebadmin/ReadHome/hotprodedit" class="btna">编辑所有</a>
        <table class="table" border="0" style=" margin-top:-1px;">
        	<tr>
                  <?php foreach($this->hot_prod as $key=>$partarr){?>
                       <td style="padding:10px;"><a href="/proddetails?partid=<?=$partarr['comid']?>" target="_blank">
                       <img src="<?=PRODUCTICON.($partarr['part_img']==''?'no.gif':$partarr['part_img'])?>" height="50" width="50"/>
					   <?=$partarr['part_no']?></a>(<?=$partarr['brandname']?>)
                 <?php 
				 if($partarr['status']==1) {?> 
                <a href="javascript:;" onclick="changestatus(<?=$partarr['id']?>,0)" title="点击下线"><font color="#006600">已上线</font></a>
				<?php }else {?>
                <a href="javascript:;" onclick="changestatus(<?=$partarr['id']?>,1)" title="点击上线"><font color="#FF0000">已下线</font></font></a>
                <?php }?>
                       </td>
		   	     <?php if(($key+1)%3==0) echo '<tr>';
				 }?>
                 </table>
        </div>
      </div>
     </div>
     </div>
      <!-- 结束区域-->
 </div>
<script type="text/javascript">
function addhotprod(id){
   var displayorder = document.getElementById("displayorder").value;
   var prod_id = document.getElementById("prod_id").value;
   if(prod_id=='') {alert('请输入产品ID');return;}
   $.ajax({
            url: '/icwebadmin/ReadHome/hotprodadd',
            data: {'prod_id':prod_id,'displayorder':displayorder},
            type: 'post',
            dataType: 'json',
            success: function(arr) {
			  alert(arr.message);
              if(arr.code == 0) location.reload();
			}
	});
}
function changestatus(id,status)
{
	 $.ajax({
            url: '/icwebadmin/ReadHome/changestatus',
            data: {'id':id,'status':status},
            type: 'post',
            dataType: 'json',
            success: function(arr) {
			    document.getElementById('message_sess').style.display = "block";
	            document.getElementById('alert_message').innerHTML = arr.message;
            	if(arr.code == 0)
                {
                    location.reload();
                }
            }
	  });
}
</script>