
<script type="text/javascript">
//轮转
    $(function(){
        var tab = $(".tabbar li");
        tab.click(function(){
            $(this).addClass("selected").siblings().removeClass("selected");
			var index = tab.index(this);
            $(".listtab_con").eq(index).show().siblings().hide();		
        });
     })
</script>


<div class="w">
  <div class="breadcrumbs2013">
    <a  class="focs">BOM采购</a>
  </div>
</div>

<div class="w">
	<div class="BOMpage MT20 msg24">
    
    <div class="<?php if(isset($_SESSION['code']) && $_SESSION['code']>0) echo "error";elseif($_SESSION['message']) echo "ok";?>" id="index_message">
  <?php if(isset($_SESSION['message'])){echo $_SESSION['message'];}?>
    </div>
    
    	<div class="tipsbox" >
            <b>温馨提示：</b>
            <span>在IC易站上你可以通过批量上传和逐条上传两种方式上传BOM采购单，任何方式每次都最多提交100条。</span>
        </div>
        <div class=" clearfix">
    		<ul class="tabbar clearfix">
                <li class="selected"><a href="javascript:" >逐条上传<b class="blank3"></b></a></li>
                <li class=""><a href="javascript:" >批量上传<b class="blank3"></b></a></li>
            </ul>
        </div>
        <div class="onebox  ">
            
            <div class="listtab_con">
                <div class="ImportExcel">
                   <strong>说明：</strong><br>
                      —— 可以通过添加新行来添加型号。<br>
                      —— 型号，品牌和需求数量是必填项。 <br>   
                      —— 每次最多提交100条BOM采购。 <br>                                                                                                                                                      
                </div>
                <form id='bompost' name="bompost" action='/bompurchase' method='post'>
                <div class="BOMinfo clearfix boxshadow_h">
    <table cellpadding="0" cellspacing="0"  class="BOMtable clearfix" border="0">
      <thead>
        <tr>
          <th width="15%"  class="bgsep">品牌<em>*</em></th>
          <th width="15%"  class="bgsep">型号<em>*</em></th>
          <th width="15%"  class="bgsep">需求数量<em>*</em></th>
          <th width="15%">目标单价</th>
          <th width="15%">要求交货日期</th>
          <th width="10%">备注</th>
          <th width="10%">&nbsp;</th>
        </tr>
      </thead>
      <tbody>
        <tr>
        <td colspan="8">
        <input type="hidden" value="0" id="theValue" name="theValue" />
        <input type="hidden" value="0" id="theValueNum" name="theValueNum" />
        <div id="myDiv"></div></td>
        </tr>
        
        <tr><td colspan="8" align="right" >
        <a href="javascript:;" onClick="addEvent('','','','','','','','','');"  class="gbqfb" ><b>添加行+</b></a></td></tr>
        </tbody></table>
              		<div class="dl2013 clearfix">
                    <dl>
                        <dt><em>*</em>结算货币：</dt>
                        <dd>
                           <select name="currency" id="currency" onchange="changeMbprice(this.value)">
       <option value="RMB" <?php if(isset($_SESSION['currency']) && $_SESSION['currency']=='RMB') echo "selected";?>>人民币(RMB)</option>
       <option value="HKD" <?php if(isset($_SESSION['currency']) && $_SESSION['currency']=='HKD') echo "selected";?>>港币(HKD)</option>
       <option value="USD" <?php if(isset($_SESSION['currency']) && $_SESSION['currency']=='USD') echo "selected";?>>美元(USD)</option>
       </select>
                        </dd>
                    </dl>
                    <dl>
                        <dt>交货地：</dt>
                        <dd>
                           <input type="hidden" name="delivery" id="delivery" value="<?=isset($_SESSION['delivery'])?$_SESSION['delivery']:"SZ"?>" />
          <select name="delivery_show" id="delivery_show" disabled="disabled">
          <option value="SZ" <?php if(isset($_SESSION['delivery']) &&$_SESSION['delivery'] == 'SZ') echo "selected";?>>国内</option>
          <option value="HK" <?php if(isset($_SESSION['delivery']) &&$_SESSION['delivery'] == 'HK') echo "selected";?>>香港</option>
          </select>
                        </dd>
                    </dl>
                    <dl class="dl100">
                        <dt>说明：</dt>
                        <dd>
                           <textarea name="description" id="description" rows="3" ><?=(isset($_SESSION['description'])?$_SESSION['description']:'')?></textarea>
                        </dd>
                    </dl>
                    <dl class="dl100">
                        <dt>&nbsp;</dt>
                        <dd><div id="orderbtn">
                        <input type="button" value="提交BOM单" onclick="changeaddress()" class="btnok-new1 " style=" margin:0px 0 0 600px;"></div>
                        </dd>
                    </dl>
                    <div class="clr"></div>
                </div>
              	</div></form>
            </div>
            
            <div class="listtab_con"  style="display:none">
                <div class="ImportExcel clearfix" >
                  <strong>说明：</strong><br>
                  —— 文件必须是.xls等格式的Excel文件（<a href="/upload/default/bomexcel/bom_example.xlsx">点击下载BOM Excel样例</a>）。 <br>
                  —— 每次最多提交100条BOM采购。 <br>                                                                           
                </div>
                <div class="BOMinfo dl2013 clearfix boxshadow_h">
                    <dl class="dl100">
                        <dt><em>*</em>上传Excel文件文件：</dt>
                        <dd><form id='filepost' name="filepost" action='/bompurchase/separate' method='post' enctype="multipart/form-data">
          <strong>上传BOM采购清单：</strong>
          <input type="file" name="uploadtext" id="uploadtext" class="input200" onchange="return fileaction();">
    </form></dd>
                    </dl>
                    <div class="clr"></div>
                </div>
               
            </div>
            
        </div>
        
        <div class="ac"></div>  
    </div> 
</div>
<script src="/js/default/bompurchase.js" type="text/javascript"></script>
<script type="text/javascript">
$('.boxshadow_h').hover(function(){
		$(this).addClass("boxshadow");
	},function(){
		$(this).removeClass("boxshadow");
	});
function fileaction(){
	$.ajax({
            url: '/index/checklogin',
            data: {},
            type: 'post',
            dataType: 'json',
            success: function(arr) {
			   if(arr.code==0)
			   {  
			     	$.ajax({
					url: '/bompurchase/checkuser',
						data: {},
						type: 'post',
						dataType: 'json',
						success: function(arr) {
							if(arr.code==0)
							{
								document.getElementById('filepost').submit();
							}else if(arr.code==400)
							{
								 $.openPopupLayer({
								 name: "companyinfoBox",
								 url: "/center/companyinfo"
								 });
	
							}
							
						}
				    });
			   }else if(arr.code==100){
			   	 $.openPopupLayer({
		             name: "loginBox",
		             target: "login_box"
	              });
			   }else if(arr.code==200){
			   	   window.location.href ="/user/verification";
			   }
            }
    });	
}
//提交
function changeaddress()
{
$.ajax({
            url: '/index/checklogin',
            data: {},
            type: 'post',
            dataType: 'json',
            success: function(arr) {
			
			   if(arr.code==0)
			   {  
			   	  var subtmp = document.getElementById("orderbtn");
			     	$.ajax({
					url: '/bompurchase/checkuser',
						data: {},
						type: 'post',
						dataType: 'json',
						success: function(arr) {
							if(arr.code==0)
							{
								document.getElementById('bompost').submit();
				                subtmp.innerHTML = '<input type="button" value="提交中..." class="btnok-new1 " style=" margin:0px 0 0 600px;">';
							}else if(arr.code==400)
							{
								 $.openPopupLayer({
								 name: "companyinfoBox",
								 url: "/center/companyinfo"
								 });
	
							}
							
						}
				    });
			   }else if(arr.code==100){
			   	 $.openPopupLayer({
		             name: "loginBox",
		             target: "login_box"
	              });
			   }else if(arr.code==200){
			   	   window.location.href ="/user/verification";
			   }
            }
    });	
}
<?php
//填上excel内容
if(isset($_SESSION['alldata']) && $_SESSION['alldata']){
   foreach($_SESSION['alldata'] as $darr){
   if($darr){
   echo 'addEvent("'.$darr[0].'","'.$darr[1].'","'.$darr[2].'","'.$darr[3].'","'.date('Y-m-d',strtotime($darr[4])).'","'.$darr[5].'","","","");';}
   }
   unset($_SESSION['alldata']);
}elseif(!$_SESSION['code']){
   for($i=0;$i<1;$i++)
   {
      echo 'addEvent("","","","","","","","","");';
   }
}
if(isset($_SESSION['code']) && $_SESSION['code']>0){
    for($i=1;$i<=$_SESSION['valuenum'];$i++){
	$mfr     = $_SESSION['mfr'][$i];
	$part_no = $_SESSION['partno'][$i];
	$buynum  = $_SESSION['buynum'][$i];
	$price  = $_SESSION['price'][$i];
	$deliverydate  = $_SESSION['deliverydate'][$i];
	$remarks = $_SESSION['remarks'][$i];
echo 'addEvent("'.$mfr.'","'.$part_no.'","'.$buynum.'","'.$price.'","'.$deliverydate.'","'.$remarks.'","'.$_SESSION['m_mesg'][$i].'","'.$_SESSION['p_mesg'][$i].'","'.$_SESSION['n_mesg'][$i].'");';
   }
}
?>
//setTimeout('hidMessage()',6000);
function hidMessage(){
	document.getElementById("index_message").style.display = 'none';
}
</script>
<?php 
unset($_SESSION['code']);
unset($_SESSION['message']);
?>