<div id="myHiddenDiv">
  <div class="popup">
    <div class="popup-header">
    <h2>上线通知：编号<?=$this->id?></h2>
    <a href="javascript:;" onclick="$.closePopupLayer('courierBox');" title="关闭" class="dialogBoxClose">关闭</a> </div>
    <div class="popup-body" style="width:550px;">
     <!-- 需要填写的区域-->
      <table width="740px" border="0" cellpadding="1">
        <tr>
         <td height="10" colspan="3" align="center">
         <div id="message_sess_son" style="display:none" class="message_sess">
         <span title="关闭" class="but" onclick="document.getElementById('message_sess_son').style.display='none'"></span>
         <span id="alert_message_son"></span>
         </div></td>
         </tr>
         <tr>
          <td width="100"><em>*</em>新上线产品ID：</td>
          <td><input type="text" name="part_id" id="part_id" /></td>
        </tr>
        <tr>
          <td align="right">备注：</td>
          <td><textarea name="result" id="result" rows="3" cols="50"></textarea></td>
        </tr>
        <tr>
          <td align="center" colspan="2"><div id="orderbtn">
          <input type="button"  class="btnabig"  value="提交" onclick="editaction('<?=$this->id?>')"/>
          </div>
          </td>
        </tr>
      </table>
      <!-- 结束区域-->
    </div>
  </div>
</div>