
<link rel="stylesheet" type="text/css"
	href="<?=$_SESSION['new_version']?>/css/default/home2013.css" />
<link rel="stylesheet" type="text/css"
	href="<?=$_SESSION['new_version']?>/css/default/index.css" />
<script type="text/javascript" language="javascript"> widescreen_css();</script>
<link rel="stylesheet" type="text/css"
	href="/js/jsplug/scroll/scroll<?=$_SESSION['new_version']?>.css" />
<script type="text/javascript" src="/js/jsplug/scroll/scroll.js"></script>



<script type="text/javascript">
$(function(){
	$('.pprice201312').hover(function(){
		$(this).addClass("item-hover");
	},function(){
		$(this).removeClass("item-hover");
	});
	$('.boxshadow_h').hover(function(){
		$(this).addClass("boxshadow");
	},function(){
		$(this).removeClass("boxshadow");
	});
	$('.boxshadow_h1').hover(function(){
		$(this).addClass("boxshadow1");
	},function(){
		$(this).removeClass("boxshadow1");
	});
	$('.item').hover(function(){
		$(this).addClass("boxshadow");
	},function(){
		$(this).removeClass("boxshadow");
	});
	$('.por_box2013').hover(function(){
		$(this).addClass("tabelbtn_h");
	},function(){
		$(this).removeClass("tabelbtn_h");
	});
});
$(function(){
var tab = $(".tabbar li");
tab.click(function(){
	$(this).addClass("selected").siblings().removeClass("selected");		
	var index = tab.index(this);
	$(".layout").eq(index).show().siblings().hide();	
});
})
$(function(){
var tab = $(".tabbar1 li");
tab.click(function(){
	$(this).addClass("selected").siblings().removeClass("selected");		
	var index = tab.index(this);
	$(".layout").eq(index).show().siblings().hide();	
});
})

</script>

<!---------------------------------------------------------------------首页内容 开始--------------------------------------------------------------------->
<div class="home201312">
	<div class="w ">
		<div class="mainbannerbox">
			<div class="fl">
				<div class="indexShow scroll">
					<div class="indexShowBox scroll_cont" id="FS_Cont_01"
						data-client="focus">
						<!-- 抓站_焦点图 begin -->
          
          <?php
        foreach ($this->topimageArr as $v) {
            $url_target = '_self';
            if ($v['url_target'] == 2)
                $url_target = '_blank';
            ?>
          <div class="box homeimages">
							<div>
								<a href="<?=$v['url']?>" target="<?=$url_target?>"
									title="<?=$v['title']?>" class="logclick" rev='topimage'
									rel='<?=$v['id']?>'><img class="homeimages" height="342"
									alt="<?=$v['title']?>" src="<?=$v['image']?>"
									title="<?=$v['title']?>" /></a>
							</div>
							<div class="bg"></div>
							<!--<div class="txt">
              <p><a href="<?=$v['url']?>"  target="<?=$url_target?>" title="<?=$v['title']?>"  class="logclick" rev='topimage' rel='<?=$v['id']?>'><?=$v['title']?></a></p>
            </div>-->
						</div>
          <?php }?>
          <!-- 抓站_焦点图 end -->
					</div>
					<a href="javascript:;" title="上一张" class="arr_left"
						id="FS_arr_left_01"></a> <a href="javascript:;" title="下一张"
						class="arr_right" id="FS_arr_right_01"></a>
					<div class="scroll_num" id="FS_numList_01"></div>
				</div>
				<script type="text/javascript" language="javascript"> 
var widescreen = false;
var standard_width = 550;
if (screen.width >= 1280) { 
     standard_width = 700;
	 widescreen = true;
}
$(".homeimages").css("width", standard_width); 
</script>
				<script language="javascript" type="text/javascript">
			  <!--//--><![CDATA[//><!--
			  var focusScroll_01 = new ScrollPic();
			  focusScroll_01.scrollContId   = "FS_Cont_01"; //内容容器ID
			  //focusScroll_01.arrLeftId      = "FS_arr_left_01";//左箭头ID
			  //focusScroll_01.arrRightId     = "FS_arr_right_01"; //右箭头ID
			  focusScroll_01.dotListId      = "FS_numList_01";//点列表ID
			  focusScroll_01.dotClassName   = "";//点className
			  focusScroll_01.dotOnClassName	= "current";//当前点className
			  focusScroll_01.listType		= "";//列表类型(number:数字，其它为空)
			  focusScroll_01.listEvent      = "onmouseover"; //切换事件
			  focusScroll_01.frameWidth     = standard_width;//显示框宽度
			  focusScroll_01.pageWidth      = standard_width; //翻页宽度
			  focusScroll_01.upright        = false; //垂直滚动
			  focusScroll_01.speed          = 10; //移动速度(单位毫秒，越小越快)
			  focusScroll_01.space          = 60; //每次移动像素(单位px，越大越快)
			  focusScroll_01.autoPlay       = true; //自动播放
			  focusScroll_01.autoPlayTime   = 5; //自动播放间隔时间(秒)
			  focusScroll_01.circularly     = true;
			  focusScroll_01.initialize(); //初始化
			  sina.$('FS_arr_left_01').onmousedown = function(){
				focusScroll_01.pre();
				return false;
			  }
			  sina.$('FS_arr_right_01').onmousedown = function(){
				focusScroll_01.next();
				return false;
			  }
			  //--><!]]>
			  function showbrand(showclass,hideclass){
			       $("."+hideclass).hide();
			  	   $("."+showclass).fadeIn();	
			  }
			  //定时换 推荐品牌
			  var showbrandnow = 1;
			  function change_showbrand(){
			  	  if(showbrandnow==1){ showbrandnow = 2;showbrand('brand_2','brand_1');}
				  else if(showbrandnow==2){ showbrandnow = 1;showbrand('brand_1','brand_2');}
			  }
			  setInterval("change_showbrand()",6000);
			  //快速订购
			  function q_action(){
			  	 // var q_shipto = $("#q_shipto").val();
				  var q_partno = $("#q_partno").val();
				 // var q_number = $("#q_number").val();
				  if(q_partno=='' || q_partno=='请输入型号') {$("#q_partno").focus();return;};
				  //if(q_number=='' || q_number=='数量') {$("#q_number").focus();return;};
				  //提交订单
					 var subtmp = document.getElementById("baojiabtn");
					 subtmp.innerHTML = '<input value="提交中..." type="button" class="gbqfb">';
					 $.ajax({
							url: '/cart/quickorder',
							data: {'q_partno':q_partno},
							type: 'post',
							dataType: 'json',
							success: function(arr) {
							   if(arr.code == 0){
								   buy(arr.id);
							   }else if(arr.code == 1){
							       if(confirm(arr.message)){
									   openInquiry(arr.id);
								   }
							   }else if(arr.code == 2){
									window.location.href=arr.url;   
							   }else if(arr.code == 100){
									window.location.href="/search?keyword="+q_partno+"&st=searchmodel";   
							   }else if(arr.code == 200){
							        if(confirm(arr.message)){
									    window.location.href="/search?keyword="+q_partno+"&st=searchmodel";   
									}
							   }else{
								  alertbox(arr.message);
							   }
							   subtmp.innerHTML = '<input onclick="q_action()" value="确 认" type="button" class="gbqfb">';
							}
					});
			  }
		</script>
				<div class="brand_wall btnpx">
					<ul class="brandBox">
						<li id="marqueebox">
            <?php foreach($this->actingBrand as $k=>$actingbrand){ $showclass = $k<12?'brand_1':'brand_2';?>
            <a
							href="/pl/<?=$actingbrand['name']?><?php if(in_array($actingbrand['comid'],array(17,13))){echo '?t=1';}?>"
							title="<?=$actingbrand['name']?>"
							class="flowTip logclick <?=$showclass?>" rev="acting_brand"
							rel="<?=$actingbrand['comid']?>" target="_blank"> <img
								height="40"
								src="/images/default/brand/<?=$actingbrand['comid']?>.png"
								<?=$icss?> title="<?=$actingbrand['name']?>" /> <span><?=$actingbrand['name']?></span></a>
            <?php }?>
          </li>
					</ul>
					<a class="btn_prev" id="btn_prev" href="javascript:;"
						onClick="showbrand('brand_1','brand_2')"></a> <a class="btn_next"
						id="btn_next" href="javascript:;"
						onClick="showbrand('brand_2','brand_1')"></a>
				</div>
			</div>
			<div class="clr"></div>
			<div class="mainrightbox">

				<div class="mod_tab boxshadow_h">
					<div class="clearfix ">
						<ul class="tabbar clearfix">
							<li class="li_1_a selected"><a href="/market">行业新闻<b
									class="blank3"></b></a></li>
						</ul>
					</div>
					<div class="mod_tab_c">
						<div class="content">
							<div class="div_1">
								<ul>
                <?php
                foreach ($this->hynews as $solutiontmp) {
                    ?>
                <li><ins class="dot"></ins><a
										href="/news-<?=$solutiontmp['id']?>.html"
										title="<?=$solutiontmp['title']?>" class="logclick"
										rev="index_solution" rel="<?=$solutiontmp['id']?>"
										target="_blank">
                  <?=$this->fun->utf_substr($solutiontmp['title'],34)?>
                  </a></li>
                <?php }?>
              </ul>
							</div>
						</div>
					</div>
				</div>
				<div class="clr"></div>
				<div class="mod_tab boxshadow_h">
					<div class="clearfix ">
						<ul class="tabbar clearfix">
							<li class="li_1_a selected"><a href="/company">企业动态<b
									class="blank3"></b></a></li>
						</ul>
					</div>
					<div class="mod_tab_c">
						<div class="content">
							<div class="div_1">
								<ul>
                <?php
                foreach ($this->qynews as $solutiontmp) {
                    ?>
                <li><ins class="dot"></ins><a
										href="/news-<?=$solutiontmp['id']?>.html"
										title="<?=$solutiontmp['title']?>" class="logclick"
										rev="index_solution" rel="<?=$solutiontmp['id']?>"
										target="_blank">
                  <?=$this->fun->utf_substr($solutiontmp['title'],34)?>
                  </a></li>
                <?php }?>
              </ul>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="clr"></div>

		</div>

		<div style="margin-bottom: 20px">
			<h2>热卖推荐</h2>
			<div class="home container">
				<ul class="overseas-sub-list col-md-24">
					<?php foreach ($this->hot_prod as $hotProd) {?>
					<li>
						<div>
							<a class="fr" target="_blank"
								href="/search?keyword=<?php echo $hotProd['part_no'];?>&st=searchall"> 
								<img
								src="<?=PRODUCTICON.($hotProd['part_img']==''?'no.gif':$hotProd['part_img'])?>"
								alt="" width="60px"
								data-original="<?=PRODUCTICON.($hotProd['part_img']==''?'no.gif':$hotProd['part_img'])?>"
								class="lazy" />
							</a>
							<div class="sub-list">
								<h5 class="ellipsis" title="<?php echo $hotProd['part_no'];?>">
									<a class="theme-link-default" target="_blank"
										href="/search?keyword=<?php echo $hotProd['part_no'];?>&st=searchall">
										<?php echo $hotProd['part_no'];?></a>
								</h5>
		
								<p class="fs-12 c-999"><?php echo $hotProd['manufacturer'];?>
								</p>
							</div>
						</div>
					</li>
					<?php }?>
					
				</ul>
			</div>
			<div class="clr"></div>
		</div>
		<div class="index_box_three">

			<div class="cont clear">
				<div class="ad">
					<a href="#"><img src="/images/default/nx/home1.jpg"></a>
				</div>
				<ul class="block">
                <?php foreach($this->supplier as $v){?>
                    <li title="<?php echo $v['name'];?>"><a> <img
							src="<?php echo $v['img'];?>"><span><?php echo $v['name'];?></span></a></li>
                   <?php }?> 
                 </ul>
			</div>
		</div>
<div class="clr"></div>
		<div style="padding-top: 20px">
			<img class="" src="/images/default/nx/ad1.jpg" width="1180"
				height="100">
		</div>
	</div>
</div>

