<link rel="stylesheet" type="text/css" href="/css/default/myself.css" />
<?php 
$statusarr = array('101'=>'<font color="#fd2323">待客户支付货款</font>',
				'102'=>'<font color="#fd2323">待处理</font>',
				'103'=>'<font color="#fd2323">待支付余款</font>',
				'201'=>'<font color="#fd2323">待发货</font>',
				'202'=>'<font color="#03b000">已发货</font>',
				'301'=>'<font color="#03b000">已完成</font>',
				'302'=>'<font color="#03b000">已评价</font>',
				'401'=>'<font color="#fd2323">订单被取消</font>');
$paystatus = array('101'=>'<font color="#fd2323">待付款</font>',
				'102'=>'<font color="#03b000">已付预付款</font>',
				'103'=>'<font color="#03b000">已付预付款</font>',
				'201'=>'<font color="#03b000">已付全部货款</font>',
				'202'=>'<font color="#03b000">已付全部货款</font>',
				'301'=>'<font color="#03b000">已付全部货款</font>',
				'302'=>'<font color="#03b000">已付全部货款</font>',
				'401'=>'<font color="#03b000">订单被取消</font>');
$codarr = array('101'=>'<font color="#FF0000">等待审核</font>',
'102'=>'<font color="009944">处理中</font>',
'103'=>'<font color="#FF0000">待支付余款</font>',
'201'=>'<font color="009944">待发货</font>',
'202'=>'<font color="009944">待确认收货</font>',
'301'=>'已完成',
'302'=>'已完成',
'401'=>'订单被取消','501'=>'退款','502'=>'退货退款');
$deliveryArr = array('HK'=>'香港','SZ'=>'国内');
if(in_array($this->orderarr['paytype'],array('transfer','online')))
{ 
 $down_payment = number_format($this->orderarr['down_payment'],DECIMAL);
 $surplus = number_format($this->orderarr['total']-$this->orderarr['down_payment'],DECIMAL);
 $statusarr = $statusarr;
}else{
 $down_payment = '--';
 $surplus = '--';
 $statusarr = $codarr;
}
$paytypearr = array('transfer'=>'银行汇款','online'=>'在线支付','cod'=>'货到付款','mts'=>'款到发货');
$deliveryArr = array('HK'=>'香港','SZ'=>'国内');
$type = array('spot'=>'现货','order'=>'订货');
$expressarr = array('1'=>'国内快递','2'=>'公司配送');
$unitArr = array('RMB'=>'￥','USD'=>'$','HKD'=>'HK$');
$arr = array('1'=>'明细','2'=>'电子元件','3'=>'耗材');
?>
<div id="header" class="w">
  <div id="logo"><a hidefocus="true" href="/"><img alt="IC易站" src="/images/default/logo.jpg"></a></div>
  <h1>订单详情</h1>
</div>

<!--content-->
<div class="w">
  <div class="breadcrumbs"> <span><?=$this->translate('Menu_CurrentPosition')?></span><a href="/" ><?=$this->translate('Menu_Home');?></a>&nbsp;&nbsp;»&nbsp;&nbsp;<a href="/center/order" ><?=$this->translate('Menu_MyOrder')?></a>&nbsp;&nbsp;»&nbsp;&nbsp;<a href="/center/inqorder" >询价订单</a>&nbsp;&nbsp;»&nbsp;&nbsp;<span>订单详情</span> </div>
</div>
<div class="blank10"></div>
<div class="w"  id="onlineso">
  <table width="730" border="0" align="center" cellpadding="0" cellspacing="0" style=" color:#555555;  background:#fff; font-family:'微软雅黑'; margin:0 auto 20px auto">
  <tbody>
  <tr>
  	<td height="36" style="background:#fff; text-align:right">
    	<a href="#" onclick="javascrīpt:printDiv('onlineso')" target="_self">打印订单</a>
    </td>
  </tr>
  <tr><td style=" height:3px; background-color:#f00;"></td></tr>
  <tr>
    <td bgcolor="#ffffff" style="text-align:center; padding:10px 0;"><h1 style="padding-bottom:5px ; font-size:18px; background:#fff;">IC易站订单</h1></td>
  </tr>
  <tr>
  	<td bgcolor="#ffffff" >
    	<table cellpadding="0" cellspacing="0" border="0" style="background:#f9f9f9">
        	<!--订单详情-->
            <?php $mess ='<tr valign="top">
    <td >
        <table cellspacing="0" cellpadding="0" border="0" align="center" width="850" bgcolor="#f9f9f9"  style=" font-size:12px; line-height:20px; color:#5b5b5b;font-family:\'微软雅黑\'; padding:0 0 10px 0; margin:0; border-collapse:separate; border-spacing:0px" >       
        <tr>
           <td bgcolor="#f9f9f9">
            <table cellspacing="0" border="0" cellpadding="0" width="830" style="font-family:\'微软雅黑\';" >
                <tr>
                    <td valign="middle" colspan="2" align="left" height="40">
                    <span style="font-size:14px;font-weight:bold; display:inline-block; padding:3px 0; background:#555555;color:#ffffff;font-family:\'微软雅黑\'">&nbsp;&nbsp;&nbsp;订单详情&nbsp;&nbsp;&nbsp;</span>
                	</td>
                </tr>
                <tr>
                    <td style="font-size:34px; ">&nbsp;</td>
                    <td valign="top" align="left" >
                      <table width="830" border="0" cellspacing="0" cellpadding="0" bgcolor="#ffffff" style="line-height:20px; font-size:12px; color:#565656;font-family:\'微软雅黑\'; border:1px solid #d6d6d6">
                            <tr  bgcolor="#ffffff">
                              <td width="100" height="30" style="background:#ffffff;font-family:\'微软雅黑\';border-bottom:1px solid #d6d6d6;border-right:1px solid #d6d6d6 ">&nbsp;&nbsp;订单号：</td>
                              <td width="300" style="background:#ffffff;font-family:\'微软雅黑\'; border-bottom:1px solid #d6d6d6;border-right:1px solid #d6d6d6"><strong style="color:#ff6600;font-family:\'微软雅黑\'">&nbsp;&nbsp;'.$this->orderarr['salesnumber'].'</strong></td>
                              <td width="100" style="background:#ffffff;font-family:\'微软雅黑\'; border-bottom:1px solid #d6d6d6;border-right:1px solid #d6d6d6">&nbsp;&nbsp;订单状态：</td>
                              <td style="background:#ffffff;font-family:\'微软雅黑\';border-bottom:1px solid #d6d6d6;"><strong style="color:#000000;font-family:\'微软雅黑\'">&nbsp;&nbsp;'.$statusarr[$this->orderarr['status']].'</strong></td>
                            </tr>
                            <tr>                              
                              <td style="background:#ffffff;font-family:\'微软雅黑\';border-bottom:1px solid #d6d6d6;border-right:1px solid #d6d6d6 ">&nbsp;&nbsp;订单金额：</td>
                              <td style="background:#ffffff;font-family:\'微软雅黑\';border-bottom:1px solid #d6d6d6;border-right:1px solid #d6d6d6 ">&nbsp;&nbsp;<strong style="color:#fd2323;font-family:\'微软雅黑\'"><span style="color:#000000">'.$this->orderarr['currency'].'</span> '.number_format($this->orderarr['total'],DECIMAL).'</strong></td>
							  <td height="30" style="background:#ffffff;font-family:\'微软雅黑\';border-bottom:1px solid #d6d6d6;border-right:1px solid #d6d6d6">&nbsp;&nbsp;下单时间 ：</td>
                              <td style="background:#ffffff;font-family:\'微软雅黑\';border-bottom:1px solid #d6d6d6;"><strong style="color:#000000;font-family:\'微软雅黑\'">&nbsp;&nbsp;'.date('Y/m/d H:i:s',$this->orderarr['created']).'</strong></td>
                              
                            </tr>';
							if($this->orderarr['total'] != $this->orderarr['down_payment']){
							        $mess .=' <tr  bgcolor="#ffffff">
                              <td width="100" height="30" style="background:#ffffff;font-family:\'微软雅黑\';border-bottom:1px solid #d6d6d6;border-right:1px solid #d6d6d6 ">&nbsp;&nbsp;预付款：</td>
                              <td width="300" style="background:#ffffff;font-family:\'微软雅黑\'; border-bottom:1px solid #d6d6d6;border-right:1px solid #d6d6d6">&nbsp;&nbsp;<strong style="color:#fd2323;font-family:\'微软雅黑\'"><span style="color:#000000">'.$this->orderarr['currency'].'</span> '.number_format($this->orderarr['down_payment'],DECIMAL).'</strong></td>
                              <td width="100" style="background:#ffffff;font-family:\'微软雅黑\'; border-bottom:1px solid #d6d6d6;border-right:1px solid #d6d6d6">&nbsp;&nbsp;剩余款：</td>
                              <td style="background:#ffffff;font-family:\'微软雅黑\';border-bottom:1px solid #d6d6d6;">&nbsp;&nbsp;<strong style="color:#fd2323;font-family:\'微软雅黑\'"><span style="color:#000000">'.$this->orderarr['currency'].'</span> '.number_format($this->orderarr['total']-$this->orderarr['down_payment'],DECIMAL).'</strong></td>
                            </tr>';
                              }
                            $mess .='<tr  bgcolor="#ffffff">
                              <td height="30" style="background:#ffffff;font-family:\'微软雅黑\';border-bottom:1px solid #d6d6d6;border-right:1px solid #d6d6d6">&nbsp;&nbsp;付款方式：</td>
                              <td style="background:#ffffff;font-family:\'微软雅黑\';border-bottom:1px solid #d6d6d6;border-right:1px solid #d6d6d6"><strong style="color:#000000;font-family:\'微软雅黑\'">&nbsp;&nbsp;'.$paytypearr[$this->orderarr['paytype']].'</strong></td>
                              <td height="30" style="background:#ffffff;font-family:\'微软雅黑\';border-bottom:1px solid #d6d6d6;border-right:1px solid #d6d6d6">&nbsp;&nbsp;付款状态：</td>
                              <td style="background:#ffffff;font-family:\'微软雅黑\';border-bottom:1px solid #d6d6d6;"><strong style="color:#000000;font-family:\'微软雅黑\'">&nbsp;&nbsp;'.$paystatus[$this->orderarr['status']].'</strong></td>
                            </tr> 
                            <tr  bgcolor="#ffffff">
                              <td height="30" style="background:#ffffff;font-family:\'微软雅黑\';border-right:1px solid #d6d6d6">&nbsp;&nbsp;订单备注：</td>
                              <td colspan="3" style="background:#ffffff;font-family:\'微软雅黑\';"><table border="0" cellspacing="0" cellpadding="0"><tr><td width="7">&nbsp;</td><td style="font-family:\'微软雅黑\'; font-size:12px;" ><strong style="color:#000000;font-family:\'微软雅黑\'">'.nl2br($this->orderarr['remark']).'</strong></td></tr></table></td>
                            </tr>';
							if($this->orderarr['ship_salesnumber']){
								$mess .='<tr>
								<td height="30" style="background:#ffffff;font-family:\'微软雅黑\';border-top:1px solid #d6d6d6;border-right:1px solid #d6d6d6">&nbsp;&nbsp;合并订单：</td>
								<td colspan="3" style="background:#ffffff;font-family:\'微软雅黑\'; border-top:1px solid #d6d6d6;"><p><strong class="fontorg">&nbsp;&nbsp;此订单与订单#：<a href="/inquiryorder/view?salesnumber='.$this->orderarr['ship_salesnumber'].'" title="查看订单详细" target="_blank" class="number">'.$this->orderarr['ship_salesnumber'].'</a>一起发货。</strong></p></td>
								</tr>';
						    }
                      $mess .='</table>
                    </td>
                </tr>
            </table>
        </td>
        </tr>
        </table>
    </td>
</tr>

<tr>
    <td valign="top" align="left" >
        <table cellspacing="0" cellpadding="0" border="0" align="center" width="730" bgcolor="#f9f9f9"  style=" font-size:12px; line-height:20px; color:#5b5b5b;font-family:\'微软雅黑\'; padding:10px 0; margin:0; border-collapse:separate; border-spacing:0px" >
            <tr>
                <td width="10" bgcolor="#f9f9f9" style="line-height:1px; font-size:10px; ">&nbsp;&nbsp;</td>
                <td bgcolor="#f9f9f9">
                <table width="830" border="0" cellspacing="0" bgcolor="#d6d6d6" cellpadding="0" style="line-height:20px; font-size:12px; color:#565656;font-family:\'微软雅黑\'; border:2px solid #fd2323; text-align:center; border-collapse:collapse">
                    <tr bgcolor="#f3f3f3">
                        <th width="35" height="30">项次</th>
                        <th>产品型号</th>
						<th>客户物料号</th>
                        <th>品牌</th>
                        <th width="30">单位</th>
                        <th>数量</th>
                        <th>单价('.$this->orderarr['currency'].')</th>
                        <th>金额('.$this->orderarr['currency'].')</th>
                        <th>需求日期</th>
                    </tr>';
		foreach($this->pordarr as $k=>$v){
			$mess .='<tr bgcolor="#FFFFFF" >
                        <td width="35" height="30" style="border-right:1px solid #d6d6d6;border-top:1px solid #d6d6d6">'.($k+1).'</td>
                        <td style="border-right:1px solid #d6d6d6;border-top:1px solid #d6d6d6"><strong style="color:#0055aa; "><a target="_blank" href="/item-b0-0-'.$v['prod_id'].'-'.$this->fun->filterUrl($v['part_no']).'.html">'.$v['part_no'].'</a></strong></td>
						<td style="border-right:1px solid #d6d6d6;border-top:1px solid #d6d6d6"><strong style="color:#0055aa; ">'.$v['customer_material'].'</strong></td>
                        <td style="border-right:1px solid #d6d6d6;border-top:1px solid #d6d6d6">'.$v['brand'].'</td>
                        <td width="30" style="border-right:1px solid #d6d6d6;border-top:1px solid #d6d6d6">个</td>
                        <td style="border-right:1px solid #d6d6d6;border-top:1px solid #d6d6d6">'.$v['buynum'].'</td>
                        <td style="border-right:1px solid #d6d6d6;border-top:1px solid #d6d6d6"><strong style="color:#fd2323;font-family:\'微软雅黑\'">'.$unitArr[$this->orderarr['currency']].' '.$v['buyprice'].'</strong></td>
                        <td style="border-right:1px solid #d6d6d6;border-top:1px solid #d6d6d6"><strong style="color:#fd2323;font-family:\'微软雅黑\'">'.$unitArr[$this->orderarr['currency']].' '.($v['buyprice']*$v['buynum']).'</strong></td>
                        <td style="border-top:1px solid #d6d6d6;">'.($v['needs_time']?date('Y/m/d',$v['needs_time']):'--').'</td>
                    </tr>';
		}
		$mess .='<tr  bgcolor="#FFFFFF">
                        <td height="30" colspan="9" align="right" style="border-top:1px solid #d6d6d6;">
			   商品金额：<strong style="color:#fd2323; margin-left:5px;">'.$unitArr[$this->orderarr['currency']].' '.number_format($this->orderarr['total']-$this->orderarr['freight'],DECIMAL).'</strong> 
              <strong style="font-size:16px; color:#000000">+</strong> 
                            运费及包装费：<strong style="color:#fd2323; margin-left:5px;">'.$unitArr[$this->orderarr['currency']].' '.number_format($this->orderarr['freight'],DECIMAL).'</strong> 
				<strong style="font-size:16px; color:#000000">=</strong>
                            合计:<b style="color:#fd2323; margin:0 5px;font-size:14px;">'.$this->orderarr['currency'].' '.number_format($this->orderarr['total'],DECIMAL).'</b>
                        </td>
                    </tr>
            </table>
           
        </td>
                
                
            </tr>
        </table>
        </td>     
    </td>
</tr>
 
<!--收货信息-->
<tr valign="top">
    <td >
        <table cellspacing="0" cellpadding="0" border="0" align="center" width="730" bgcolor="#f9f9f9"  style=" font-size:12px; line-height:20px; color:#5b5b5b;font-family:\'微软雅黑\'; padding:0 0 10px 0; margin:0; border-collapse:separate; border-spacing:0px" >       
        <tr>
           <td bgcolor="#f9f9f9">';
            if(in_array($this->orderarr['delivery_type'],array(1,2))){
				$mess .='<table cellspacing="0" border="0" cellpadding="0" width="830" style="font-family:\'微软雅黑\';" >
                <tr>
                    <td valign="middle" colspan="2" align="left" height="40">
                    <span style="font-size:14px;font-weight:bold; display:inline-block; padding:3px 0; background:#555555;color:#ffffff;font-family:\'微软雅黑\'">&nbsp;&nbsp;&nbsp;收货信息&nbsp;&nbsp;&nbsp;</span>
                	</td>
                </tr>
                <tr>
                    <td style="font-size:34px; ">&nbsp;</td>
                    <td valign="top" align="left" >
                      <table width="830" border="0" cellspacing="0" cellpadding="0" bgcolor="#ffffff" style="line-height:20px; font-size:12px; color:#565656;font-family:\'微软雅黑\';border:1px solid #d6d6d6">
                            <tr  bgcolor="#ffffff">
                              <td height="30" width="100" style="background:#ffffff;font-family:\'微软雅黑\';border-bottom:1px solid #d6d6d6;border-right:1px solid #d6d6d6">&nbsp;&nbsp;公司名称：</td>
                              <td width="300" style="background:#ffffff;font-family:\'微软雅黑\'; border-bottom:1px solid #d6d6d6;border-right:1px solid #d6d6d6"><strong style="color:#000000;font-family:\'微软雅黑\'">&nbsp;&nbsp;'.$this->orderarr['companyname'].'</strong></td>
                              <td width="100" style="background:#ffffff;font-family:\'微软雅黑\';border-bottom:1px solid #d6d6d6;border-right:1px solid #d6d6d6">&nbsp;&nbsp;收货人：</td>
                              <td style="background:#ffffff;font-family:\'微软雅黑\';border-bottom:1px solid #d6d6d6;"><strong style="color:#000000;font-family:\'微软雅黑\'">&nbsp;&nbsp;'.$this->orderarr['name'].'</strong></td>
                            </tr>
                            <tr>
                              <td width="100" height="30" style="background:#ffffff;font-family:\'微软雅黑\';border-bottom:1px solid #d6d6d6;border-right:1px solid #d6d6d6">&nbsp;&nbsp;货运方式：</td>
                              <td width="200" style="background:#ffffff;font-family:\'微软雅黑\';border-bottom:1px solid #d6d6d6;border-right:1px solid #d6d6d6"><strong style="color:#000000;font-family:\'微软雅黑\'">&nbsp;&nbsp;'.$expressarr[$this->orderarr['delivery_type']].'</strong></td>
                              <td width="100" style="background:#ffffff;font-family:\'微软雅黑\';border-bottom:1px solid #d6d6d6;border-right:1px solid #d6d6d6">&nbsp;&nbsp;手机：</td>
                              <td style="background:#ffffff;font-family:\'微软雅黑\';border-bottom:1px solid #d6d6d6;"><strong style="color:#000000;font-family:\'微软雅黑\'">&nbsp;&nbsp;'.$this->orderarr['mobile'].'</strong></td>
                            </tr>
                            
                            <tr  bgcolor="#ffffff">
                              <td height="30" style="background:#ffffff;font-family:\'微软雅黑\';border-bottom:1px solid #d6d6d6;border-right:1px solid #d6d6d6">&nbsp;&nbsp;固定电话：</td>
                              <td style="background:#ffffff;font-family:\'微软雅黑\';border-bottom:1px solid #d6d6d6;border-right:1px solid #d6d6d6"><strong style="color:#000000;font-family:\'微软雅黑\'">&nbsp;&nbsp;'.$this->orderarr['tel'].'</strong></td>
                              <td style="background:#ffffff;font-family:\'微软雅黑\';border-bottom:1px solid #d6d6d6;border-right:1px solid #d6d6d6">&nbsp;&nbsp;邮编：</td>
                              <td style="background:#ffffff;font-family:\'微软雅黑\';border-bottom:1px solid #d6d6d6;"><strong style="color:#000000;font-family:\'微软雅黑\'">&nbsp;&nbsp;'.$this->orderarr['zipcode'].'</strong></td>
                            </tr>
                            <tr  bgcolor="#ffffff">
                              <td height="30" style="background:#ffffff;font-family:\'微软雅黑\';border-right:1px solid #d6d6d6">&nbsp;&nbsp;详细地址：</td>
                              <td style="background:#ffffff;font-family:\'微软雅黑\';border-right:1px solid #d6d6d6"><strong style="color:#000000;font-family:\'微软雅黑\'">&nbsp;&nbsp;'.$this->fun->createAddress($this->orderarr['province'],$this->orderarr['city'],$this->orderarr['area'],$this->orderarr['address']).'</strong></td>
							  <td style="background:#ffffff;font-family:\'微软雅黑\';border-right:1px solid #d6d6d6">&nbsp;&nbsp;入仓号：</td>
                              <td style="background:#ffffff;font-family:\'微软雅黑\';"><strong style="color:#000000;font-family:\'微软雅黑\'">&nbsp;&nbsp;'.$this->orderarr['warehousing'].'</strong></td>
                            </tr>
                      </table>
                    </td>
                </tr>
            </table>';
		   }elseif($this->orderarr['delivery_type']==3){
		     $mess .='<table cellspacing="0" border="0" cellpadding="0" width="830" style="font-family:\'微软雅黑\';" >
                <tr>
                    <td valign="middle" colspan="2" align="left" height="40">
                    <span style="font-size:14px;font-weight:bold; display:inline-block; padding:3px 0; background:#555555;color:#ffffff;font-family:\'微软雅黑\'">&nbsp;&nbsp;&nbsp;收货信息&nbsp;&nbsp;&nbsp;</span>
                	</td>
                </tr>
                <tr>
                    <td style="font-size:34px; ">&nbsp;</td>
                    <td valign="top" align="left" >
                      <table width="830" border="0" cellspacing="0" cellpadding="0" bgcolor="#ffffff" style="line-height:20px; font-size:12px; color:#565656;font-family:\'微软雅黑\';border:1px solid #d6d6d6">
                            <tr  bgcolor="#ffffff">
                              <td height="30" width="80" style="background:#ffffff;font-family:\'微软雅黑\';border-bottom:1px solid #d6d6d6;border-right:1px solid #d6d6d6">&nbsp;&nbsp;公司名称：</td>
                              <td width="320" style="background:#ffffff;font-family:\'微软雅黑\';border-bottom:1px solid #d6d6d6;border-right:1px solid #d6d6d6 "><strong style="color:#000000;font-family:\'微软雅黑\'">&nbsp;&nbsp;'.$this->orderarr['companyname'].'</strong></td>
                              <td width="80" style="background:#ffffff;font-family:\'微软雅黑\';border-bottom:1px solid #d6d6d6;border-right:1px solid #d6d6d6">&nbsp;&nbsp;</td>
                              <td style="background:#ffffff;font-family:\'微软雅黑\';border-bottom:1px solid #d6d6d6;"><strong style="color:#000000;font-family:\'微软雅黑\'">&nbsp;&nbsp;</strong></td>
                            </tr>
                            <tr>
                              <td width="80" height="30" style="background:#ffffff;font-family:\'微软雅黑\';border-bottom:1px solid #d6d6d6;border-right:1px solid #d6d6d6">&nbsp;&nbsp;货运方式：</td>
                              <td width="200" style="background:#ffffff;font-family:\'微软雅黑\';border-bottom:1px solid #d6d6d6;border-right:1px solid #d6d6d6"><strong style="color:#000000;font-family:\'微软雅黑\'">&nbsp;&nbsp;用户上门自取</strong></td>
                              <td width="80" style="background:#ffffff;font-family:\'微软雅黑\';border-bottom:1px solid #d6d6d6;border-right:1px solid #d6d6d6">&nbsp;&nbsp;取货时间：</td>
                              <td style="background:#ffffff;font-family:\'微软雅黑\';border-bottom:1px solid #d6d6d6;"><strong style="color:#000000;font-family:\'微软雅黑\'">&nbsp;&nbsp;'.($this->orderarr['delivery_place']=='SZ'?$this->delivery_workdate_sz:$this->delivery_workdate_hk).'</strong></td>
                            </tr>
		   	
                            <tr  bgcolor="#ffffff">
                              <td height="30" style="background:#ffffff;font-family:\'微软雅黑\';border-bottom:1px solid #d6d6d6;border-right:1px solid #d6d6d6">&nbsp;&nbsp;取货地址：</td>
                              <td style="background:#ffffff;font-family:\'微软雅黑\';border-bottom:1px solid #d6d6d6;border-right:1px solid #d6d6d6"><strong style="color:#000000;font-family:\'微软雅黑\'">&nbsp;&nbsp;'.($this->orderarr['delivery_place']=='SZ'?$this->delivery_add_sz:$this->delivery_add_hk).'</strong></td>
                              <td style="background:#ffffff;font-family:\'微软雅黑\';border-bottom:1px solid #d6d6d6;border-right:1px solid #d6d6d6">&nbsp;&nbsp;联系电话：</td>
                              <td style="background:#ffffff;font-family:\'微软雅黑\';border-bottom:1px solid #d6d6d6;"><strong style="color:#000000;font-family:\'微软雅黑\'">&nbsp;&nbsp;'.($this->orderarr['delivery_place']=='SZ'?$this->delivery_tel_sz:$this->delivery_tel_hk).'</strong></td>
                            </tr>
                            <tr  bgcolor="#ffffff">
                              <td height="30" style="background:#ffffff;font-family:\'微软雅黑\';border-right:1px solid #d6d6d6">&nbsp;&nbsp;备注：</td>
                              <td colspan="3" style="background:#ffffff;font-family:\'微软雅黑\';"><strong style="color:#000000;font-family:\'微软雅黑\'">&nbsp;&nbsp;'.($this->orderarr['delivery_place']=='SZ'?$this->delivery_des_sz:$this->delivery_des_hk).'</strong></td>
                            </tr>
                      </table>
                    </td>
                </tr>
            </table>';
		  }elseif($this->orderarr['delivery_type']==4){
		   	  $mess .='<table cellspacing="0" border="0" cellpadding="0" width="830" style="font-family:\'微软雅黑\';" >
                <tr>
                    <td valign="middle" colspan="2" align="left" height="40">
                    <span style="font-size:14px;font-weight:bold; display:inline-block; padding:3px 0; background:#555555;color:#ffffff;font-family:\'微软雅黑\'">&nbsp;&nbsp;&nbsp;收货信息&nbsp;&nbsp;&nbsp;</span>
                	</td>
                </tr>
                <tr>
                    <td style="font-size:34px; ">&nbsp;</td>
                    <td valign="top" align="left" >
                      <table width="830" border="0" cellspacing="0" cellpadding="0" bgcolor="#ffffff" style="line-height:20px; font-size:12px; color:#565656;font-family:\'微软雅黑\';border:1px solid #d6d6d6">
                            <tr  bgcolor="#ffffff">
                              <td height="30" width="80" style="background:#ffffff;font-family:\'微软雅黑\';border-bottom:1px solid #d6d6d6;border-right:1px solid #d6d6d6">&nbsp;&nbsp;公司名称：</td>
                              <td width="320" style="background:#ffffff;font-family:\'微软雅黑\';border-bottom:1px solid #d6d6d6;border-right:1px solid #d6d6d6 "><strong style="color:#000000;font-family:\'微软雅黑\'">&nbsp;&nbsp;'.$this->orderarr['companyname'].'</strong></td>
                              <td width="80" style="background:#ffffff;font-family:\'微软雅黑\';border-bottom:1px solid #d6d6d6;border-right:1px solid #d6d6d6">&nbsp;&nbsp;快递商：</td>
                              <td style="background:#ffffff;font-family:\'微软雅黑\';border-bottom:1px solid #d6d6d6;"><strong style="color:#000000;font-family:\'微软雅黑\'">&nbsp;&nbsp;'.$this->orderarr['express_name'].'</strong></td>
                            </tr>
                            <tr>
                              <td width="80" height="30" style="background:#ffffff;font-family:\'微软雅黑\';border-bottom:1px solid #d6d6d6;border-right:1px solid #d6d6d6">&nbsp;&nbsp;货运方式：</td>
                              <td width="200" style="background:#ffffff;font-family:\'微软雅黑\';border-bottom:1px solid #d6d6d6;border-right:1px solid #d6d6d6"><strong style="color:#000000;font-family:\'微软雅黑\'">&nbsp;&nbsp;客户提供账号</strong></td>
                              <td width="80" style="background:#ffffff;font-family:\'微软雅黑\';border-bottom:1px solid #d6d6d6;border-right:1px solid #d6d6d6">&nbsp;&nbsp;快递账号：</td>
                              <td style="background:#ffffff;font-family:\'微软雅黑\';border-bottom:1px solid #d6d6d6;"><strong style="color:#000000;font-family:\'微软雅黑\'">&nbsp;&nbsp;'.($this->orderarr['express_account']).'</strong></td>
                            </tr>
		   	
                            <tr  bgcolor="#ffffff">
                              <td height="30" style="background:#ffffff;font-family:\'微软雅黑\';border-bottom:1px solid #d6d6d6;border-right:1px solid #d6d6d6">&nbsp;&nbsp;收货人：</td>
                              <td style="background:#ffffff;font-family:\'微软雅黑\';border-bottom:1px solid #d6d6d6;border-right:1px solid #d6d6d6"><strong style="color:#000000;font-family:\'微软雅黑\'">&nbsp;&nbsp;'.($this->orderarr['name']).'</strong></td>
                              <td style="background:#ffffff;font-family:\'微软雅黑\';border-bottom:1px solid #d6d6d6;border-right:1px solid #d6d6d6">&nbsp;&nbsp;联系方式：</td>
                              <td style="background:#ffffff;font-family:\'微软雅黑\';border-bottom:1px solid #d6d6d6;"><strong style="color:#000000;font-family:\'微软雅黑\'">&nbsp;&nbsp;'.($this->orderarr['tel']).'</strong></td>
                            </tr>
                            <tr  bgcolor="#ffffff">
                              <td height="30" style="background:#ffffff;font-family:\'微软雅黑\';border-right:1px solid #d6d6d6">&nbsp;&nbsp;收货地址：</td>
                              <td colspan="3" style="background:#ffffff;font-family:\'微软雅黑\';"><strong style="color:#000000;font-family:\'微软雅黑\'">&nbsp;&nbsp;'.$this->orderarr['address'].'</strong></td>
                            </tr>
                      </table>
                    </td>
                </tr>
            </table>';
		   }                              		              		
        $mess .='</td>
        </tr>
        </table>
    </td>
</tr>';
        if($this->orderarr['invoiceid']>0){
        	$mess .='<!--发票信息-->
<tr valign="top">
    <td >
        <table cellspacing="0" cellpadding="0" border="0" align="center" width="730" bgcolor="#f9f9f9"  style=" font-size:12px; line-height:20px; color:#5b5b5b;font-family:\'微软雅黑\'; padding:0 0 10px 0; margin:0; border-collapse:separate; border-spacing:0px" >       
        <tr>
           <td bgcolor="#f9f9f9">
        	<table cellspacing="0" border="0" cellpadding="0" width="830" style="font-family:\'微软雅黑\';" >
                <tr>
                    <td valign="middle" colspan="2" align="left" height="40">
                    <span style="font-size:14px;font-weight:bold; display:inline-block; padding:3px 0; background:#555555;color:#ffffff;font-family:\'微软雅黑\'">&nbsp;&nbsp;&nbsp;发票信息&nbsp;&nbsp;&nbsp;</span>
                	</td>
                </tr>
                <tr>
                    <td style="font-size:34px; ">&nbsp;</td>
                    <td valign="top" align="left" >';
        	        if($this->orderarr['itype']==1){
        	        	$mess .='<table width="830" border="0" cellspacing="0" cellpadding="0" bgcolor="#ffffff" style="line-height:20px; font-size:12px; color:#565656;font-family:\'微软雅黑\';border:1px solid #d6d6d6">
                            <tr  bgcolor="#ffffff">
                              <td height="30" width="100" style="background:#ffffff;font-family:\'微软雅黑\';border-bottom:1px solid #d6d6d6;border-right:1px solid #d6d6d6">&nbsp;&nbsp;发票类型：</td>
                               <td colspan="3" width="300" style="background:#ffffff;font-family:\'微软雅黑\';border-bottom:1px solid #d6d6d6;"><strong style="color:#000000;font-family:\'微软雅黑\'">&nbsp;&nbsp;普通发票</strong></td>
                            </tr>
                            <tr>
                              <td width="100" height="30" style="background:#ffffff;font-family:\'微软雅黑\';border-bottom:1px solid #d6d6d6;border-right:1px solid #d6d6d6">&nbsp;&nbsp;发票抬头：</td>
                              <td width="300" style="background:#ffffff;font-family:\'微软雅黑\';border-bottom:1px solid #d6d6d6;border-right:1px solid #d6d6d6"><strong style="color:#000000;font-family:\'微软雅黑\'">&nbsp;&nbsp;'.$this->orderarr['iname'].'</strong></td>
                              <td width="100" style="background:#ffffff;font-family:\'微软雅黑\';border-bottom:1px solid #d6d6d6;border-right:1px solid #d6d6d6">&nbsp;&nbsp;发票内容：</td>
                              <td style="background:#ffffff;font-family:\'微软雅黑\';border-bottom:1px solid #d6d6d6;"><strong style="color:#000000;font-family:\'微软雅黑\'">&nbsp;&nbsp;'.$contypeArr[$this->orderarr['contype']].'</strong></td>
                            </tr>';
        	        }else{
        	        	$mess .='<table width="830" border="0" cellspacing="0" cellpadding="0" bgcolor="#ffffff" style="line-height:20px; font-size:12px; color:#565656;font-family:\'微软雅黑\';border:1px solid #d6d6d6">
                            <tr  bgcolor="#ffffff">
                              <td height="30" width="100" style="background:#ffffff;font-family:\'微软雅黑\';border-bottom:1px solid #d6d6d6;border-right:1px solid #d6d6d6">&nbsp;&nbsp;发票类型：</td>
                              <td colspan="3" width="300" style="background:#ffffff;font-family:\'微软雅黑\';border-bottom:1px solid #d6d6d6;"><strong style="color:#000000;font-family:\'微软雅黑\'">&nbsp;&nbsp;增值税发票(17%)</strong></td>
                             </tr>
                            <tr>
                              <td width="100" height="30" style="background:#ffffff;font-family:\'微软雅黑\';border-bottom:1px solid #d6d6d6;border-right:1px solid #d6d6d6">&nbsp;&nbsp;单位名称：</td>
                              <td width="300" style="background:#ffffff;font-family:\'微软雅黑\';border-bottom:1px solid #d6d6d6;border-right:1px solid #d6d6d6"><strong style="color:#000000;font-family:\'微软雅黑\'">&nbsp;&nbsp;'.$this->orderarr['iname'].'</strong></td>
                              <td width="100" style="background:#ffffff;font-family:\'微软雅黑\';border-bottom:1px solid #d6d6d6;border-right:1px solid #d6d6d6">&nbsp;&nbsp;纳税人识别号：</td>
                              <td style="background:#ffffff;font-family:\'微软雅黑\';border-bottom:1px solid #d6d6d6;"><strong style="color:#000000;font-family:\'微软雅黑\'">&nbsp;&nbsp;'.$this->orderarr['identifier'].'</strong></td>
                            </tr>
                            <tr>
                              <td height="30" style="background:#ffffff;font-family:\'微软雅黑\';border-bottom:1px solid #d6d6d6;border-right:1px solid #d6d6d6">&nbsp;&nbsp;注册地址：</td>
                              <td style="background:#ffffff;font-family:\'微软雅黑\';border-bottom:1px solid #d6d6d6;border-right:1px solid #d6d6d6"><strong style="color:#000000;font-family:\'微软雅黑\'">&nbsp;&nbsp;'.$this->orderarr['regaddress'].'</strong></td>
                              <td style="background:#ffffff;font-family:\'微软雅黑\';border-bottom:1px solid #d6d6d6;border-right:1px solid #d6d6d6">&nbsp;&nbsp;注册电话：</td>
                              <td style="background:#ffffff;font-family:\'微软雅黑\';border-bottom:1px solid #d6d6d6;"><strong style="color:#000000;font-family:\'微软雅黑\'">&nbsp;&nbsp;'.$this->orderarr['regphone'].'</strong></td>
                            </tr>		
                            <tr>
                              <td height="30" style="background:#ffffff;font-family:\'微软雅黑\';border-bottom:1px solid #d6d6d6;border-right:1px solid #d6d6d6">&nbsp;&nbsp;开户银行：</td>
                              <td style="background:#ffffff;font-family:\'微软雅黑\';border-bottom:1px solid #d6d6d6;border-right:1px solid #d6d6d6"><strong style="color:#000000;font-family:\'微软雅黑\'">&nbsp;&nbsp;'.$this->orderarr['bank'].'</strong></td>
                              <td style="background:#ffffff;font-family:\'微软雅黑\';border-bottom:1px solid #d6d6d6;border-right:1px solid #d6d6d6">&nbsp;&nbsp;银行账户：</td>
                              <td style="background:#ffffff;font-family:\'微软雅黑\';border-bottom:1px solid #d6d6d6;"><strong style="color:#000000;font-family:\'微软雅黑\'">&nbsp;&nbsp;'.$this->orderarr['account'].'</strong></td>
                            </tr>';
        	        }
        	        if(in_array($this->orderarr['delivery_type'],array(1,2))){
        	        	if($this->orderarr['addressid']!=$this->orderarr['invoiceaddress'])
        	        	{
        	        		$mess .='<tr  bgcolor="#ffffff">
                              <td height="30" style="background:#ffffff;font-family:\'微软雅黑\';border-right:1px solid #d6d6d6">&nbsp;&nbsp;收发票地址：</td>
                              <td colspan="3" style="background:#ffffff;font-family:\'微软雅黑\';"><strong style="color:#000000;font-family:\'微软雅黑\'">&nbsp;&nbsp;'.$this->fun->createAddress($this->orderarr['province_i'],$this->orderarr['city_i'],$this->orderarr['area_i'],$this->orderarr['address_i']).' ; '.$this->orderarr['name_i'].' ; '.$this->orderarr['tel_i'].'  '.$this->orderarr['mobile_i'].'</strong></td>
                            </tr>';
        	        	}else{
        	        		$mess .='<tr  bgcolor="#ffffff">
                              <td height="30" style="background:#ffffff;font-family:\'微软雅黑\';border-right:1px solid #d6d6d6">&nbsp;&nbsp;收发票地址：</td>
                              <td colspan="3" style="background:#ffffff;font-family:\'微软雅黑\';"><strong style="color:#000000;font-family:\'微软雅黑\'">&nbsp;&nbsp;'.$this->fun->createAddress($this->orderarr['province_i'],$this->orderarr['city_i'],$this->orderarr['area_i'],$this->orderarr['address_i']).'</strong></td>
                            </tr>';
        	        	}
        	        }
                    $mess .='</table></td>
                </tr>
            </table>
        </td>
        </tr>
        </table>
    </td>
</tr>';}
		echo $mess;
		?>
        	
        </table>
    </td>
  </tr>


</tbody></table>
</div>
<div class="clr"></div>