<?php 
$paytypearray = array('online'=>'在线支付','transfer'=>'银行转账','cod'=>'货到付款','mts'=>'款到发货');
$statusarr = array('101'=>'待客户支付货款',
    			'102'=>'待处理',
    			'103'=>'待支付余款',
    			'201'=>'待发货',
    			'202'=>'已发货',
    			'301'=>'已完成',
    			'302'=>'已评价',
    			'401'=>'订单被取消');
?>
<div class="conmian">
  <h1><?php echo $this->AreaTitle;?>
  <?php if($this->soprod){?>
   -> <a href="/icwebadmin/RepoOr/export?sdata=<?=$this->sdata?>&edata=<?=$this->edata?>&property=<?=$this->property?>&brand=<?=$this->selectbrand?>&xsname=<?=$this->xsname?>&prodtype=<?=$this->prodtype?>&ordertype=<?=$this->ordertype?>" target="_blank" title="将搜索结果导出成Excel">导出Excel</a>
  <?php }?>
  </h1>
  <form id="myform"  class="form-search" name="myform" action="" method="get">
    <label>开始时间：</label>
    <input type="text"  style="width:80px;" name="sdata" value="<?=$this->sdata?>" onclick="WdatePicker({startDate:'',dateFmt:'yyyy-MM-dd',alwaysUseStartDate:true,lang:'sc'})"/>
    <label>结束时间：</label>
    <input type="text"  style="width:80px;" name="edata" value="<?=$this->edata?>" onclick="WdatePicker({startDate:'',dateFmt:'yyyy-MM-dd',alwaysUseStartDate:true,lang:'sc'})"/>
    
    <select name="property">
<option value="">客户性质-全部</option>
<option value='merchant' <?=($this->property=='merchant'?'selected':'')?>>贸易商</option>
<option value='enduser' <?=($this->property=='enduser'?'selected':'')?>>终端用户</option>
</select>
   
<select name="brand">
<option value="">产品线-全部</option>
<?php foreach($this->brand as $bd){?>
<option value='<?=$bd['id']?>' <?=$bd['id']==$this->selectbrand?'selected':''?>><?=$bd['name']?></option>
<?php }?>
</select>

<select name="prodtype">
<option value="">型号类型-全部</option>
<option value='staged' <?=$this->prodtype=='staged'?'selected':''?>>难寻器件</option>
</select>

<?php if($_SESSION['staff_sess']['level_id']!='XS'){?>
<div class="input-append">
<select name="xsname" id="xsname">
      <option value="" <?=$this->xsname==''?'selected':''?>>跟进销售-全部</option>
      <option value="alina.shang" <?=$this->xsname=='alina.shang'?'selected':''?>>尚玉(alina.shang)</option>
      <?php for($i=0;$i<count($this->xs_staff);$i++){?>
      <option value="<?=$this->xs_staff[$i]['staff_id']?>" <?=$this->xsname==$this->xs_staff[$i]['staff_id']?'selected':''?>><?=$this->xs_staff[$i]['lastname'].$this->xs_staff[$i]['firstname']."(".$this->xs_staff[$i]['staff_id'].")"?></option>
      <?php }?>
</select>
</div>
<?php }?>
&nbsp;
<select name="ordertype" id="ordertype">
  <option value="online" <?=$this->ordertype=='online'?'selected':''?>>线上订单</option>
  <option value="outline" <?=$this->ordertype=='outline'?'selected':''?>>线下订单</option>
  <option value="all" <?=$this->ordertype=='all'?'selected':''?>>全部</option>
</select>
    &nbsp;
    <input type="submit" class="btn" value="确 定"/>
  </form>
  <div id="message_sess" style="display:none" class="message_sess">
    <div title="关闭" class="but" onclick="document.getElementById('message_sess').style.display='none'">&nbsp;</div>
    <div id="alert_message"></div>
  </div>
  <!-- 需要填写的区域-->
  <br/>
  <table width="100%" cellspacing="0" cellpadding="0" border="1" align="center" style="border-collapse:collapse;font-size: 12px;border:1px #999 solid;padding-top:0px;">
    <tbody>
      <tr bgcolor="#00B0F0" style="color:#FFFFFF; font-weight:bold;">
        <th>部门</th> 
        <th>销售</th> 
        <th >公司名称</th>
    
        <th >订单号</th>
        
        <th >下单时间</th>
        <th >品牌</th>
        <th >型号</th>
        <th >数量</th>
        <th >单价</th>
        <th >订单金额</th>
        <th >币种</th>
        <th  width="50">支付类型</th>
        <th  width="50">订单状态</th>
        <th  width="50">类型</th>
        <th >SAP订单号</th>
      </tr>
    </tbody>
    <tbody>
      <?php if($this->soprod){
	    foreach($this->soprod as $v){
	  ?>
      <tr height="30px">

       <td><?=$v['department']?></td>
      <td><?=$v['lastname'].$v['firstname']?></td>
      <td><?php if($v['companyname']) echo $v['companyname'];
			else echo $v['uname'];?></td>
     
      <td><?=$v['salesnumber']?></td>
      
      <td><?=date('Y/m/d',$v['created'])?></td>
      <td><?=$v['brandname']?></td>
      <td><?=$v['part_no']?></td>
      <td><?=$v['buynum']?></td>
      <td><?=$v['buyprice']?></td>
      <td><?=number_format($v['buynum']*$v['buyprice'],DECIMAL);?></td>
      <td><?=$v['currency']?></td>
      <td><?=$paytypearray[$v['paytype']]?></td>
      <td><?=$statusarr[$v['sostatus']]?></td>
     <td><?=$v['back_order']?'线下':'线上'?></td>
      <td><?=$v['order_no']?></td>
      </tr>
      <?php }}else echo '<tr height="30px"><td colspan="21" align="center" style="color:#FF0000">请选择时间段查询</td></tr>';?>
        </tbody>
  </table>
  <br/>
  <!-- 结束区域-->
</div>
<script src="/js/jsplug/My97DatePicker/WdatePicker.js" type="text/javascript"></script>