<link rel="stylesheet" href="/js/kindeditor/themes/default/default.css" />
<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
<script src="/js/kindeditor/kindeditor.js"></script>
<script src="/js/kindeditor/lang/zh_CN.js"></script>
<style type="text/css">
span.tag{
border: 1px solid #DDD;
background: #F6F6F6 ;
font-weight: bold;
padding:3px;
margin-right:5px;
}
.tag a{ padding-left:5px;}
#ic-box{ margin-bottom:10px;}
</style>
<div class="conmian">
  <h1><?php echo $this->AreaTitle;?> -> 编辑 <a href="<?=$this->indexurl?>">返回&gt;&gt;</a> </h1>
<?php if (count($this->messages)) : ?>
<div class="alert alert-error">
     <button type="button" class="close" data-dismiss="alert">×</button>
<?php foreach ($this->messages as $message) : ?>
    <strong><?php echo ($message); ?></strong>
<?php endforeach; ?>
 </div>
<?php endif; ?>
<form id="thisform" class="form-horizontal validate-form" style="text-align:left" method="post" action="<?php echo $this->editurl;?>" enctype="multipart/form-data">
  <input type="hidden" name="id" value="<?=$this->data['id']?>" />
  <div class="control-group">
    <label class="control-label" for="contents">立即上线</label>
    <div class="controls">
     <input type="checkbox" name="status" value="1" <?=$this->data['status']==1?'checked':''?> >
    </div>
  </div>
   <div class="control-group">
    <label class="control-label" for="contents">推荐</label>
    <div class="controls">
     <input type="checkbox" name="push" value="1" <?=$this->data['push']==1?'checked':''?> >
    </div>
  </div>  
  <div class="control-group">
    <label class="control-label" for="published">上线日期</label>
    <div class="controls">
      <input type="text" id="published" name="published" class="required input-xlarge" title="required" value="<?=date('Y-m-d',$this->data['published'])?>">
    </div>
  </div>  
  <div class="control-group">
    <label class="control-label" for="title">作者</label>
    <div class="controls">
      <input type="text" id="author" name="author" class="required input-xlarge" title="required" style="width:500px;" value="<?=$this->data['author']?>">
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="title">来源</label>
    <div class="controls">
      <input type="text" id="source" name="source" class="required input-xlarge" title="required" style="width:500px;" value="<?=$this->data['source']?>">
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="title"><em>*</em>标题</label>
    <div class="controls">
      <input type="text" id="title" name="title" class="required input-xlarge" title="required" style="width:500px;" value="<?=$this->data['title']?>">
    </div>
  </div>
  
   <div class="control-group">
    <label class="control-label" for="title">设置密码</label>
    <div class="controls">
      <input type="checkbox" name="need_pass" id="need_pass" value="1" <?=$this->data['need_pass']==1?'checked':''?> onclick="changepass(this)">
      <span id="pass_span" style="<?=$this->data['need_pass']==1?'':'display:none'?>">
      密码：<input type="text" id="pass" name="pass" class="required" style="width:100px;" value="<?=$this->data['pass']?>">
      <font color="#666666">0代表密码失效</font>
      </span>
    </div>
  </div>
  
  <div class="control-group">
    <label class="control-label" for="title">需花费积分</label>
    <div class="controls">
    <label><input type="radio" name="spendpoints" value="0" checked="checked"/> 0</label>
    <label><input type="radio" name="spendpoints" value="1" <?=$this->data['spendpoints']==1?'checked="checked"':''?>/>1</label>
    <label><input type="radio" name="spendpoints" value="2" <?=$this->data['spendpoints']==2?'checked="checked"':''?>/>2</label>
    <label><input type="radio" name="spendpoints" value="5" <?=$this->data['spendpoints']==5?'checked="checked"':''?>/>5</label>
    <label><input type="radio" name="spendpoints" value="10" <?=$this->data['spendpoints']==10?'checked="checked"':''?>/>10</label>
    <label><input type="radio" name="spendpoints" value="20" <?=$this->data['spendpoints']==20?'checked="checked"':''?>/>20</label>
    <label><input type="radio" name="spendpoints" value="50" <?=$this->data['spendpoints']==50?'checked="checked"':''?>/>50</label>
    <label><input type="radio" name="spendpoints" value="100" <?=$this->data['spendpoints']==100?'checked="checked"':''?>/>100</label>
      <!--<select id="spendpoints" name="spendpoints">
<option value="0" <?=$this->data['spendpoints']==0?'selected="selected"':''?>>0</option>
<option value="1" <?=$this->data['spendpoints']==1?'selected="selected"':''?>>1</option>
<option value="2" <?=$this->data['spendpoints']==2?'selected="selected"':''?>>2</option>
<option value="5" <?=$this->data['spendpoints']==5?'selected="selected"':''?>>5</option>
<option value="10" <?=$this->data['spendpoints']==10?'selected="selected"':''?>>10</option>
<option value="20" <?=$this->data['spendpoints']==20?'selected="selected"':''?>>20</option>
<option value="50" <?=$this->data['spendpoints']==50?'selected="selected"':''?>>50</option>
<option value="100" <?=$this->data['spendpoints']==100?'selected="selected"':''?>>100</option></select>-->
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="author"><em>*</em>开发环境</label>
    <div class="controls">
      <input type="text" id="dep_environment" class="input-xlarge" style="width:500px;" name="dep_environment" value="<?=$this->data['dep_environment']?>">
    </div>
  </div>

 <div class="control-group">
    <label class="control-label" for="keyword"><em>*</em>关键字</label>
    <div class="controls">
      <input  id="keyword"  class="input-xlarge" name="keyword" style="width:500px;" type="text" value="<?=$this->data['keyword']?>">
    </div>
  </div>     

  <div class="controls"  id="ic-box">
  <?php if($this->data['part_id']){
  					foreach($this->data['part_id'] as $key=>$val){
  	?>
  				<span class="tag"><span class="tag-label"><?=$key?></span><a href="#" class="tag-close">x</a>
  				<input type="hidden" name="part_id[<?=$key?>]"  value="<?=$val?>" >
  				</span>
  <?php 		} 
		}?>
  </div>   
  <div class="control-group">
    <label class="control-label" for="app_level"><em>*</em>应用分类</label>
    <div class="controls">
		<?php echo $this->appSelect('app_level1',1,$this->data['app_level1']);?>
		<?php echo $this->appSelect('app_level2',2,$this->data['app_level2']);?>
    </div>
  </div>    
   


  <div class="control-group">
    <label class="control-label" for="description"><em>*</em>简介</label>
    <div class="controls">
      <textarea  id="description"  name="description" rows="3"  style="width:500px;"><?=$this->data['description']?></textarea>
    </div>
  </div>       
  <div class="control-group">
    <label class="control-label" for="contents"><em>*</em>详细描述</label>
    <div class="controls">
      <textarea name="content" id="content" rows="20" class="kindeditor span9"><?php echo $this->data['content'];?></textarea>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="description"><em>*</em>代码</label>
    <div class="controls">
      <input type="file" id="annexpath"  name="annexpath" />
      <a href="/icwebadmin/NeCode/download?key=<?=$this->fun->encryptVerification($this->data['id'])?>" target="_blank"><?=$this->data['annexname']?></a>
      <em>&nbsp;只支持/.zip/.rar 格式的压缩文件</em>
    </div>
  </div>  
  <div class="control-group">
    <div class="controls">
      <input type="submit" value="编辑" class="btn" />
    </div>
  </div>
</form>
        <br>
      <!-- 结束区域-->
</div>
<?php  $_SESSION['post'] = array();?>
<script type="text/javascript">
function changepass(obj){
	if(obj.checked){
		$("#pass_span").show();
	}else{
		$("#pass_span").hide();
	}
}
$(function(){
	$( "#published" ).datepicker({'dateFormat':'yy-mm-dd'});
	$("#app_level2").chained("#app_level1"); 
	$('#part_level2').chained('#part_level1');
	$('#part_level3').chained('#part_level2');
	$('#related_ic').typeahead(
		{	
			items:8,
			minLength:3,			
		    source: function (query, process) {
		        return $.getJSON('<?php echo $this->ajax_url?>', { q: query }, function (data) {
			        var part =[];
			        map =[];
			        $.each(data,function(id,item){
			        	part.push(item);
			        	map[item] = id;
				     });
		            return process(part);
		        });
		    },
		    updater : function(item)
		    {
				var part_id = map[item];
				var button = '<span class="tag"><span class="tag-label">'+item+'</span><a class="tag-close" href="#">x'+'</a>'
									+'<input type="hidden" name="part_id['+item+']" value="'+part_id+'" ></span>';
				$('#ic-box').append(button);
				return '';
		    }
		    

		}
	);
	$('.tag-close').live('click',function(){
		$(this).parent().remove();
		return false;
	});
});

KindEditor.ready(function(K) {
			var editor =  K.create('#content', {
		     allowFileManager : true
	       });
			 //News Image
			var spe_head_editor = K.editor({
					allowFileManager : true,
					uploadJson : '/icwebadmin/common/upload?part=upload/default/news/',
                    fileManagerJson : '/icwebadmin/common/filemanagerjson?part=upload/default/news/'
			});
			K('#image-upload').click(function() {
				spe_head_editor.loadPlugin('image', function() {
					spe_head_editor.plugin.imageDialog({
						imageUrl : K('#image-upload').val(),
						clickFn : function(url, title, width, height, border, align) {
							K('#image-upload').val(url);
							K('#image').val(url);
							spe_head_editor.hideDialog();
						}
					});
				});
			});
});


</script>
<script src="/js/bootstrap/bootstrap.min.js" type="text/javascript"></script>
<script src="/js/jsplug/jquery.chained.js" type="text/javascript"></script>
<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js" type="text/javascript"></script>