<div class="conmian">
  <h1><?php echo $this->AreaTitle;?>
  <?php if($this->mycommon->checkA($this->Staff_Area_ID) || $this->mycommon->checkW($this->Staff_Area_ID)){?>
                        <a href="<?php echo $this->addurl;?>" >添加+</a>
 <?php }?>
 </h1>
 <form id="myform"  class="form-search" name="myform" action="" method="get">
<?php echo $this->appSelect('app_level1',1,$_GET['app_level1'])?>|
<select name="status" class="span1">
<option value="">状态</option>
<option value="1"  <?php echo $_GET['status'] =='1' ? "selected" : ""; ?>>上线</option>
<option value="0" <?php echo $_GET['status'] =='0' ? "selected" : "";?>>下线</option>
</select>|
<label>标题/关键字：</label>
<div class="input-append">
  <input type="text" class="span3 search-query" id="title" value="<?=$_GET['q']?>" name="q" />
</div>
<input type="submit" class="btn" value="查 找"/>
</form>
<?php if (count($this->messages)) : ?>
<div class="alert fade in">
     <button type="button" class="close" data-dismiss="alert">×</button>
<?php foreach ($this->messages as $message) : ?>
    <p class="message"><strong><?php echo $this->escape($message); ?></strong></p>
<?php endforeach; ?>
 </div>
<?php endif; ?>      
<table class="table ordertable"  border="0" style=" margin-top:-1px;">
                <thead>
                <tr>
                <th>编号</th>
                <th>标题</th>
                <th>作者</th>
                <th>来源</th>
                <th>是否需要密码</th>
                <th>需花费积分</th>
                <th>开发环境</th>
                <th>关键字</th>
                <th>应用分类</th>
                <th>代码</th>
                <th>下载次数</th>
                <th>文件大小</th>
                <th>上线日期</th>
                <th>推荐</th>
                <th>状态</th>
                <th>操作</th>
                </tr>
                </thead>
                <tbody>
				<?php 
				foreach($this->data as $data) : ?>
				<tr>
                <td><?php echo $data['id'];?></td>
				<td><?php echo $data['title'];//echo $inquiry->product;?></td>
                <td><?php echo $data['author'];?></td>
                <td><?php echo $data['source'];?></td>
                <td><?php if($data['need_pass']==1) echo '<font color="#006600">是</font>';else echo '<font color="#FF0000">否</font>';?>
                <br/><?php if($data['need_pass']==1){if($data['pass']!="0"){echo '密码：'.$data['pass'];}else{echo '密码已使用';}};?>
                </td>
				<td><?php echo $data['spendpoints'];?></td>
				<td><?php echo $data['dep_environment'];?></td>
				<td><span title="<?=$data['keyword']?>"><?=$this->fun->utf_substr($data['keyword'],10,'')?></span></td>
				<td><?php echo $data['appname'];?></td>
                <td><a href="/icwebadmin/NeCode/download?key=<?=$this->fun->encryptVerification($data['id'])?>" target="_blank"><?=$data['annexname']?></a></td>
                <td><?=$data['downloadnumber']?></td>
                <td><?=$this->fun->format_bytes(filesize($data['annexpath']))?></td>
				<td><?php echo date('Y-m-d',$data['published']);//echo $inquiry->user;?></td>
                <td><?php if($this->mycommon->checkA($this->Staff_Area_ID) || $this->mycommon->checkW($this->Staff_Area_ID))
				{if($data['push']==1) {?> 
                <a href="/icwebadmin/NeCode/active/id/<?=$data[id]?>?push=0" title="取消推荐"><font color="#006600">是</font></a>
				<?php }else {?>
                <a href="/icwebadmin/NeCode/active/id/<?=$data[id]?>?push=1" title="推荐"><font color="#FF0000">否</font></font></a>
                <?php }}?>
                </td>
                <td><?php if($this->mycommon->checkA($this->Staff_Area_ID) || $this->mycommon->checkW($this->Staff_Area_ID))
				{if($data['status']==1) {?> 
                <a href="/icwebadmin/NeCode/active/id/<?=$data[id]?>?flag=0"  title="点击下线"><font color="#006600">已上线</font></a>
				<?php }else {?>
                <a href="/icwebadmin/NeCode/active/id/<?=$data[id]?>?flag=1" title="点击上线"><font color="#FF0000">已下线</font></font></a>
                <?php }}?>
                </td>
				<td><a href="/code-<?=$data['id']?>.html?preview=1" target="_blank">Preview</a>  
				<?php if($this->mycommon->checkA($this->Staff_Area_ID) || $this->mycommon->checkW($this->Staff_Area_ID)){?>
                 | <a href="/icwebadmin/NeCode/edit/id/<?=$data['id']?>" >Edit</a>
                <?php }?>
				</td>
				</tr>
				<?php endforeach ; ?>
                </tbody>
            </table>      
         <div class="pagination divpage" >
            <?=$this->page_bar;?>
        </div>      
      <!-- 结束区域-->
</div>