<?php $pricearr = explode(',',$this->solution['solution_img']);
 for($k=0;$k<count($pricearr);$k++)
 {
	 if(empty($pricearr[$k])) unset($pricearr[$k]);
 }
 $pricenum = count($pricearr);
?>
<link rel="stylesheet" type="text/css" href="/js/jsplug/imgshow/iStu12.css"/>
<script language="javascript" type="text/javascript" src="/js/jsplug/imgshow/iStu12.js"></script>
<link rel="stylesheet" type="text/css" href="/<?=$_SESSION['new_version']?>/css/default/se2013.css"/>
<script type="text/javascript" language="javascript"> widescreen_css();</script>
<div class="w">
  <div class="breadcrumbs2013"> <span> <a href="/solutionlist" class="focs">应用方案</a> 
  &nbsp;&nbsp;»&nbsp;&nbsp; <a href="/solutionlist-<?=$this->solution['appid']?>.html"><?=$this->solution['name']?></a> 
  &nbsp;&nbsp;»&nbsp;&nbsp; <span title=""><?=$this->solution['title']?></span> </div>
</div>
<div class="w clearfix sch_detal sebox2013">
  <div class="clearfix infolist boxshadow pos-re" >
  <?php if(!$this->solutionrule && !$this->ruled){?>
    <div class="sce_tip"> 
    <a href="javascript:;" onclick="$('.sce_tip').css('display', 'none');" class="sce_tip_close">关闭</a> 
    <a href="javascript:;" onclick="applyapprule('<?=$this->fun->encryptVerification($this->solution['id'])?>')" class="sce_tip_ofter">立即申请</a> </div>
  <?php }?>
    <div class="schemeimg_d fl"> <img src="<?=($this->solution['sol_img'])?(APPICON.$this->solution['sol_img']):(SOLUTIONICON.$pricearr[0])?>"  width="300" height="210" alt="<?=$this->solution['title']?>"/> </div>
    <div class="posts pos-re">
      <h1><span class="ifotip2013"><em><?=$this->solution['name']?></em><i></i></span><?=$this->solution['title']?></h1>
      <div class="postmeta"> <span>标签：</span><?php 
					$tip = explode(',',$this->solution['tags']);
					for($i=0;$i<count($tip);$i++){
						echo $tip[$i].' ';
					}?></div>
      <div class="row">
        <div class="post-cont">
          <p> <?=$this->solution['description']?></p>
        </div>
      </div>
      <div class="read_more">
        <div class="fl"> 
		<?=$this->solution['solution_no']?'<span class="fontgray">方案编号：</span>'.$this->solution['solution_no']:'';?> 
		<?=$this->solution['source']?'<span class="fontgray">来源：'.$this->solution['source'].'&nbsp;&nbsp;</span>':''?>
        <?=$this->solution['author']?'<span class="fontgray">作者：'.$this->solution['author'].'&nbsp;&nbsp;</span>':''?>
        <span class="fontgray">创建时间：<?=date('Y-m-d',$this->solution['created'])?></span>
        </div>
        <div class="fr">
        <?php if(!empty($this->solution['datasheet'])){?>
      <a href="<?=$this->solution['datasheet']?>" target="_blank" class="btnok-new1 logclick"  rev="solutionview_datasheet" rel="     <?=$this->solution['id']?>"><i class=""></i>方案下载</a>
      <?php }?>
      </div>
        <div class="clr"></div>
      </div>
    </div>
  </div>
  
  <!--无权限-->
  <?php if(!$this->loginview){?>
  <div class=" clearfix " style="margin-top:3PX">
    <div class="layout rigybg" >
      <div class="shoplist fl">
        <div class="MT20 fore1">
          <div class="list—tit">
            <h2>方案概述</h2>
          </div>
          <div class="shoplistbox_con boxshadow_h">
            <p><?=$this->solution['outline']?></p>
          </div>
        </div>
        <div class="MT20 fore2">
          <div class="list—tit">
            <h2>核心优势</h2>
          </div>
          <div class="shoplistbox_con boxshadow_h">
            <p> <?=$this->solution['superiority']?></p>
          </div>
        </div>
        <?php  if(!empty($pricearr)){?>
        <div class="MT20 fore3">
          <div class="list—tit">
            <h2>方案设计图</h2>
          </div>
          <div class="shoplistbox_con">
            <ul class="iStu12 clearfix">
          <?php  if($pricenum > 1) echo '<li class="prev" title="上一张"></li>';?>
          <li class="images">
            <div class="slide">
              <?php 
					foreach($pricearr as $pricesrc){ 
						echo '<img src="'.SOLUTIONICON.$pricesrc.'""/>';
					}
			    ?>
            </div>
          </li>
          <?php  if($pricenum > 1) echo '<li class="next" title="下一张"></li>';?>
          <li class="caption"></li>
        </ul>
          </div>
        </div>
        <?php }?>
        
         <?php if(!empty($this->solprodArray)){?>
        <div class="MT20 fore4">
          <div class="list—tit">
            <h2>方案关键器件表</h2>
            <!--<div class="list—tit_ifo labelinput"> <a href="#" class="gbqfb">购买所选产品</a>
              <label>
              <input type="checkbox" />
              全选</label>
            </div>-->
          </div>
          <div class=" ">
            <table cellpadding="0" cellspacing="0"  class="listtable boxshadow_h" border="0">
              <tbody>
               <tr>
            <th width="10%">图片</th>
            <th width="15%">型号</th>
            <th width="10%">品牌</th>
            <th width="15%">产品描述</th>
            <th width="10%">数据文档</th>
            <th width="10%">应用笔记</th>
            <th width="5%">库存</th>
            <th width="10%">阶梯价格</th>
            <th width="10%">操作</th>
        </tr>
        <?php
		  foreach($this->solprodArray as $k=>$prod){
			$prod = $this->fun->filterProduct($prod);
			$break_price='';
			$stock = 0;$show_price = 0;
			if($prod['f_show_price_sz']){
			    $show_price = $prod['f_show_price_sz'];
				$stock      = $prod['f_stock_sz'];
				$break_price = $prod['f_break_price_notitle_sz'];
			}elseif($prod['f_show_price_hk']){
			    $show_price = $prod['f_show_price_hk'];
				$stock      = $prod['f_stock_hk'];
				$break_price = $prod['f_break_price_notitle_hk'];
			}elseif($prod['f_break_price_notitle_sz']){
				$break_price = $prod['f_break_price_notitle_sz'];
			}elseif($prod['f_break_price_notitle_hk']){
				$break_price = $prod['f_break_price_notitle_hk'];
			}
			$bgclass='';
			if($k%2==1) $bgclass = 'class="trbg"';
		?>
        <tr <?=$bgclass?>>
            <td class="productIMG">
            <a target="_blank" href="<?=$prod['f_produrl']?>" class="model logclick" title="<?=$prod['part_no']?>" rev="prodlist_part_id" rel="<?=$prod['id']?>"><img src="<?=PRODUCTICON.($prod['part_img']==''?'no.gif':$prod['part_img'])?>" width="80" /></a>
            </td>
            <td align="left" >
          	 <div class="productNO pmodel201312" >
                <a target="_blank" href="<?=$prod['f_produrl']?>" class="model logclick" title="<?=$prod['part_no']?>" rev="prodlist_part_id" rel="<?=$prod['id']?>"><?=$prod['part_no']?></a>
                <sup>
                 <?php if($prod['staged']) echo '<span class="sup_SALE">特卖</span>';
				if($prod['pdnpcn']['pdn']) echo '<a class="sup_PDN">PDN</a>';
				if($prod['pdnpcn']['pcn']) echo '<a class="sup_PCN">PCN</a>';
				?>
                </sup>
            </div>
            </td>
            <td><?=$prod['bname']?></td>
            <td align="left" class="en"><p title="<?=$prod['description']?>" style="word-break:break-all;"><?=$this->fun->utf_substr($prod['description'],68)?></p> </td>
            <td>
            <?php if($prod['datasheet']) {
	        $dsarr = explode('<>',$prod['datasheet']);
			$dsstr = $dsarr[0]?$dsarr[0]:$dsarr[1];
			     $datasheet_name = $datasheet = '';
    			 $tmparr = explode('()',$dsstr);
				 if(count($tmparr)==2){
				 	$datasheet_name = $tmparr[0];
					$datasheet      = $tmparr[1];
				 }else{
				 	$datasheet_name = '数据文档';
					$datasheet      = $tmparr[0];
				 }
				
				 ?>
                <!--<?=$datasheet_name?><br />-->
            <a href="<?=$datasheet?>" target="_blank" title="<?=$prodarr['part_no'].$datasheet_name;?>"  class="logclick" rev="prodderails_datasheet" rel="<?=$this->prodarr['id']?>"><i class="icon_pdf"></i></a>
            <?php }else echo '--';?>
            </td>
            <td>
            <a href="<?=$prod['f_produrl']?>" target="_blank"><i class="icon_download"></i></a></td>
            <td><?php
                    if(($prod['f_stock_sz']+$prod['f_stock_hk'])>0){echo '<font color="#469F68">现货</font>';}
					else {echo '<font color="#FC9C30">订货</font>';}?></td>
            <td align="center">
                <div class="pprice201312_detail">
                        <?=($break_price?$break_price:'--')?>
                    </div>                 
</td>
            <td  class="borderbottomlas">
            	<div class="tabelbtn">
                   
            
            <?php if($show_price){?><a href="javascript:" onclick="buy('<?=$prod['id']?>.')"  class="gbqfb logclick" title="购买"  rev="prodlist_part_id" rel="<?=$prod['id']?>"><i class="i_buy_s"></i>在线购买</a>
            <?php }else{?>
           <!-- <a class="gbqfb ">购买</a>-->
            <?php }?>
            
            <?php if($prod['samples'] && $prod['f_stock_sz']>0){?>
                <a href="javascript:;" class="gbqfbbig_h" onclick="appSamples('<?=$this->fun->encryptVerification($prod['id'])?>')" title="我要申请">免费样片</a><?php }?>
                
                <?php if(!$prod['noinquiry']){?>
                 <a href="javascript:" onclick="openInquiry('<?=$prod['id']?>')" class="gbqfb logclick" title="询价"  rev="prodlist_part_id" rel="<?=$prod['id']?>"><i class="i_xun_s"></i>批量询价</a><br/>
            <?php }else{?>
            	<!--<a class="gbqfb ">询价</a>-->
            <?php }?>
                </div> 
            </td>
        </tr>
		<?php }//end ?>
              </tbody>
            </table>
          </div>
        </div>
        <?php }?>
      </div>
      <div class="fr righttuij">
        <div id="hotsearch">
          <div style=" margin:20px;"><img src="/images/admin/ajax-loader.gif" /></div>
        </div>
        <div id="hotnews"></div>
        <div id="hotwebinar"></div>
        <div id="htocode"></div>
        <div id="hotsolution"></div>
      </div>
      <div class="clr"></div>
    </div>
  </div>
  <script language="javascript">
	$(function(){
		$("#hotsearch").load("/publicbox/hotsearch");
		$("#hotsolution").load("/publicbox/hotsolution?sid=<?=$this->solution['id']?>");
		$("#hotnews").load("/publicbox/hotnews");
		$("#hotwebinar").load("/publicbox/hotwebinar");
		$("#htocode").load("/publicbox/htocode");
	})
</script>
  <!--end 无权限-->
  <?php }else{?>
  <!-- 有权限-->
  
  <script src="/js/jsplug/jGrowl-master/jquery.jgrowl.js"></script>
  <link rel="stylesheet" type="text/css" href="/js/jsplug/jGrowl-master/jquery.jgrowl.css"/>
  <link rel="stylesheet" type="text/css" href="/js/jsplug/jGrowl-master/theme.css"/>

<script type="text/javascript">
    //计算时间
	var f_time =  s_time = <?=time()?>;
    //点击切换
    var end = false;
	var view= new Array();
	var nowtype = '<?=$_SESSION['view_now'][$this->solid]['type'];?>';
	var now = <?=$_SESSION['view_now'][$this->solid]['visit']?>;
	var view_number = <?=$_SESSION['view_now'][$this->solid]['number'];?>
	//历史访问过的
	for(var i=1;i<=view_number;i++){
		view[i] = i;
	}
	
	function changeli(num,type){
	    if(num==now){return;}
	    if(num > (now+1) && !end){
		    var exit = false;
		    for (var i = 0; i <view.length; i++) {
                if (view[i] == num || view[i] == (num-1)) {exit = true;break;}
            }
			if(!exit) {
			    //alert('此模块还没激活，请按顺序访问。');
			    return;
			}
		}
		if((num-1)==now && !end){
				var lastobj = $(".li_"+(num-1));
				lastobj.removeClass("start1");
				lastobj.addClass("start4");
				lastobj.removeClass("start6");
				
				var nowobj = $(".li_"+num);
				nowobj.removeClass("start2")
				nowobj.removeClass("start4");
				nowobj.addClass("start1");
				nowobj.addClass("start5");
				
				var nextobj = $(".li_"+(num+1));
				nextobj.removeClass("start3");
				var exit2=false;
				for (var i = 0; i <view.length; i++) {
                   if (view[i] == num) {exit2 = true;break;}
                }
				if(!exit2) {nextobj.addClass("start2");}
		}else{
		    var nowobj = $(".li_"+num);
			nowobj.removeClass("start2");
			nowobj.addClass("start1");
			nowobj.addClass("start5");
			nowobj.addClass("start6");
			var oldobj = $(".li_"+(now));
			oldobj.removeClass("start1");
			oldobj.removeClass("start6");
			oldobj.addClass("start4");
			if(!end){
				var exit3=false;
				for (var i = 0; i <view.length; i++) {
                   if (view[i] == (num+1)) {exit3 = true;break;}
                }
				if(!exit3) {
				  var nextobj = $(".li_"+(num+1));
				  nextobj.removeClass("start3");
				  nextobj.addClass("start2");
				}
			}
		}
		//显示，隐藏div
		$(".content_"+type).removeClass("hide");
		$(".content_"+nowtype).addClass("hide");
		
		//记录开始停留时间
		logaddtime(now,num,s_time,nowtype,type);
		
		//赋值
		nowtype = type;
		now = num;
		if(now==9) end = true;
		view[num] = num;
	}
//关闭或刷新
window.onbeforeunload = function(){
	logaddtime(now,now,s_time,nowtype,nowtype);
    return '';
}
//记录时间
function logaddtime(now,num,time,nowtype,type){
	$.ajax({
        url: '/applications/recordtime',
        data: {'solid':<?=$this->solid?>,'now':now,'num':num,'s_time':time,'nowtype':nowtype,'type':type},
        type: 'post',
        dataType: 'json',
        success: function(arr) { 
			s_time = arr.nowtime;
			//打开提示框
			$('#messagebox').jGrowl(arr.messagehtml);
		}
    });
}
</script>
<!--提示框-->
<div id="messagebox" class="jGrowl bottom-right"></div>

<div class="clearfix">
  <div class="steptitle fl">
    <div class="steptopok"></div>
    <ul>
      <?php 
	  $typenameArray = array('fags'=>'方案概述','hxyx'=>'核心优势','fakt'=>'方案框图',
		  		'hxqj'=>'核心器件','zbqj'=>'周边器件','bomd'=>'BOM清单',
		  		'cgal'=>'成功案例','sjwd'=>'设计文档','jszq'=>'技术支持');
	  $linum = 0;
	  foreach($this->solutionrule as $typename=>$rule){
	      if($rule=='A'){$linum++;?>
      <li <?=(count($this->solutionrule)==$linum?'class="listartend"':'')?>>
        <div class="steplidiv li_<?=$linum?> <?php if($_SESSION['view_now'][$this->solid]['visit']==$linum) echo 'start1 start6';
								   elseif($_SESSION['view_now'][$this->solid]['number']==($linum-1)) echo 'start2';
		                           elseif($_SESSION['view_now'][$this->solid]['number']<$linum) echo 'start3';
								   else echo 'start4 start5';?>">
          <div class="stepmidbg"></div>
          <div class="stepicon"></div>
          <a href="javascript:" onclick="changeli(<?=$linum?>,'<?=$typename?>');return false;"><?=$typenameArray[$typename]?></a> <i class="triangebg"></i> </div>
      </li>
      <?php }
	  }
	  ?>
    </ul>
    <div class="stepbottom"></div>
  </div>
  <?php if(array_key_exists('fags',$this->solutionrule)){?>
  <!-- 方案概述-->
  <div class="schemecontent fr content_fags <?php if($_SESSION['view_now'][$this->solid]['visittype']!='fags') echo 'hide';?>">
    <div class="schemecontent_tit">
      <h3>方案概述</h3>
    </div>
    <div class="schemecontent_box">
      <?=$this->solution['outline']?>
    </div>
  </div>
  <?php }?>
  
   <?php if(array_key_exists('hxyx',$this->solutionrule)){?>
   <!-- 核心优势-->
    <div class="schemecontent fr content_hxyx <?php if($_SESSION['view_now'][$this->solid]['visittype']!='hxyx') echo 'hide';?>">
    	<div class="schemecontent_tit"><h3>核心优势</h3></div>
        <div class="schemecontent_box">
             <?=$this->solution['superiority']?>
        </div>
    </div>
    <?php }?>
    
    <?php if(array_key_exists('fakt',$this->solutionrule)){?>
   <!--方案图片-->
    <div class="schemecontent fr content_fakt <?php if($_SESSION['view_now'][$this->solid]['visittype']!='fakt') echo 'hide';?>">
      <div class="schemecontent_tit"><h3>方案框图</h3></div>
      <div class="schemecontent_box">
              <?php 
					foreach($pricearr as $pricesrc){ 
						echo '<img src="'.SOLUTIONICON.$pricesrc.'" style="max-width:760px"
/><br/><br/>';
					}
			    ?>
      </div>
    </div>
    <?php }?>
    
    <?php if(array_key_exists('hxqj',$this->solutionrule)){?>
    <!--核心器件-->
    <div class="schemecontent fr content_hxqj <?php if($_SESSION['view_now'][$this->solid]['visittype']!='hxqj') echo 'hide';?>">
    	<div class="schemecontent_tit"><h3>核心器件</h3></div>
        <div class="schemecontent_box">
        	<p class="pmarg"><?=$this->solution['core_device_des']?></p>
            <div class="promianbox">	
			<?php 
			if($this->hxpart){
			foreach($this->hxpart as $v){
			$v = $this->fun->filterProduct($v);
         	$break_price=$priceshow = $buyshow= '';$stock = 0;$show_price = 0;
         	if($v['f_show_price_sz']){
         		$show_price = $v['f_show_price_sz'];
         		$stock      = $v['f_stock_sz'];
         		$break_price = $v['f_break_price_notitle_sz'];
         	}elseif($v['f_show_price_hk']){
         		$show_price = $v['f_show_price_hk'];
         		$stock      = $v['f_stock_hk'];
         		$break_price = $v['f_break_price_notitle_hk'];
         	}         
         	if($v['f_show_price_sz']){
         		//低至价格
         		$showprice = $v['f_rmb'].number_format($v['f_lowest_price_sz'],DECIMAL);
         		//阶梯价格
         		$btable = $v['f_break_price_notitle_sz'];
         	
         	}elseif($v['f_show_price_hk']){
         		//低至价格
         		$showprice = $v['f_usd'].number_format($v['f_lowest_price_hk'],DECIMAL);
         		//阶梯价格
         		$btable = $v['f_break_price_notitle_hk'];
         	
         	}         	
         	if($v['f_show_price_sz'] || $v['f_show_price_hk']){
         		$topstyle = '';
         		$priceshow = '<dl><dt>低至：</dt> <strong class="price"><span id="sell_price">'.$showprice.'</span></strong></dl>';
         		$buyshow = '<a href="javascript:" onclick="buy('.$v['id'].');return false;" class="button  logclick"  rev="solutionview_part_id" rel="'.$v['id'].'" title="购买">购买</a>';
         	}        
				?>
            	<div class="boxTb boxshadow_h"> 			
                <div class="pdMegPic">
                    <div class="imgmiddle">
                        <a href="<?=$v['f_produrl']?>" target="_blank" class="logclick"  rev="solutionview_part_id" rel="<?=$v['id']?>">
                        <?php $img = ($v['part_img']) ? PRODUCTICON.$v['part_img'] : PRODUCTICON."no.gif";?>
                        <img src="<?php echo $img;?>" height="90" alt="<?=$v['part_no']?>" title="<?=$v['part_no']?>"></a>
                    </div>
                    <p><a href="<?=$v['datasheet']?>" target="_blank" title="<?=$v['part_no']?>"  class="logclick"  rev="solutionview_datasheet" rel="<?=$v['id']?>"><img src="images/default/download_pdf.gif" alt="download">数据手册下载</a></p>
                </div> 			
                <div class="boxDes"> 				
                    <div class="p-title">
                        <a target="_blank" href="<?=$v['f_produrl']?>" title="<?=$v['part_no']?>" class="model logclick"  rev="solutionview_part_id" rel="<?=$v['id']?>"><?=$v['part_no']?></a>
                        <a href="/pl/<?=$v['bname']?>" target="_blank" title="<?=$v['bname']?>"  class="logclick"  rev="solutionview_brand" rel="<?=$v['manufacturer']?>">
                        	<img src="images/default/brand/<?=$v['manufacturer']?>_h.png" height="36" title="<?=$v['bname']?>" class="png_ie6"></a>
                    </div>
                    <div class="promianboxdl promianboxdl0">
                    	<dl>
                        	<dt>标准包装：</dt>
                            <dd><?php echo ($v['mpq']) ? $v['mpq'] : "--";?></dd>
                        </dl>
                        <dl>
                        	<dt>封装：</dt>
                            <dd><?php echo ($v['supplier_device_package']) ? $v['supplier_device_package'] : "--";?></dd>
                        </dl>
                        <dl>
                        	<dt>包装：</dt>
                            <dd><?php echo ($v['packaging']) ? $v['packaging'] : "--";?></dd>
                        </dl>
                        <dl>
                        	<dt>类别：</dt>
                            <dd><a href="/list-<?=$v['part_level1']?>-<?=$v['part_level2']?>-<?=$v['part_level3']?>.html " target="_blank" title="<?php echo $v['cname3']?$v['cname3']:$v['cname2'];?>"  class="logclick"  rev="solutionview_category" rel="<?=($v['cname3']?$v['cname3']:$v['cname2'])?>"><?php echo $v['cname3']?$v['cname3']:$v['cname2'];?></a></dd>
                        </dl>
                        <dl>
                        	<dt>无铅情况：</dt>
                            <dd><?=$v['rohs']==1?'<img src="/images/default/RoHS.gif"  title="符合"/>':'<img src="/images/default/NO_RoHS.gif" title="不符合"/>';?></dd>
                        </dl>
                        <dl>
                        	<dt>产品描述：</dt>
                            <dd><?=$this->fun->utf_substr($v['description'],68)?></dd>
                        </dl>
                    </div>	
                    <div class="promianboxdl">
                        <?php echo $priceshow;?>
                        <dl>
                          <dt>最小起订量：</dt>
                          <dd><?php echo $v['moq'];?></dd>
                        </dl>
                        <dl>
                          <dt>库存：</dt>
                          <dd><?php
                    if(($v['f_stock_sz']+$v['f_stock_hk'])>0){echo '<font color="#469F68">现货</font>';}
					else {echo '<font color="#FC9C30">订货</font>';}?></dd>
                        </dl>
                    </div>	
                    <div class="promianboxdl promianboxBtn ">
                        <?php if(!$v['noinquiry']){?>
                         <a href="javascript:" onclick="openInquiry('<?php echo $v['id'];?>');return false;" title="询价" class="button logclick"  rev="solutionview_part_id" rel="<?=$v['id']?>">询价</a>
                         <?php }?>
                        <?=$buyshow?>
                    </div>	
                            	
                </div>			
                <div class="clear"></div> 		            
            </div>
                <?php }}//end foreach($this->hxpart as $v){?>
         	</div>
            
            <?php if($this->outside){?>
            <h4>相关视频</h4>
            <div class="w_100">
                 <?php foreach($this->outside as $k=>$ov){?>
    	         <div class="schenews schenews<?=$k+1?>" style="border:0">
                 	 <a href="<?=$ov['url']?>"  target="_blank"><i class="schenewsicon"></i>
                     <img src="<?=$ov['image']?>" alt="<?=$ov['name']?>" title="<?=$ov['name']?>" width="246" height="150"></a>
                     <h2><a href="<?=$ov['url']?>"  target="_blank"><?=$ov['name']?></a></h2>           
                 </div>
                 <?php }?>
            </div>
            <?php }//end if($this->outside)?>
            
            <?php if($this->news){?>
            <h4>相关资讯</h4>
            <div class="w_100">
                <?php foreach($this->news as $k=>$news){?>
    	         <div class="schenews schenews<?=$k+1?>">
                     <a href="/news-<?=$news['id']?>.html"  target="_blank">
                     <img src="<?=$news['image']?>" alt="<?=$news['title']?>" title="<?=$news['title']?>" width="246" height="150"></a>
                     <h2><a href="/news-<?=$news['id']?>.html"  target="_blank"><?=$news['title']?></a></h2>
                 </div>
                 <?php }?>
            </div>
            <?php }?>
    </div>
</div>
    <?php }?>
    
    <?php if(array_key_exists('zbqj',$this->solutionrule)){?>
    <!--周边器件-->
    <div class="schemecontent fr content_zbqj <?php if($_SESSION['view_now'][$this->solid]['visittype']!='zbqj') echo 'hide';?>">
    	<div class="schemecontent_tit"><h3>周边器件</h3></div>
        <div class="schemecontent_box">
            <p class="pmarg"><?=$this->solution['peripherals_des']?></p>
            <div class="promianbox">	
            <?php 
			if($this->zbpart){
			foreach($this->zbpart as $v){
			$v = $this->fun->filterProduct($v);
         	$break_price=$priceshow = $buyshow= '';$stock = 0;$show_price = 0;
         	if($v['f_show_price_sz']){
         		$show_price = $v['f_show_price_sz'];
         		$stock      = $v['f_stock_sz'];
         		$break_price = $v['f_break_price_notitle_sz'];
         	}elseif($v['f_show_price_hk']){
         		$show_price = $v['f_show_price_hk'];
         		$stock      = $v['f_stock_hk'];
         		$break_price = $v['f_break_price_notitle_hk'];
         	}         
         	if($v['f_show_price_sz']){
         		//低至价格
         		$showprice = $v['f_rmb'].number_format($v['f_lowest_price_sz'],DECIMAL);
         		//阶梯价格
         		$btable = $v['f_break_price_notitle_sz'];
         	
         	}elseif($v['f_show_price_hk']){
         		//低至价格
         		$showprice = $v['f_usd'].number_format($v['f_lowest_price_hk'],DECIMAL);
         		//阶梯价格
         		$btable = $v['f_break_price_notitle_hk'];
         	
         	}         	
         	if($v['f_show_price_sz'] || $v['f_show_price_hk']){
         		$topstyle = '';
         		$priceshow = '<dl><dt>低至：</dt> <strong class="price"><span id="sell_price">'.$showprice.'</span></strong></dl>';
         		$buyshow = '<a href="javascript:" onclick="buy('.$v['id'].');return false;" class="button logclick" title="购买"  rev="solutionview_part_id" rel="'.$v['id'].'">购买</a>';
         	}        
				?>
                <div class="boxTb boxshadow_h"> 			
                <div class="pdMegPic">
                    <div class="imgmiddle">
                        <a href="<?=$v['f_produrl']?>" target="_blank" class="logclick"  rev="solutionview_part_id" rel="<?=$v['id']?>">
                        <?php $img = ($v['part_img']) ? PRODUCTICON.$v['part_img'] : PRODUCTICON."no.gif";?>
                        <img src="<?php echo $img;?>" height="90" alt="<?=$v['part_no']?>" title="<?=$v['part_no']?>"></a>
                    </div>
                    <p><a href="<?=$v['datasheet']?>" target="_blank" title="<?=$v['part_no']?>"  class="logclick"  rev="solutionview_datasheet" rel="<?=$v['id']?>"><img src="images/default/download_pdf.gif" alt="download">数据手册下载</a></p>
                </div> 			
                <div class="boxDes"> 				
                    <div class="p-title">
                        <a target="_blank" href="<?=$v['f_produrl']?>" title="<?=$v['part_no']?>" class="model logclick"  rev="solutionview_part_id" rel="<?=$v['id']?>"><?=$v['part_no']?></a>
                        <a href="/pl/<?=$v['bname']?>" target="_blank" title="<?=$v['bname']?>"  class="logclick"  rev="solutionview_brand" rel="<?=$v['manufacturer']?>">
                        	<img src="images/default/brand/<?=$v['manufacturer']?>_h.png" height="36" title="<?=$v['bname']?>" class="png_ie6"></a>
                    </div>
                    <div class="promianboxdl promianboxdl0">
                    	<dl>
                        	<dt>标准包装：</dt>
                            <dd><?php echo ($v['mpq']) ? $v['mpq'] : "--";?></dd>
                        </dl>
                        <dl>
                        	<dt>封装：</dt>
                            <dd><?php echo ($v['supplier_device_package']) ? $v['supplier_device_package'] : "--";?></dd>
                        </dl>
                        <dl>
                        	<dt>包装：</dt>
                            <dd><?php echo ($v['packaging']) ? $v['packaging'] : "--";?></dd>
                        </dl>
                        <dl>
                        	<dt>类别：</dt>
                            <dd><a href="/list-<?=$v['part_level1']?>-<?=$v['part_level2']?>-<?=$v['part_level3']?>.html " target="_blank" title="<?php echo $v['cname3']?$v['cname3']:$v['cname2'];?>"  class="logclick"  rev="solutionview_category" rel="<?=($v['cname3']?$v['cname3']:$v['cname2'])?>"><?php echo $v['cname3']?$v['cname3']:$v['cname2'];?></a></dd>
                        </dl>
                        <dl>
                        	<dt>无铅情况：</dt>
                            <dd><?=$v['rohs']==1?'<img src="/images/default/RoHS.gif"  title="符合"/>':'<img src="/images/default/NO_RoHS.gif" title="不符合"/>';?></dd>
                        </dl>
                        <dl>
                        	<dt>产品描述：</dt>
                            <dd><?=$this->fun->utf_substr($v['description'],68)?></dd>
                        </dl>
                    </div>	
                    <div class="promianboxdl">
                        <?php echo $priceshow;?>
                        <dl>
                          <dt>最小起订量：</dt>
                          <dd><?php echo $v['moq'];?></dd>
                        </dl>
                        <dl>
                          <dt>库存：</dt>
                          <dd><?php
                    if(($v['f_stock_sz']+$v['f_stock_hk'])>0){echo '<font color="#469F68">现货</font>';}
					else {echo '<font color="#FC9C30">订货</font>';}?></dd>
                        </dl>
                    </div>	
                    <div class="promianboxdl promianboxBtn ">
                       <?php if(!$v['noinquiry']){?>
                         <a href="javascript:" onclick="openInquiry('<?php echo $v['id'];?>');return false;" title="询价" class="button logclick"  rev="solutionview_part_id" rel="<?=$v['id']?>">询价</a>
                         <?php }?>
                        <?=$buyshow?>
                    </div>	
                            	
                </div>			
                <div class="clear"></div> 		            
            </div>
            <?php }}//end foreach($this->zbpart as $v)?>
                
         	</div>
        </div>


    </div>
    <?php }?>
    
    <?php if(array_key_exists('bomd',$this->solutionrule)){?>
    <!--BOM清单-->
    <div class="schemecontent fr content_bomd <?php if($_SESSION['view_now'][$this->solid]['visittype']!='bomd') echo 'hide';?>">
    	<div class="schemecontent_tit"><h3>BOM清单</h3></div>
        <div class="schemecontent_box">
            <div class="promianbox">
				<table cellpadding="0" cellspacing="0" border="0" class="table">
                	<tr>
                    	<th width="30">序号</th>
                    	<th width="110">型号</th>
                        <th width="60">品牌</th>	
                    	<th width="40">用量</th>	
                    	<th width="80">类型</th>	
                    	<th width="60">封装</th>	
                    	<th >备注</th>
                        <th width="40">库存</th>
                        <th width="100">价格</th>
                        <th width="110">操作</th>
                    </tr>
                    <?php 
					   if($this->bom){
					   foreach($this->bom as $k=>$bom){
					      if($k%2==1) $bgclass = ' class="tabletrf9"';
						  else $bgclass='';
					   if($bom['prod_info']['part_no']){
						  $break_price='';$totalstock = $stock = 0;$show_price = 0;
					      if($bom['prod_info']){
						  	    $bom['prod_info'] = $this->fun->filterProduct($bom['prod_info']);
								if($bom['prod_info']['f_show_price_sz']){
									$show_price = $bom['prod_info']['f_show_price_sz'];
									$stock      = $bom['prod_info']['f_stock_sz'];
									$break_price = $bom['prod_info']['f_break_price_notitle_sz'];
								}elseif($bom['prod_info']['f_show_price_hk']){
									$show_price = $bom['prod_info']['f_show_price_hk'];
									$stock      = $bom['prod_info']['f_stock_hk'];
									$break_price = $bom['prod_info']['f_break_price_notitle_hk'];
								}
								$totalstock = $bom['prod_info']['f_stock_sz']+$bom['prod_info']['f_stock_hk'];
						  }
					?>
                	<tr <?=$bgclass?>>
                    	<td><?=$k+1?></td>
                        <td><?php if($bom['prod_info']){?>
                        <a href="<?=$bom['prod_info']['f_produrl']?>" target="_blank" class="model logclick"  rev="solutionview_part_id" rel="<?=$v['id']?>"><?=$bom['prod_info']['part_no']?></a>
                        <?php }else{?>
                        <span class="model"><?=$bom['part_no']?></span>
                        <?php }?>
                        </td>
                        <td><?=$bom['brand_name']?$bom['brand_name']:$bom['prod_info']['bname']?></td>
                        <td><?=$bom['dosage']?$bom['dosage']:'--'?></td>
                        <td><?=$bom['category_type']?$bom['category_type']:($bom['prod_info']['cname1']?$bom['prod_info']['cname1']:'--')?></td>
                        <td><?=$bom['sd_package']?$bom['sd_package']:($bom['prod_info']['supplier_device_package']?$bom['prod_info']['supplier_device_package']:'--')?></td>
                        <td><?=$bom['remark']?$bom['remark']:'--'?></td>
                        <?php
                            if($totalstock>0) echo '<td class="fontgreen">现货</td>';
					        elseif($bom['prod_info']) echo '<td class="fontorange">预订</td>';
							else echo '<td class="fontorange">--</td>';
						?>
                        <td><div class="price_btn_table"><?=($break_price?$break_price:'--')?></div></td>
                        <td><div class="tabelbtn">
                        <?php if($bom['prod_info']){?>
                        <?php if(!$bom['prod_info']['noinquiry']){?>
                        <a href="javascript:" onclick="openInquiry('<?=$bom['prod_info']['id']?>')" class="abtnquestion logclick"  rev="solutionview_part_id" rel="<?=$v['id']?>" title="询价">询价</a>
                        <?php }else{?>
            	        <a class="abtnquestion_gray ">询价</a>
                        <?php }?>
                        <?php if($show_price){?><a href="javascript:" onclick="buy('<?=$bom['prod_info']['id']?>.')"  class="abtnbuy logclick"  rev="solutionview_part_id" rel="<?=$v['id']?>" title="购买">购买</a>
                        <?php }else{?>
                        <a class="abtnbuy_gray ">购买</a>
                        <?php }
                        }else echo '--';
                        ?>
                        </div></td>
                    </tr>
                    <?php } 
					}?>
                    <tr class="tabletrf9">
                    	<td colspan="10" align="right"><a href="/applications/exportbom?key=<?=$this->fun->encryptVerification($this->solid)?>" target="_blank" title="下载BOM清单">下载BOM清单</a></td>
                    </tr>
					<?php }else{?>
                    <tr class="tabletrf9">
                    	<td colspan="10">暂无记录</td>
                    </tr>
                    <?php }?>
                </table>
         	</div>
        </div>
    </div>
    <?php }?>
    
    <?php if(array_key_exists('cgal',$this->solutionrule)){?>
    <!--成功案例-->
    <div class="schemecontent fr content_cgal <?php if($_SESSION['view_now'][$this->solid]['visittype']!='cgal') echo 'hide';?>">
    	<div class="schemecontent_tit"><h3>成功案例</h3></div>
        <div class="schemecontent_box">
            <?php if($this->caseinfo){foreach($this->caseinfo as $case){?>
        	<div class="schemecontentdl">
                <dl>
                    <dt>公司名称：</dt> 
                    <dd><?=$case['company_name']?></dd>
                </dl>
                <dl>
                    <dt>公司简介：</dt> 
                    <dd><?=$case['company_profile']?></dd>
                </dl>
                <dl>
                    <dt>项目：</dt> 
                    <dd><?=$case['project_name']?></dd>
                </dl>
            </div>
            <?php }}?>
        </div>
    </div>
    <?php }?>
    
    <?php if(array_key_exists('sjwd',$this->solutionrule)){?>
    <!--设计文档-->
   <div class="schemecontent fr content_sjwd <?php if($_SESSION['view_now'][$this->solid]['visittype']!='sjwd') echo 'hide';?>">
    	<div class="schemecontent_tit"><h3>设计文档</h3></div>
        <div class="schemecontent_box schemedownload">
            <?php if($this->document){foreach($this->document as $document){if($document[0]['url']&&$document[0]['url']!='#'){?>
        	<dl>
            	<dt><h5><?=$document[0]['type_name']?></h5></dt>
                <dd><p><a href="/applications/solutiondoc?s=<?=md5(session_id())?>&key=<?=$this->fun->encryptVerification($document[0]['id']);?>" target="_blank">
                <img src="images/default/download_pdf.gif" /><?=$document[0]['name']?></a></p></dd>
            </dl>
            <?php }}}?>
        </div>
    </div>
     <?php }?>
    
    <?php if(array_key_exists('jszq',$this->solutionrule)){?>
    <!--技术支持-->
    <div class="schemecontent fr content_jszq <?php if($_SESSION['view_now'][$this->solid]['visittype']!='jszq') echo 'hide';?>">
    	<div class="schemecontent_tit"><h3>技术支持</h3></div>
        <div class="schemecontent_box">
            <?php if($this->engineer){foreach($this->engineer as $engineer){?>
        	<div class="schemecontentdl">
            	<div class="schemehead"><img src="<?=$engineer['head']?>"  width="100"/> </div>
				<div class=" schemecontentdl1">
                <dl>
                    <dt>姓名：</dt> 
                    <dd><?=$engineer['name']?></dd>
                </dl>
                <dl>
                    <dt>职位：</dt> 
                    <dd><?=$engineer['office']?></dd>
                </dl>
                <dl>
                    <dt>简介：</dt> 
                    <dd><?=$engineer['introduction']?></dd>
                </dl>
                <dl>
                    <dt>电话：</dt> 
                    <dd><?=$engineer['tel'].'  '.$engineer['phone']?></dd>
                </dl>
                <dl>
                    <dt>Email：</dt> 
                    <dd><a href="mailto:<?=$engineer['email']?>"><?=$engineer['email']?></a></dd>
                </dl>
            </div>           
            </div>
            <?php }}?>
        </div>
    </div>
     <?php }?>
</div>
  
  <!-- end有权限-->
  <?php }?>
</div>




<script type="text/javascript">
$('.boxshadow_h').hover(function(){
		$(this).addClass("boxshadow");
	},function(){
		$(this).removeClass("boxshadow");
	});
	
function applyapprule(key){
	$.ajax({
            url: '/index/checklogin',
            data: {},
            type: 'post',
            dataType: 'json',
            success: function(arr) {
			   if(arr.code==0)
			   {  
			       $.ajax({
						url: '/user/checkdetailed',
						data: {},
						type: 'post',
						dataType: 'json',
						success: function(arr) {
							if(arr.code==0)
							{
								//成功
								$.openPopupLayer({
								 name: "applyappruleBox",
								 url: "/applications/applyapprule?key="+key
								});
							}else{
								$.openPopupLayer({
								 name: "companyinfoBox",
								 url: "/center/companyinfo?opbox=applyappruleBox&opurl=/applications/applyapprule&key="+key
								});
							}
						}
					});
			   }else if(arr.code==100){
			   	  $.openPopupLayer({
		             name: "loginBox",
		             target: "login_box"
	              });
			   }else if(arr.code==200){
			   	   window.location.href ="/user/verification";
			   }
            }
    });
}
</script>
<!-- 划词分享 -->
<script type="text/javascript">
(function(){
  window.rmwbShareConf = {
    pageWidth : 960, //网页宽度，用于定位左侧固定漂浮按钮的位置
    contentId : 'share_content' //正文内容id，用于划词分享
  };
  var s = document.createElement('script');
  s.src = '/js/jsplug/sharetowb/share.js';
  document.getElementsByTagName('head')[0].appendChild(s);
})();
</script>
<!-- /划词分享 --> 
<!-- Baidu Button BEGIN -->
<script type="text/javascript" id="bdshare_js" data="type=slide&amp;img=5&amp;pos=right&amp;uid=784927" ></script>
<script type="text/javascript" id="bdshell_js"></script>
<script type="text/javascript">
var bds_config={"bdTop":205,'bdText':'#盛芯电子#向大家分享盛芯电子里的<?=$this->solution['name']?>应用方案：<?=$this->solution['title']?>'};
document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + Math.ceil(new Date()/3600000);
</script>
<!-- Baidu Button END -->