<div class="popup" style="width:850px;" >
    <div class="popup-header">
        <h2>编辑代码：</h2>
        <a href="javascript:;" onclick="$.closePopupLayer('box');removenotsupport();" title="关闭" class="dialogBoxClose">关闭</a>
    </div>
    <div class="popup-body">
    <table  cellpadding="0" border="0" cellspacing="0">
      <tbody>
    <tr>
    <td  valign="top" align="right">代码：</td>
    <td><textarea name="code" id="code" style="width:730px; height:400px; font-size:14px"><?=$this->even['code']?></textarea>
    </td>
    </tr>
    </tbody></table>
        <div class="pbtn" id="baojiabtn2"><input type="button" onClick="editcodeAction()" value="提 交" class="btnabig"></div>
        <div class="clear"></div>
    </div>
</div>
<script type="text/javascript">
function editcodeAction() {
    var code = document.getElementById('code').value;
	$.ajax({
		url: '/icwebadmin/ReadEven/editcode',
		data: {'id':'<?=$this->even['id'];?>','code':code},
		type: 'post',
		dataType: 'json',
		success: function(arr) {
		    alert(arr.message);
			if(arr.code == 0){
				  location.reload();
             }
		}
	});
}
</script>