<div class="pop pop_shopbox">
	<div class="popbox">
    	<div class="poptit1">
            <input type="button" title="关闭"  class="closebtn" onclick="$.closePopupLayer('alertBox')">
        </div>
        <div class="popcon clearfix msg" style="width:90%; text-align:center">
        	<div class="tips"  style="text-align:left">
            <p><?=$this->message?></p>
            </div>
         </div>
    </div>
</div>