<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML>
<HEAD>
<meta http-equiv="content-type" content="text/html; charset=utf-8">
<title>IC易站 - 搜索！</title><meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<meta name="description" content="IC易站是行业领先的一站式元器件电商平台，专注于服务电子制造企业的设计链和供应链，满足客户从产品设计到批量生产的全程需求！IC易站有海量的产品数据、设计方案及在线技术研讨会等服务。IC易站便捷的在线订购流程及批量采购询价、样片申请，技术支持等服务，为你带来全新采购体验！IC易站传承30年品牌价值，100%正品保证，便捷的网上下单流程，正规增值税发票，快速的物流服务，是您最佳的元器件在线采购平台。" />
<meta name="keywords" content="IC元器件电商平台，IC芯片网上采购，元器件采购，小批量采购，元器件询价，IC样片申请，免费样片，技术方案，现货库存，MCU，MOSFET，K60开发板，KL25开发板，K60，KL25，飞思卡尔代理，Freescale代理，IDT代理，Intersil代理，AOS代理，Qualcomm代理，CSR代理，IC Easy，IC采购" />
<script src="/js/jsplug/jquery.1.8.2.min.js" type="text/javascript"></script>
<link rel="shortcut icon" href="/images/default/favicon.ico" />
<link type="text/css" rel="stylesheet" href="/css/default/search.css">
</HEAD>
<BODY>
<table cellpadding="0" border="0" cellspacing="0" width="800">
  <tr>
    <td width="280"><a href="/" hidefocus="true"><img src="/images/default/logo.jpg" title="IC Easy - IC采购，从此Easy !" alt="IC易站"></a></td>
    <td valign="bottom" style="height:60px;font-size:16px; padding-bottom:0px;" width="450">
    
	<?php if($this->st=='searchsolution'){?>
    <a href="/searcha?q=<?=$this->q?>&st=searchgoogle" class="search_g" title="搜索全站">全站</a>&nbsp;&nbsp;
    <b>方案(<?=$this->solutiontotal?>)</b>&nbsp;&nbsp;
    <a href="/searcha?q=<?=$this->q?>&st=searchnews" class="search_n" title="搜索资讯">资讯(<?=$this->newstotal?>)</a>&nbsp;&nbsp;
    <a href="/searcha?q=<?=$this->q?>&st=searchwebinar" class="search_w" title="搜索研讨会">研讨会(<?=$this->seminartotal?>)</a>&nbsp;&nbsp;
	<a href="/searcha?q=<?=$this->q?>&st=searchcode" class="search_w" title="搜索代码库">代码库(<?=$this->codetotal?>)</a>

	<?php }elseif($this->st=='searchnews'){?>
    <a href="/searcha?q=<?=$this->q?>&st=searchgoogle" class="search_g" title="搜索全站">全站</a>&nbsp;&nbsp;
    <a href="/searcha?q=<?=$this->q?>&st=searchsolution" class="search_f" title="搜索方案">方案(<?=$this->solutiontotal?>)</a>&nbsp;&nbsp;
    <b>资讯(<?=$this->newstotal?>)</b>&nbsp;&nbsp;
    <a href="/searcha?q=<?=$this->q?>&st=searchwebinar" class="search_w" title="搜索研讨会">研讨会(<?=$this->seminartotal?>)</a>&nbsp;&nbsp;
    <a href="/searcha?q=<?=$this->q?>&st=searchcode" class="search_w" title="搜索代码库">代码库(<?=$this->codetotal?>)</a>
	<?php }elseif($this->st=='searchwebinar'){?>
    <a href="/searcha?q=<?=$this->q?>&st=searchgoogle" class="search_g" title="搜索全站">全站</a>&nbsp;&nbsp;
    <a href="/searcha?q=<?=$this->q?>&st=searchsolution" class="search_f" title="搜索方案">方案(<?=$this->solutiontotal?>)</a>&nbsp;&nbsp;
    <a href="/searcha?q=<?=$this->q?>&st=searchnews" class="search_n" title="搜索资讯">资讯(<?=$this->newstotal?>)</a>&nbsp;&nbsp;
    <b>研讨会(<?=$this->seminartotal?>)</b>
    <a href="/searcha?q=<?=$this->q?>&st=searchcode" class="search_w" title="搜索代码库">代码库(<?=$this->codetotal?>)</a>
    <?php }elseif($this->st=='searchcode'){?>
    <a href="/searcha?q=<?=$this->q?>&st=searchgoogle" class="search_g" title="搜索全站">全站</a>&nbsp;&nbsp;
    <a href="/searcha?q=<?=$this->q?>&st=searchsolution" class="search_f" title="搜索方案">方案(<?=$this->solutiontotal?>)</a>&nbsp;&nbsp;
    <a href="/searcha?q=<?=$this->q?>&st=searchnews" class="search_n" title="搜索资讯">资讯(<?=$this->newstotal?>)</a>&nbsp;&nbsp;
    <a href="/searcha?q=<?=$this->q?>&st=searchwebinar" class="search_w" title="搜索研讨会">研讨会(<?=$this->seminartotal?>)</a>
    <b>代码库(<?=$this->codetotal?>)</b>
	<?php }else{?>
    <b>全站</b>&nbsp;&nbsp;
    <a href="/searcha?q=<?=$this->q?>&st=searchsolution" class="search_f" title="搜索方案">方案(<?=$this->solutiontotal?>)</a>&nbsp;&nbsp;
    <a href="/searcha?q=<?=$this->q?>&st=searchnews" class="search_n" title="搜索资讯">资讯(<?=$this->newstotal?>)</a>&nbsp;&nbsp;
    <a href="/searcha?q=<?=$this->q?>&st=searchwebinar" class="search_w" title="搜索研讨会">研讨会(<?=$this->seminartotal?>)</a>&nbsp;&nbsp;
    <a href="/searcha?q=<?=$this->q?>&st=searchcode" class="search_w" title="搜索代码库">代码库(<?=$this->codetotal?>)</a>
    <?php }?>
    &nbsp;&nbsp;
    <a href="/search?keyword=<?=$this->q?>&st=searchmodel" class="search_m" title="搜索产品型号">型号(<?=$this->producttotal?>)</a>
    &nbsp;&nbsp;
    <?php if(!empty($this->q)){?>
    <a href="http://www.baidu.com/baidu?word=<?=$this->q?>&tn=bds&cl=3&ct=2097152&si=www.iceasy.com" target="_blank" title="百度一下"><img src="/images/default/baidu.png">百度</a>
    <?php }?>
    </td>
  </tr>
  <tr height="5px"><td colspan="2">&nbsp;</td></tr>
  </table>
  <table cellpadding="0" border="0" cellspacing="0" width="800">
  <tr>
    <td>
    <?php if($this->google==1){?>
<style type="text/css">
table.gsc-search-box {
/*display: none;*/
}
.gcsc-branding,.gsc-adBlock {
display: none;
}
input.gsc-input {
border-color: #D9D9D9;
font-size: 15px;
padding: 5px 6px;
}
.gsc-search-button{cursor:pointer;}
</style>
<script>
  (function() {
    var cx = '013757454638023408461:izq0qtrxv2m';
    var gcse = document.createElement('script');
    gcse.type = 'text/javascript';
    gcse.async = true;
    gcse.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') +
        '//www.google.com/cse/cse.js?cx=' + cx;
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(gcse, s);
  })();
</script>
<gcse:search></gcse:search>
    <?php }else{?>
    <form action="/searcha" method="get">
        <table>
          <tr>
            <td><div align="left" class="bg s_ipt_wr">
                <input type="text" name="q" id="q" size="40" value="<?=$this->q?>" class="s_ipt">
              </div>
            <td><input type="submit" value="搜索" class="s_btn">
            </td>
          </tr>
        </table>
         <input type="hidden" name="st" id="st" value="<?=$this->st?>" />
      </form>
    <?php }?>  
    </td>
  </tr>
  <tr height="5px"><td colspan="2">&nbsp;</td></tr>
</table>

<?php if(!$this->google){?>
	<?php if($this->message){ echo '<div id="result_report">'.$this->message.'</div>';}?>
    <div id="results">
    
    <!-- results listing -->
    <?php foreach($this->rearray as $v){
          $url = '';$title='';$des = '';
          if($this->st=='searchsolution'){
              $url   = "http://www.iceasy.com/solution-".$v['id'].".html";
          }elseif($this->st=='searchnews'){
              $url   = "http://www.iceasy.com/news-".$v['id'].".html";
          }elseif($this->st=='searchwebinar'){
              $url   = "http://www.iceasy.com/webinar-".$v['id'].".html";
          }elseif($this->st=='searchcode'){
		  	  $url   = "http://www.iceasy.com/code-".$v['id'].".html";
		  }
          $title = str_ireplace($this->q,"<em>{$this->q}</em>",$v['title']);
          $des   = str_ireplace($this->q,"<em>{$this->q}</em>",$this->fun->utf_substr($v['description'],256));
    ?>
    <a href="<?=$url?>" class="title" target="_blank"><?=$title?></a><br/>
            <div class="description"><?=$des?></div>
            <div class="url"><?=$url?></div>
            <br/>
    <?php }?>
    
    </div>
    <!-- links to other result pages-->
    <?php if($this->total > 0){?>
    <table><tr><td><div class="pagination "><?=$this->page_bar?></div></td>
	<td>
        <div class="matchword">为您找到相关结果<?=$this->total?>个</div>
    </td></tr></table>
	<?php }?>	
    
    
    <?php if($this->total>10){?>
    <table cellpadding="0" border="0" cellspacing="0" class="searchBox" width="780" style="margin-top:20px;">
    <tr>
        <td colspan="2"><form action="/searcha" method="get">
            <table>
              <tr>
                <td><div align="left" class="bg s_ipt_wr">
                    <input type="text" name="q" id="q" size="40" value="<?=$this->q?>" class="s_ipt">
                  </div>
                <td><input type="submit" value="搜索" class="s_btn">
                </td>
              </tr>
            </table>
             <input type="hidden" name="st" id="st" value="<?=$this->st?>" />
          </form></td>
      </tr>
    </table>
    <?php }?>
<?php }?>

<div class="copyRight ">
      <p > <span>
      <a href="/help/index/type/aboutus" target="_blank">关于IC易站</a></span> <span>|</span> <span>
      <a href="/help/index/type/customer" target="_blank">联系我们</a></span> <span>|</span> <span>
      <a href="http://www.ceacsz.com.cn/jobs/" target="_blank">人才招聘</a></span> <span>|</span> <span>
      <a href="http://www.ceacsz.com.cn/" target="_blank">友情链接</a></span> </p>
      <p>
      <a href="http://www.ceacsz.com.cn/" target="_blank">中国电子器材深圳有限公司</a> 版权所有 <span style="font-family:Arial">©</span> 2013 粤ICP备05143739号-2</p>
    </div>
<script type="text/javascript">
$(document).ready(function(){
		$("#q").live("keyup",function(){
			var kw = $(this).val();
			if(kw!=''){
				$(".search_f").attr("href","/searcha?q="+kw+"&st=searchsolution");
				$(".search_n").attr("href","/searcha?q="+kw+"&st=searchnews");
				$(".search_w").attr("href","/searcha?q="+kw+"&st=searchwebinar");
				
			    $(".search_ic").attr("href","/searchi?query="+kw+"&search=1&st=searchall");
				$(".search_g").attr("href","/searcha?q="+kw+"&st=searchgoogle");
				$(".search_m").attr("href","/search?keyword="+kw+"&st=searchmodel");
			}
        });
});
$(document).ready(function(){
	$(".gsc-search-button-v2").live("click",function(){
		var kw = $("#gsc-i-id1").val(); 
		$(".search_f").attr("href","/searcha?q="+kw+"&st=searchsolution");
		$(".search_n").attr("href","/searcha?q="+kw+"&st=searchnews");
		$(".search_w").attr("href","/searcha?q="+kw+"&st=searchwebinar");
		$(".search_ic").attr("href","/searchi?query="+kw+"&search=1&st=searchall");
		$(".search_m").attr("href","/search?keyword="+kw+"&st=searchmodel");
	});
		$(".gsc-input").live("keyup",function(){
			var kw = $(this).val();
			if(kw!=''){
			   $(".search_f").attr("href","/searcha?q="+kw+"&st=searchsolution");
				$(".search_n").attr("href","/searcha?q="+kw+"&st=searchnews");
				$(".search_w").attr("href","/searcha?q="+kw+"&st=searchwebinar");
				$(".search_ic").attr("href","/searchi?query="+kw+"&search=1&st=searchall");
				$(".search_m").attr("href","/search?keyword="+kw+"&st=searchmodel");
			}
        });
});
</script>
</body>
</html>