<link href="/js/bootstrap/bootstrap-editable/css/bootstrap-editable.css" rel="stylesheet">
	<div class="conmian">
	<h1><?php echo $this->AreaTitle;?> : 一共 <?=$this->total?> 条  <a href="javascript:;" onclick="update(0,'更新所有','all')">已更新所有</a></h1>
				<div id="message_sess" style="display:none" class="message_sess"> 
          <div title="关闭" class="but" onclick="document.getElementById('message_sess').style.display='none'">&nbsp;</div>
          <div id="alert_message"></div> 
          </div>
<form id="myform"  class="form-search" name="myform" action="" method="get">
<label>在盛芯电子上没有找到的型号：	<input type = "checkbox" name="part_id" value="-1"  <?php echo ($this->part_id ==-1) ? "checked" : "";?>></label>
<?php echo $this->ECBrandSelect('brand',$this->brand,'',$this->part_id); ?> 
<input type="submit" class="btn" value="查 找"/>
</form>          
	  <!-- 需要填写的区域-->
      <div class="contentmia">
      <table class="table ordertable"  border="1" style=" margin-top:-1px;">
          <thead>
           <tr>
            <th>产品线名称</th>
            <th>ICEasy型号ID</th>
            <th>ICEasy型号</th>
            <th>SAP型号</th>
            <th>工厂</th>
            <th>仓位</th>
            <th>库存</th>
            <th>更新时间</th>
            </tr>
            </thead>
          <tbody>
            <?php  if(empty($this->product)){?>
            <tr><td colspan="19"><center>暂无记录。</center></td></tr>
            <?php }else{
				 		foreach($this->product as $k=>$data){
 				 ?>
            <tr>
                <td><?=$data['oa_mfr']?></td>
                <td><?=$data['part_id']?></td>
                <td><a href="#"  id="ic_part_no" class="bedit" data-type="text" data-pk="<?php echo $data['id'];?>" data-url="<?php echo $this->editurl;?>" data-title="输入盛芯电子型号"><?php echo $data['ic_part_no'];?></a></td>
                <td><?=$data['sap_part_no']?></td>
                <td><?=$data['sap_factory']?></td>
                <td><?=$data['sap_warehouse']?></td>
                <td><?=$data['stock']?></td>
                <td><?=$data['updated_at']?></td> 
            </tr>
          <?php }}?>
          </tbody>
          
        </table>
        </div>
      <!-- 结束区域-->
	</div>
<!-- Modal -->
<script src="/js/bootstrap/bootstrap.min.js"></script>
<script src="/js/bootstrap/bootstrap-editable/js/bootstrap-editable.js"></script>
<script type="text/javascript">
//$.fn.editable.defaults.mode = 'inline'; 				 
$(document).ready(function() {
    $('.bedit').editable();
});
 </script>