<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<title><?=$this->headTitle?></title>
<link rel="shortcut icon" href="/images/default/favicon.ico" />
<meta content="<?=$this->description?>" name="description" /> 
<meta content="<?=$this->keywords?>" name="keywords" />
<script src="/js/jsplug/jquery.1.8.2.min.js" type="text/javascript"></script>

<script src="/upload/default/seminar/video/loadflash.js"> </script>
		<!-- this needs to be present for height="100%" to work properly in some browsers -->
		<style type="text/css">
			<!--
				body,html {
					margin:0px; 
					padding:0px;
					height:100%;
					overflow:hidden;
				}
			-->
		</style>
		<script type="text/vbscript" language="VBScript">
			<!--
				Sub SlideContent_FSCommand(ByVal command, ByVal args)
					select case command
						case "putHREF" location.href = args
						case "putTitle" document.title = args
						case else call SlideContent_DoFSCommand(command, args)
					end select
				end sub
			-->
		</script>
		<script type="text/javascript" language="JavaScript">
			<!--
				function flashPutHref(href) { location.href = href; }
				function flashPutTitle(title) { document.title = title; }
			-->
		</script>
</head>

<body bgcolor="#7C837B">
    <!-- 视频部分  -->
        <script type="text/javascript" language="JavaScript">
			showFlash("/upload/default/seminar/video/<?=$this->semdet['id']?>/viewer.swf", '98%', '100%', false);
		</script>
</body>
<!-- Baidu Button BEGIN -->
<script type="text/javascript" id="bdshare_js" data="type=slide&amp;img=5&amp;pos=right&amp;uid=784927" ></script>
<script type="text/javascript" id="bdshell_js"></script>
<script type="text/javascript">
var bds_config={"bdTop":205,'bdText':'#盛芯电子#向大家分享：盛芯电子 - 在线技术研讨会 <?=$this->semdet['title']?>'};
document.getElementById("bdshell_js").src = "http://bdimg.share.baidu.com/static/js/shell_v2.js?cdnversion=" + Math.ceil(new Date()/3600000);
</script>
<!-- Baidu Button END -->
</html>