<?php $paytypearr = array('transfer'=>'银行转账','online'=>'在线支付','cod'=>'货到付款','mts'=>'款到发货');
$statusarr = array('101'=>'<font color="#FF0000">待审核</font>','201'=>'<font color="009944">通过</font>','202'=>'<font color="#FF0000">不通过</font>');
?>
<div class="conmian">
  <h1><?php echo $this->AreaTitle;?></h1>
  <div id="message_sess" style="display:none" class="message_sess"> 
          <div title="关闭" class="but" onclick="document.getElementById('message_sess').style.display='none'">&nbsp;</div>
          <div id="alert_message"></div> 
          </div>
    <div class="fr u_right">
    <div class="tab_content">
    <div class="tab_tit1">
        <ul class="fl">
          <li <?=$this->type=='no'?'class="on"':''?>><a href="/icwebadmin/OrInva" style="width:140px;">等待审批<em>(<?=$this->nototal?>)</em><b class="blank3"></b></a></li>
          <li <?=$this->type=='pass'?'class="on"':''?>><a href="/icwebadmin/OrInva?type=pass" style="width:140px;">申请通过<em>(<?=$this->passtotal?>)</em><b class="blank3"></b></a></li>
          <li <?=$this->type=='nopass'?'class="on"':''?>><a href="/icwebadmin/OrInva?type=nopass" style="width:140px;">申请不通过<em>(<?=$this->nopasstotal?>)</em><b class="blank3"></b></a></li>
        </ul>
        </div>
      </div>
      <div class="tab_con mb10">
        <table class="producttable table" border="0">
          <thead>
          <tr><th width="100">订单号</th>
            <th width="80">订单商品</th>
            <th width="60">订单金额</th>
            <th width="60">支付类型</th>
            <th width="60">收货人</th>
            <th width="90">下单时间</th>
            <th width="60">状态</th>
            <th width="70" class="lrb"></th>
            </tr></thead>
          <tbody>
          <?php if(empty($this->invoiceapply)){echo '<tr><td colspan="8">暂没记录</td></tr>';}
		  	else{
				foreach($this->invoiceapply as $key=>$sodata){
				$url='#';
		   ?>
			  <tr>
              <td><?=$sodata['salesnumber']?></td>
              <td><?php $partnos = explode(',',$sodata['partnos']);
				 foreach($partnos as $k=>$part_no){?>
                <p><a href="/proddetails?partno=<?=$part_no;?>"  target="_blank" class="fontblue fontwei fontb"><?=$part_no?></a></p><?php }?></td>
              <td class="fontred fontwei fontb"><?=$sodata['currency'].number_format($sodata['total'],DECIMAL)?></td>
              <td class="fontGray"><?=$paytypearr[$sodata['paytype']];?></td>
              <td class="fontGray"><?=$sodata['consignee'];?></td>
              <td class="fontGray"><?=date('Y-m-d H:i:s',$sodata['created'])?></td>
              <td><?=$statusarr[$sodata['iastatus']];?></td>
              <td style="border-left:1px solid #ececec">
              <?php
			  if($sodata['iastatus']==201 || $sodata['iastatus']==202){?>
			  	  <a href="<?=$this->url(array('controller'=>'OrInva', 'action'=>'view', 'salesnumber'=>$sodata['salesnumber'],'sotype'=>$sodata['so_type']))?>" class="btncancel mb5">查看</a>
			  <?php }elseif($sodata['created'] >= strtotime("-".INVOICE_DAY." day")){?>
                  <a href="<?=$this->url(array('controller'=>'OrInva', 'action'=>'applyinvoice', 'salesnumber'=>$sodata['salesnumber'],'sotype'=>$sodata['so_type']))?>" class="btncancel mb5">审核</a>
              <?php }else{ echo '<font color="#FF0000">已过期</font>';}?>
              </td>
            </tr>
		  <?php		
				}
			}
		  ?></tbody>
        </table>
    <div class="pagination divpage">
        <?=$this->page_bar;?>
      </div>
  </div>
</div>
</div>
