<!-------------------------------------------------样片中心 主体------------------------------------------------->
<link rel="stylesheet" type="text/css" href="/css/default/samples.css"/>
<link rel="stylesheet" type="text/css" href="/css/default/directory.css"/>
<!-------------------------------------------------样片详细 主体------------------------------------------------->
<div class="samples_detail_main w 1h">
    <div class="samples_detail_model ">
        <h1 class="model">AOZ1039DI</h1><img src="brand/10_h.png"  height="36" class="png_ie6"/>
        
        <div id="bdshare" class="bdshare_t bds_tools get-codes-bdshare" style=" float:right; margin-right:10px;" > <span class="bds_more" style="line-height:14px ; margin:0 0 0 3px;" >分享到：</span> <a class="bds_qzone"></a> <a class="bds_tsina"></a> <a class="bds_tqq"></a> <a class="bds_renren"></a></div>
  <script type="text/javascript" id="bdshare_js" data="type=tools&amp;uid=6435517" ></script>
  <script type="text/javascript" id="bdshell_js"></script>
  <script type="text/javascript">
			var bds_config = {'bdText':'向大家分享盛芯电子里的样片。品牌：<?=$prodarr['bname'];?>，型号：<?=$prodarr['part_no'];?>。快来免费申请吧。'};
            document.getElementById("bdshell_js").src = "http://share.baidu.com/static/js/shell_v2.js?cdnversion=" + new Date().getHours();
            </script>
            
        <div class="samples_detail_m"></div>
    </div>
    <div class="details_bar clearfix">
        <div class="details_info">
        	<s></s><i></i>
            <div class="details_buy">
                <div class="Sampleslistcont">      	        
                    <div class="price_all">
                        <p class="vip_price price fl"><span class="txt_price">¥</span><span class="num_price">0</span></p>
                        <p class="original_price fl"><span class="tit">原价</span> <del>¥572</del></p>
                        <p class="clr"></p>
                    </div>
                    <div class="Sampleslistifo">
                        <p>交货地：国内</p>
                        <p>标准包装：168</p>
                        <p>参考交期：8-18 W</p>
                    </div>  
                    <div class="info_time">
                        <p class="business">有<strong>200</strong>人申请</p>
                        <p class="">已有<strong>20</strong>人成功申请</p>
                    </div>  
                    <div class="info_down">
                        <a href="#" target="_blank"><img src="/images/default/download_pdf.gif" alt="download" />数据手册下载</a>
                        <a href="javascript:;" title="收藏该商品" onclick="favorites('10018')"><img src="/images/default/collection_icon.jpg" alt="collection_icon" /><span>收藏该商品</span></a>
                   </div>    				
                    
                </div>
                <div class="Samplesapply">&nbsp;
                    <a href="#" class="abtnapply">立即申请</a>
                </div> 
                <div class="status " >
                    <p class="xian png_ie6"></p>
                    <p class="ding png_ie6"></p>
                </div>
               
            </div>
    	</div>
        <div class="details_photo">
            <!-- 团购大图 开始 -->
            <div class="banner_large">
                <ul class="banner_content">
                    <li id="showDetailPhoto"><img src="/css/img/samples/01.jpg" width="680" height="300"></li>
                </ul>
            </div>
            <!-- 团购大图 结束 -->
        </div>

    </div>
</div>


<div class="w clearfix">
    <div class="shoplist fl ">
    	<div class="samplesrule">
            <div class="samplesrule_t">免费样片申请须知</div>
            <ol class="ruleolli">
                <li>在线样片申请所接受的有效电子邮件必须是公司域名或教育机构域名。</li>
                <li>申请用户必须是盛芯电子的注册用户。</li>
                <li>每次样片申请限制为4种，每种2片。如果您在设计中需要更多的产品数量，请联系我们。</li>
            </ol>
            <img src="/css/img/samples/telsamples.jpg" alt="img" />
        </div>
       	<table cellpadding="0" cellspacing="0" class="mtable" >
    	<tbody>
        <tr>
        	<td width="100" style="border-left:0" class="mtabletdbg">厂商</td><td width="250"><strong>CSR</strong></td>
            <td width="100" class="mtabletdbg">最少包装数</td><td width="250">2000</td>
        </tr>
        <tr>
        	<td style="border-left:0" class="mtabletdbg">封装</td><td>QFN</td>
            <td class="mtabletdbg">包装</td><td>REEL</td>
        </tr>
        <tr>
        	<td style="border-left:0" class="mtabletdbg">类别</td><td>模数/数模转换器</td>
            <td class="mtabletdbg">无铅情况/ROHS</td><td><img src="images/default/NO_RoHS.gif" alt="NORoHS" /></td>
        </tr>
        <tr>
        	<td style="border-left:0; border-bottom:0" class="mtabletdbg">产品描述</td><td colspan="3" style="border-bottom:0">
			BC6145 BlueCore6-Audio DSP ROM, QFN</td>
        </tr>
    	</tbody>
        </table>
    	<ul class="tabbar clearfix" >
            <li class="selected">
                <a href="#description">产品信息<b></b></a>
            </li>
            <li><a href="#J_Reviews">文档<b></b></a></li>
         </ul>
         <div class="tab_con" style="display: block;">
        <table class="mtable mtable01 " border="0" cellpadding="0" cellspacing="0">
          <tbody><tr>
            <th>参数</th>
            <th>数值</th>
          </tr>
          <tr>
          <td >Ambient Operating Temperature(Min-Max)(°C)</td>
          <td style="text-align:left; padding-left:10px;">-40 to 85<br> </td>
          </tr>
          <tr>
          <td >Battery Charger</td>
          <td style="text-align:left; padding-left:10px;">Li-Ion<br> </td>
          </tr>
          <tr><td >Charge Current Type</td><td style="text-align:left; padding-left:10px;">Tickle Charge Current<br> Constant Charge Current<br> End of Charge Current<br> </td></tr>       </tbody></table>
      </div>
		
    </div>
    <div class="fr rightbox">
    	<div class="blank10"></div>
        <div class="subhot">
            <div id='hotpord'></div>
        </div>
        <div class="blank10"></div>
    </div>
</div>
<script type="text/javascript">
//加载热销
hotpord();
</script>