<div class="popup" style="width:950px;">
    <div class="popup-header">
        <h2><?=($this->comid?'修改':'添加')?>公司：</h2>
        <a href="javascript:;" onclick="$.closePopupLayer('box2');" title="关闭" class="dialogBoxClose">关闭</a> 
    </div>
    <div class="popup-body">
    	<div class=" overflowh">
        	<div class="publicOne">
                <table cellpadding="0" cellspacing="0" border="0" class="table" width="90%" id="SignFrame">
                <thead>
                  <tr id="trHeader">
                    <th width="250">公司名称<em>*</em></th>
                    <th width="500">简介简介<em>*</em></th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td><input type="text" name="company_name" id="company_name" style="width:250px;" value="<?=$this->company['company_name']?>"/></td>
                    <td><textarea name="company_profile" id="company_profile" rows="3" style="width:500px;"><?=$this->company['company_profile']?></textarea></td>
                  </tr>
                  <tr><td>&nbsp;</td><td>
                  <input type="button" onclick="addcompany()" value="<?=($this->comid?'修 改':'添 加')?>" class="btnabig"></td></tr>
                </tbody>
              </table>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
//添加公司
function addcompany(partid,key)
{
	var company_name = document.getElementById("company_name").value;
	if(company_name=='') {alert('请输入公司名称');document.getElementById('company_name').focus();return;}
	var company_profile = document.getElementById("company_profile").value;
	if(company_profile=='') {alert('请输入公司简介');document.getElementById('company_profile').focus();return;}
	$.ajax({
		url: '/icwebadmin/CpSogl/addcompany',
		data: {'comid':'<?=$this->company['id']?>','company_name':company_name,'company_profile':company_profile},
		type: 'post',
		dataType: 'json',
		success: function(arr) {
		    alert(arr.message);
			if(arr.code == 0 || arr.code == 1){
				choosecompany('<?=$this->id?>',arr.comid,arr.comname);
            }
		}
	});
}

</script>