<link rel="stylesheet" href="/js/kindeditor/themes/default/default.css" />
<script src="/js/kindeditor/kindeditor.js"></script>
<script src="/js/kindeditor/lang/zh_CN.js"></script>
<div class="conmian">
  <h1><a href="<?=$this->indexurl?>"><?php echo $this->AreaTitle;?></a> -> <?=$this->processData['title']?> -> 成功案例 | <a href="/icwebadmin/CpSogl/jszq/id/<?=$this->processData['id']?>">技术支持</a> | <a href="/icwebadmin/CpSogl/sjwd/id/<?=$this->processData['id']?>">设计文档</a></h1>
<div id="message_sess" style="display:none" class="message_sess">
                  <div title="关闭" class="but" onclick="document.getElementById('message_sess').style.display='none'">&nbsp;</div>
                  <div id="alert_message"></div>
                </div>
<?php if (isset($_SESSION['messages'])) : ?>
          <div class="alert fade in">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <p class="message"><strong><?php echo $_SESSION['messages'];unset($_SESSION['messages']);?></strong></p>
          </div>
 <?php endif; ?>
<form class="form-horizontal form-validate" style="text-align:left" method="post" action="" enctype="multipart/form-data">
           <input type="hidden" name="solid" value="<?=$this->processData['id']?>" />
           <br/>
                <table cellpadding="0" cellspacing="0" border="0" class="table" style="width:800px;" id="SignFrame">
                <thead>
                  <tr id="trHeader">
                    <th width="200">公司</th>
                    <th width="300">项目名称</th>
                    <th width="50"><a href="javascript:;" class="gbqfb" onclick="AddSignRow()">添加项目</a></th>
                    <input name='txtTRLastIndex' type='hidden' id='txtTRLastIndex' value="<?=count($this->cgal)?>" />
                  </tr>
                </thead>
                <tbody>
                <?php foreach($this->cgal as $k=>$v){?>
                  <input type="hidden" name="id[]" value="<?=$v['id']?>"/>
                  <tr id="SignItem<?=($k)?>">
                    <td><input type="hidden" name="company_id[]" id="company_id_<?=$k?>" value="<?=$v['company_id']?>"/>
					<span id="comname_<?=$k?>"><?=$v['company_name']?></span> &nbsp;<a href="javascript:;" onclick="openbox('/icwebadmin/CpSogl/company?id=<?=$k?>&cid=<?=$v['company_id']?>')">选择&gt;&gt;</a></td>
                    <td><input type="text" name="project_name[]" value="<?=$v['project_name']?>" style="width:300px"/></td>
                    <td><a href='javascript:;' class='gbqfb' onclick="DeleteSignRow('SignItem<?=($k)?>')">删除</a></td>
                  </tr>
                   <?php }?>
                </tbody>
              </table>
            <div class="control-group">
              <div class="controls">
                <input type="submit" class="btn" value="更 新">
              </div>
            </div>
          </form>
          <br>
          <!-- 结束区域-->
</div>
<script language="javascript">// Example: obj = findObj("image1");
function findObj(theObj, theDoc)
{ 
   var p, i, foundObj; 
   if(!theDoc) theDoc = document; 
   if( (p = theObj.indexOf("?")) > 0 && parent.frames.length) 
   {    
       theDoc = parent.frames[theObj.substring(p+1)].document;
	   theObj = theObj.substring(0,p); 
   } 
   if(!(foundObj = theDoc[theObj]) && theDoc.all) foundObj = theDoc.all[theObj]; 
   for (i=0; !foundObj && i < theDoc.forms.length; i++)
   foundObj = theDoc.forms[i][theObj]; 
   for(i=0; !foundObj && theDoc.layers && i < theDoc.layers.length; i++) 
	 foundObj = findObj(theObj,theDoc.layers[i].document); 
   if(!foundObj && document.getElementById) 
   foundObj = document.getElementById(theObj);    
   return foundObj;
}
//添加一个参与人填写行
function AddSignRow(){ //读取最后一行的行号，存放在txtTRLastIndex文本框中 
   var txtTRLastIndex = findObj("txtTRLastIndex",document);
   var rowID = parseInt(txtTRLastIndex.value);
   var signFrame = findObj("SignFrame",document);
   //添加行
   var newTR = signFrame.insertRow(signFrame.rows.length);
   newTR.id = "SignItem" + rowID;
   //添加列:型号
   var newNameTD=newTR.insertCell(0);
   newNameTD.innerHTML = '<input type="hidden" name="company_id[]" id="company_id_'+rowID+'"/><span id="comname_'+rowID+'"></span> &nbsp;<a href="javascript:;" onclick="openbox(\'/icwebadmin/CpSogl/company?id='+rowID+'&cid=\')">选择&gt;&gt;</a>';
   
   //添加列:品牌(产品线)
   var newNameTD=newTR.insertCell(1);
   newNameTD.innerHTML = '<input type="text" name="project_name[]"  style="width:300px"/>';
 
   //添加列:删除按钮
   var newDeleteTD=newTR.insertCell(2);
   //添加列内容
   newDeleteTD.innerHTML = "<a href='javascript:;' class='gbqfb' onclick=\"DeleteSignRow('SignItem" + rowID + "')\">删除</a>";
   //将行号推进下一行
   txtTRLastIndex.value = (rowID + 1).toString() ;
}
//删除指定行
function DeleteSignRow(rowid){
  var signFrame = findObj("SignFrame",document);
  var signItem = findObj(rowid,document);
  //获取将要删除的行的Index
  var rowIndex = signItem.rowIndex;
  //删除指定Index的行
  signFrame.deleteRow(rowIndex);
}
</script>
