<div class="popup" style="width:950px;">
    <div class="popup-header">
        <h2>选择公司：</h2>
        <a href="javascript:;" onclick="$.closePopupLayer('box');" title="关闭" class="dialogBoxClose">关闭</a> 
    </div>
    <div class="popup-body">
    	<div class=" overflowh">
        	<div class="publicOne">
                <table cellpadding="0" cellspacing="0" border="0" class="table" width="90%" id="SignFrame">
                <thead>
                  <tr id="trHeader">
                    <th width="200">公司</th>
                    <th width="300">简介</th>
                    <th width="50"><a href='javascript:;' class='gbqfb' onclick="openbox2('/icwebadmin/CpSogl/addcompany?id=<?=$this->id?>')">添加</a></th>
                  </tr>
                </thead>
                <tbody>
                <?php foreach($this->company as $k=>$v){?>
                  <tr>
                    <td><?=$v['company_name']?></td>
                    <td><?=$v['company_profile']?></td>
                    <td><a href='javascript:;' class='gbqfb' onclick="choosecompany('<?=$this->id?>','<?=$v['id']?>','<?=$v['company_name']?>')">选择</a>
                    <a href='javascript:;' class='gbqfb' onclick="openbox2('/icwebadmin/CpSogl/addcompany?id=<?=$this->id?>&comid=<?=$v['id']?>')">修改</a>
                    </td>
                  </tr>
                   <?php }?>
                </tbody>
              </table>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
//选择公司
function choosecompany(id,comid,comname)
{
	$("#company_id_"+id).val(comid);
	$("#comname_"+id).html(comname);
	$.closePopupLayer('box');
	$.closePopupLayer('box2');
}
</script>