<div class="w">
    <div class="breadcrumbs">		
    	<span><?=$this->translate('Menu_CurrentPosition')?></span><a href="/" ><?=$this->translate('Menu_Home');?></a>&nbsp;&nbsp;»&nbsp;&nbsp;<span><?=$this->translate('Menu_Bom')?></span>        
    </div>
</div>

<div class="w lh msg24">
    <div class="<?php if(isset($_SESSION['code']) && $_SESSION['code']>0) echo "error";elseif($_SESSION['message']) echo "ok";?>" id="index_message">
  <?php if(isset($_SESSION['message'])){echo $_SESSION['message'];}?>
    </div>

    <div class="bomorder">
    <div class="rightbox fr">
    	<div class="bomorder_tip">
            <h2 class="titbg1ts">BOM采购提示:<em class="emtriangleright5px"></em></h2>
            <p>1、可以手动输入也可以提交Excel</p>
            <p>2、<a href="/upload/default/bomexcel/bom_example.xlsx">下载BOM Excel样例</a></p>
            <p>3、每次最多提交100条BOM采购</p>
        </div>
    </div>
	<div class="fl shoplist">
    <div class="bombox">
    <h2 class="titbg1ts"><?=$this->translate('Menu_Bom')?></h2>
    <form id='filepost' name="filepost" action='/bompurchase/separate' method='post' enctype="multipart/form-data">
          <strong>上传BOM采购清单：</strong>
          <input type="file" name="uploadtext" id="uploadtext" class="input200" onchange="return fileaction();">
    </form>
    </div>

    <form id='bompost' name="bompost" action='/bompurchase' method='post'>
    <table cellpadding="0" cellspacing="0"  class="tablea table" border="0">
      <thead>
        <tr>
          <th width="15%" style="border-top:1px solid #ddd">品牌<em>*</em></th>
          <th width="15%" style="border-top:1px solid #ddd">型号<em>*</em></th>
          <th width="15%" style="border-top:1px solid #ddd">需求数量<em>*</em></th>
          <th width="15%" style="border-top:1px solid #ddd">目标单价</th>
          <th width="15%" style="border-top:1px solid #ddd">要求交货日期</th>
          <th width="10%" style="border-top:1px solid #ddd">备注</th>
          <th width="10%" style="border-top:1px solid #ddd">&nbsp;</th>
        </tr>
      </thead>
      <tbody>
        <tr>
        <td colspan="8">
        <input type="hidden" value="0" id="theValue" name="theValue" />
        <input type="hidden" value="0" id="theValueNum" name="theValueNum" />
        <div id="myDiv"></div></td>
        </tr>
        
        <tr><td colspan="8" align="right" class="tabletrf9">
        <a href="javascript:;" onClick="addEvent('','','','','','','','','');"  class="abutton" style="padding-right:5px;"><b>添加行+</b></a></td></tr>
        
        
        </tbody></table>

        <table cellpadding="0" cellspacing="0" class="table" style="margin-top:10px;">
        <tr>
            <td align="right"><font color="#FF0000">*</font>结算货币：</td>
            <td align="left">
       <select name="currency" id="currency" onchange="changeMbprice(this.value)">
       <option value="RMB" <?php if(isset($_SESSION['currency']) && $_SESSION['currency']=='RMB') echo "selected";?>>人民币(RMB)</option>
       <option value="HKD" <?php if(isset($_SESSION['currency']) && $_SESSION['currency']=='HKD') echo "selected";?>>港币(HKD)</option>
       <option value="USD" <?php if(isset($_SESSION['currency']) && $_SESSION['currency']=='USD') echo "selected";?>>美元(USD)</option>
       </select>
      		</td>
      </tr> 
      <tr>
        	<td width="120" align="right"><font color="#FF0000">*</font>交货地：</td>
            <td align="left" >
           <input type="hidden" name="delivery" id="delivery" value="<?=isset($_SESSION['delivery'])?$_SESSION['delivery']:"SZ"?>" />
          <select name="delivery_show" id="delivery_show" disabled="disabled">
          <option value="SZ" <?php if(isset($_SESSION['delivery']) &&$_SESSION['delivery'] == 'SZ') echo "selected";?>>国内</option>
          <option value="HK" <?php if(isset($_SESSION['delivery']) &&$_SESSION['delivery'] == 'HK') echo "selected";?>>香港</option>
          </select>
          </td>
        </tr>
        <tr>
      	<td align="right">说明：</td>
        <td align="left">
        <textarea name="description" id="description" rows="3" style="width:500px;"><?=(isset($_SESSION['description'])?$_SESSION['description']:'')?></textarea>
        </td>
      </tr>
        <tr>
          <td colspan="2" align="center"><div id="orderbtn"><input type="button"  value="提 交" onclick="changeaddress()" class="button bigbutton"/></div>
          </td>
        </tr>
    </table>
    </form>
    </div> 
    </div>
</div>

<div class="clr"></div>
<script src="/js/default/bompurchase.js" type="text/javascript"></script>
<script type="text/javascript">
function fileaction(){
	$.ajax({
            url: '/index/checklogin',
            data: {},
            type: 'post',
            dataType: 'json',
            success: function(arr) {
			   if(arr.code==0)
			   {  
			     	$.ajax({
					url: '/bompurchase/checkuser',
						data: {},
						type: 'post',
						dataType: 'json',
						success: function(arr) {
							if(arr.code==0)
							{
								document.getElementById('filepost').submit();
							}else if(arr.code==400)
							{
								 $.openPopupLayer({
								 name: "companyinfoBox",
								 url: "/center/companyinfo"
								 });
	
							}
							
						}
				    });
			   }else if(arr.code==100){
			   	 $.openPopupLayer({
		             name: "loginBox",
		             target: "login_box"
	              });
			   }else if(arr.code==200){
			   	   window.location.href ="/user/verification";
			   }
            }
    });	
}
//提交
function changeaddress()
{
$.ajax({
            url: '/index/checklogin',
            data: {},
            type: 'post',
            dataType: 'json',
            success: function(arr) {
			
			   if(arr.code==0)
			   {  
			   	  var subtmp = document.getElementById("orderbtn");
			     	$.ajax({
					url: '/bompurchase/checkuser',
						data: {},
						type: 'post',
						dataType: 'json',
						success: function(arr) {
							if(arr.code==0)
							{
								document.getElementById('bompost').submit();
				                subtmp.innerHTML = '<input type="button" class="button bigbutton" value="提交中..." disabled="disabled" style="cursor:default"/>';
							}else if(arr.code==400)
							{
								 $.openPopupLayer({
								 name: "companyinfoBox",
								 url: "/center/companyinfo"
								 });
	
							}
							
						}
				    });
			   }else if(arr.code==100){
			   	 $.openPopupLayer({
		             name: "loginBox",
		             target: "login_box"
	              });
			   }else if(arr.code==200){
			   	   window.location.href ="/user/verification";
			   }
            }
    });	
}
<?php
//填上excel内容
if(isset($_SESSION['alldata']) && $_SESSION['alldata']){
   foreach($_SESSION['alldata'] as $darr){
   if($darr){
   echo 'addEvent("'.$darr[0].'","'.$darr[1].'","'.$darr[2].'","'.$darr[3].'","'.date('Y-m-d',strtotime($darr[4])).'","'.$darr[5].'","","","");';}
   }
   unset($_SESSION['alldata']);
}elseif(!$_SESSION['code']){
   for($i=0;$i<1;$i++)
   {
      echo 'addEvent("","","","","","","","","");';
   }
}
if(isset($_SESSION['code']) && $_SESSION['code']>0){
    for($i=1;$i<=$_SESSION['valuenum'];$i++){
	$mfr     = $_SESSION['mfr'][$i];
	$part_no = $_SESSION['partno'][$i];
	$buynum  = $_SESSION['buynum'][$i];
	$price  = $_SESSION['price'][$i];
	$deliverydate  = $_SESSION['deliverydate'][$i];
	$remarks = $_SESSION['remarks'][$i];
echo 'addEvent("'.$mfr.'","'.$part_no.'","'.$buynum.'","'.$price.'","'.$deliverydate.'","'.$remarks.'","'.$_SESSION['m_mesg'][$i].'","'.$_SESSION['p_mesg'][$i].'","'.$_SESSION['n_mesg'][$i].'");';
   }
}
?>
//setTimeout('hidMessage()',6000);
function hidMessage(){
	document.getElementById("index_message").style.display = 'none';
}
</script>
<?php 
unset($_SESSION['code']);
unset($_SESSION['message']);
?>