<link rel="stylesheet" type="text/css"
	href="/<?=$_SESSION['new_version']?>/css/default/list.css" />
<div class="w">
	<div class="breadcrumbs">
		<span>
    <?=$this->translate('Menu_CurrentPosition')?>
    </span><a href="/">
    <?=$this->translate('Menu_Home');?>
    </a>&nbsp;&nbsp;»&nbsp;&nbsp;<span><b><?=$this->keyword?></b> 搜索结果</span>
	</div>
</div>
<div class="searchresult">
	<div class="w">
		<div class="wrap filter-box">
			<div data-type="search" id="filterNav" class="bd">
				<div class="filter-items" id='supplierGrabTab'>
					<dl>
					<dt>供应商：</dt>
					<dd>
						<ul>
							<li><span><a id='searchprd-all' href="javascript:;"
									class='searchprd curr' data-id='all'>不限</a></span></li>
										                    <?php foreach($this->supplierCrab as $v){?>
									            <li><span><a id='searchprd-<?php echo $v['id']?>'
									href="javascript:;" class="searchprd cblue"
									data-id='<?php echo $v['id']?>'><?php echo $v['name'];?></a></span></li>
										                    <?php }?>
										    </ul>
					</dd>
				</dl>
				</div>
			</div>
		</div>

<?php foreach($this->supplierCrab as $k=>$v){?>
		<!-- 供应商 -->
		<div id="product<?php echo $v['id']?>" class="wrap pro-list clearfix ">
			<?php //if($k==0){?>
			<div style=" margin:20px;"><img src="/images/admin/ajax-loader.gif" /></div>
			<?php //}?>
		</div>
		<!-- end 供应商 -->
<?php }?>

<div id="filter-null">
	<div class="filter-null l-box">
	        很抱歉，我们没有找到与"<strong class="corg"><?=$this->keyword?></strong>"相关的制造商型号
	</div>
</div>
    
<script type="text/javascript">
$(function(){
	var keyword = '<?=$this->keyword?>';
	var seachArr = [];
	var allid = [];
	<?php foreach($this->supplierCrab as $v){?>
		if(keyword.length >= 3){
			seachprd('<?php echo $v['id']?>','<?=$this->keyword?>');
			allid[<?php echo $v['id']?>] = <?php echo $v['id']?>;
		}else{
			$(".pro-list").html('');
			alert('型号最小字符必须为3个字符以上');
			return;
		}
	<?php }?>
	$(".searchprd").click(function(){
		var id = $(this).data("id");
		var allnull = true;
		if(id=='all'){
			for (var key in allid) {
				$("#product"+key).css('display','block');
			}
			for (var key in seachArr) {
				seachArr[key] = 0;
			}
		}else{
			if (!inarray(id, seachArr)) {
				seachArr[id] = id;
	        }else{
	        	seachArr[id] = 0;
	        }
			for (var key in allid) {
				$("#product"+key).css('display','none');
			}
		}
		for (var key in seachArr) {
			 if(seachArr[key]==0){
				 $("#product"+key).css('display','none');
				 $("#searchprd-"+key).removeClass("curr");
			 }else{
				 allnull = false;
				 $("#product"+key).css('display','block');
				 $("#searchprd-"+key).addClass("curr");
			 }
		}
		//全部空
		if(allnull){
			for (var key in allid) {
				$("#product"+key).css('display','block');
			}
			$("#searchprd-all").addClass("curr");
		}else{
			$("#searchprd-all").removeClass("curr");
		}
		//$("#searchboxtmp").removeClass("searchTxt");
		//$("#searchboxtmp").addClass("searchTxtHover");
    });	
	
})
function seachprd(sup,keyworld){
	
	$.ajax({
	       type: 'post',
	       url: "/search/product",
	       dataType: 'html',
	       data: {keyworld:keyworld,sup:sup},
	       success: function(result){
		       if(result=='"no"'){
		    	   $("#searchprd-"+sup).remove();
		    	   $("#product"+sup).html('');
		       }else{
		    	   $("#filter-null").css('display','none');
	    	   	   $("#product"+sup).html(result);
		       }
	       }
	   }); 	
}
function inarray(search, array) {
    for (var i in array) {
        if (array[i] == search) {
            return true;
        }
    }
    return false;
}
</script>
		<div class="clr"></div>
	</div>
</div>
