<?php header('Content-Type: text/html; charset=utf-8'); ?>
<script type="text/javascript">
$('.boxshadow_h').hover(function(){
		$(this).addClass("boxshadow");
	},function(){
		$(this).removeClass("boxshadow");
	});
//ajax应用分类分页
	 function ajaxpage(url){
	 	 $("#search_info").load(url);
		 scrollTo(0,150);  
	 }
</script>
<div class="w_100">
        <?php 
			 if(empty($this->rearray)){
			 ?>
			 <div class="posts p15 bg boxshadow_h" style="padding:50px 50px;">
                
                <h2>很抱歉您搜索的 ”<em><?=$this->keyword?></em>“ 没有相关搜索结果</h2>
             </div>
        <?php 
		}else{
			 foreach($this->rearray as $i=>$v){
			 if($i%2==0) $bg = "bg";
			 else $bg='';
          $url = HTTPHOST;$title='';$des = '';
          if($this->st=='searchsolution'){
              $url  .= "/solution-".$v['id'].".html";
          }elseif($this->st=='searchnews'){
              $url  .= "/news-".$v['id'].".html";
          }elseif($this->st=='searchwebinar'){
              $url  .= "/webinar-".$v['id'].".html";
          }elseif($this->st=='searchcode'){
		  	  $url  .= "/code-".$v['id'].".html";
		  }
          $title = str_ireplace($this->keyword,"<em>{$this->keyword}</em>",$v['title']);
          $des   = str_ireplace($this->keyword,"<em>{$this->keyword}</em>",$this->fun->utf_substr($v['description'],256));
        ?>
      
      <div class="posts p15 <?=$bg?> boxshadow_h">
                <h2><a target="_blank" rel="<?=$v['id']?>" rev="<?=$this->view->st?>" class="logclick" title="<?=$v['title']?>" href="<?=$url?>"><?=$title?></a></h2>
                <div class="postmeta">
                <?php if($v['source']){?><span>来源：</span><?=$v['source']?><?php }?>
                <?php if($v['author']){?><span class="ml10">作者：</span><?=$v['author']?><?php }?>
                <span class="ml10">关键词：</span><?php 
					
					$tip = explode(',',$v['keyword']?$v['keyword']:$v['tags']);
					for($i=0;$i<count($tip);$i++){
						echo $tip[$i].' ';
				 }?>                 
                </div>
                <div class="row">
                    <p><?=$des?><br/>
                    <a target="_blank" rel="<?=$v['id']?>" rev="<?=$this->view->st?>" class="logclick" title="<?=$v['title']?>" href="<?=$url?>"><?=$url?></a></p>
                </div>
    
      </div>

    <?php }?>
	 <div class="page_box">
        <div class="page clearfix"><?=$this->page_bar?></div>
        </div>
	<?php }?>
    
</div>