<?php echo $this->supplierCrab['id'];?>
||
<div class="product-list rel jsDataInfoParent jsTabMore">
<div class="hd clearfix">
	<div class="fl pro-title">
		<div class=" fl imglazy">
			<img alt="<?php echo $this->supplierCrab['name']?>" title="f" class="img-onerror" src="<?php echo $this->supplierCrab['img']?>">
			
		</div>
	</div>
</div>
<div class="batch-box rel">
	<table class="ic-list-tbl pro-list-tbl rel" style="width: 100%;"
		border='0'>
		<colgroup>
			<col width="15%">
			<col width="10%">
			<col width="13%">
			<col width="13%">
			<col width="7%">
			<col width="6%">
			<col width="10%">
			<col width="10%">
			<col width="14%">
		</colgroup>
		<thead>
			<tr>
				<th class="tl pl20">制造商型号</th>
				<th>制造商</th>
				<th>库存</th>
				<th>交期</th>
				<th>起订量<br> <span class="c9 f12">(MOQ)</span></th>
				<th>阶梯</th>
				<th>境内交货<br> <span class="c9 f12">(含17%税)</span></th>
				<th>境外交货<br> <span class="c9 f12">(美元)</span></th>
				<th class="tr pr50">购买操作</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach($this->product as $k=>$pv){
			    if(is_array($pv)){
			        if($this->supplierCrab['id']==1){
			            $url = "/item?scid=".$this->product['scid']."&supid=".$this->supplierCrab['id']."&pid=".$pv['product_id'];
			        }else{
			            $url = "/item?scid=".$this->product['scid']."&supid=".$this->supplierCrab['id']."&pid=0&kw=".$this->keyworld."&it=".$k."&pn=".$pv['pratNo'];
			        }
			    ?>
			<tr <?php if($k>2) echo 'class="productTr'.$this->supplierCrab['id'].' none"';?>>
				<td class="tl pl30">
					<div class="ic-no rel">
						<a title="<?php echo $pv['pratNo'];?>" 
								href="<?php echo $url;?>"
								target="_blank"> <?php echo $pv['pratNo'];?> </a>
					</div>
				</td>
				<td align="center"><?php echo $pv['brand'];?></td>
				<td align="center"><span><em class="corg">  <?php echo $pv['stock'];?> </em></span></td>
				<td align="center">
				    <span>国内：<em class="corg"><?php echo $this->supplierCrab['delivery_cn']?></em></span>
				    <br>
					<span>香港：<em class="corg"><?php echo $this->supplierCrab['delivery_hk']?></em></span>
				</td>


				<td align="center"><?php echo $pv['moq'];?></td>

				<td class="no-padding" colspan="3">
					<div class="price-list jsMore">
						<?php if($pv['bookprice']){?>
						<table class="step-price-tbl " align="center">
							<colgroup>
								<col width="20%">
								<col width="40%">
								<col width="40%">
							</colgroup>
							<tbody>
								<?php foreach($pv['bookprice'] as $bp){?>
								<tr>
									<th><?php echo $bp['moq']?'+'.$bp['moq']:'--';?></th>
									<td><?php echo $bp['rmbprice']?'¥'.$bp['rmbprice']:'--';?></td>
									<td><?php echo $bp['usdprice']?'$'.$bp['usdprice']:'--';?></td>
								</tr>
								<?php }?>
							</tbody>
						</table>
						<?php }?>
					</div>
				</td>

				<td class="tl pl30">

					<div class="tabelbtn">
		<?php if($pv['stock']>0 && $pv['bookprice']){?>
								<a href="<?php echo $url;?>" 
									class="gbqfb logclick" title="购买" rev="prodlist_part_id"
									target="_blank"><i class="i_buy_s"></i>在线购买</a> <br />
	<?php }?>
									 <a
									href="<?php echo $url;?>"
									class="gbqfb logclick" title="询价" rev="prodlist_part_id"
									target="_blank"><i class="i_xun_s"></i>批量询价</a><br>
							</div>

				</td>
			</tr>
			<?php }}?>
			<?php if(count($this->product)-2>3){?>
			<tr><td colspan="9"><div class="tab-more jsShowMoreTr<?php echo $this->supplierCrab['id']?>">查看更多<i></i></div></td></tr>
			<?php }?>
		</tbody>
	</table>
</div>
</div>
<script type="text/javascript">
$(function(){
	$(".jsShowMoreTr<?php echo $this->supplierCrab['id']?>").click(function(){
		$(".productTr<?php echo $this->supplierCrab['id']?>").show();
		$(".jsShowMoreTr<?php echo $this->supplierCrab['id']?>").remove();
	});	
})
</script>