<div id="myHiddenDiv">
  <div class="popup">
    <div class="popup-header">
    <h2>取消兑换：<?=$this->giftexchange['giftname']?></h2>
    <a href="javascript:;" onclick="$.closePopupLayer('cancelBox');" title="关闭" class="dialogBoxClose">关闭</a> </div>
    <div class="popup-body" style="width:500px;">
     <!-- 需要填写的区域-->
      <table width="740px" border="0" cellpadding="1">
        <tr>
          <td><em>*</em>说明：</td>
          <td><textarea name="notice" id="notice" rows="3" style="width:300px"></textarea></td>
        </tr>
        <tr>
          <td>&nbsp;</td>
          <td>
          <input type="button"  value="确认"  class="btnabig"  onclick="cancelaction()"/>
          </td>
        </tr>
      </table>
      <!-- 结束区域-->
    </div>
  </div>
</div>
<script type="text/javascript">
function cancelaction()
{
	 var notice = $('#notice').val();
	 if(notice=='') {
	      alert('请填写说明');$('#notice').focus();return;
     }
	 $.ajax({
            url: '/icwebadmin/GiftDhgl/cancel',
            data: {'id':'<?=$this->giftexchange['id']?>','notice':notice},
            type: 'post',
            dataType: 'json',
            success: function(arr) {
            	alert(arr.message);
            	if(arr.code == 0)
                {
                    location.reload();
                }
            }
	  });
}
</script>